### ISSUE TITLE
Open boundary conditions for Stokes drift

### ISSUE THREAD

**Issue by lsf911** [jcwarner-usgs/COAWST#102]
Hi all,

I am running a coupled wave-circulation model using COAWST. I was wondering what would be approprate open boundary conditions (OBC) for the Stokes drift. I checked the test cases in Projects, they usually use gradient boundary conditions.

./Sandy/ocean_sandy.in:169:   LBC(isU2Sd) ==   Clo     Gra     Gra     Gra \       ! 2D U-stokes
./Sandy/ocean_sandy.in:173:   LBC(isU3Sd) ==   Clo     Gra     Gra     Gra \       ! 3D U-stokes

When I tried the gradient OBC in the coupled model, the reuslts have some suspicious currents along the OBC compared with the circulation-only run. 

In the coupled model, the OBCs are set as:
! Wec boundary conditions
    LBC(isU2Sd) ==   Clo     Gra     Clo     Clo         ! 2D U-stokes
    LBC(isV2Sd) ==   Clo     Gra     Clo     Clo         ! 2D V-stokes
    LBC(isU3Sd) ==   Clo     Gra     Clo     Clo         ! 3D U-stokes
    LBC(isV3Sd) ==   Clo     Gra     Clo     Clo         ! 3D V-stokes

coupled model run
![图片](https://user-images.githubusercontent.com/36282703/195237579-ce435900-b994-4bbc-9bf6-d12ddc6f918f.png)

circulation-only run
![图片](https://user-images.githubusercontent.com/36282703/195235170-5b9e0c0c-e03b-438b-97b6-fbccd5a5f8de.png)

 Anyone have any suggetsions? Thank you in advance!

**Comment by jcwarner-usgs** [comment]
suggest you use Gra for all the open boundaries for the stokes.  
I am not sure which boundary is open for your application, but set that bndry to use Gra.
then compare the eulerian vels for the non-coupled to the coupled, there should not be much difference there, but they could be different because the stokes flows will alter zeta and that can change the eulerian vels.

**Comment by lsf911** [comment]
> suggest you use Gra for all the open boundaries for the stokes. I am not sure which boundary is open for your application, but set that bndry to use Gra. then compare the eulerian vels for the non-coupled to the coupled, there should not be much difference there, but they could be different because the stokes flows will alter zeta and that can change the eulerian vels.

Thank you for your suggestion. The open boudaries are in the south and east. I will try to use Gra for all the open boundaraies.

**Comment by lsf911** [comment]
> suggest you use Gra for all the open boundaries for the stokes. I am not sure which boundary is open for your application, but set that bndry to use Gra. then compare the eulerian vels for the non-coupled to the coupled, there should not be much difference there, but they could be different because the stokes flows will alter zeta and that can change the eulerian vels.

Hi John, The fake currents along the boundary are due to umbalanced mass flux as I turned on the volume conservation. The issue was solved when I included the transport induced by Stokes drift in the obc_volcons.F. The Indeed, the Gra is good for the Stokes drift. Thank you for your suggestion.

**Comment by jcwarner-usgs** [comment]
great!   so can we close this ticket now?
