### ISSUE TITLE
Cannot read Matlab output files from "Sandy" test case

### ISSUE THREAD

**Issue by noviceroms** [jcwarner-usgs/COAWST#107]
Hi Warner,
I am running the Sandy test case of COAWST. I could complete the simulation but could not use the ".mat"  output files. Getting the following error.

**Unable to read MAT-file /home/user12/Sandy_hsig.mat. File might be corrupt.**

I am using gfortran. 

_GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc._

I would be grateful for any suggestions for resolving this error.
Thanks in advance

**Comment by jcwarner-usgs** [comment]
yeah i have seen this one.
you might need to change the gfortran compile flags.
In Compilers/Linux-gfortran it uses
           FFLAGS += -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian

you could change that to 
           FFLAGS += -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none 

(i think it needs to remove both the  record marker 4 and the big endian.)
then recompile and see if that works.
Also, We usually output all the SWAN data through ROMS into the roms netcdf his files.  so we usually do not even look at the swan mat files.
-j

**Comment by noviceroms** [comment]
Hi Warner,
That worked. Thanks a lot.
