### ISSUE TITLE
Model Ends With Error (SWAN Only version of SANDY test case)

### ISSUE THREAD

**Issue by noviceroms** [jcwarner-usgs/COAWST#108]
Hi Warner,
When I tried the SWAN only test case (for the wave field without interaction) using SANDY test case, the model ends normally with 40 cpus. If I prescribe more than 40 cpus, the model ends with the following error. I got this error with my own test case so came back to "Sandy" test case to check this. Can we not use more than 40 processors with SWAN only case? I would be grateful for any insights to this.

**+time 20121030.120000   , step    960; iteration    1; sweep 3 grid   1
+time 20121030.120000   , step    960; iteration    1; sweep 4 grid   1
At line 4990 of file swanparll.f90 (unit = 1046, file = 'È7ª­b+')
Fortran runtime error: Too many open files
-------------------------------------------------------**

Thanks for your time and consideration

**Comment by jcwarner-usgs** [comment]
every model application has a maximum number of processors, usually dictated by the grid size.
SWAN tiles the grid into strips, along the longest dimension. Also every swan tile needs to have water in it (this is a limitation in the way i coupled the system).  That swan grid is small, 86x64.  so it will tile along the 86 dimension.
if you use 40 procs, then you get 40 strips about 2x64 each.   that is pretty small to begin with.

**Comment by noviceroms** [comment]
Hi Warner,
Thanks for the information and help
