### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#109]
Hello, I have recently reinstalled COAWST on a new computer but I am having some problems getting it to run.
I tried to do a coupled WRF-ROMS simulation and used a set of mesh data that I could have calculated.But when I mpirun the run the model exploded.I have checked some previous answers to my questions, but I still don't know what is the cause.

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
coawstM            0000000003306B9A  Unknown               Unknown  Unknown
libpthread-2.23.s  00007FEEC8F20390  Unknown               Unknown  Unknown
coawstM            0000000001A8A50F  Unknown               Unknown  Unknown
coawstM            00000000019C0EA1  Unknown               Unknown  Unknown
coawstM            0000000000AED94D  Unknown               Unknown  Unknown
coawstM            00000000009677DC  Unknown               Unknown  Unknown
coawstM            000000000041DBAC  MAIN__                    227  master.f90
coawstM            0000000000419CF2  Unknown               Unknown  Unknown
libc-2.23.so       00007FEEC8961840  __libc_start_main     Unknown  Unknown
coawstM            0000000000419
BE9  Unknown               Unknown  Unknown

I have put the run logs below, hope you can help me.
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/9921355/logs.txt)

**Comment by jcwarner-usgs** [comment]
not sure.  here are some suggestions.
have you run WRF by itself and ROMS by itself?
then try them coupled.
how did you create the scrip interpolation weigths file?
maybe try to compile with debug=on and rerun as coawstG.

**Comment by SakuraLz** [comment]
OK, I consulted with others. The problem would be an error in the wrf run.
When the 'severe (174): SIGSEGV, segmentation fault occurred' problem occurs it is probably a memory problem, I was able to run it again with success by typing 'ulimit -s unlimited'.
