### ISSUE TITLE
create_roms_tides

### ISSUE THREAD

**Issue by ruirvieira** [jcwarner-usgs/COAWST#110]
Hello,

I used the create_roms_tides.m script to create tides for my simulation centered in Madeira Archipelago in Atlantic Ocean.

In the script, we choose the osu option using the tpx_uv.mat and tpx_h.mat that are not in the current repository. We got it from older coawst version.

We are getting strange outputs, for example the tide_Cphase looks like this:
![image](https://user-images.githubusercontent.com/117355621/199703372-b42e70ee-b24b-4432-839f-099d54b908ff.png)

Any ideia to fix these strange lines?

Thank you
Best regards

**Comment by jcwarner-usgs** [comment]
not sure, but ROMS only uses info along the open boundary. it does not use the data inside the model.
there is a new option in roms to additionally include the tidal potential, but i have not used it.
Give it a try with what you have and compare zeta to some measured tidal stations.
-j

**Comment by ruirvieira** [comment]
Hello

We will do that, try and test.

Thank you for your fast reply.

Best regards
