### ISSUE TITLE
nc file does not output swrad results

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#111]
I am doing a coupled simulation of wrf-roms. Today I suddenly found that the output of his.nc has no swrad results, it shows all 0. But when I check lwrad the results are normal. And my model is working fine and the SST results are fine. I don't know if this is because the simulation results are not exported to the file or because the simulation is not doing the swrad calculation. Will this have an effect on my simulation results? Will this result in no diurnal variation in SST?
Can you help me please?
![2022-11-09 21-45-06](https://user-images.githubusercontent.com/44939791/200861995-8b6f03be-6160-4efc-a41b-60176ac97e15.png)
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/9972175/logs.txt)
[mangkhut.h.txt](https://github.com/jcwarner-usgs/COAWST/files/9972178/mangkhut.h.txt)
[roms_mangkhut_r1.in.txt](https://github.com/jcwarner-usgs/COAWST/files/9972184/roms_mangkhut_r1.in.txt)

**Comment by jcwarner-usgs** [comment]
you have define ANA_SRFLUX
and that will make it use whatever is in ROMS/Functionals/ana_srflux 
and that is the short wave.
you can undef ANA_SRFLUX and if your forcing nc data has swrad, then the model will use swrad from the netcdfile.
-j

**Comment by SakuraLz** [comment]
That means if I define ANA_SRFLUX, then it won't output the swrad result? This has nothing to do with lwrad right.
Also with the wrf-roms coupling I'm using, I'm not using a forcing file, only driving tides. If I undef ANA_SRFLUX then will roms get swrad from wrf? Or do I need to provide the swrad file alone.

**Comment by jcwarner-usgs** [comment]
ok.  you do have SWRAD in the output, but it is all 0's.
  I think the #define ANA_SRFLUX is making roms take the shortwave from the ana file. the short wave should come from wrf.
so undef that ana_srflux, recompile, and rerun. the shortwave should come from wrf to roms.
