### ISSUE TITLE
Wave data

### ISSUE THREAD

**Issue by Ntmanh18196** [jcwarner-usgs/COAWST#112]
Hi John,

I want to create the TPAR boundary files for SWAN on 26 Sep, 2022. However, I find out that the gfswave data from this url (http://nomads.ncep.noaa.gov:80/dods/wave/gfswave) is not available. 
Can you kindly give me some url to download this data?
If yes, can you give me the url of hindcast data or something else cover to present?
Thank you very much!

**Comment by jcwarner-usgs** [comment]
my suggestion is to look here
https://polar.ncep.noaa.gov/waves/download2.shtml?
and ask someone on that site.
-j

**Comment by Ntmanh18196** [comment]
Hi John,
Thank you for your suggestion. I will do that.
