### ISSUE TITLE
Compiling WW3+ROMS error

### ISSUE THREAD

**Issue by lfpareja** [jcwarner-usgs/COAWST#113]
Hello,
I'm a long-time user of COAWST (ROMS+SWAN) - now trying ROMS+WW3. I just ran the Inlet test case with ROMS/SWAN but am getting errors when compiling the same case for ROMS/WW3:

The compilation seems to go well for a while and then I get this error:

> ifort: error #10236: File not found:  'WW3/model/obj_MPI/libWW3.a'
> Master/Module.mk:22: recipe for target '/glade/scratch/pareja/inlet_ww3/coawstM' failed
> make: *** [/glade/scratch/pareja/inlet_ww3/coawstM] Error 1

My ww3 switch keys are:

> F90 NOGRB COAWST LRB4 SCRIP SCRIPNC NC4 TRKNC DIST MPI PR3 UQ FLX0 LN1 ST4 STAB0 NL1 BT4 DB1 MLIM TR0 BS0 IC2 IS2 REF1 IG1 XX0 WNT2 WNX1 RWND CRT1 CRX1 TIDE O0 O1 O2 O2a O2b O2c O3 O4 O5 O6 O7

I attach the roms header file and the coawst.bash. I do see something about WW3 specific build files in the coawst .doc manual, but I don't know how to proceed with this in particular (if that's the issue):

> You may need to edit some WW3 specific build files.  So if you selected ifort (for example), then we need to look at COAWST/WW3/bin/comp.Intel 
COAWST/WW3/bin/link.Intel

Thanks,
FernandoP@Rutgers
[coawstbash.txt](https://github.com/jcwarner-usgs/COAWST/files/10005596/coawstbash.txt)
[inlet_test.txt](https://github.com/jcwarner-usgs/COAWST/files/10005597/inlet_test.txt)

(.h and .bash extensions removed).

**Comment by jcwarner-usgs** [comment]
can you send the whole output during the build?
scrip build.log
./coawst.bash
exit
and then send build.log

**Comment by lfpareja** [comment]
Ok. See attached.
it seems it's not finding the switch key file, but it is in my local folder. 
[build.log](https://github.com/jcwarner-usgs/COAWST/files/10005887/build.log)

**Comment by jcwarner-usgs** [comment]
ERROR: /glade/u/home/pareja/COAWST/COAWST/WW3/model/bin/switch_switch_inlet_ww3 not found

maybe the word 'switch' is there too many times?
maybe in coawst.bash try to remove that word 
 export  WW3_SWITCH_FILE=switch_inlet_ww3
to
 export  WW3_SWITCH_FILE=inlet_ww3

??
if that doesnt work i will try it later today.
i am running roms+ww3 for Hurricane Michael so i know it works.
-j
