### ISSUE TITLE
How to run a real case of sediment in coawst?

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#114]
Hello, after some time I have been able to run my own fully coupled WRF-ROMS-SWAN model. After that I would like to try the sediment operation in a real case like the SANDY model.
I know that I need to define SEDIMENT in ROMS and that I need to change 'bed_thickness', 'bed_porosity', 'bed_biodiff' and 'bed_biodiff' in the ini file. 'bed_biodiff', 'bed_tau_crit' and other parameters in the ini file. As well as the need to change the 'sediment_sed_bed_toy.in' file.But after that the model crashed after I tried to run it.
But I don't know exactly what to do and which values I should change for these parameters? I did not find any relevant case studies. Have you tried Sandy's sediment calculation case?
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/10049847/logs.txt)
[roms.h.txt](https://github.com/jcwarner-usgs/COAWST/files/10049808/roms.h.txt)
[roms_sed.zip](https://github.com/jcwarner-usgs/COAWST/files/10049845/roms_sed.zip)

**Comment by jcwarner-usgs** [comment]
Tracer Advection Scheme: NLM
 ========================

 Variable               Grid  Horizontal         Vertical
 ---------              ----  ------------       ------------

 temp                     1   Upstream3          Centered4
                          2   Upstream3          Centered4

 salt                     1   Upstream3          Centered4
                          2   Upstream3          Centered4

 mud_01                   1   HSIMT              HSIMT
                          2   9VV             @lVV     

 mud_02                   1   HSIMT              HSIMT
                          2        !                  !     

 sand_01                  1   HSIMT              HSIMT
                          2     PVV             °7VV   

 sand_02                  1   HSIMT              HSIMT
                          2   ÑVV             ÑVV     

looks like it is having trouble figuring out the sediment advection.  edit the sediment.in,
not sure if it needs to be listed 8 times or just 4.

   Hadvection == HSIMT \                         ! idsed(:), compact
HSIMT \
HSIMT \
HSIMT \
HSIMT \
HSIMT \
HSIMT \
HSIMT 

   Vadvection == HSIMT \                         ! idsed(:), compact
HSIMT \
HSIMT \
HSIMT \
HSIMT \
HSIMT \
HSIMT \
HSIMT

**Comment by Z1562** [comment]
Hi, I would like to ask if you have more information to share about adding sediment module to COAWST. I need some help. I would be very grateful.
