### ISSUE TITLE
Results output about swan

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#115]
Hi
I was recently able to run the WRF-SWAN model successfully, but I have some questions on the SWAN output that I would like to ask.I'm sorry I'm just getting started with the SWAN model.
Firstly is it still not possible for coawst to output separate results for nested meshes?
Secondly, I would like SWAN to be able to place multiple parameters (e.g. HS, DIR, etc.) in the same nc file. I would like to know how to set this in the 'input' file.
To do this I have tried a number of methods.
1. I set the following command in the input file and all three nc files can output

BLOCK 'COMPGRID' NOHEADER 'hdir.nc'    LAY 4 DIR 1.    OUTPUT 20050901.000000 6 HR
BLOCK 'COMPGRID' NOHEADER 'hsig.nc'    LAY 4 HSIGN 1.  OUTPUT 20050901.000000 6 HR
**BLOCK 'COMPGRID' NOHEADER 'SWAN.nc' LAY 4 HSIGN DIR 1. OUTPUT 20050901.000000 6 HR**

2.When I put the three parameters 'HS, DIR, HSWELL' into one nc file it runs with an error.

BLOCK 'COMPGRID' NOHEADER 'hdir.nc'    LAY 4 DIR 1.    OUTPUT 20050901.000000 6 HR
BLOCK 'COMPGRID' NOHEADER 'hsig.nc'    LAY 4 HSIGN 1.  OUTPUT 20050901.000000 6 HR
**BLOCK 'COMPGRID' NOHEADER 'SWAN.nc'    LAY 4 HSIGN DIR HSWELL PDIR TDIR 1.  OUTPUT 20050901.000000 6 HR**

The error shows
`  ---- WARNING : Maybe old non-HVC input, setting default 1d array values for TF
  ---- WARNING : Older v3 input data detected`

Eventually I found that the command 'OUTPUT 20050901.000000 6 HR' must be written in column 56 to output the results properly, so I would like to ask if I can only output a maximum of two results to one file?

**Comment by jcwarner-usgs** [comment]
i am not sure how many results can go into each swan file.  i typically do not use swan to write out the data, i usually go through roms.  but if you have wrf and swan together, wrf can write out some of the swan data, but probably not all the fields you want.
I do have a limitation in coawst - if you are running swan with a nest, i can only write out data from either the parent or the nest, not both.  But you seem to not be running with a nest.
So .... i think swan should be able to process this command correctly
BLOCK 'COMPGRID' NOHEADER 'SWAN.nc' LAY 4 HSIGN DIR HSWELL PDIR TDIR 1. OUTPUT 20050901.000000 6 HR
try it with the other 2 BLOCK lines commented.  maybe they are messing things up.


-the non-HVC is a WRF error in start_em.F
  IF ( grid%c1f(1) .NE. 1. ) THEN
         CALL wrf_debug ( 0 , '---- WARNING : Maybe old non-HVC input, setting default 1d array values for TF' )
I am not sure what this is for.

**Comment by SakuraLz** [comment]
HI!
Well, I ran what was actually the 'JOE_TC' case yesterday and made changes to the output parameters.
The results seem to have improved after I tried again on my model to output only some of the parameters.

BLOCK 'COMPGRID' NOHEADER 'WAVE.nc' LAY 4 HSIGN HSWELL 1.    OUTPUT 20180913.000000 1 HR
BLOCK 'COMPGRID' NOHEADER 'DIR.nc'  LAY 4 DIR PDIR 1.      OUTPUT 20180913.000000 1 HR

I am using nested meshes and I don't know if this will output the results for fine meshes. Also I have a lot of *.nc-001,*.nc-002 files when I do mpirun, the number of files is equal to the number of nodes in the swan model, does this affect the results?

Also, I do see results for HWAVE, PWAVE etc in wrfoutd01 and d02, which is handy. But does this allow for other data such as DIR to be output in wrf? If so what should I do.

**Comment by jcwarner-usgs** [comment]
yes, for SWAN each core will create an output file, then at the end of the simulation they get pulled together into 1 file.
so if you have 3 cores, you will get wave.nc-001, wave.nc-002, wave.nc-003, then at end of sim they get pulled together into 
wave.nc.

WRF will output the coupled params, like Hwave Pwave Dwave Lwave.  WRF may not output all the varaibles.
So it is up to you.  Sounds like you can get swan to work, although it may only have 2 vars per file. And some of them can get written by wrf.  It seems the functionality you need is there, but not quite exactly how you want it.

**Comment by jbzambon** [comment]
@SakuraLz I added some wave parameters to output to ROMS that are not enabled by default

- Peak Wavelength (Lwavep)
- Peak Wave Direction (Dwavep)

To do so, first make sure that the wave parameters are activated in the code. Check cppdefs, need any of: WEC_MELLOR, WEC_VF, BBL_MODEL, WAVES_OCEAN, INWAVE_MODEL to activate Peak Wave Direction (WAVES_DIRP)

Then modify ROMS.in to include these as output (they should already be in vardefs)

```
Hout(idWlep) == T       ! Lwavep             peak wave length
Hout(idWdip) == T       ! Dwavep             peak wave direction
```

If you want this output into WRF, the process is similar, but you'll need to modify Registry.EM in order to get these variables output and recompile.

Hope that helps!

**Comment by SakuraLz** [comment]
Thank you very much!
I can already output wave direction and other data.

If I use ROMS, SWAN coupling, can I just turn on the white capping and not the wave breaking along the water depth?

**Comment by jcwarner-usgs** [comment]
the SWAN manual has directions for the swan physics.
but i think swan needs the wave breaking, otherwise i am not sure what would happen to the wave energy.
https://swanmodel.sourceforge.io/download/zip/swanuse.pdf

**Comment by SakuraLz** [comment]
Here is my roms file. Will I be able to turn on white capping and wave breaking along the water depth if I make the following settings?
[roms.h.txt](https://github.com/jcwarner-usgs/COAWST/files/10208810/roms.h.txt)

If I defin MY25_MIXING instead of define GLS_MIXING do I also get the wave interaction results?

**Comment by jcwarner-usgs** [comment]
white capping and wave breaking are computed in SWAN.
those values come to ROMS.
wave breaking is used in roms in the WEC_VF option and is used to drive currents. see the Kumar ocean modeling paper.
Kumar, N., Voulgaris, G., Warner, J.C., and M., Olabarrieta (2012). Implementation of a vortex force formalism in a coupled modeling system for inner-shelf and surf-zone applications. Ocean Modelling, 47, 65-95. 

white capping dissipation does come to roms and can be used with dissip_breaking in the GLS mixing to account for surface flux of tke due to surface waves breaking.  this is also discussed in Kumar 2012.

We did not implement these tke flux computations into MY25.

**Comment by SakuraLz** [comment]
Thank you very much for your answer!

So I had to add to roms.h
 define WEC_VF
 define WDISS_WAVEMOD ?
I am in the process of learning about this so I may not know some of the basics very well. If I use MY25_MIXING I can get results for dissip_breaking and white cap dissipation but not for turbulent kinetic energy?

**Comment by SakuraLz** [comment]
Thank you very much for your answer!

So I had to add to roms.h
 define WEC_VF
 define WDISS_WAVEMOD ?
I am in the process of learning about this so I may not know some of the basics very well. If I use MY25_MIXING I can get the results for dissip_breaking and white capping dissipation but I can't calculate the turbulent kinetic energy caused by the waves?

**Comment by jcwarner-usgs** [comment]
yes those are a good start.
there resolution of that sandy grid is rather coarse, so it will not resolve those physcis well.
you can look here for other pubs on this
https://github.com/jcwarner-usgs/COAWST/wiki/Publications
