### ISSUE TITLE
About the different wave dissipation options in roms

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#117]
I note in the manual that coawst offers three different wave dissipation schemes.
define WDISS_THORGUZA wave dissipation from Thorton/Guza
define WDISS_CHURTHOR wave dissipation from Church/Thorton
define WDISS_WAVEMOD wave dissipation from a wave model

But when I use the WDISS_THORGUZA and WDISS_CHURTHOR schemes in a coupled model of ROMS and SWAN, I find that SWAN cannot output the results of Dissip_wcap. That is, no wave breaking results for white caps for these two scenarios? When I use the WDISS_WAVEMOD scheme I can get normal white cap results. Is this normal please?

**Comment by jcwarner-usgs** [comment]
yes that is normal.
the wdiss_wavemod means that roms will get the 3 wave dissipation terms from a wave model (white capping, bottom fric, and breaking).
but if you select thorguza or churthor, then roms is computing the wave dissip term of breaking, and the other 2 (white cap and bottom fric) are not computed internally.
Wec/wec_dissip.F
# ifdef WDISS_THORGUZA
!
!  Calcualate wave dissipation using empirical parameters of 
!  Thornton and Guza, 1986
!
          cff2=1.0_r8/((gammaw**4.0_r8)*(Dstp**5.0_r8))
          Dissip_break(i,j)=0.2621_r8*fac1*sigmat*                      &
     &                     (cff1**7.0_r8)*cff2
          Dissip_wcap(i,j)=0.0_r8
!
# elif defined WDISS_CHURTHOR
!
!  Calculate wave dissipation using empirical parameters of
!  Church and Thornton, 1993.
! 
          cff2=1.0_r8/(gammaw*Dstp)
          RB1=1.0_r8+tanh(8.0_r8*((cff1*cff2)-1.0_r8))
          RB2=1.0_r8-(1.0_r8+(cff1*cff2)**2.0_r8)**(-2.5_r8) 
          Dissip_break(i,j)=(0.2621_r8/Dstp)*fac1*sigmat*               &
     &                      (cff1**3.0_r8)*RB1*RB2
          Dissip_wcap(i,j)=0.0_r8
# endif
