### ISSUE TITLE
ROMS nested simulation Error

### ISSUE THREAD

**Issue by shihab-saran** [jcwarner-usgs/COAWST#120]
I am trying to run a nested simulation in ROMS model. Unfortunately I am getting error which shows:
---------------------------------------------------------------------------------------------------------------------------------
26308800 2019-01-02 00:00:00.00  9.324909E-03  7.402117E+01  7.403049E+01  2.153949E+09  02
                     (181,013,22)  1.145567E-02  9.384614E-03  0.000000E+00  3.347391E-01
      DEF_HIS     - creating  history      file, Grid 02: ./job_output/concorde_Nest_Bayst_his_01828.nc
      WRT_HIS     - wrote history     fields (Index=1,1) in record = 0000001               02
      DEF_AVG     - creating  average      file, Grid 02: ./job_output/concorde_Nest_Bayst_avg_01828.nc
      DEF_DIAGS   - creating  diagnostics  file, Grid 02: ./job_output/concorde_Nest_Bayst_dia_01828.nc

 PUT_REFINE2D - unbounded contact points temporal:  interpolation:
  cr       = 01        dg         = 01        ng         = 02
  iic(dg)  = 8764801   told       = 1         tnew       = 2
  iic(ng)  = *******   Wold       = ********  Wnew       = ********
  time(ng) = *******   time(told) = *******   time(tnew) = *******
 Found Error: 08   Line: 5439     Source: ROMS/Nonlinear/nesting.F

 PUT_REFINE2D - unbounded contact points temporal:  interpolation:
  cr       = 01        dg         = 01        ng         = 02
  iic(dg)  = 8764801   told       = 1         tnew       = 2
  iic(ng)  = *******   Wold       = ********  Wnew       = ********
  time(ng) = *******   time(told) = *******   time(tnew) = *******
 Found Error: 08   Line: 5439     Source: ROMS/Nonlinear/nesting.F

 PUT_REFINE3D - unbounded contact points temporal:  interpolation:
  cr       = 01        dg         = 01        ng         = 02
  iic(dg)  = 8764801   told       = 1         tnew       = 2
  iic(ng)  = *******   Wold       = ********  Wnew       = ********
  time(ng) = *******   time(told) = *******   time(tnew) = *******
 Found Error: 08   Line: 5929     Source: ROMS/Nonlinear/nesting.F
 Found Error: 08   Line: 6273     Source: ROMS/Nonlinear/nesting.F
 Found Error: 08   Line: 570      Source: ROMS/Nonlinear/nesting.F
 Found Error: 08   Line: 570      Source: ROMS/Nonlinear/nesting.F

Does anybody have idea about this error. Please let me know

**Comment by jcwarner-usgs** [comment]
Brandy sent the whole out file, and I see this:

NLM: GET_STATE - Reading state initial conditions,                       2019-01-01 00:00:00.00
                   (Grid 01, t = 1826.0000, File: exp_his_01827.nc, Rec=0001, Index=1)
...
 NLM: GET_STATE - Reading state initial conditions,                       2019-01-02 00:00:00.00
                   (Grid 02, t = 1827.0000, File: Concorde_Nest_MSS_BaySt_01827_init.nc, Rec=0001, Index=1)

so the init files are starting at different times (off by 1 day).

is see t=1826 is 2019-01-01.
dstart =0.
and
20140101.00  time_ref
so i guess 2019-01-01 is 1826 days after 20140101.


 NL ROMS/TOMS: started time-stepping: (Grid: 01 TimeSteps: 000008764801 - 000009340800)
 NL ROMS/TOMS: started time-stepping: (Grid: 02 TimeSteps: 000026308801 - 000028036800)
...
   8764800 2019-01-01 00:00:00.00  1.233864E-02  2.437923E+02  2.438046E+02  6.428529E+11  01
  26308800 2019-01-02 00:00:00.00  9.324909E-03  7.402117E+01  7.403049E+01  2.153949E+09  02

so the 2 grids are starting on different days and that is causing the error.
get grid 2 to start on 2019-01-01

see if that helps.
-j

**Comment by shihab-saran** [comment]
Hi John,
Thanks for your prompt response. Following Brandy's suggestion, I have
edited the initial file and use the same date reference for parent and
nested initial files. But unfortunately I am getting the same error. Now I
am puzzled. I have attached the edited input files for your kind perusal. I
will be grateful if you kindly let me know what else I need to check.
Thanks again.

Regards,
Shihab Hossain Saran.
Graduate Research Assistant,
Division of Marine Science, University of Southern Mississippi

**Comment by jcwarner-usgs** [comment]
you need to modify the times in
 Concorde_Nest_MSS_BaySt_01827_init.nc

**Comment by jcwarner-usgs** [comment]
is this fixed  now?

**Comment by shihab-saran** [comment]
Sorry for late reply, JcWarner. I am happy to share that it is fixed now and the model is running its job.
