### ISSUE TITLE
Unable to change wave roughness setting

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#123]
Hi John,
I wanted to work on different wave roughness parameters and I knew I needed to choose one of these parameters.

#define COARE_TAYLOR_YELLAND

#define COARE_OOST

#define Drennan

But I don't know why the wrf results don't change after I set each of the three parameters. These wave roughness parameters do not have an effect on the wind field of wrf and I would like to know why this is?Do I have to undef DRAGLIM_DAVIS?
Can you kindly help me how to apply these scheme for WRF model.
[mangkhut_DRENNAN.h.txt](https://github.com/jcwarner-usgs/COAWST/files/10859853/mangkhut_DRENNAN.h.txt)
[mangkhut_COARE_OOST.h.txt](https://github.com/jcwarner-usgs/COAWST/files/10859854/mangkhut_COARE_OOST.h.txt)
[mangkhut_COARE_TAYLOR_YELLAND.h.txt](https://github.com/jcwarner-usgs/COAWST/files/10859855/mangkhut_COARE_TAYLOR_YELLAND.h.txt)

**Comment by jcwarner-usgs** [comment]
for WRF, you need to be using the WRF/phys/module_sf_mynn.F or myjsfc.F routines.
look in those and you will see code like this: 

#if defined SWAN_COUPLING || defined WW3_COUPLING
# if defined COARE_TAYLOR_YELLAND
          ZNT(I)=MAX(1200.0*HWAVE(I)*                                   &
     &           (HWAVE(I)/(LWAVEP(I)+0.001))**4.5+                     &
     &            0.11*VISC/(UST(I)+0.001),1.59E-5)
# elif defined DRENNAN
          CWAVE=MAX(LWAVEP(I)/(PWAVE(I)+0.001),0.1)
          ZNT(I)=MAX(3.35*HWAVE(I)*(MIN(UST(I)/CWAVE,0.1))**3.4+        &
     &           0.11*VISC/(UST(I)+0.001),1.59E-5)
# elif defined COARE_OOST
          CWAVE=MAX(LWAVEP(I)/(PWAVE(I)+0.001),0.1)
          ZNT(I)=MAX(25.0/3.141593*LWAVEP(I)*                           &
     &           (MIN(UST(I)/CWAVE,0.1))**4.5+                          &
     &           0.11*VISC/(UST(I)+0.001),1.59E-5)
# else
!         ZNT(I)=CZ0*UST(I)*UST(I)/G+bvisc/ust(i)                                   
          ZNT(I)=0.016*UST(I)*UST(I)/G+1.5E-5/ust(i)
# endif
#else
....

You would most likely (unfortunately) need to recompile the whole thing for each change.
So first check the WRF/phys/module_sf_mynn.f90  or myjsfc.f90 and see if those sections of code were activated for each time you built it (for drennan or oost etc).
Then you need to make sure you are using one of those sfclay options: 
sf_sfclay_physics = 5   mynn 
sf_sfclay_physics = 2 myj 

here are all the schemes, but we only coded the waves for 2 and 5:

 sf_sfclay_physics (max_dom)         surface-layer option (old bl_sfclay_physics option)
                                     = 0, no surface-layer
                                     = 1, Revised MM5 Monin-Obukhov scheme (Jimenez, renamed in v3.6)
                                     = 2, Monin-Obukhov (Janjic) scheme
                                     = 3, NCEP Global Forecast System scheme 
                                     = 4, QNSE surface layer
                                     = 5, MYNN surface layer
                                     = 7, Pleim-Xiu surface layer (ARW only)
                                     = 10, TEMF surface layer (ARW only)
                                     = 91, Old MM5 scheme (previously option 1)

**Comment by SakuraLz** [comment]
Thank you for your reply, I think I know where the problem lies.
First of all my WRF/phys/module_sf_mynn.f90 file matches the results you gave and I think it works fine
But when I look at the namelist.input file I set
sf_sfclay_physics = 1
I think this may be the problem, I will try changing 'sf_sfclay_physics = 5' and try again.

**Comment by jcwarner-usgs** [comment]
can i close this issue?
