### ISSUE TITLE
On the setting of different wave-current interaction parameters

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#124]
I recently discovered that there are two formulas to choose from regarding wave-current interactions at COAWST
#define WEC_MELLOR
#define WEC_VF
After some experimentation, I found that these two parameters have a very dramatic effect on the ROMS results.
I know that WEC_VF is used in the Sandy case, and I see that WEC_VF is described in detail by Kurma et al.（Implementation of the vortex force formalism in the coupled ocean-atmosphere-wave-sediment transport (COAWST) modeling system for inner shelf and surf zone applications）
But how do I go about understanding the WEC_MELLOR option?
I would like to know what the difference is between these two options?
What literature should I look at? 
I would appreciate any recommendations you can give me.

**Comment by jcwarner-usgs** [comment]
strongly recommend that you use the WEC_VF from Kumar et al.
We spent over a decade trying to get the multitude of Mellor options to work, and in the end, the nearshore community did not strongly support the Mellor approach.  IF you Google for "Mellor ocean wave current interaction"  you get a lot of the papers.  There was a lot of replies from Fabric Ardhuin et al and Mellor.  You can search for all that.  here is a relevant paper

https://archimer.ifremer.fr/doc/00056/16705/14198.pdf
