### ISSUE TITLE
SCRIP_COAWST error- forrtl: severe (19): invalid reference to variable in NAMELIST input

### ISSUE THREAD

**Issue by lfpareja** [jcwarner-usgs/COAWST#126]
Hello, 
I am working on the inlet test case trying to build and run SCRIP_COAWST in the trunk
I am in my trunk folder /coawst2/trunk/Projects/Inlet_test/DiffGrid and have all the grids in the same folder (in this case roms and swan grids). 

I execute: 
`scrip_coawst scrip_coawst_inlet_test_diffgrid.in
`
and I get the error: 

```
 ================================================
  Read input_file for SCRIP_COAWST Wrapper
 ================================================
forrtl: severe (19): invalid reference to variable in NAMELIST input, unit 0, file /cache/home/lfp33/coawst2/trunk/Projects/Inlet_test/DiffGrid/scrip_coawst_inlet_test_diffgrid.in, line 16, position 11
Image              PC                Routine            Line        Source
scrip_coawst       00000000007C24F3  Unknown               Unknown  Unknown
scrip_coawst       00000000007E1F68  Unknown               Unknown  Unknown
scrip_coawst       000000000045603A  Unknown               Unknown  Unknown
scrip_coawst       000000000040441E  Unknown               Unknown  Unknown
libc-2.17.so       00002B789E7CE555  __libc_start_main     Unknown  Unknown
scrip_coawst       0000000000404329  Unknown               Unknown  Unknown

```

The contents of the script are:

```
$INPUTS
!
!  Input file for scrip_coawst.
!  The $INPUTS line is required at the top of this file.
!  Edit this file to enter the correct information below.
!  Then run this program as "./scrip_coawst[.exe] scrip_coawst_inlet_test_diffgrid.in"
!
! 1) Enter name of output netcdf4 file
!
OUTPUT_NCFILE='scrip_inlet_test_diffgrid.nc'

! 2) Enter total number of ROMS, SWAN, WW3, and WRF grids:
!
NGRIDS_ROMS=1,
NGRIDS_SWAN=1,
NGRIDS_WW3=0,
NGRIDS_WRF=0,
NGRIDS_HYD=0,

! 3) Enter name of the ROMS grid file(s):
!
ROMS_GRIDS(1)='inlet_test_grid.nc',

! 4) Enter SWAN information:
!    -the name(s) of the SWAN grid file(s) for coords and bathy.
!    -the size of the SWAN grids (full number of center points), and
!    -if the swan grids are Spherical(set cartesian=0) or
!                           Cartesian(set cartesian=1).
!
!
SWAN_COORD(1)='inlet_test_grid_coord2.grd',
SWAN_BATH(1)='inlet_test_bathy2.bot',
SWAN_NUMX(1)=87,
SWAN_NUMY(1)=82,
CARTESIAN(1)=1,

! 5) Enter WW3 information
!    -the name(s) of the WW3 grid file(s) for x- y- coords and bathy.
!    -the size of the WW3 grids (full number of grid center points).
!
WW3_XCOORD(1)=' ',
WW3_YCOORD(1)='',
WW3_BATH(1)='',
WW3_NUMX(1)=1,
WW3_NUMY(1)=1,

! 6) Enter the name of the WRF input grid(s). If the grid is a
!    moving child nest then enter that grid name as 'moving'.
!    Also provide the grid ratio, this is used for a moving nest.
!
WRF_GRIDS(1)='wrfinput_d01',
PARENT_GRID_RATIO(1)=1,
PARENT_ID(1)=0

! 7) Enter the name of the WRF Hydro input grid(s).
!
HYDRO_GRIDS(1)='../../WRF_hydro/forcings/WRF-Hydro/DOMAIN/Fulldom_hires.nc',

!
!  The $END statement below is required
!
$END
```

**Comment by jcwarner-usgs** [comment]
so i have a new version of code, i cd into Lib/SCRIP_COAWST, i changed the makefile to use gfortran, type make, it built. and then in the Lib/SCRIP_COAWST folder i just type
 ./scrip_coawst scrip_coawst_inlet_test_diffgrid.in

and then it ran:


 ================================================
  Read input_file for SCRIP_COAWST Wrapper
 ================================================
 Ngrid_roms=           1
 Ngrid_swan=           1
 Ngrid_ww3=            0
 Ngrid_wrf =           0
 Ngrid_hyd =           0
 Common netcdf file is: scrip_inlet_test_diffgrid.nc                                               
 Number of netcdf subgroups            2
 Input ROMS grid 1  = ../../Projects/Inlet_test/DiffGrid/inlet_test_grid.nc
 Input SWAN grid 1  = ../../Projects/Inlet_test/DiffGrid/inlet_test_grid_coord2.grd
 Input SWAN bath 1  = ../../Projects/Inlet_test/DiffGrid/inlet_test_bathy2.bot
 Cartesian input In meters=                    1
 ================================================
 Reading ROMS grids
 Reading SWAN grids
 ROMS and SWAN same grids (0=no or 1=yes)            0
 Calling ocn2wav_mask
 =============================================
 Begin mapping between the two grids
 ---------------------------------------------
 The interp file is: ocn1_to_wav1_weights.nc                                                       
 The src grid is: ../../Projects/Inlet_test/DiffGrid/inlet_test_grid.nc                            
 The dst grid is: ../../Projects/Inlet_test/DiffGrid/inlet_test_grid_coord2.grd                    
 ----------------------------------------------
 grid1 dimensions=          77          72
 ----------------------------------------------
 ----------------------------------------------
 grid2 dimensions=          87          82
 ----------------------------------------------
 Using latitude bins to restrict search.
  Computing remappings between: ../../Projects/Inlet_test/DiffGrid/inlet_test_grid.nc              
                           and  ../../Projects/Inlet_test/DiffGrid/inlet_test_grid_coord2.grd      
 -------------------------------------------
 Reached the end of mapping one set of grids
 Calling wav2ocn_mask
 =============================================
 Begin mapping between the two grids
 ---------------------------------------------
 The interp file is: wav1_to_ocn1_weights.nc                                                       
 The src grid is: ../../Projects/Inlet_test/DiffGrid/inlet_test_grid_coord2.grd                    
 The dst grid is: ../../Projects/Inlet_test/DiffGrid/inlet_test_grid.nc                            
 ----------------------------------------------
 grid1 dimensions=          87          82
 ----------------------------------------------
 ----------------------------------------------
 grid2 dimensions=          77          72
 ----------------------------------------------
 Using latitude bins to restrict search.
  Computing remappings between: ../../Projects/Inlet_test/DiffGrid/inlet_test_grid_coord2.grd      
                           and  ../../Projects/Inlet_test/DiffGrid/inlet_test_grid.nc              
 -------------------------------------------
 Reached the end of mapping one set of grids
 end of scrip package


I can not recreate your error.  
For me, line 16 is
# The USE_MPF90 will activate the call to mpif90.

can you try to run it from the Lib/SCRIP_COAWST folder just as i did above?  you would not need to change any paths.

**Comment by lfpareja** [comment]
Forgot to update. This worked, thanks.
