### ISSUE TITLE
coawst for tropical cyclone simulation duration

### ISSUE THREAD

**Issue by jc-suen** [jcwarner-usgs/COAWST#129]
Hello
I found that if I start the coawst simulation a few days before a tropical cyclone appears, the tc path shift is very strong. So can the simulation only be started at the beginning of the cyclone? I see that the sandy case also starts at the beginning of the cyclone. If I want to compare the response of the ocean in the month before and the month after the TC, can I only run the roms for one month alone with the forcing field file without coupling, and then coupled for the next month? Or do I only couple when the TC appears and run the roms separately for the rest of the time?

**Comment by jcwarner-usgs** [comment]
yes i saw your post on the other site and just responded the same thing there.
The Sandy test case is a test case. I do that for purposes to demonstrate a procedure for setting up and running the coupled system. The grids are very coarse, and the simulation is short, just to show how to do things.
Every event is different. I encourage you to start with just WRF, and run that for the duration that you want to simulate. Then run ROMS for that duration. Then run them coupled. TCs are extreme events, and even the most robust high resolution forecast models do not get them correct. You will need to try many things.  There are applications of the coupled system for longer durations. You can look here for some other examples:  https://github.com/jcwarner-usgs/COAWST/wiki/Publications

**Comment by jc-suen** [comment]
Thank you very much for your answer, I will study the simulation in comparison to the reference catalogue you gave.
