### ISSUE TITLE
A bug for read LBC from the XXX.in ,when use LMD_MIXING and WEC

### ISSUE THREAD

**Issue by site291** [jcwarner-usgs/COAWST#132]
The BUG like this :
If active the LMD_MIXING and WEC, the Wec LBC is different from the in file ：
For the in ：
   LBC(isFsur) ==   Che     Che     Che     Clo         ! free-surface
   LBC(isUbar) ==   Shc     Shc     Shc     Clo         ! 2D U-momentum
   LBC(isVbar) ==   Shc     Shc     Shc     Clo         ! 2D V-momentum
   LBC(isUvel) ==   RadNud  RadNud  RadNud  Clo         ! 3D U-momentum
   LBC(isVvel) ==   RadNud  RadNud  RadNud  Clo         ! 3D V-momentum
   LBC(isMtke) ==  RadNud  RadNud  RadNud  Clo         ! mixing TKE
   LBC(isTvar) ==   RadNud  RadNud  RadNud  Clo \       ! temperature
                             RadNud  RadNud  RadNud  Clo         ! salinity
! Wec boundary conditions
   LBC(isU2Sd) ==   Clo     Clo     Clo     Clo         ! 2D U-stokes
   LBC(isV2Sd) ==   Clo     Clo     Clo     Clo         ! 2D V-stokes
   LBC(isU3Sd) ==   Clo     Clo     Clo     Clo         ! 3D U-stokes
   LBC(isV3Sd) ==   Clo     Clo     Clo     Clo         ! 3D V-stokes

But the out file is:
  Lateral Boundary Conditions: NLM
 ============================
 Variable               Grid  West Edge    South Edge   East Edge    North Edge
 ---------              ----  ----------   ----------   ----------   ----------
 zeta                     1   Chapman Exp  Chapman Exp  Chapman Exp  Closed
 ubar                     1   Shchepetkin  Shchepetkin  Shchepetkin  Closed
 vbar                     1   Shchepetkin  Shchepetkin  Shchepetkin  Closed
 u                        1   Rad + Nud    Rad + Nud    Rad + Nud    Closed
 v                        1   Rad + Nud    Rad + Nud    Rad + Nud    Closed
 temp                     1   Rad + Nud    Rad + Nud    Rad + Nud    Closed
 salt                     1   Rad + Nud    Rad + Nud    Rad + Nud    Closed
 ubar_stokes              1   Rad + Nud    Rad + Nud    Rad + Nud    Closed
 vbar_stokes              1   Closed       Closed       Closed       Closed
 u_stokes                 1   Closed       Closed       Closed       Closed
 v_stokes                 1   Closed       Closed       Closed       Closed

the ubar_stokes likes get the salt LBC.
  so ,I find the code in Module/mod_ncparam.F:

 #if defined SOLVE3D && (defined GLS_MIXING || defined MY25_MIXING)
      isMtke=isTvar(MT)+1                     ! turbulent variables
 #endif
      ic=ic+1   ! counter logic seems off for Wvel, need to add one for Mtke

I change the coda like this and it‘s work:
#if defined SOLVE3D && (defined GLS_MIXING || defined MY25_MIXING)
      isMtke=isTvar(MT)+1                     ! turbulent variables
      ic=ic+1                                 ! counter logic seems off for Wvel, need to add one for Mtke
#endif
      !ic=ic+1   ! counter logic seems off for Wvel, need to add one for Mtke

**Comment by jcwarner-usgs** [comment]
sorry for the late reply.  yes you are correct.  thanks for the update.
-j
