### ISSUE TITLE
WRF model real.exe run error

### ISSUE THREAD

**Issue by NareshGaneshi** [jcwarner-usgs/COAWST#133]
Can anyone help me in solving following error while ./real.exe

********************
[Thu Apr 20 19:26:58 2023] [unknown] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(537): 
MPID_Init(249).......: channel initialization failed
MPID_Init(638).......:  PMI2 init failed: 1 
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source             
real.exe           0000000002971B3A  for__signal_handl     Unknown  Unknown
libpthread-2.22.s  00002B18842E1B20  Unknown               Unknown  Unknown
libc-2.22.so       00002B188481F8C7  gsignal               Unknown  Unknown
libc-2.22.so       00002B1884820C9A  abort                 Unknown  Unknown
libmpich_intel.so  00002B1883A282C8  Unknown               Unknown  Unknown
libmpich_intel.so  00002B18839B2182  MPIR_Handle_fatal     Unknown  Unknown
libmpich_intel.so  00002B18839B2276  MPIR_Err_return_c     Unknown  Unknown
libmpich_intel.so  00002B1883937364  MPI_Init              Unknown  Unknown
libmpich_intel.so  00002B1883984E97  MPI_INIT              Unknown  Unknown
real.exe           0000000000869E5B  Unknown               Unknown  Unknown
real.exe           000000000131EEF9  Unknown               Unknown  Unknown
real.exe           000000000040F8BF  Unknown               Unknown  Unknown
real.exe           000000000040F7CE  Unknown               Unknown  Unknown
libc-2.22.so       00002B188480B6D5  __libc_start_main     Unknown  Unknown
real.exe           000000000040F6E9  Unknown               Unknown  Unknown
Aborted (core dumped)
**************************

**Comment by jbzambon** [comment]
Naresh,

How are you invoking real.exe? Are you using a job submit script for your HPC (e.g. slurm)? Are you calling mpiexec or whatever your HPC setup requires? If it can't find libmpich, that suggests to me something is wrong with your environment or how you're invoking the executable.

-Joe

**Comment by NareshGaneshi** [comment]
No I am not using any Job submit scrip for HPC.
I am calling "mpirun -np 10 ./real.exe" for run

**Comment by jcwarner-usgs** [comment]
do me a favor and try it this way.
compile COAWST with just 
#define WRF_MODEL
run real
and then re-compile coawst as coupled and run it coupled.

**Comment by NareshGaneshi** [comment]
@jcwarner-usgs 
how to compile COAWST?

**Comment by jcwarner-usgs** [comment]
are you using COAWST? 
there is a user manual word doc, and there are tutorials on line here:
https://drive.google.com/drive/folders/1OIV4r5lym-kRiBvuOMpojjySXgxWDsZy

**Comment by NareshGaneshi** [comment]
Thank you for sharing manual. Do you have other method to fix this error?

**Comment by jcwarner-usgs** [comment]
i am unclear as to what you are really doing.
seems like you are running real.exe and having an issue.
how did you compile the code?  can you send the full build log?

**Comment by NareshGaneshi** [comment]
Thank you for asking. I resolved the issue
