### ISSUE TITLE
Error in wrf-roms-swan tide level simulation

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#134]
When I used the WRF-ROMS-SWAN coupled simulation, I found that the simulated results of the water level differed considerably from the actual measurements. There was a 6 hour error in the phase at the highest water level. But before the typhoon the water level simulation results are relatively good. 
If only the ROMS model is used, the simulated results are in good agreement with the tide table predictions. I would like to know what the problem is?

**Comment by jcwarner-usgs** [comment]
you need to look at the winds and the waves.  IF you just used roms, what winds did you use?
How do those winds compare to WRF?

**Comment by SakuraLz** [comment]
I didn't couple wrf in the roms model, so I don't think I used any wind field data.Here is my roms file.
I think my model has some problems with the coupling of the WRF and ROMS. Maybe there is a bias in the timing of the wind? I am not sure what to change.
[roms_xxx_r.txt](https://github.com/jcwarner-usgs/COAWST/files/11344951/roms_xxx_r.txt)

**Comment by jcwarner-usgs** [comment]
i am a little confused on what you are saying/doing.
First, you need to make sure the winds are correct. That will control the surge. 

Where are you getting the winds from?

**Comment by SakuraLz** [comment]
I am sorry I made some mistakes in my previous reply. I don't understand if my interpretation of the model is correct.
In the roms model, I only used tidal forcing(no wind forcing)(Do I have to use the wind file here?)
FRCNAME = Projects/Sandy/tide_forc.nc
So I use the tidal forecast data to validate the roms model.

In the WRF-ROMS model. I use data from NCEP Final Analysis (GFS-FNL) as initial and boundary conditions for the wrf calculations. 
I have used actual measured water levels for validation. The validation results were not satisfactory.

**Comment by jcwarner-usgs** [comment]
if you run roms with no wind, that is ok.  but the ocean will not be affected by the winds. so the results will mostly just be tidal.
What do those plots look like (similar to the ones above, but the model will not have the elevated tidal signal, right?)

if you run roms+wrf, and then you get the plots above?
That would be telling me that the winds are not that good.  The winds are probably early.
Can you compare the model winds to observed winds?
If you are not happy with the WRF winds, then run WRF by itself and maybe post some messages on WRF forum. 
This forum is more on the coupling, you might not get a lot of wrf users here.

-j

**Comment by SakuraLz** [comment]
Initially, I also thought it was a problem with the wrf simulated wind field. But according to my verification results, my barometric pressure and wind speed are even later than the measured data. Yet the wrf-roms-swan coupled model does get water levels earlier than the actual measured water levels.
Due to the data, the stations for water level and barometric pressure are not the same, but this result is strange and I don't know why this is a problem.
![image](https://user-images.githubusercontent.com/44939791/235932446-920e17fd-5634-480c-a973-cb6c63abf988.png)
![image](https://user-images.githubusercontent.com/44939791/235934337-56f25310-3472-414e-b0a9-cade6acc94da.png)

**Comment by jcwarner-usgs** [comment]
yes i see.
You need to look at both time series and spatial patterns.  If the storm is located in a slightly different location, it will affect the results. this is getting more into the dynamics of your actual application. I am not really able to keep helping at this point, as it is more of your application rather than a coupling aspect. 

Some things to look at are:
if you run wrf by itself, are the winds ok? 
Then maybe you could ask on the WRF forum as to why the winds are late.  etc. 

other things to look at would be : what changes to the winds happen when you couple to roms?
etc.

**Comment by SakuraLz** [comment]
Yes, thank you very much for your suggestion, I will continue to try.
