### ISSUE TITLE
Error about roms-swan coupling results

### ISSUE THREAD

**Issue by jc-suen** [jcwarner-usgs/COAWST#146]
Hi, warner
  I was doing a coupling on roms to swan and found that there were problems with the results. I have given 32 cores to roms and 32 cores to swan, but there is a problem with the results. swan has 32 results, but I have only specified one output in its input file. And if I want to check it with matlab like ncdisp scs_hsig.nc, I get an error saying 'Unknown file format (NC_ENOTNC)', suggesting that there is a problem with the file format. How can I fix this?
  I look forward to your reply.

[ecs_swan.in.txt](https://github.com/DOI-USGS/COAWST/files/11856735/ecs_swan.in.txt)
![图片](https://github.com/DOI-USGS/COAWST/assets/112635139/5d459e97-6ed0-4fac-87cd-3b3a90cde9ad)

**Comment by jcwarner-usgs** [comment]
the job most likely did not complete correctly. can you look at the log file to make sure the job finished.

**Comment by jc-suen** [comment]
> the job most likely did not complete correctly. can you look at the log file to make sure the job finished.

`      
8640 2019-08-13 00:00:00.00  1.174736E-02  1.881414E+04  1.881416E+04  4.374022E+15
                     (047,369,11)  1.505633E-03  5.011008E-03  4.816690E-02  1.684854E+00
 ** ROMS grid  1 recv data from SWAN grid  1
SWANtoROMS Min/Max DISBOT  (Wm-2):     0.000000E+00  6.214261E-03
 == SWAN grid  1 sent wave data to ROMS grid  1
SWANtoROMS Min/Max DISSURF (Wm-2):     0.000000E+00  1.785538E-03
SWANtoROMS Min/Max DISWCAP (Wm-2):     0.000000E+00  1.438920E-02
SWANtoROMS Min/Max HSIGN   (m):        0.000000E+00  6.674656E+00
SWANtoROMS Min/Max RTP     (s):        0.000000E+00  1.118034E+01
SWANtoROMS Min/Max TMBOT   (s):        0.000000E+00  2.098691E+01
SWANtoROMS Min/Max DIR     (rad):      3.203250E-03  6.278742E+00
SWANtoROMS Min/Max DIRP    (rad):      8.726647E-02  6.195919E+00
SWANtoROMS Min/Max WLEN    (m):        1.000000E+00  1.208800E+02
 ** ROMS grid  1 sent data to SWAN grid  1
 == SWAN grid  1 recv data from ROMS grid  1
ROMStoSWAN Min/Max DEPTH   (m):        1.000000E+01  5.000000E+03
ROMStoSWAN Min/Max WLEV    (m):       -6.305735E-02  1.635021E+00
ROMStoSWAN Min/Max VELX    (ms-1):    -1.212339E+00  1.279229E+00
ROMStoSWAN Min/Max VELY    (ms-1):    -9.531823E-01  1.283060E+00
ROMStoSWAN Min/Max ZO      (m):        5.000000E-02  5.000000E-02
Failed to append data to this file. It would result in a irregular record axis

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

WRT_HIS     - wrote history     fields (Index=1,1) in record = 25
WRT_AVG     - wrote averaged    fields             in record = 24

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

Process name: [[30937,1],32]
Exit code:    2

`
**_The log file does have a message at the end that it is not completed correctly. What could be the cause of this error? Maybe the dt setting on swan is too large? In the COMPUTE section of swan's input I set the time to the same dt as the 2 mode coupling, could this be the reason for the error?_**

**Comment by jcwarner-usgs** [comment]
i have never seen this before, but i did the google.
https://github.com/sandialabs/SNL-SWAN/blob/master/src/agioncmd.ftn90
looks like it is trying to write to a netcdf file.
try to run without SWAN writing to netcdf files, just to see if it works.

what does your swan.in look like?



John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
***@***.******@***.***>

https://www.usgs.gov/staff-profiles/john-warner


________________________________
From: jc-suen ***@***.***>
Sent: Saturday, June 24, 2023 11:44 AM
To: DOI-USGS/COAWST ***@***.***>
Cc: Warner, John C ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [DOI-USGS/COAWST] Error about roms-swan coupling results (Issue #146)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



the job most likely did not complete correctly. can you look at the log file to make sure the job finished.

`
8640 2019-08-13 00:00:00.00 1.174736E-02 1.881414E+04 1.881416E+04 4.374022E+15
(047,369,11) 1.505633E-03 5.011008E-03 4.816690E-02 1.684854E+00
** ROMS grid 1 recv data from SWAN grid 1
SWANtoROMS Min/Max DISBOT (Wm-2): 0.000000E+00 6.214261E-03
== SWAN grid 1 sent wave data to ROMS grid 1
SWANtoROMS Min/Max DISSURF (Wm-2): 0.000000E+00 1.785538E-03
SWANtoROMS Min/Max DISWCAP (Wm-2): 0.000000E+00 1.438920E-02
SWANtoROMS Min/Max HSIGN (m): 0.000000E+00 6.674656E+00
SWANtoROMS Min/Max RTP (s): 0.000000E+00 1.118034E+01
SWANtoROMS Min/Max TMBOT (s): 0.000000E+00 2.098691E+01
SWANtoROMS Min/Max DIR (rad): 3.203250E-03 6.278742E+00
SWANtoROMS Min/Max DIRP (rad): 8.726647E-02 6.195919E+00
SWANtoROMS Min/Max WLEN (m): 1.000000E+00 1.208800E+02
** ROMS grid 1 sent data to SWAN grid 1
== SWAN grid 1 recv data from ROMS grid 1
ROMStoSWAN Min/Max DEPTH (m): 1.000000E+01 5.000000E+03
ROMStoSWAN Min/Max WLEV (m): -6.305735E-02 1.635021E+00
ROMStoSWAN Min/Max VELX (ms-1): -1.212339E+00 1.279229E+00
ROMStoSWAN Min/Max VELY (ms-1): -9.531823E-01 1.283060E+00
ROMStoSWAN Min/Max ZO (m): 5.000000E-02 5.000000E-02
Failed to append data to this file. It would result in a irregular record axis

Primary job terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

WRT_HIS - wrote history fields (Index=1,1) in record = 25
WRT_AVG - wrote averaged fields in record = 24

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

Process name: [[30937,1],32]
Exit code: 2

`
The log file does have a message at the end that it is not completed correctly. What could be the cause of this error? Maybe the dt setting on swan is too large? In the COMPUTE section of swan's input I set the time to the same dt as the 2 mode coupling, could this be the reason for the error?

**Comment by jc-suen** [comment]
Hi, warner
Thank you very much for your reply, I think I may have found the cause and solved it, perhaps it has something to do with the naming of PROJECT.
