### ISSUE TITLE
Unable to run coupled WRF-SWAN, but able to run them independently

### ISSUE THREAD

**Issue by adithyavemuri** [jcwarner-usgs/COAWST#148]
Hi,

I am currently running the COAWST model, specifically the coupled form of WRF + SWAN. While I have successfully executed these models independently, I have encountered an error when attempting to run them in a coupled manner. My experience primarily lies with WRF, so I am relatively new to working with the coupled framework.

The specific error message I am encountering is as follows:

MCT::m_SparseMatrix::importGlobalRowIndices_:: ERROR, lsize > lsize_(sMat).lsize = 1 lsize_(sMat) = 0
000.MCT(MPEU)::die.: from MCT::m_SparseMatrix::importGlobalRowIndices_()

I would greatly appreciate any assistance or guidance you can provide to help me overcome this issue. If there is any additional information that you require, please do not hesitate to let me know.

Thank you for your attention to this matter. 
Adithya
Ph.D. researcher, SeaFD VKI-VUB

**Comment by jcwarner-usgs** [comment]
looks like coawst is trying to get grid interpolation data from a scrip netcdf file.
Are you running wrf and swan on different grid sizes?

**Comment by adithyavemuri** [comment]
Hello dr. Warner,

Yes, I am running wrf and swan on different grid sizes.

I am not sure how that would be an issue as the case was run before by a colleague. That said, I would like to point out that, I use openmpi to compile COAWST and MCT libraries (FC=mpif90). However, I faced issues installing SCRIP_COAWST, I had to utilize the flag: make  FFLAGS=-Wno-argument-mismatch.

I would also like to point out that I am also unable to run the example case study, Sandy. I get the following error:
[~] *** An error occurred in MPI_Send
[~] *** reported by process [3933863937,2]
[~] *** on communicator MPI_COMM_WORLD
[~] *** MPI_ERR_TAG: invalid tag
[~] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[~] ***    and potentially your MPI job)

**Comment by jcwarner-usgs** [comment]
ok there are several issues being discussed here and i want to keep them separate.

for script - if you used gfortran you may need to add that -allow-argument-mismatch. but that should have been in the Compilers file. What is your compiler (gfortran or ifort?)

for Sandy - that mpi error is the last thing that ended.  The actual error was something before that.   look in the log file to see what the first problem was.

for the grid size mismatch - if you just use the previous scrip weights file, does it work?

**Comment by adithyavemuri** [comment]
Apologies for create several issues in a single thread. I am under the assumption these are linked.

For script - I am using gfortran compiler, with GCC --version 9.3.0. From my understanding the flag "allow-argument-mismatch" was introduced in 10.0. Which was my reason for modifying the Linux-gfortran.mk. As scrip would not compile without commenting this flag.

For Sandy - Please find attached the log file from the run. I could not find an error apart from the MPI. Perhaps I am missing something?
[log_run.txt](https://github.com/DOI-USGS/COAWST/files/11960673/log_run.txt)

For grid mismatch - It has come to my attention that we had trouble running the model at our workstations in the past. I tried running the setup with the previous scrip weights, but I receive the same error as my initial post:

MCT::m_SparseMatrix::importGlobalRowIndices_:: ERROR, lsize > lsize_(sMat).lsize = 1 lsize_(sMat) = 0
000.MCT(MPEU)::die.: from MCT::m_SparseMatrix::importGlobalRowIndices_()

**Comment by jcwarner-usgs** [comment]
for script - ok i guess you had to change that flag and now it works.  so we can call that one done.

for Sandy log_run i see at the very top
READ MODEL INPUTS - Unable to open wrf input file.
Project/Sandy/namelist.input               
Can you make sure the namelist.input file is in the root dir with the coawstM?  I think wrf looks for it at the same dir as teh coawstM, not down in the Proj folder.
then edit the coupling.in to just say namelist.input, not Projects/Sandy/namelist.input.

for the grid mismatch- can i see the full output of that run?

**Comment by adithyavemuri** [comment]
Thanks, you were correct, the path to namelist.input was missing and I was running the simulation from the projects folder.

For sandy: please find attached the log of the run. I still get these 3 flags as notes. I am not sure what is causing them:
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_UNDERFLOW_FLAG
[log_run_sandy.txt](https://github.com/DOI-USGS/COAWST/files/11998813/log_run_sandy.txt)

For grid-mismatch (internal run): I was running the case similar to Sandy, from the project folder. Please find attached the log for the correct run. I get a segmentation fault at the coupling of wrf and swan. 
[log_run_fino.txt](https://github.com/DOI-USGS/COAWST/files/11998886/log_run_fino.txt)

Any advice would be helpful, thank you.

**Comment by jcwarner-usgs** [comment]
for the first one:  those ieee underflow flags are just saying a warning at exit.  Looks like that run worked fine.  you can disregard those ieee warnings.

for the run_fino:  i see:
ATMgrid 02 dt=   3.3 -to- WAVgrid 01 dt=  90.0, CplInt:  1800.0 Steps: ***
ATMgrid 03 dt=   0.7 -to- WAVgrid 01 dt=  90.0, CplInt:  1800.0 Steps: ***

you need to make sure all the grid time steps divide evenly. 
wave grid 1 time step is 90 and atm grid 2 is at 3.3  So 90/3.3 is not an integer.
maybe try: atm grids at 9 3 and 1 sec
waves at 90 and 30
coupling at 1800 
should work

**Comment by adithyavemuri** [comment]
For Sandy, 
Noted, thank you.

For run_fino: I tried running the wrf with 9 3 1, but I still get the same error, please refer the log file below
[log_run_fino_931.txt](https://github.com/DOI-USGS/COAWST/files/12028098/log_run_fino_931.txt)

I also tried the simulation with a larger wrf timestep of 90 30 10, resulting in the same error
[log_run_fino.txt](https://github.com/DOI-USGS/COAWST/files/12028080/log_run_fino.txt)

**Comment by jcwarner-usgs** [comment]
are you getting any Err* files from SWAN?
is there anything strange in the PRINT files?

**Comment by jcwarner-usgs** [comment]
can i see your swan input files (both of them)

**Comment by adithyavemuri** [comment]
Thank you dr. Warner for your fast responses and for guiding me through the COAWST simulations.  I was able to resolve the issue from the PRINT files. I had initially turned off QUAD as it was causing some errors when running from the projects folder, I do not have the log for it.
 
Please find attached the log of the completed run for a short period of 2 hours. I refrain from sharing the input files for now unless you request them.
[log_run_fino.txt](https://github.com/DOI-USGS/COAWST/files/12039441/log_run_fino.txt)

**Comment by jcwarner-usgs** [comment]
glad things are progressing.
so is it all working now?  can we close this ticket.

**Comment by adithyavemuri** [comment]
Yes! Thanks for the help!

**Comment by adithyavemuri** [comment]
Hello dr. Warner, 

Over the past week, I have been making my setup for the WRF+SWAN model. I have run into 2 main errors when using the Matlab script from the coawst tutorial.

1. I get the following error when running the script ncei_swan when downloading and creating the wind-forcing dat file. I have cross-checked if the URL is working. 
On Matlab 2019b and 2022a, I have tried nctoolbox 2012, and the latest one avail on Git Hub.
"The NetCDF library encountered an error during execution of 'open' function - 'Malformed or inaccessible DAP DDS (NC_EDDS)'.
If the data source was an  OPeNDAP URL, see the OPeNDAP Troubleshooting section in the Users Guide."

2. When utilizing bathymetry from the following sources and running SWAN independently with a 25m/s wind forcing, the significant wave height always remained less than 1m (for a 1-day run) which seemed unrealistic to me. I would like to have your opinion on this. I have attached the input files for swan for your reference.
- ETOPO2v2f, ETOPO2v2c, ETOPOv1 2022, and GEBCO.
[swan_fino.txt](https://github.com/DOI-USGS/COAWST/files/12110164/swan_fino.txt)
[swan_fino_ref3.txt](https://github.com/DOI-USGS/COAWST/files/12110165/swan_fino_ref3.txt)

Thank you

**Comment by jcwarner-usgs** [comment]
ok.  i suggest you do not use the nctoolbox.  just use the built-in matlab features now.
sometimes the opendap will time out if you ask for too much data at once.  try to create a shorter wind file just to see if the method works (like just try for 1 day to see if it works), then change to a longer time period.

you will have to look at the bathy file to make sure the values look reasonable. i cant tell from the input file.
change
&INIT 
to
INIT
i dont think you need the INPGRID WIND command and the associated nonstat commmand if you use
WIND SPD DIR
so try this:
&INPGRID WIND REGULAR -20 45 0 450 250 0.1 0.1 &
&NONSTATIONARY 20201218.000000 1 HR 20201224.000000
& READINP WIND 1 '/storage/wrf/nobackup/vemuri/COAWST_VKI/Projects/Case_LP/swan_2010_init_nonstat_w25.dat' 4 0 FREE
WIND 10. 25.

BLOCK 'COMPGRID' NOHEADER 'wind.mat'   LAY 4 WIND 1.   OUTPUT 20201218.000000 1 HR
and see what the winds look like
BLOCK 'COMPGRID' NOHEADER 'hsig.mat'   LAY 4 HSIGN 1.  OUTPUT 20201218.000000 1 HR

**Comment by adithyavemuri** [comment]
1. I tried running the ncei_swan script without the nctoolbox for a single day, it still fails with the same error. After a plethora of trials I ultimately resorted to downloading ERA5 reanalysis and creating the wind data input. Which is working fine now.
2. Thank you for the corrections to my input file. Similar to the wind data, I used the ERA5 bathymetry product for swan instead of the products I mentioned earlier. I am able to get reasonable wind and hsig output from swan.

I was wondering if there was a to run swan with varying bathymetry files? As ERA5 provides the product for each day, I would like to utlize them. Any advice would be helpful.

Thanks

**Comment by jcwarner-usgs** [comment]
sorry you had troubles.  it is most likely the internet connection, but sometimes the noaa servers get busy.
glad it seems to work now.
We run swan with vary bathymetry in coawst, with morphology updating as we study barrier island breaching during hurricanes.  we predict how the morphology will change. But i dont think that is what you want.

So i went to the ERA5 page and i see they have bathy
"Model bathymetry	m	This parameter is the depth of water from the surface to the bottom of the ocean. It is.."

But what spatial scale is this?  I am not sure how accurate the global bathy data would be for the last 50 years. 
I suggest you first look at that data and see if it makes sense.
SWAN can have time dependent, you would need to make an input ASCII file with bathy for (lets say) every month and then use a command like:


INPGRID BOTTOM CURVILINEAR 0 0 86 64 EXC 9.999000e+003
READINP BOTTOM 1 'Projects/Sandy/Sandy_swan_bathy.bot' 4 0 FREE  &
       NONSTATIONARY 20000100.000000 30 DAY 20010000.000000
something like that

**Comment by adithyavemuri** [comment]
Hello dr. Warner, apologies for my late reply. 
I see thanks for the insight, you are right my requirement is not to understand the morphology but rather the atmospheric dynamics when coupled to swan under extreme weather.

The resolution of ERA5 is maintained at 0.25deg =~ 30km. The data does make sense from my knowledge of the North Sea, with an average depth of around 50m.

Thanks for providing a guide on how to provide continuous bathy to swan, I think given the scope of the project I will keep this record for later use.

With that said, thanks for the support again. I hope not to reopen this ticket, haha.

Adithya

**Comment by adithyavemuri** [comment]
Hello dr. Warner, I apologize for reopening this ticket again, I am looking into retrieving high-resolution wave elevation from swan at 0.25s as I intend to couple this to access loading. I notice the swan manual does not specify wave elevation as part of its swan's default output variables.

That said, does it physically make sense to run swan at very low timesteps such as 0.25s? Would I be observing excess dissipation similar to WRF?

Also, is there a way for me to retrieve an equivalent Johnswap spectrum from swan out, to determine the shape parameter?

Thank you

**Comment by jcwarner-usgs** [comment]
These sound like questions specific to SWAN.  I suggest you read the SWAN manual or look on a SWAN user forum to ask those questions.
SWAN is a spectral wave model, not a free surface resolving model. So a 0.25s time step seems too small to me.
The type of output from swan is discussed in the swan manual.  You can write out 1D or 2D spectra at different points.
You can see all that here:
https://gitlab.tudelft.nl/citg/wavemodels/swan
https://swanmodel.sourceforge.io/online_doc/swanuse/swanuse.html
