### ISSUE TITLE
unable to run real.exe and coawstM (segmentation fault error)

### ISSUE THREAD

**Issue by almacarolina** [jcwarner-usgs/COAWST#150]
Dear forum,

With the help of this forum, I have finally compiled COAWST using a Cray compiler, and the appropriate .exe files and coawstM file have been created (although with some warnings and errors when compiled). The problem I am having now is that when I try to run real.exe after compiling only WRF through COAWST or just using the WRF code by itself or when I try to run coawstM after compiling only ROMS I get the following error.
srun: error: nid00236: tasks 64-95: Segmentation fault
What is weird to me is that I am able to run roms using just romsM when I compile ROMS by itself (I should point out that romsM was compiled before some compiler updates were made on the HPC). Any suggestions on how to debug this problem appreciated since again the HPC helpdesk seems really confused.

Alma

**Comment by jcwarner-usgs** [comment]
is there more in the std out other than just that error?
are you building any of our test cases?

**Comment by almacarolina** [comment]
This is the full output:
Due to MODULEPATH changes, the following have been reloaded:
  1) intel-classic/2022.2.1


Due to MODULEPATH changes, the following have been reloaded:
  1) intel-classic/2022.2.1

srun: error: nid00251: task 0: Segmentation fault
srun: Terminating StepId=206558137.0

I was building my northwest Atlantic Model that had previously worked without errors on WHOI Poseidon HPC.

**Comment by jcwarner-usgs** [comment]
i am not sure. 
if it worked before on poseidon, then it must be the new system you are on.
compile  a roms only case using build_coawst.sh and try to run that.
what does you command run line look like?
srun -np X ./coawstM ocean.in

can you try a test case we distribute?

**Comment by almacarolina** [comment]
I just tried the simple upwelling test using roms only and I get the segmentation fault error. I had successfully tried the upwelling test case before they did some compiler updates on the HPC  so I believe this must be something related to the system :(. Thanks a lot.

**Comment by almacarolina** [comment]
I think I am making some progress. 
I updated the HPC environment and recompiled ROMS and Coawst. I was able to run my Roms-only northwest Atlantic model just using build.bash.sh from the ROMS repository and the following command 
srun --ntasks=64 ./romsM ocean_nes.in  
But now I am having the following error when I try to run the exact same roms-only model using coawst and the following command 
srun --ntasks=64 ./coawstM ocean_nes.in

Error below:
Rank 32 [Thu Jul 13 04:58:58 2023] [c3-0c0s6n0] Fatal error in MPIR_CRAY_Bcast_Tree: Other MPI error, error stack:
MPIR_CRAY_Bcast_Tree(405): message sizes do not match across processes in the collective routine: Received 1 but expected 3
aborting job:

Thanks

**Comment by jcwarner-usgs** [comment]
how did you build the same model config using coawst?  did you use build_coawst.sh?
if it is roms only, there really should not be much differences.
are you using all new files with the new version of coawst - new build_coawst.sh, new makfile, Compilers, ocean.in etc?
-j

**Comment by almacarolina** [comment]
Hi John,

I built coawst using coawst.bash.  I am not using the new files with the newest version of coawst. Should I upgrade?

Alma

**Comment by jcwarner-usgs** [comment]
you need to use whatever build scripts came with the code.
if you are using v3.7, then you need to use coawst.bash.
if you are using v3.8 , then you need to use build_coawst.sh

**Comment by almacarolina** [comment]
Sorry for not clarifying.  I did everything with v3.7 and used coawst.bash. I did a clean and recompiled and at least the roms-only model is running on coawst! Thanks a lot

**Comment by jcwarner-usgs** [comment]
nice!
stick with 3.7 for now and get it all working.

**Comment by almacarolina** [comment]
Hi John,
Following on this same issue. As I said before I managed to compile ROMS-only in COAWST. I also managed to run real.exe to process the ERA5 files for WRF. But now I am having an issue with running WRF only through COAWST. This issue also arises If I try to run wrf.exe using the WRF code distributed by UCAR. The error appears after the 1st WRF time step is created.

srun: error: nid00727: tasks 28-55: Exited with exit code 255
srun: Terminating StepId=269303517.0

And the last lines on the log file are just this:
Timing for processing lateral boundary for domain        1:    0.46409 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y 
WRF TILE   1 IS      1 IE     20 JS      1 JE     13
WRF NUMBER OF TILES =   1  

I contacted the WRF forum and they think could be related to the compilation on Cray but I wanted to have a second opinion. I have run this model both using WRF and COAWST this WRF in Poseidon without errors. I am not even sure what else to try to debug this error.

**Comment by jcwarner-usgs** [comment]
in your namelist.input set the nproc_x and nproc_y
see if that helps.

**Comment by almacarolina** [comment]
Unfortunately, I get the same error if set the nproc_x and nproc_y to some value. I have also experimented with different numbers in nproc_x and nproc_y and I get the same error.

**Comment by jcwarner-usgs** [comment]
wrf does have a debug_level command.
i think it is in the namelist.input.
you could try setting that with a 50 or higher.

might also have to deal with memory on each node.
-j

**Comment by almacarolina** [comment]
Hi John,
Actually, the error above was solved by changing the physics part in the namelist.input. I do not understand why this happened since that configuration worked on Poseidon and just not on a Cray compiler HPC.

Anyway, I am now able to run my Northwest Atlantic model with COAWST using Roms only and WRF only but now I am having a compilation error when I try to compile WRF and ROMS together. I think it could be something related to the coupler. I attach the compilation log file. Please let me know if you have some insight into how to approach those errors.
This is an example of an error on the log file.

MODULE atm_coupler_mod
ftn-855 ftn: ERROR ATM_COUPLER_MOD, File = atm_coupler.f90, Line = 286, Column = 14
  The compiler has detected errors in module "ATM_COUPLER_MOD".  No module information file will be created for this module.^

[coawstc5.log](https://github.com/DOI-USGS/COAWST/files/12210585/coawstc5.log)
