### ISSUE TITLE
How to compile 'em_tropical_cyclone' in COAWST to conduct a coupled simulation for ideal tropical cyclone

### ISSUE THREAD

**Issue by tofei-liu** [jcwarner-usgs/COAWST#151]
Dear Warner,

Hope things are going well.
I'm considering how to conduct a coupled simulation for an ideal tropical cyclone (TC), which can be created by 'em_tropical_cyclone' in WRF. 
I have successfully compiled the 'JOE_TC/COUPLED' case, which suggests that the environment and libraries are suitable for model. However, when I tried to compile em_tropical_cyclone in the directory of 'COAWST/WRF/', it failed.  
I guess that the default compilation for WRF in COAWST is the 'em_real', is that right? I'm confused about **how to compile the idealized WRF case in COAWST**. Could you please give me some suggestions?
Thank you very much for your time and consideration.

Fu

**Comment by jcwarner-usgs** [comment]
Hello Fu-

I have not tried the idealized WRF cases in a long time. I have set up coawst to compile WRF em_real, as you saw.
I suppose you could just cd WRF and compile the code as if it was just regular WRF setup.  you would not have the coupling, but that would give you the wrf idealized case.  Or you could just download WRF from their github and run it with their setup.
I guess i am not sure what you want to do.  Do you want to use their idealized case but run it coupled?
-j

**Comment by tofei-liu** [comment]
Hi Warner,

    Thank you very much for your quick reply and valuable advices~
    As you mentioned, I plan to use idealized TC cases in WRF but run it coupled (WRF+ROMS). I want to see the ocean responses and the feedback of ocean responses to TC itself. The reason for using an idealized TC case is to avoid the influence of background field and to make the primary phenomenon cleaner and simpler. Then we can see the fundamental physical process more clearly.
    I will do more literature review. Hope I can find another way to make an idealized TC case in WRF and then run it coupled by compiling 'em_real'.

Best wishes,
Fu

**Comment by tofei-liu** [comment]
Hi Warner,

Thank you very much for your quick reply and valuable advices~
As you mentioned, I plan to use idealized TC cases in WRF but run it coupled (WRF+ROMS). I want to see the ocean responses and the feedback of ocean responses to TC itself. The reason for using an idealized TC case is to avoid the influence of background field and to make the primary phenomenon cleaner and simpler. Then we can see the fundamental physical process more clearly.
I will do more literature review. Hope I can find another way to make an idealized TC case in WRF and then run it coupled

Best wishes,
Fu

**Comment by jcwarner-usgs** [comment]
when you create the idealized cases, does it create all the files you would need to run a real case?  does it create wrflow wrfbdy and wrfinput?

**Comment by tofei-liu** [comment]
I just checked the 'WRF-ARW V3 User's Guide'. According to the 'WRF-ARW V3 User's Guide', **all idealized cases do not require a lateral boundary file, and only 'wrfinput' is created for idealized cases.**. It seems that idealized cases in WRF cannot be coupled, or we need to modify the code to make it coupled. 
Sorry to bother you. I should read the 'WRF-ARW V3 User's Guide' more carefully. 

Fu

**Comment by jcwarner-usgs** [comment]
ok.  well sorry.  Maybe you can use the JOE_TC.
i am going to close this ticket but let me know if you need help with Joetc.
-j
