### ISSUE TITLE
The "Sandy" case fails to compile when only using SWAN.

### ISSUE THREAD

**Issue by whiteliutw** [jcwarner-usgs/COAWST#152]
Hello seniors,
In the "Sandy" case, when only SWAN is used, there will be a lot of errors similar to the following when compiling. However, both ROMS+SWAN+WRF and ROMS+SWAN can be compiled successfully.

``
 /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[3]: *** [lib/CMakeFiles/swan.exe.dir/build.make:103: bin/swan.exe] Error 1
make[2]: *** [CMakeFiles/Makefile2:165: lib/CMakeFiles/swan.exe.dir/all] Error 2
make[1]: *** [Makefile:139: all] Error 2
ar: creating /home/white/COAWST/diy/Sandy/Build_roms/libROMS.a
/usr/bin/ld: /home/white/COAWST/SWAN/build/lib/libswan41.45.a(swn_outnc.f90.o): in function `__swn_outnc_MOD_swn_outnc_openblockfile':
swn_outnc.f90:(.text+0x2442): undefined reference to `__netcdf_MOD_nf90_put_att_text'
/usr/bin/ld: swn_outnc.f90:(.text+0x247b): undefined reference to `__netcdf_MOD_nf90_put_att_text'
/usr/bin/ld: swn_outnc.f90:(.text+0x2c9c): undefined reference to `__netcdf_MOD_nf90_put_att_text'
/usr/bin/ld: swn_outnc.f90:(.text+0x2cd5): undefined reference to `__netcdf_MOD_nf90_put_att_text'
/usr/bin/ld: /home/white/COAWST/SWAN/build/lib/libswan41.45.a(swn_outnc.f90.o): in function `__swn_outn`
``

``
agioncmd.f90:(.text+0x10887): undefined reference to `__netcdf_MOD_nf90_enddef'
/usr/bin/ld: agioncmd.f90:(.text+0x108a3): undefined reference to `__netcdf_MOD_nf90_redef'
/usr/bin/ld: agioncmd.f90:(.text+0x10921): undefined reference to `__netcdf_MOD_nf90_def_dim'
/usr/bin/ld: agioncmd.f90:(.text+0x10973): undefined reference to `__netcdf_MOD_nf90_def_var_onedim'
/usr/bin/ld: agioncmd.f90:(.text+0x109b0): undefined reference to `__netcdf_MOD_nf90_put_att_text'
/usr/bin/ld: agioncmd.f90:(.text+0x109e9): undefined reference to `__netcdf_MOD_nf90_put_att_text'
collect2: error: ld returned 1 exit status
make: *** [Master/Module.mk:23: /home/white/COAWST/diy/Sandy/coawstM] Error 1
``

Attached is the compilation message.
[build.log](https://github.com/DOI-USGS/COAWST/files/12167648/build.log)

Thank you for any help.

**Comment by jcwarner-usgs** [comment]
that is odd if it can build roms+swan but not swan only.
can you build roms+swan and send that log out file?
It might just be the order the libs are listed in the final link stage. not sure.

**Comment by whiteliutw** [comment]
Thanks for reply. The compilation information of ROMS+SWAN is as the following attachment.
[build_ROMS_SWAN.log](https://github.com/DOI-USGS/COAWST/files/12208396/build_ROMS_SWAN.log)

**Comment by jcwarner-usgs** [comment]
ok do you know which Compilers file you are using?
would it be Linux-gfortran.mk?
in your build_coawst.sh, did you set FORT=gfortran ?

**Comment by whiteliutw** [comment]
I compile with gfortran, using the same build_coawst.sh and Linux-gfortran.mk settings. 
Just recompiled and got the same result (ROMS+SWAN compiled successfully, SWAN failed to compile). 

I know it's weird.
The compilation message, build_coawst.sh and Linux-gfortran.mk are attached.
[build_ROMS_SWAN.log](https://github.com/DOI-USGS/COAWST/files/12246642/build_ROMS_SWAN.log)
[build_SWAN.log](https://github.com/DOI-USGS/COAWST/files/12246643/build_SWAN.log)
[build_coawst.sh.txt](https://github.com/DOI-USGS/COAWST/files/12246651/build_coawst.sh.txt)
[Linux-gfortran.mk.txt](https://github.com/DOI-USGS/COAWST/files/12246652/Linux-gfortran.mk.txt)

**Comment by jcwarner-usgs** [comment]
try to build with this version of Linux-gfortran.mk
[Linux-gfortran.mk.txt](https://github.com/DOI-USGS/COAWST/files/12251188/Linux-gfortran.mk.txt)

**Comment by whiteliutw** [comment]
thanks John.  it's worked.

PS: The output file in mat format appears corrupted. But the nc format is readable.
