### ISSUE TITLE
SWAN mode cannot use netcdf format output at the same time in multi-layer.

### ISSUE THREAD

**Issue by whiteliutw** [jcwarner-usgs/COAWST#156]
Hello everyone advanced,
I am testing the "Sandy" case only using SWAM mode, when the .in file is set to output in netcdf format, the following error occurs immediately after execution.

`NetCDF: Not a valid ID
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
STOP 1`

The setting of swan_sandy.in is
`BLOCK  'COMPGRID' NOHEADER 'Sandy_hsig.nc'   LAY 4 HSIGN 1.   OUTPUT 20121028.000000 1 HR`
The setting of swan_sandy_ref.in is
`BLOCK 'COMPGRID' NOHEADER 'Sandy_ref3_hsig.nc'   LAY 4 HSIGN 1.   OUTPUT 20121028.000000 1 HR`

Changing the output format of either swan_sandy.in or swan_sandy_ref3.in from ".nc" to ".mat" can avoid the above error message,  but the two .in files cannot be output in ".nc" format at the same time.

I'm not sure if two regions use the same NetCDF ID to cause conflicts when exporting nc files.
Could anyone please give some advice?

OS:ubuntu 22.04
compiler:Gfortran 11.4
PS: The ".txt" format output of my current nested grid simulation is normal.

**Comment by jcwarner-usgs** [comment]
yes this is an issue on my list.
If you run nested, you can only have netcdf for the parent or child, not both.
this is an issue with the way i have the concurrent grids.
Most people run this coupled to roms, and so just have the netcdf output written through roms.
-j

**Comment by whiteliutw** [comment]
Thank you for continuing to develop this coupled model.
