### ISSUE TITLE
Problems with SWAN coupling. A few undefined references

### ISSUE THREAD

**Issue by lhba87** [jcwarner-usgs/COAWST#159]
Dear all.

I received this message while installing SWAN.

`cd /home/alves/COAWST/SWAN/build/lib && /usr/bin/cmake -E cmake_link_script CMakeFiles/swan.exe.dir/link.txt --verbose=1
/opt/intel/oneapi/mpi/2021.10.0/bin/mpiifort -O2 -W0 -assume byterecl -traceback -diag-disable 8290 -diag-disable 8291 -diag-disable 8293 -I/home/alves/COAWST/Build_roms -I/home/alves/opt_intel/include CMakeFiles/swan.exe.dir/swanmain.f.o -o ../bin/swan.exe  -Wl,-rpath,/home/alves/opt_intel/lib: libswan41.45.a /home/alves/opt_intel/lib/libnetcdff.so -L/home/alves/opt_intel/lib -lnetcdff -L/home/alves/opt_intel/lib -lnetcdf -lnetcdf -lm /home/alves/opt_intel/lib/libnetcdf.so -L/home/alves/opt_intel/lib -lnetcdf /home/alves/COAWST/Build_roms/mct_coupler_params.o -L/home/alves/opt_intel/lib -lmct -lmpeu 
ld: /opt/intel/oneapi/compiler/2023.2.1/linux/bin/intel64/../../compiler/lib/intel64_lin/for_main.o: in function `main':
for_main.c:(.text+0x19): undefined reference to `MAIN__'
ld: libswan41.45.a(SwanBraggScat.f90.o): in function `swanbraggscat_mp_swbrbot_':
SwanBraggScat.f90:(.text+0x1105): undefined reference to `cfft2i_'
ld: SwanBraggScat.f90:(.text+0x275d): undefined reference to `cfft2b_'
ld: SwanBraggScat.f90:(.text+0x4fb1): undefined reference to `cfft2b_'
ld: libswan41.45.a(SwanQCM.f90.o): in function `swanqcm_mp_swqcsurf_':
SwanQCM.f90:(.text+0x332e): undefined reference to `cfft2b_'
ld: SwanQCM.f90:(.text+0x3790): undefined reference to `cfft2f_'
ld: libswan41.45.a(SwanQCM.f90.o): in function `swanqcm_mp_swqcdft_':
SwanQCM.f90:(.text+0xc679): undefined reference to `cfft2f_'
ld: SwanQCM.f90:(.text+0xd234): undefined reference to `cfft2f_'
ld: libswan41.45.a(SwanQCM.f90.o): in function `swanqcm_mp_swqcuft_':
SwanQCM.f90:(.text+0xf9d6): undefined reference to `cfft2f_'
ld: SwanQCM.f90:(.text+0x106a7): undefined reference to `cfft2f_'
ld: libswan41.45.a(swancom1.f.o): in function `swcomp_':
swancom1.f:(.text+0x72e5): undefined reference to `cfft2i_'
ld: swancom1.f:(.text+0x14470): undefined reference to `cfft2i_'
ld: libswan41.45.a(SwanCompUnstruc.f90.o): in function `swancompunstruc_':
SwanCompUnstruc.f90:(.text+0x805b): undefined reference to `cfft2i_'
ld: SwanCompUnstruc.f90:(.text+0x19a03): undefined reference to `cfft2i_'
ld: libswan41.45.a(waves_coupler.f.o): in function `waves_coupler_mod_mp_initialize_wav_coupling_':
waves_coupler.f:(.text+0x15941): undefined reference to `mod_coupler_iounits_mp_scrip_opt_'
ld: waves_coupler.f:(.text+0x15a36): undefined reference to `mod_coupler_iounits_mp_a2wname_'
ld: waves_coupler.f:(.text+0x15a54): undefined reference to `mod_coupler_iounits_mp_a2wname_'
ld: waves_coupler.f:(.text+0x15a61): undefined reference to `mod_coupler_iounits_mp_a2wname_'
ld: waves_coupler.f:(.text+0x15a69): undefined reference to `mod_coupler_iounits_mp_a2wname_'
ld: waves_coupler.f:(.text+0x15a70): undefined reference to `mod_coupler_iounits_mp_a2wname_'
ld: waves_coupler.f:(.text+0x15aa4): undefined reference to `get_sparse_matrix_'
ld: waves_coupler.f:(.text+0x16166): undefined reference to `mod_coupler_iounits_mp_scrip_opt_'
ld: waves_coupler.f:(.text+0x16267): undefined reference to `mod_coupler_iounits_mp_w2aname_'
ld: waves_coupler.f:(.text+0x16273): undefined reference to `mod_coupler_iounits_mp_w2aname_'
ld: waves_coupler.f:(.text+0x1627e): undefined reference to `mod_coupler_iounits_mp_w2aname_'
ld: waves_coupler.f:(.text+0x1628e): undefined reference to `mod_coupler_iounits_mp_w2aname_'
ld: waves_coupler.f:(.text+0x16295): undefined reference to `mod_coupler_iounits_mp_w2aname_'
ld: waves_coupler.f:(.text+0x162c9): undefined reference to `get_sparse_matrix_'
make[3]: * [lib/CMakeFiles/swan.exe.dir/build.make:103: bin/swan.exe] Error 1
make[3]: Leaving directory '/home/alves/COAWST/SWAN/build'
make[2]: * [CMakeFiles/Makefile2:165: lib/CMakeFiles/swan.exe.dir/all] Error 2
make[2]: Leaving directory '/home/alves/COAWST/SWAN/build'
make[1]: * [Makefile:139: all] Error 2
make[1]: Leaving directory '/home/alves/COAWST/SWAN/build'`
The coawstM generate sucessifully and I can generate results with Sandy examples. 

I can ignore this Error?

**Comment by jcwarner-usgs** [comment]
yes you can ignore that error.
I am trying to have that part skipped, but for now it is ok.
I do not need a swan.exe, " -o ../bin/swan.exe  "
i make only 1 exe at the end.  thanks for asking.
if you get a coawstM you are good to go.
-j

**Comment by lhba87** [comment]
Ok! I have the coawstM in the end. 
Thank you very much!
