### ISSUE TITLE
Error during SCRIP_COAWST installation in COAWST

### ISSUE THREAD

**Issue by met-sree** [jcwarner-usgs/COAWST#163]
Dear Sir,
      We are new to the COAWST model and trying to install the COAWST model with Intel compilers. All the libraries are installed by setting environment variables:   CC=mpicc; CXX=mpicxx; FC=mpiifort; FCFLAGS= -m64; F77 =mpif77; FFLAGS = -m64. The MCT was also installed without errors. 
1. While trying to install "SCRIP_COAWST", errors appear to be like
                 "/opt/intel/oneapi/mpi/2021.9.0//bin/mpif90 -fp-model precise -c ./kinds_mod.f
                 gfortran: error: unrecognized command-line option ‘-fp-model’; did you mean ‘-fipa-modref’?
                  make: *** [makefile:85: kinds_mod.o] Error 1 "
2. To overcome this, we used "export I_MPI_F90=ifort". With this option,  "make" works properly. But, it is not created  "scrip_coawst.exe". 
            Please provide any suggestions to overcome this issue.

**Comment by jcwarner-usgs** [comment]
that looks like mpif90 is pointing towards gfortran, but you probably set FC=ifort in the SCRIP_COAWST makefile (?). This causes the compiler flags to  come from Compilers/Linux-ifort.mk, but those flags are not known by gfortran.
so...
in the Compilers/Linux-ifort.mk it should also have
               FC := ifort
           FFLAGS := -fp-model precise
           FFLAGS += -fc=ifort
does your file have the -fc=ifort flag?  that did not seem to come through.

**Comment by jcwarner-usgs** [comment]
also, if make worked properly, then there should be a scrip_coawst (there may not be a .exe) 
do a
ls -ltr
and see if it is an 'x' executable file.

**Comment by met-sree** [comment]
Dear Sir, 
I appreciate your reply. Previously, I did not review or modify the "Compilers/Linux-ifort.mk" file. I recently verified. The Fortran variables "FC:= ifort; FFLAGS:= -fp-model precise; FFLAGS += -fc=ifort" are valid, as mentioned above.

In this file, however, the C flags: "CC=gcc; CXX=g++" and "INCDIR DIR path" are incorrect. Should it be substituted? Why because, during coast running, "gfortran" was being used and I encountered errors.

**Comment by jcwarner-usgs** [comment]
can you show me what you set in the  Lib/SCRIPT_COAWST/makefile?
just the top part, like this:

#  1. You need to set: FORT
#

FORT = ifort
#FORT = gfortran
#FORT  = pgi

# 2. If you want to run in MPI, then set USE_MPI=on,
# otherwise just keep it blank USE_MPI=  [just keep it blank].
# The USE_MPF90 will activate the call to mpif90.

USE_MPI=on               # distributed-memory parallelism
USE_MPIF90=on            # compile with mpif90 script
USE_NETCDF4=on

#
#   3. At the command prompt, type-->      make
#
#   4. YOU  SHOULD NOT NEED TO CHANGE ANYTHING BELOW HERE

**Comment by met-sree** [comment]
These are options in my Lib/SCRIPT_COAWST/makefile
"FORT = ifort
#FORT = gfortran
#FORT  = pgi
USE_MPI=on               # distributed-memory parallelism
USE_MPIF90=on         # compile with mpif90 script
USE_NETCDF4=on
USE_SCRIP := on
COMPILERS = ../../Compilers"

In addition,  I added "export I_MPI_F90=ifort" in the command prompt. I got the "scrip_coawst" file. But, again it takes gofrtan only at the coawst.bash  running.

**Comment by jcwarner-usgs** [comment]
ok so then when you type make, it should use ../../Compilers/Linux-ifort.mk and that file should have
               FC := ifort
           FFLAGS := -fp-model precise
           FFLAGS += -fc=ifort
then further down it has

ifdef USE_MPI
         CPPFLAGS += -DMPI
 ifdef USE_MPIF90
  ifeq ($(which_MPI), intel)
               FC := mpiifort
  else
               FC := mpif90
  endif
 else
             LIBS += -lfmpi -lmpi
 endif
endif

so that is where FC is set to mpif90.  but there still should be the fflags = -fc=ifort.  not sure why that is not appearing on your build line:
/opt/intel/oneapi/mpi/2021.9.0//bin/mpif90 -fp-model precise 
there should also be the -fc=ifort.

if you say it built with that other setting you did, what do you have with   ls -ltr

**Comment by met-sree** [comment]
With ls -lrt, I got files like : 
-rw-r--r-- 1 root root   11006 Aug 24 21:30 read_swan.fpp
-rw-r--r-- 1 root root   10451 Aug 24 21:30 read_roms.fpp
-rw-r--r-- 1 root root   16706 Aug 24 21:30 read_wrf.fpp
-rw-r--r-- 1 root root   97498 Aug 24 21:30 remap_conserv.fpp
-rw-r--r-- 1 root root   33283 Aug 24 21:30 remap_bilinear.fpp
-rw-r--r-- 1 root root   20762 Aug 24 21:30 scrip.fpp
-rw-r--r-- 1 root root  126487 Aug 24 21:30 create_masks.fpp
-rw-r--r-- 1 root root    9050 Aug 24 21:31 scrip_coawst.fpp
-rwxr-xr-x 1 root root 1598496 Aug 24 21:31 scrip_coawst

and find the attached error file at running of coawst.bash: i.e. coawst.log 
[coawst.log](https://github.com/DOI-USGS/COAWST/files/12440593/coawst.log)

**Comment by jcwarner-usgs** [comment]
-rwxr-xr-x 1 root root 1598496 Aug 24 21:31 scrip_coawst
that is your executable!  the 'x' means executable.  
that should work.  give it a try.
-j

**Comment by met-sree** [comment]
Dear Sir, 
            I installed all the Libraries (netcdf, pnetcdf, hdf5, etc.) per your recommendation. Additionally, MCT and SCRIP_COAWST were successfully installed. However, I encountered the following errors during the COAWST-3.8 (build_coawst.sh) installation.
1. cp: cannot stat '/home/user1/COAWST_BUILD/COAWST_38/Projects/Niotc/coawstG': No such file or directory
2. All executables are created in WRF/test/em_real, except wrf.exe.
      Please look into below attached coawst.log file and provide suggestions to overcome this issue.
    [coawst.log](https://github.com/DOI-USGS/COAWST/files/12447990/coawst.log)

Thank you

**Comment by jcwarner-usgs** [comment]
did you get a coawstM (or coawstG)?
i dont let WRF create a wrf.exe, i can only have   1 executable and that is coawstM or coawstG (if debug).

"The system may take a while to build. If it was successful, then you will get a coawstM or coawstM.exe file. If you get that file then the build was successful.  In some instances you may see an error or warning “undefined wrf.main.” That is the only error that is ok. We can not allow a wrf.exe to be built, nor an ocean.exe, and/or swan.exe to be created. Only one executable is created, and that is called coawstM[.exe]."  p. 15

**Comment by met-sree** [comment]
Sir,
I didn't get coawstM  (or coawstG).

**Comment by jcwarner-usgs** [comment]
the coawstM /G would be at the root level, not in the WRF/test/em_real.
also, it almost looks like the build stopped before it finished. is there more than what is in the file?

**Comment by srinivasny** [comment]
Dear Sir, 
At the root level, there is no "coawstM /G". I retried, that only the entire file; there is nothing missing.

**Comment by jcwarner-usgs** [comment]
the system had trouble building swan.  i see

cd /home/user1/COAWST_BUILD/COAWST_38/SWAN/build/lib && /opt/intel/oneapi/mpi/2021.9.0/bin/mpif90  -I/apps/coawst_libs/include -O2 -W0 -assume byterecl -traceback -diag-disable 8290 -diag-disable 8291 -diag-disable 8293 -I/home/user1/COAWST_BUILD/COAWST_38/Projects/Niotc/Build_romsG -I/apps/coawst_libs/MCT/include -module ../mod -c /home/user1/COAWST_BUILD/COAWST_38/SWAN/src_coawst/swmod1.f -o CMakeFiles/swan41.45.dir/swmod1.f.o
[01m[Kgfortran:[m[K [01;31m[Kerror: [m[Kunrecognized command-line option ‘[01m[K-W0[m[K’; did you mean ‘[01m[K-W[m[K’?
[01m[Kgfortran:[m[K [01;31m[Kerror: [m[Kunrecognized command-line option ‘[01m[K-assume[m[K’
[01m[Kgfortran:[m[K [01;31m[Kerror: [m[Kunrecognized command-line option ‘[01m[K-traceback[m[K’
[01m[Kgfortran:[m[K [01;31m[Kerror: [m[Kunrecognized command-line option ‘[01m[K-module[m[K’; did you mean ‘[01m[K-Mmodules[m[K’?
make[3]: *** [lib/CMakeFiles/swan41.45.dir/build.make:78: lib/CMakeFiles/swan41.45.dir/swmod1.f.o] Error 1

there are lots of missing characters, so i am not clear what it is trying to do.
Can you try to build SWAN alone
#define SWAN_MODEL
and just build that?
-j

**Comment by met-sree** [comment]
[coawst.log](https://github.com/DOI-USGS/COAWST/files/12457419/coawst.log)
Dear Sir, 
The MPIF90 wrapper error has been resolved by using "export I_MPI_F90=ifort". Currently, everything is fine. However, no CoawstG/M file is created. Please look into the attached log file and provide your suggestions.
Thank you.
[coawst.log](https://github.com/DOI-USGS/COAWST/files/12457401/coawst.log)

**Comment by jcwarner-usgs** [comment]
ok this looks new.
": /home/user1/COAWST_BUILD/COAWST38/WRF/main/libwrflib.a(module_io_quilt.o): in function `module_wrf_quilt_mp_quilt_':
module_io_quilt.f90:(.text+0xb0c2): undefined reference to `ext_pnc_inquire_filename_'"

I have seen this error before.
i think you have parallel netcdf activated for WRF, and we need to turn that off.
"Will use PNETCDF in dir: /apps/coawst_libs"
i see  "-DNETCDF -DPNETCDF -DHDF5 "
maybe try to set
export PNETCDF=
with a blank there.  and see if that stops wrf from using parallel netcdf.
-j

**Comment by met-sree** [comment]
[coawst.log](https://github.com/DOI-USGS/COAWST/files/12460951/coawst.log)
Your assistance is greatly appreciated, sir. It appears that the installation was carried out without any problems. The "coawstG" file was created in the main folder.
             drwxr-xr-x  2 root root      4096 Aug 29 09:48 Compilers
             drwxr-xr-x 19 root root      4096 Aug 29 09:50 WRF
             drwxr-xr-x 10 root root      4096 Aug 29 11:10 SWAN
             drwxr-xr-x  2 root root     40960 Aug 29 11:19 Build_romsG
             **-rwxr-xr-x  1 root root 125393736 Aug 29 11:19 coawstG**
               -rw-r--r--  1 root root   2064384 Aug 29 11:30 coawst.log

Thank you,
Srinivas

**Comment by jcwarner-usgs** [comment]
NICE !
