### ISSUE TITLE
Failed to make  SCRIP_COAWST

### ISSUE THREAD

**Issue by cnwong2023** [jcwarner-usgs/COAWST#164]
home/openmpi2/bin/mpif90 -frepack-arrays -fallow-argument-mismatch -c ./kinds_mod.f
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [makefile:85: kinds_mod.o] Error 1 

Information:
gcc --version
gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0

g++ --version
g++ (Ubuntu 7.5.0-6ubuntu2) 7.5.0

gfortran --version
GNU Fortran (Ubuntu 7.5.0-6ubuntu2) 7.5.0

mpiexec --version
mpiexec (OpenRTE) 4.1.4

**Comment by jcwarner-usgs** [comment]
strange.
you may need to edit  Compilers/Linux-gfortran.mk and comment that part out of the FFLAGS.
change
           FFLAGS := -frepack-arrays -fallow-argument-mismatch
to
#          FFLAGS := -fallow-argument-mismatc
           FFLAGS := -frepack-arrays
and see if it likes that.

**Comment by cnwong2023** [comment]
I edited the code:
 ##FFLAGS := -frepack-arrays -fallow-argument-mismatch
		   FFLAGS := -fallow-argument-mismatch
		   FFLAGS := -frepack-arrays

However, when I made the SCRIP_COAWST, new errors appeared.
make
frepack-arrays -c ./kinds_mod.f
make: frepack-arrays: Command not found
make: [makefile:85: kinds_mod.o] Error 127 (ignored)
frepack-arrays -c ./constants.f
make: frepack-arrays: Command not found
make: [makefile:88: constants.o] Error 127 (ignored)
frepack-arrays -c ./iounits.f
make: frepack-arrays: Command not found
make: [makefile:91: iounits.o] Error 127 (ignored)
frepack-arrays -c ./netcdf.f
make: frepack-arrays: Command not found
make: [makefile:94: netcdf.o] Error 127 (ignored)
frepack-arrays -c ./scripwrap_mod.f
make: frepack-arrays: Command not found
make: [makefile:102: scripwrap_mod.o] Error 127 (ignored)
frepack-arrays -c ./create_fullgrid.f
make: frepack-arrays: Command not found
make: [makefile:105: create_fullgrid.o] Error 127 (ignored)
frepack-arrays -c ./grids.f
make: frepack-arrays: Command not found
make: [makefile:98: grids.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./read_swan.f  ./read_swan.fpp
frepack-arrays -c ./read_swan.fpp
make: frepack-arrays: Command not found
make: [makefile:110: read_swan.o] Error 127 (ignored)
frepack-arrays -c ./read_ww3.f
make: frepack-arrays: Command not found
make: [makefile:114: read_ww3.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./read_roms.f  ./read_roms.fpp
frepack-arrays -c ./read_roms.fpp
make: frepack-arrays: Command not found
make: [makefile:119: read_roms.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./read_wrf.f  ./read_wrf.fpp
frepack-arrays -c ./read_wrf.fpp
make: frepack-arrays: Command not found
make: [makefile:124: read_wrf.o] Error 127 (ignored)
frepack-arrays -c ./read_hydro.f
make: frepack-arrays: Command not found
make: [makefile:128: read_hydro.o] Error 127 (ignored)
frepack-arrays -c ./remap_vars.f
make: frepack-arrays: Command not found
make: [makefile:132: remap_vars.o] Error 127 (ignored)
frepack-arrays -c ./remap_distwgt.f
make: frepack-arrays: Command not found
make: [makefile:141: remap_distwgt.o] Error 127 (ignored)
frepack-arrays -c ./timers.f
make: frepack-arrays: Command not found
make: [makefile:153: timers.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./remap_conserv.f  ./remap_conserv.fpp
frepack-arrays -c ./remap_conserv.fpp
make: frepack-arrays: Command not found
make: [makefile:137: remap_conserv.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./remap_bilinear.f  ./remap_bilinear.fpp
frepack-arrays -c ./remap_bilinear.fpp
make: frepack-arrays: Command not found
make: [makefile:146: remap_bilinear.o] Error 127 (ignored)
frepack-arrays -c ./remap_bicubic.f
make: frepack-arrays: Command not found
make: [makefile:150: remap_bicubic.o] Error 127 (ignored)
frepack-arrays -c ./remap_write.f
make: frepack-arrays: Command not found
make: [makefile:157: remap_write.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./scrip.f  ./scrip.fpp
frepack-arrays -c ./scrip.fpp
make: frepack-arrays: Command not found
make: [makefile:171: scrip.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./create_masks.f  ./create_masks.fpp
frepack-arrays -c ./create_masks.fpp
make: frepack-arrays: Command not found
make: [makefile:176: create_masks.o] Error 127 (ignored)
/usr/bin/cpp -P -traditional -w               -DMPI  ./scrip_coawst.f  ./scrip_coawst.fpp
frepack-arrays -c ./scrip_coawst.fpp
make: frepack-arrays: Command not found
make: [makefile:183: scrip_coawst.o] Error 127 (ignored)
frepack-arrays kinds_mod.o constants.o iounits.o netcdf.o scripwrap_mod.o create_fullgrid.o grids.o read_swan.o read_ww3.o read_roms.o read_wrf.o read_hydro.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o timers.o remap_write.o scrip.o create_masks.o scrip_coawst.o  -o ./scrip_coawst  -L/usr/lib/x86_64-linux-gnu -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -lnetcdf -lnetcdf -ldl -lm
make: frepack-arrays: Command not found
make: [makefile:81: scrip_coawst] Error 127 (ignored)

Thanks in advance.

**Comment by cnwong2023** [comment]
if I comment all FFLAGS, the terminal shows:
make
/home/leon/opt/openmpi2/bin/mpif90  -c ./kinds_mod.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./constants.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./iounits.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./netcdf.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./scripwrap_mod.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./create_fullgrid.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./grids.f
/usr/bin/cpp -P -traditional -w               -DMPI  ./read_swan.f  ./read_swan.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./read_swan.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./read_ww3.f
/usr/bin/cpp -P -traditional -w               -DMPI  ./read_roms.f  ./read_roms.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./read_roms.fpp
/usr/bin/cpp -P -traditional -w               -DMPI  ./read_wrf.f  ./read_wrf.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./read_wrf.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./read_hydro.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./remap_vars.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./remap_distwgt.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./timers.f
/usr/bin/cpp -P -traditional -w               -DMPI  ./remap_conserv.f  ./remap_conserv.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./remap_conserv.fpp
/usr/bin/cpp -P -traditional -w               -DMPI  ./remap_bilinear.f  ./remap_bilinear.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./remap_bilinear.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./remap_bicubic.f
/home/leon/opt/openmpi2/bin/mpif90  -c ./remap_write.f
/usr/bin/cpp -P -traditional -w               -DMPI  ./scrip.f  ./scrip.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./scrip.fpp
/usr/bin/cpp -P -traditional -w               -DMPI  ./create_masks.f  ./create_masks.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./create_masks.fpp
/usr/bin/cpp -P -traditional -w               -DMPI  ./scrip_coawst.f  ./scrip_coawst.fpp
/home/leon/opt/openmpi2/bin/mpif90  -c ./scrip_coawst.fpp
/home/leon/opt/openmpi2/bin/mpif90  kinds_mod.o constants.o iounits.o netcdf.o scripwrap_mod.o create_fullgrid.o grids.o read_swan.o read_ww3.o read_roms.o read_wrf.o read_hydro.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o timers.o remap_write.o scrip.o create_masks.o scrip_coawst.o  -o ./scrip_coawst  -L/usr/lib/x86_64-linux-gnu -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -lnetcdf -lnetcdf -ldl -lm
/usr/bin/ld: warning: libgfortran.so.5, needed by /usr/lib/x86_64-linux-gnu/libnetcdff.so, may conflict with libgfortran.so.4

Does this mean I successfully made the code?
Thanks in advance.

**Comment by jcwarner-usgs** [comment]
do an 
ls -ltr
and see if there is a scrip_coawst with an 'x' in the listing.

**Comment by cnwong2023** [comment]
Only .f, .fpp, .o exist in the folder.
scrip_coawst.f
scrip_coawst.fpp
scrip_coawst.o

Thanks.

**Comment by jcwarner-usgs** [comment]
this command

/home/leon/opt/openmpi2/bin/mpif90 kinds_mod.o constants.o iounits.o netcdf.o scripwrap_mod.o create_fullgrid.o grids.o read_swan.o read_ww3.o read_roms.o read_wrf.o read_hydro.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o timers.o remap_write.o scrip.o create_masks.o scrip_coawst.o -o ./scrip_coawst -L/usr/lib/x86_64-linux-gnu -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -lnetcdf -lnetcdf -ldl -lm

has -o ./scrip_coawst
that means -output file is = ./scrip_coawst
and it looks like it worked.  so there should be a scrip_coawst there
type make
and see if it does it again.

**Comment by cnwong2023** [comment]
make
/home/leon/opt/openmpi2/bin/mpif90  kinds_mod.o constants.o iounits.o netcdf.o scripwrap_mod.o create_fullgrid.o grids.o read_swan.o read_ww3.o read_roms.o read_wrf.o read_hydro.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o timers.o remap_write.o scrip.o create_masks.o scrip_coawst.o  -o ./scrip_coawst  -L/usr/lib/x86_64-linux-gnu -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -lnetcdf -lnetcdf -ldl -lm
/usr/bin/ld: warning: libgfortran.so.5, needed by /usr/lib/x86_64-linux-gnu/libnetcdff.so, may conflict with libgfortran.so.4

ls -ltr
![image](https://github.com/DOI-USGS/COAWST/assets/143377335/68241776-e3c3-4b73-b72d-00c87792154d)

it seems that the file has been made successfully.
Thanks.

**Comment by jcwarner-usgs** [comment]
nice !
