### ISSUE TITLE
Saving the variable wave breaking (percent)

### ISSUE THREAD

**Issue by asuanda** [jcwarner-usgs/COAWST#168]
Hello John,
In a coupled ROMS/SWAN COAWST application, I would like to save the variable "Wave_break." Although I have set the output to write my HIS output:
**Hout(idWbrk) == T       ! Wave_break         wave breaking (percent)**
I don't think I have the correct options defined in my .h file. 

Besides, **#define WDISS_WAVEMOD**, is there another module I need to define to record the wave_break output?

Thank you,

Ata Suanda

**Comment by jcwarner-usgs** [comment]
i think that wave_break was a percent wave breaking (is that right) and we used to use it for one of the roller options.
if defined ROLLER_SVENDSEN
          real(r8), pointer :: wave_break(:,:)

I dont think we use it much anymore. So you can have swan write it out directly as a separate netcdf file or mat file.
then you dont need to worry about any roms settings.
in the swan.in add
BLOCK 'COMPGRID' NOHEADER 'wvbrk.mat'   LAY 4 QB 1.    OUTPUT 20000101.000000 1 HR (or whatever the times are)

**Comment by asuanda** [comment]
Thanks, John!
