### ISSUE TITLE
Error in running case Sandy

### ISSUE THREAD

**Issue by chunlei666** [jcwarner-usgs/COAWST#173]
Hi John
I compiled the Sandy case and ran it. I gave me "MCT::m_SparseMatrixPlus::initFromRoot_:: FATAL--length of vector y different from row count of sMat.Length of y =    45240 Number of rows in sMat =     5655". 
45240/5655=8, just equal to the number of processors for SWAN. It seems I can only run SWAN with 1 pro. I am confused and need your help, thanks.

**Comment by chunlei666** [comment]
@jcwarner-usgs

**Comment by jcwarner-usgs** [comment]
make sure you have the correct scrip weights file chosen.
did you run the case as it is distributed or did you make any changes?

**Comment by chunlei666** [comment]
Thanks for your reply. I only modified the *.in files for WRF, ROMS and the coupling to arrange the number of processors. A similar problem I encountered when I ran the JOE_TC, I could only run the swan with only 1 processor. I attach the files. 
Have a nice day!
[coupling_sandy.in.txt](https://github.com/DOI-USGS/COAWST/files/12571282/coupling_sandy.in.txt)
[namelist.input.txt](https://github.com/DOI-USGS/COAWST/files/12571286/namelist.input.txt)
[ocean_sandy.in.txt](https://github.com/DOI-USGS/COAWST/files/12571287/ocean_sandy.in.txt)
[slurm-7835924.out.txt](https://github.com/DOI-USGS/COAWST/files/12571288/slurm-7835924.out.txt)
[sub.sh.txt](https://github.com/DOI-USGS/COAWST/files/12571289/sub.sh.txt)

**Comment by jcwarner-usgs** [comment]
not sure.
try to set these values in the namelist.input  (not .txt, just namelist.input)
 nproc_x                             = 4
 nproc_y                             = 4

is that slurm all the output?  because there should be a lot more header info.

**Comment by chunlei666** [comment]
That is all the slurm output. it reminds me of one thing I could not compile the SWAN with the original perl options (It just stopped complling in the beginning with no error coming out), so I changed the 'switch.pl' and deleted the ${SWITCHES} in the SWAN's  CMakeLists, and it went well.  I do not know if it makes a difference. i attach the switch.pl 
Thanks again!
[switch.pl.txt](https://github.com/DOI-USGS/COAWST/files/12571893/switch.pl.txt)

**Comment by jcwarner-usgs** [comment]
i am not sure what will happen if swan does not do the switches.
it is like the cppdefs for roms, it sets different options in the swan code, like mpi.
i think you need to get the switches to work.

also, are you pointing to the coupling.in file when you run it?  there should be a bunch of header info that writes out.

**Comment by chunlei666** [comment]
Hi, John
I do run the case pointing to the coupling.in file. I set the npro to 1 for SWAN and it gave me much more header info, even though it stopped with an MPI error. The slurm output is attached. 
I tested the JOE_TC, it gave me
           "MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3
           MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch
           LocalMap Gsize =       237208  RemoteMap Gsize =        29651"
Also, 237208/29651=8, which is the npro of  SWAN. When I arranged only 1 processor to swan, it worked well.

So, firstly, should I have to reset the perl options for SWAN? Secondly, do you have any advice for the MPI error that happened in Sandy? Thank you very much for your time.
Have a nice day! 

[slurm-7836259.out.txt](https://github.com/DOI-USGS/COAWST/files/12581347/slurm-7836259.out.txt)

**Comment by chunlei666** [comment]
Hi, John
i tried the V3.7. it worked fine. Maybe i will try to learn the model based on V3.7. Thanks for your contributions on this model. 
Best regards.
