### ISSUE TITLE
Question about the initial conditions files

### ISSUE THREAD

**Issue by chunlei666** [jcwarner-usgs/COAWST#179]
Hi, john
         Sorry to bother you again.  I tried to build the SWAN initial File by running swan itself. I ran it successfully and no errors came out, however, the size of  _int.hot files confused me.  The size of "_int.hot" for the parent grid is around 26M, but the "_ref3_int,hot" of the child grid is only 1.1M. I checked the hotfiles and found that all ZERO for the child grid. I do not know if it is acceptable.  
[swan_int.zip](https://github.com/DOI-USGS/COAWST/files/12735289/swan_int.zip)

**Comment by jcwarner-usgs** [comment]
sorry but i dont have the time to look at your init files.
how about you activate the writing of Hsig and look at that?  it will only be 1 time step, but that will let you see what SWAN converged to.
-j
