### ISSUE TITLE
Unable to generate any *.exe when compiling WPS in a WRF-only application

### ISSUE THREAD

**Issue by qwdy** [jcwarner-usgs/COAWST#180]
Hello everyone!
I have trouble compiling WPS which no geogrid.exe, ungrib.exe, metgrid.exe were generated.I attach my configure.wps file and log.compile file below.
Actually, I found something strange in the configure.wps file which are the 'COMPRESSION_LIBS' and 'COMPRESSION_INC'.The paths followed them doesn't exist in my computer. But even though I edited them to: 

COMPRESSION_LIBS = -L/home/coawst/Build_COAWST/LIBRARIES/jasper/lib -L/home/coawst/Build_COAWST/LIBRARIES/libpng/lib -L/home/coawst/Build_COAWST/LIBRARIIES/zlib/lib -ljasper -lpng -lz

COMPRESSION_INC = -I/home/coawst/Build_COAWST/LIBRARIES/jasper/include -I/home/coawst/Build_COAWST/LIBRARIES/libpng/include -I/home/coawst/Build_COAWST/LIBRARIES/zlib/include

I still got the same error. So I'm confused about two things:1)what's the real reason to the issue? 2) do I need to change the 'COMPRESSION_LIBS' and 'COMPRESSION_INC'
I'd appreciate it if somebody help me get through it.
[configure.wps.txt](https://github.com/DOI-USGS/COAWST/files/12750845/configure.wps.txt)
[log.txt](https://github.com/DOI-USGS/COAWST/files/12750846/log.txt)

**Comment by jcwarner-usgs** [comment]
i see in the log file 
 module_stringutil.f90:14:1:
 ../../ungrib/src/module_stringutil.F
 1
Error: Invalid character in name at (1)

can you find that file, it might be in ungrib/src and see what is on line 14?

**Comment by qwdy** [comment]
Sure, they are attached below.There are 13 lines blank space existing in module_stringutil.f90 file. and the other content between two files is same, I think.
[module_stringutil.F.txt](https://github.com/DOI-USGS/COAWST/files/12751231/module_stringutil.F.txt)
[module_stringutil.f90.txt](https://github.com/DOI-USGS/COAWST/files/12751232/module_stringutil.f90.txt)

**Comment by jcwarner-usgs** [comment]
i am not sure.  maybe download the code from the wrf site and try directly with that.
if you have problems with the code from their site then contact them.  i dont change anything in WPS.

**Comment by qwdy** [comment]
I already posted the issue on the wrf forum, any progress I'll share in the github. I'm really grateful for your reply so quickly, still I look forward to your suggestion if you come up with some idea about the issue.

**Comment by qwdy** [comment]
Hello, Dr.warner. I want to tell you I successfully compiled WPS . I cloned WPS v4.1 from github to my /COAWST directory and compiled again in the /WPS_new directory which worked well. I really appreciate your help!
