### ISSUE TITLE
Error when run the WRF+ROMS+SWAN 

### ISSUE THREAD

**Issue by chunlei666** [jcwarner-usgs/COAWST#186]
Hi, John,
           i compiled and ran the sandy case successfully, however, i got an error when i ran the designed case (shared the coawstM of Sandy case). firstly, it gave me that "cannot find file MPTABLE.TBL" which seems to be a TBL file for the NoahMP surface physics in WRF, so i copied the MPTABLE.TBL file from the original WRF code(I cannot find that file in the COAWST/WRF).    But, "forrtl: severe (19): invalid reference to variable in NAMELIST input, unit 15, file /public3/home/scg9255/WCL/COAWST/COAWST_sandy-3.7/MPTABLE.TBL, line 198, position 10" occured.  Why the Sandy ran well with the NoahMP surface physics but did not work in my case?  I am very grateful if you have any advice.
here are my *.in files and my log files.
[ocean_JS.in.txt](https://github.com/DOI-USGS/COAWST/files/13111642/ocean_JS.in.txt)
[namelist.input.txt](https://github.com/DOI-USGS/COAWST/files/13111645/namelist.input.txt)
[swan_JS_ref3.in.txt](https://github.com/DOI-USGS/COAWST/files/13111647/swan_JS_ref3.in.txt)
[swan_JS.in.txt](https://github.com/DOI-USGS/COAWST/files/13111648/swan_JS.in.txt)
[test.out.txt](https://github.com/DOI-USGS/COAWST/files/13111654/test.out.txt)
[slurm-8540446.out.txt](https://github.com/DOI-USGS/COAWST/files/13111656/slurm-8540446.out.txt)
![grid](https://github.com/DOI-USGS/COAWST/assets/44604298/10cdd3c1-1f40-428d-bfd9-704cce9fbf97)

**Comment by chunlei666** [comment]
I think i found the reason, i run the real.exe in WRFv4.1, but the WRF in coawstv3.7 is an older version and the Noah-MP is not updated. So, what is the version of WRF in coawst_v3.7?

**Comment by jcwarner-usgs** [comment]
there may have been wrf updates in the 3.7 lifecycle.
we are up to coawst 3.8 now. it has wrf 4.4.1
