### ISSUE TITLE
cant compile mct

### ISSUE THREAD

**Issue by julidamasan** [jcwarner-usgs/COAWST#191]
Hello.

I am trying to install COAWST in a ubuntu 22.04 machine, using:
hdf5-13.2
netcdf-c-9.2
netcdf-fortran-6.1
 jasper-2.0.10
I tried openmpi-5.0  and I also tried mpich-4.1.2.

While trying compile mct I recieved the error message:

mpif90 -c -I/home/juliana/LIBRARIES/openmpi/include -DSYSLINUX -DCPRUNKNOWNCPR    m_String.F90
m_String.F90:478:17:

  457 |   call MPI_bcast(ln,1,MP_INTEGER,root,comm,ier)
      |                 2
......
  478 |   call MPI_bcast(Str%c(1),ln,MP_CHARACTER,root,comm,ier)
      |                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(1)/INTEGER(4)).
make[1]: *** [Makefile:66: m_String.o] Error 1
make[1]: Saindo do diretório '/home/juliana/COAWST/Lib/MCT/mpeu'

make: *** [Makefile:10: subdirs] Error 2

Is it some problem with the libraries version or my mistake while installing?

ps: When using ubuntu 20.04 it does not happen, but I still have some other error messages

**Comment by I-N-G** [comment]
I met the same problem with ubuntu 22.04. Have you solved it now?

**Comment by jcwarner-usgs** [comment]
this probably needs the compiler flag
-fallow-argument-mismatch

**Comment by julidamasan** [comment]
> I met the same problem with ubuntu 22.04. Have you solved it now?

As we have now a computer just for this model, I  reset it and installed the ubuntu 20.04. I had another problems with ubuntu 20.04, so I also found a help here in github that told to insert my dirs and my libs on a file inside Compiler folder. It helped a lot, it is in Portuguese, but it worth to verify. 
  https://github.com/lfelipefm/Tutorial_instala-o_COAWST.git

**Comment by julidamasan** [comment]
> this probably needs the compiler flag -fallow-argument-mismatch

I solved already, but where should I put this flag? which step, or which file?

**Comment by jcwarner-usgs** [comment]
if it works, then good.
But if it still has trouble to compile MCT, then it might need those flags in Makefile.conf

**Comment by julidamasan** [comment]
Now I solve, I could install without errors, but I am having problems to compile WRF. I am cleaning, exporting the dirs and it can not find files that are there, it shows the path, but it says that could not find a file that is there.

**Comment by jcwarner-usgs** [comment]
i am not sure what you mean.
if you post the build log here, i can look at it.
sounds like it might be a permissions issues.
