### ISSUE TITLE
Nesting in coupled roms-swan

### ISSUE THREAD

**Issue by rececilio** [jcwarner-usgs/COAWST#194]
Hello everybody.
I am going for the nesting in roms-swan. The first level is running smoothly. The nested grids are identical between them.
I noticed that all grids are communicating with all the other level's grids. Is that right?
I thought they should communicate only between the same level. (wouldn't it be better?)
Do I also need the scrips weight file even though the grids are identical? 
Thanks.

**Comment by jcwarner-usgs** [comment]
if you have more than 1 grid, then you need scrip files.
We have instances where WRF has 3 grids and roms has 2 grids. So we have all the grids exchange data.

**Comment by rececilio** [comment]
Thank you!
However, Scrip routine is not finishing. This is the output:

....................
After all the filenames:

Reading ROMS grids
 ROMS starting i j index of parent w.r.t child grid
          39          56
 ending i & j index of parent w.r.t child grid--
         103          73
 Reading SWAN grids
 ROMS and SWAN same grids (0=no or 1=yes)            0
 SWAN starting i & j index of parent w.r.t child grid--
         188         200
 ending i & j index of parent w.r.t child grid--
         103          73
.......................

It is not recognizing the grids as identical and the swan starting i & j index is actually the total number of points in the parent grid.
The roms is right: 39 56.
Then after running the four ocn2wav, it stops in the first wav2ocn with:
...............
Point coords:   0.64472912489304723        6.2561214434258661     
 Dest grid lats:   0.65325396247478196       -1.5707963267950000       -1.5707963267950000       -1.5707963267950000     
 Dest grid lons:    6.2569163321736223       -161.94910129256451       -161.94910129256451       -161.94910129256451     
 Dest grid addresses:        10189       10190       10378       10377
 Current i,j :                        NaN                       NaN
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO
STOP Iteration for i,j exceed max iteration count
...............

What am I doing wrong?

**Comment by rececilio** [comment]
Found it!

The SCRIP routines do not handle the exception value (-9999) in swan grid file.
Made a new grid without them and it now works fine.
