### ISSUE TITLE
Problem to compile the SWAN in Coupled COAWST

### ISSUE THREAD

**Issue by met-sree** [jcwarner-usgs/COAWST#197]
Dear all, 
I have successfully installed the coupled COAWST model (with WRF+ROMS+**WW3**) in my intel system. But errors appear when I am trying to install a coupled COAWST model (with WRF+ROMS+**SWAN**) like the Sandy test case. Kindly review the errors documented in the attached coawst.log file and provide valuable suggestions to overcome them.

[Uploading coawst.log…]()

Thank you,
Srinivas

**Comment by jcwarner-usgs** [comment]
i cant see the log file.  maybe try to upload it again.
for SWAN, look for any Err* files.

**Comment by met-sree** [comment]
I forgot to attach the file log file. Please find the attached files now.
[coawst_log.txt](https://github.com/DOI-USGS/COAWST/files/13477394/coawst_log.txt)

Thankyou,
Srinivas

**Comment by jcwarner-usgs** [comment]
ld: /home/user1/COAWST_BUILD/COAWST_Sandy/WRF/main/libwrflib.a(module_io.o): in function `module_io_mp_wrf_get_dom_ti_real_arr_':
module_io.f90:(.text+0x32b): undefined reference to `ext_pnc_get_dom_ti_real_'


and associated.
for some reason i can not use parallel netcdf for wrf.  so you need to deactivate parallel netcdf (pnetcdf).
"Will use PNETCDF in dir: /apps/coawst_libs"
i think there is a flag for wrf.  something like 
export PNETCDF=""

**Comment by met-sree** [comment]
Many thanks. After making the necessary changes as you advised, it installed
