### ISSUE TITLE
Question about the "coupling interval"

### ISSUE THREAD

**Issue by chunlei666** [jcwarner-usgs/COAWST#202]
Hi, John
   
       In the Sandy case, the time interval between models when coupling is set to 900 seconds.  Does it mean during the interval, the interactive variables will remain unchanged?  For example, will the SST and Z0 from the ocean and wave to the WRF model be constant during the coupling interval? In that case, does it mean the coupling process is equivalent to offering the lateral lower/upper boundary conditions for each model?

**Comment by jcwarner-usgs** [comment]
when  model A receives information from model B, that information in model A will stay the same until it is updated.
That field in model B will be updating/time stepping, but model A will not know about the changes until the next synchronous interval.
