### ISSUE TITLE
WRF moving nest problem

### ISSUE THREAD

**Issue by Cherry-jw113** [jcwarner-usgs/COAWST#204]
Although User Manual said that moving nest needs to be the last child grid of the WRF system and only support coupling to 1 moving WRF nest. I found that if I couple three layers of WRF with ROMS, the second and third layers can be mobile grids. But If I couple two layers of WRF, the second layers have two moving grids, the coawst can't work. I want to know if anyone coupled two moving nest WRF, only in this way can capture the situation of two hurricanes at the same time.

**Comment by jcwarner-usgs** [comment]
yes, i need to update the manual.
you can have zoomed wrf nests, and the last nests can be moving.  Say you have 3 wrf grids that zoom to smaller resolution, you can have grids 2 and 3 be moving.  but i did not code grids 2 and 3 to be on the same nest level, the grids need to telescope smaller.  
what you are asking should be available with esmf coupling. roms and wrf are coupled via esmf , but i have not gone down that route yet.

**Comment by Cherry-jw113** [comment]
> yes, i need to update the manual. you can have zoomed wrf nests, and the last nests can be moving. Say you have 3 wrf grids that zoom to smaller resolution, you can have grids 2 and 3 be moving. but i did not code grids 2 and 3 to be on the same nest level, the grids need to telescope smaller. what you are asking should be available with esmf coupling. roms and wrf are coupled via esmf , but i have not gone down that route yet.

Thank you so much~ :D  I hope that COAWST can take this into account in the future, as it will be good for capturing two simultaneous hurricanes.

**Comment by gutw** [comment]
> > yes, i need to update the manual. you can have zoomed wrf nests, and the last nests can be moving. Say you have 3 wrf grids that zoom to smaller resolution, you can have grids 2 and 3 be moving. but i did not code grids 2 and 3 to be on the same nest level, the grids need to telescope smaller. what you are asking should be available with esmf coupling. roms and wrf are coupled via esmf , but i have not gone down that route yet.
> 
> Thank you so much~ :D I hope that COAWST can take this into account in the future, as it will be good for capturing two simultaneous hurricanes.

Hello, I found mct gridsize mismatch problem when using wrf moving grid with WRF+ROMS+SWAN. Could you show me your scrip.in?
https://github.com/DOI-USGS/COAWST/issues/321#issue-2550928194
