### ISSUE TITLE
致命错误: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran

### ISSUE THREAD

**Issue by DYB2363021436** [jcwarner-usgs/COAWST#206]
Do you have to use GCC version 7.5.0 to compile the new version of COAWST, using gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) can't be compiled, gcc.4.8.5 can be compiled netcdf, but gcc750, on supercomputer can't be compiled!

**Comment by jcwarner-usgs** [comment]
i am not sure.
what is the error you get ?

**Comment by DYB2363021436** [comment]
When I use the default low version of gcc (COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto_wrapper) to compile COAWST, the following error is reported:
[lideshun@login 04_COAWST]$ ./build_coawst.sh 
rm -f -r core *.ipo ./Build_roms /public/home/lideshun/make_macros.mk
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
./build_coawst.sh: 第 359 行:cd: ./Build_roms: 没有那个文件或目录
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。
/public/home/lideshun/COAWST/04_COAWST//Compilers/Linux-gfortran.mk:74: *** gfortran version 7 or greater is required。 停止。

gcc(/public/software/compiler/gcc/7.3.1/libexec/gcc/x86_64-pc-linux-gnu/7/lto-wrapper) after I loaded the following library：
module load mathlib/hdf5/gnu/1.12.0
module load mathlib/netcdf/gnu/4.7.4
module load compiler/gcc/7.3.1
module load compiler/intel/2021.3.0
module load mpi/intelmpi/2021.3.0

The error is as follows
![Uploading Snipaste_2023-12-12_00-13-30.png…]()

**Comment by DYB2363021436** [comment]
public/software/mpi/intelmpi/2021.3.0/bin/mpif90 -c -frepack-arrays  -fconvert=big-endian -frecord-marker=4 -O3 -ffast-math -I/public/home/lideshun/COAWST/04_COAWST/SWAN/build/mod -I/public/home/lideshun/libs_gun/mct/include -I/public/home/lideshun/COAWST/04_COAWST//WRF/main -I/public/home/lideshun/COAWST/04_COAWST//WRF/external/esmf_time_f90 -I/public/home/lideshun/COAWST/04_COAWST//WRF/frame -I/public/home/lideshun/COAWST/04_COAWST//WRF/share get_sparse_matrix.f90;




get_sparse_matrix.f90:16:10:

       USE netcdf
          1
致命错误: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran
编译中断。
make: *** [mct_params] 错误 1

gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o ESMF_Alarm.o -c ESMF_Alarm.f
f951: 致命错误: Reading module ‘wrf_esmf_timemod’ at line 1599 column 20: Unexpected EOF
编译中断。
make[4]: [ESMF_Alarm.o] 错误 1 (忽略)
/bin/rm -f ESMF_Clock.o
sed -e "/\!.*'/s/'//g" ESMF_Clock.F90 > ESMF_Clock.b
/usr/bin/cpp -P -traditional -I/public/home/lideshun/COAWST/04_COAWST/WRF/inc -I. -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT  -DDM_PARALLEL -DNETCDF -DHDF5 -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -traditional -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -I. ESMF_Clock.b > ESMF_Clock.f
/bin/rm -f ESMF_Clock.b
gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o ESMF_Clock.o -c ESMF_Clock.f
f951: 致命错误: Reading module ‘wrf_esmf_timemod’ at line 1599 column 20: Unexpected EOF
编译中断。
make[4]: [ESMF_Clock.o] 错误 1 (忽略)
/bin/rm -f Meat.o
/bin/rm -f ESMF_AlarmClock.o
sed -e "/\!.*'/s/'//g" Meat.F90 > Meat.b
sed -e "/\!.*'/s/'//g" ESMF_AlarmClock.F90 > ESMF_AlarmClock.b
/usr/bin/cpp -P -traditional -I/public/home/lideshun/COAWST/04_COAWST/WRF/inc -I. -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT  -DDM_PARALLEL -DNETCDF -DHDF5 -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -traditional -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -I. ESMF_AlarmClock.b > ESMF_AlarmClock.f
/bin/rm -f ESMF_AlarmClock.b
/usr/bin/cpp -P -traditional -I/public/home/lideshun/COAWST/04_COAWST/WRF/inc -I. -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT  -DDM_PARALLEL -DNETCDF -DHDF5 -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -traditional -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -I. Meat.b > Meat.f
gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o ESMF_AlarmClock.o -c ESMF_AlarmClock.f
/bin/rm -f Meat.b
gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o Meat.o -c Meat.f
ESMF_AlarmClock.f:74:10:

       use WRF_ESMF_AlarmMod, only : ESMF_Alarm, ESMF_AlarmSet
          1
致命错误: Can't open module file ‘wrf_esmf_alarmmod.mod’ for reading at (1): 没有那个文件或目录
编译中断。
make[4]: [ESMF_AlarmClock.o] 错误 1 (忽略)
/bin/rm -f ESMF_Mod.o
sed -e "/\!.*'/s/'//g" ESMF_Mod.F90 > ESMF_Mod.b
/usr/bin/cpp -P -traditional -I/public/home/lideshun/COAWST/04_COAWST/WRF/inc -I. -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT  -DDM_PARALLEL -DNETCDF -DHDF5 -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -traditional -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -I. ESMF_Mod.b > ESMF_Mod.f
f951: 致命错误: Reading module ‘wrf_esmf_timemod’ at line 1599 column 20: Unexpected EOF
编译中断。
make[4]: [Meat.o] 错误 1 (忽略)
/bin/rm -f ESMF_Mod.b
gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o ESMF_Mod.o -c ESMF_Mod.f
ESMF_Mod.f:15:7:

    USE WRF_ESMF_AlarmMod
       1
致命错误: Can't open module file ‘wrf_esmf_alarmmod.mod’ for reading at (1): 没有那个文件或目录
编译中断。
make[4]: [ESMF_Mod.o] 错误 1 (忽略)
/bin/rm -f module_symbols_util.o
sed -e "/\!.*'/s/'//g" module_symbols_util.F90 > module_symbols_util.b
/usr/bin/cpp -P -traditional -I/public/home/lideshun/COAWST/04_COAWST/WRF/inc -I. -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT  -DDM_PARALLEL -DNETCDF -DHDF5 -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -traditional -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -I. module_symbols_util.b > module_symbols_util.f
/bin/rm -f module_symbols_util.b
gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o module_symbols_util.o -c module_symbols_util.f
module_symbols_util.f:28:12:

         USE ESMF_Mod, WRFU_ALARM => ESMF_ALARM
            1
致命错误: Can't open module file ‘esmf_mod.mod’ for reading at (1): 没有那个文件或目录
编译中断。
make[4]: [module_symbols_util.o] 错误 1 (忽略)
/bin/rm -f module_utility.o
sed -e "/\!.*'/s/'//g" module_utility.F90 > module_utility.b
/usr/bin/cpp -P -traditional -I/public/home/lideshun/COAWST/04_COAWST/WRF/inc -I. -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT  -DDM_PARALLEL -DNETCDF -DHDF5 -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -traditional -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -I. module_utility.b > module_utility.f
/bin/rm -f module_utility.b
gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4   -o module_utility.o -c module_utility.f
module_utility.f:15:12:

         USE module_symbols_util
            1
致命错误: Can't open module file ‘module_symbols_util.mod’ for reading at (1): 没有那个文件或目录
编译中断。
make[4]: [module_utility.o] 错误 1 (忽略)
/bin/rm -f libesmf_time.a
if [ "ar" != "lib.exe" ] ; then \
          ar ru libesmf_time.a ESMF_Alarm.o ESMF_BaseTime.o ESMF_Clock.o ESMF_Time.o Meat.o ESMF_Base.o ESMF_Calendar.o ESMF_Fraction.o ESMF_TimeInterval.o ESMF_Stubs.o ESMF_Mod.o module_symbols_util.o module_utility.o ESMF_AlarmClock.o ; \
        else \
          ar /out:libesmf_time.a ESMF_Alarm.o ESMF_BaseTime.o ESMF_Clock.o ESMF_Time.o Meat.o ESMF_Base.o ESMF_Calendar.o ESMF_Fraction.o ESMF_TimeInterval.o ESMF_Stubs.o ESMF_Mod.o module_symbols_util.o module_utility.o ESMF_AlarmClock.o ; \
        fi
ar: 正在创建 libesmf_time.a
ar: ESMF_Alarm.o: 没有那个文件或目录
make[4]: [libesmf_time.a] 错误 1 (忽略)
ranlib libesmf_time.a
ranlib: libesmf_time.a：无此文件
make[4]: [libesmf_time.a] 错误 1 (忽略)
make[4]: 离开目录“/public/home/lideshun/COAWST/04_COAWST/WRF/external/esmf_time_f90”

**Comment by jcwarner-usgs** [comment]
there are a couple of things going on there.
looks like it does need gfortran v7 or higher.
if you switch compilers, all the libraries need to be compiled by the same compiler version.
" Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran"
