### ISSUE TITLE
Cannot find CPP option 'WEC_WCAP','WEC_BREAKING' as indicated in the 2012 Kumar Ocean Modelling paper.

### ISSUE THREAD

**Issue by hotspring112** [jcwarner-usgs/COAWST#207]
Dear All,

        I am new to COAWST model and I cannot find the way to define the cpp options of  'WEC_WCAP','WEC_BREAKING' as indicated in the Kumar et al.,2012 paper. I am wondering if the effect of wave breaking from wave white-capping is still included in the present COAWST model OR only the effect of wave breaking from depth-induced wave breaking is included.  Why?    Another question is I cannot find the way to included the wave stokes drift effect in the Salinity transport equation. Is this effect included in the COAWST model by default when defining WEC_VF cpp option?  If it is included already, could anyone tell me in which subroutine as I can see u_stokes and v_stokes are included explicitly in say step3d_uv.F  but not in the step3d_t.F

Many Thanks!

**Comment by jcwarner-usgs** [comment]
I suggest you try the Inlet_test/Coupled case.  it has wec_vf defined.
the whitecapping and breaking will be activated with the wec_vf option, so you dont need to turn them on.
breaking dissipation is used to drive flows, and the white capping is used in the surface stress computation for the turbulence closure.
The stokes drift is included in the advection terms, so it will be active in the scalar transports.
look in Wec/wec_stokes for the computations, and then the u_stokes and v_stokes are throughout the code in the advection terms.

**Comment by hotspring112** [comment]
Hi John,

      Thanks very much for your reply.  But I am still confused. In Kumar 2012 paper, the white capping is also used to drive flows, why not in the present codes?  And yes I can see the stokes drift is calculated in wec_stokes.F but just wondering how it is included in the scalar transports equations?  You mentioned that  u_stokes and v_stokes are inclued in the advection terms, could you also tell me by which subroutine or .F files.  I asked this because I found almost no effect of waves on the salinity transport patterns in my ideal river plume application and thus wondering how the stokes drift is included in the advection term of salinity transport equation.  Sorry to bother you!

Many Thanks!
Peng

**Comment by jcwarner-usgs** [comment]
it was found that the white capping was being double counted if we included it to drive flows. 

"“In the light of this evidence, we surmise that including whitecapping as a vertically distributed body force in the budget is unsuitable because the contribution is already included in the wind stress. Therefore, we modify the coupling in ROMS to retain Sbr as the only contributor for the nonconservative wave force (i.e., we propose to set Swc = 0 in equation [9]"

Pareja-Roman, L. F., Chant, R. J., & Ralston, D. K. (2019). Effects of locally generated wind waves on the momentum budget and subtidal exchange in a coastal plain estuary. Journal of Geophysical Research: Oceans, 124, 1005–1028. https://doi.org/10.1029/2018JC014585


the stokes is in rhs3d, for the advection.  also in step2d for continuity.

Kumar's paper does have other scalar mixing terms from waves, that we added in but they are not active.  
MODULE wec_wave_mix_mod
#if defined SOLVE3D && defined WEC && defined WAVE_MIXING

how big are your waves?

**Comment by hotspring112** [comment]
Hi John，
Thank you very much！ I gave a 1.5m wave at the open boundary with a constant wind speed of about 11 m/s, the wave in the middle of the domain is about 2.2m and then gradually decreases towards the coast.    
I am wondering how to remove the effect of wave stokes drift in the Tracer transport equation Only (but still includes its effects in the momentum equations) in order to have an explicit picture on its effects in the salinity transport pattern?

Many Thanks
Peng

**Comment by jcwarner-usgs** [comment]
i am not sure, because the tracer transport uses the momentum.  
dC/dt + duC/dx ...  etc, the u is influenced by the stokes.

**Comment by hotspring112** [comment]
Hi John,

     Sorry to bother you again!  But after I inspected carefully the codes in pre_step3d.F, rhs3d.F, and step3d_t.F, I still have no idea on how the u_stokes/v_stokes are included in the advection terms of tracer equations.    The  rhs3d is used mainly for the momentum equations,  and in step3d_t,  Huon/Hvon are multiplied with t(i,j,k,3,itrc) to calculate the horizontal **tracer advection** term;  however, Huon/Hvon don't have u_stokes/v_stokes.     It thus seems likes to me that the u_stokes/v_stokes tracer advection terms (the red circled term in the picture ) are not coded in the present COAWST.    Hope you can give me a clue on how  u_stokes/v_stokes tracer advection terms are included in the present code.  Thanks very much!

Best Regards and Many Thanks
Peng

![Snipaste_2023-12-17_12-05-28](https://github.com/DOI-USGS/COAWST/assets/14141925/aded44cc-dae1-4da1-82d3-2f85580594d2)

**Comment by hotspring112** [comment]
Wait.  I just noticed that the Huon/Hvon includes the u_stokes/v_stokes in step3d_uv.F, is this what you mean when saying  "because the tracer transport uses the momentum", John ?

**Comment by jcwarner-usgs** [comment]
yes set_massflux:
           Huon(i,j,k)=0.5_r8*(Huon(i,j,k)+u(i,j,k,nnew)*DC(i,k))
# ifdef WEC
            Huon(i,j,k)=Huon(i,j,k)+0.5_r8*u_stokes(i,j,k)*DC(i,k)
# endif

  also in rhs_3d 
  ifdef WEC_VF
!-----------------------------------------------------------------------
!  Add in vertical advection from W_stokes.
!-----------------------------------------------------------------------
!
