### ISSUE TITLE
COAWST/WRF/external/io_grib1/WGRIB：Compile error

### ISSUE THREAD

**Issue by DYB2363021436** [jcwarner-usgs/COAWST#208]
When I compile COAWST3.8, I need to use gcc -v >= 7, I have no problem compiling in ubuntu22.04, but I got an error when compiling in centos, but it doesn't affect the generation of coawstM, and it can be computed, I don't know if there is any effect on the result of the computation, I searched for the installation of the dependency of WGRIB on zlib, libpng, and I also installed it, but it still has the following problem when compiling.
The error is as follows
wgrib_main.c: 在函数‘main’中:
wgrib_main.c:678:10: 错误：‘FLT_MAX’ undeclared (first use in this function); did you mean ‘TMP_MAX’?
   rmin = FLT_MAX;
          ^~~~~~~
          TMP_MAX
wgrib_main.c:678:10: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[5]: [wgrib_main.o] 错误 1 (忽略)

**Comment by DYB2363021436** [comment]
make[5]: 进入目录“/public/home/lideshun/COAWST/02_yanzheng/06_COAWST_W_R_S/WRF/external/io_grib1/WGRIB”
gcc -c -O wgrib_main.c
gcc -c -O seekgrib.c
gcc -c -O ibm2flt.c
wgrib_main.c: 在函数‘main’中:
wgrib_main.c:678:10: 错误：‘FLT_MAX’ undeclared (first use in this function); did you mean ‘TMP_MAX’?
   rmin = FLT_MAX;
          ^~~~~~~
          TMP_MAX
wgrib_main.c:678:10: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[5]: [wgrib_main.o] 错误 1 (忽略)
gcc -c -O readgrib.c
gcc -c -O intpower.c
gcc -c -O cnames.c
gcc -c -O BDSunpk.c
gcc -c -O flt2ieee.c
gcc -c -O wrtieee.c
gcc -c -O levels.c
gcc -c -O PDStimes.c
gcc -c -O missing.c
gcc -c -O nceptable_reanal.c
gcc -c -O nceptable_opn.c
gcc -c -O ensemble.c
gcc -c -O ombtable.c
gcc -c -O ec_ext.c
gcc -c -O gribtable.c
gcc -c -O gds_grid.c
gcc -c -O PDS_date.c
gcc -c -O ectable_128.c
gcc -c -O ectable_129.c
gcc -c -O ectable_130.c
gcc -c -O ectable_131.c
gcc -c -O ectable_140.c
gcc -c -O ectable_150.c
gcc -c -O ectable_151.c
gcc -c -O ectable_160.c
gcc -c -O ectable_170.c
gcc -c -O ectable_180.c
gcc -c -O nceptab_129.c
gcc -c -O dwdtable_002.c
gcc -c -O dwdtable_201.c
gcc -c -O dwdtable_202.c
gcc -c -O dwdtable_203.c
gcc -c -O cptectable_254.c
gcc -c -O nceptab_130.c
gcc -c -O nceptab_131.c
gcc -o wgrib.exe wgrib_main.o seekgrib.o ibm2flt.o readgrib.o intpower.o cnames.o BDSunpk.o flt2ieee.o wrtieee.o levels.o PDStimes.o missing.o nceptable_reanal.o nceptable_opn.o ensemble.o ombtable.o ec_ext.o gribtable.o gds_grid.o PDS_date.o ectable_128.o ectable_129.o ectable_130.o ectable_131.o ectable_140.o ectable_150.o ectable_151.o ectable_160.o ectable_170.o ectable_180.o nceptab_129.o dwdtable_002.o dwdtable_201.o dwdtable_202.o dwdtable_203.o cptectable_254.o nceptab_130.o nceptab_131.o #-lm
gcc: 错误：wgrib_main.o：没有那个文件或目录
make[5]: [wgrib.exe] 错误 1 (忽略)

**Comment by DYB2363021436** [comment]
I replaced lines 678 & 679 in COAWST/WRF/external/io_grib1/WGRIB/wgrib_main.c with:
         rmin = TMP_MAX;
		rmax = -TMP_MAX.

Originally:
        rmin = FLT_MAX.
		rmax = -FLT_MAX.

This is not wrong, but I don't know if it makes sense to do it this way？

**Comment by jcwarner-usgs** [comment]
i am not sure. that wrf file has not been updated in a long time.
search on the wrf forum, ask there, or search the web for flt_max.

https://askubuntu.com/questions/552150/where-is-flt-max-constant-defined-on-ubuntu

**Comment by DYB2363021436** [comment]
thank you!
