### ISSUE TITLE
WRF-SWAN problem:  MCT::m_SparseMatrixPlus::initFromRoot_:: FATAL--length of vector y different from row count of sMat.Length of y = 7200 Number of rows in sMat = 7031

### ISSUE THREAD

**Issue by linva7** [jcwarner-usgs/COAWST#209]
Dear all,
I compiled Sandy case for WRF-SWAN and ran it, there is a fatal error occured: MCT::m_SparseMatrixPlus::initFromRoot_:: FATAL--length of vector y different from row count of sMat.Length of y =     7200 Number of rows in sMat =     7031
000.MCT(MPEU)::die.: from MCT::m_SparseMatrixPlus::initFromRoot_().

I have checked my scrip file and input file, but I haven't found any contradictions. I searched online for similar problem solutions, but still haven't resolved the issue.

Here are the relevant files for my running case. Please help me identify the issue and explain the source of this error.
Thank you very much!
[Uploading coawst_files.zip…]()

**Comment by linva7** [comment]
@jcwarner-usgs

**Comment by jcwarner-usgs** [comment]
Are you running the test case we distribute or are you making your own case?
i have tested all these before i sent them out, but there could be an issue.
The files did not upload.  can you try them again?

**Comment by linva7** [comment]
Hi John, Sorry for causing confusion, I am running my own case based on Sandy, I have successfully run both the Sandy case and my own case before. For some reason, I reinstalled COAWST, and after reinstalling, I encountered this issue when running my own case.

I have re-uploaded my files. Could you please help me identify the source of the issue? Thank you very much! @jcwarner-usgs 

[coupling_2314.txt](https://github.com/DOI-USGS/COAWST/files/13710216/coupling_2314.txt)
[koinu_2314_out.txt](https://github.com/DOI-USGS/COAWST/files/13710219/koinu_2314_out.txt)
[namelist_input.txt](https://github.com/DOI-USGS/COAWST/files/13710220/namelist_input.txt)
[namelist_wps.txt](https://github.com/DOI-USGS/COAWST/files/13710221/namelist_wps.txt)
[PRINT-001.txt](https://github.com/DOI-USGS/COAWST/files/13710222/PRINT-001.txt)
[swan_2314_in.txt](https://github.com/DOI-USGS/COAWST/files/13710223/swan_2314_in.txt)
[grid_files.zip](https://github.com/DOI-USGS/COAWST/files/13710252/grid_files.zip)

**Comment by jcwarner-usgs** [comment]
if you have 2 swan grids, then you need to recompile with NESTING on.
And you need to change the coupling.in to have a '\'

   WAV_name = Projects/KOINU_2314/swan_2314.in \
              Projects/Sandy/swan_sandy_ref3.in

**Comment by linva7** [comment]
Thank you for the reminder. I only have one SWAN grid and i modified the number of grids in the 'swan.in' file to 1 and rerun it, but I encountered the same error as before. Here is my 'out' file. @jcwarner-usgs 

[koinu_2314_rerun_out.txt](https://github.com/DOI-USGS/COAWST/files/13717152/koinu_2314_rerun_out.txt)

**Comment by linva7** [comment]
Hi John, i am sorry for taking up your time. Could you please help me take a look at the issue I'm facing? @jcwarner-usgs

**Comment by jcwarner-usgs** [comment]
well a couple of things.
1 ) i see the time steps are
       ATMgrid 01 dt= 100.0 -to- WAVgrid 01 dt= 180.0, CplInt:  1800.0 Steps: 00018

       WAVgrid 01 dt= 180.0 -to- ATMgrid 01 dt= 100.0, CplInt:  1800.0 Steps: 00010

       ATMgrid 02 dt=  33.3 -to- WAVgrid 01 dt= 180.0, CplInt:  1800.0 Steps: *****

       WAVgrid 01 dt= 180.0 -to- ATMgrid 02 dt=  33.3, CplInt:  1800.0 Steps: *****

You need to make sure all the grids can time step evenly into the coupling interval.  So a 33 sec can not go into 1800.  adjust the time steps.

2) when you made the scrip file, what is the size of the swan grid and what values did you put in the scrip.in file?
for swan, you need to  Enter SWAN information:
!    -the size of the SWAN grids (full number of center points),

**Comment by linva7** [comment]
Hi John, Thank you for your suggestions. I have adjusted the time step of WRF to 108 and modified SWAN_NUMX(1) and SWAN_NUMY(1) in the scrip.in file to full number of center points. The model runs smoothly now, but I have encountered a new issue. It seems that the wind fields from WRF have not been successfully inputted into SWAN:
== SWAN grid  1 recv data from WRF grid 1
WRFtoSWAN Min/Max  U10     (ms-1):     0.000000E+00  0.000000E+00
WRFtoSWAN Min/Max  V10     (ms-1):     0.000000E+00  0.000000E+00
 == SWAN grid  1 recv data from WRF grid 2
WRFtoSWAN Min/Max  U10     (ms-1):     0.000000E+00  0.000000E+00
WRFtoSWAN Min/Max  V10     (ms-1):     0.000000E+00  0.000000E+00
 == SWAN grid  1 sent data to WRF grid     1
  ## WRF grid  1 recv data from WAVE grid  1
 WAVtoWRF  Min/Max HSIGN   (m):        0.000000E+00  0.000000E+00
 WAVtoWRF  Min/Max WLENP   (m):        0.000000E+00  0.000000E+00
 WAVtoWRF  Min/Max RTP     (m):        0.000000E+00  0.000000E+00
 == SWAN grid  1 sent data to WRF grid     2
  ## WRF grid  2 recv data from WAVE grid  1
 WAVtoWRF  Min/Max HSIGN   (m):        0.000000E+00  0.000000E+00
 WAVtoWRF  Min/Max WLENP   (m):        0.000000E+00  0.000000E+00

I have rechecked my scrip file and swan.in, but I haven't found the reason for the coupling failure. And I noticed this in outfile: "MCT::m_MCTWorld::initm_MCTERROR:  MCTWorld has already been initialized...Continuing", Is this the cause of the problem? How should I go about resolving it?

I will upload my latest run results and the modified files. I would greatly appreciate it if you could spare some more time to help me identify the root cause of the issue.

[koinu_2314_log.txt](https://github.com/DOI-USGS/COAWST/files/13759984/koinu_2314_log.txt)
[scrip_coawst_koinu.txt](https://github.com/DOI-USGS/COAWST/files/13759985/scrip_coawst_koinu.txt)
[swan_2314.txt](https://github.com/DOI-USGS/COAWST/files/13759986/swan_2314.txt)

**Comment by linva7** [comment]
@jcwarner-usgs

**Comment by jcwarner-usgs** [comment]
i am not sure why or how those time steps worked, but i  dont think they are correct.
All the grid time steps need to divide evenly into the coupling interval.
Your coupling interval is 1800 sec
then you have
atm grid 1 dt = 108
atm grid 2 dt = 36
wav grid 1 dt = 180

the wav is ok, 1800 /180 = 10.
but the atm 1 is not ok, 1800/108 is 16.66   this needs to be an intger.
atm 2 is 1800/36 = 50  that is ok

For the winds being = 0, are the lons and lats of the wrf and swan grids in the same convention?  how did you make the swan grid?

**Comment by linva7** [comment]
Thank you for your response. I have adjusted the time step for both WRF and SWAN to 150 and modified the coupling interval to 1500 to ensure better performance.

My SWAN grid is from a ROMS grid made by GridBuilder（use roms2swan.m to transform）, these are the relevant files related to my grid generation.
Thank you for your time and patience again.
[gird_files.zip](https://github.com/DOI-USGS/COAWST/files/13761088/gird_files.zip)

**Comment by linva7** [comment]
@jcwarner-usgs

**Comment by linva7** [comment]
@jcwarner-usgs

**Comment by linva7** [comment]
Hi John, i am sorry to bother you again, could you help me identify the issue？ Thank you for your time and patience again. @jcwarner-usgs

**Comment by linva7** [comment]
Hi John，i have resolved the issue. Thank you very much for your assistance before！
