### ISSUE TITLE
The output wrfout file won't open

### ISSUE THREAD

**Issue by DYB2363021436** [jcwarner-usgs/COAWST#210]
I installed COAWST in centos supercomputer, I can do the calculation, but in my own computer NCL with ncview,ncdump can't open the output file of WRF mode, compiling with the following warning

Packages in gen_scalar_indices1
WARNING: dfi_qzi is not a member of 4D array dfi_scalar
WARNING: ts_swp_tot is not a member of 4D array state
WARNING: ts_re_qs_tot is not a member of 4D array state
WARNING: ts_tau_qs_tot is not a member of 4D array state
WARNING: fire_smoke is not a member of 4D array state
WARNING: fad0_urb2d is not a member of 4D array state
WARNING: fad135_urb2d is not a member of 4D array state
WARNING: fad45_urb2d is not a member of 4D array state
WARNING: pad_urb2d is not a member of 4D array state
WARNING: fad90_urb2d is not a member of 4D array state
WARNING: rad_urb2d is not a member of 4D array state
WARNING: car_urb2d is not a member of 4D array state
WARNING: h2w_urb2d is not a member of 4D array state
WARNING: svf_urb2d is not a member of 4D array state
WARNING: z0s_urb2d is not a member of 4D array state
WARNING: z0r_urb2d is not a member of 4D array state
WARNING: z0m_urb2d is not a member of 4D array state
WARNING: zds_urb2d is not a member of 4D array state
WARNING: zdm_urb2d is not a member of 4D array state
WARNING: zdr_urb2d is not a member of 4D array state
REGISTRY WARNING: o3rad: o3rad_b is not a variable or number; ignoring it
REGISTRY WARNING: o3rad: o3rad_bt is not a variable or number; ignoring it
REGISTRY WARNING: aerod(grid%sm31,grid%sm32,grid%sm33,itrace): aerod_b is not a variable or number; ignoring it
REGISTRY WARNING: aerod(grid%sm31,grid%sm32,grid%sm33,itrace): aerod_bt is not a variable or number; ignoring it
REGISTRY WARNING: aerocu(grid%sm31,grid%sm32,grid%sm33,itrace): aerocu_b is not a variable or number; ignoring it
REGISTRY WARNING: aerocu(grid%sm31,grid%sm32,grid%sm33,itrace): aerocu_bt is not a variable or number; ignoring it
REGISTRY WARNING: om_tmp: om_tmp_b is not a variable or number; ignoring it
REGISTRY WARNING: om_tmp: om_tmp_bt is not a variable or number; ignoring it
REGISTRY WARNING: om_s: om_s_b is not a variable or number; ignoring it
REGISTRY WARNING: om_s: om_s_bt is not a variable or number; ignoring it
REGISTRY WARNING: om_u: om_u_b is not a variable or number; ignoring it
REGISTRY WARNING: om_u: om_u_bt is not a variable or number; ignoring it
REGISTRY WARNING: om_v: om_v_b is not a variable or number; ignoring it
REGISTRY WARNING: om_v: om_v_bt is not a variable or number; ignoring it
REGISTRY WARNING: om_ml: om_ml_b is not a variable or number; ignoring it
REGISTRY WARNING: om_ml: om_ml_bt is not a variable or number; ignoring it
REGISTRY WARNING: field_sf: field_sf_b is not a variable or number; ignoring it
REGISTRY WARNING: field_sf: field_sf_bt is not a variable or number; ignoring it
REGISTRY WARNING: field_pbl: field_pbl_b is not a variable or number; ignoring it
REGISTRY WARNING: field_pbl: field_pbl_bt is not a variable or number; ignoring it
REGISTRY WARNING: field_conv: field_conv_b is not a variable or number; ignoring it
REGISTRY WARNING: field_conv: field_conv_bt is not a variable or number; ignoring it
REGISTRY WARNING: ru_tendf_stoch: ru_tendf_stoch_b is not a variable or number; ignoring it
REGISTRY WARNING: ru_tendf_stoch: ru_tendf_stoch_bt is not a variable or number; ignoring it
REGISTRY WARNING: rv_tendf_stoch: rv_tendf_stoch_b is not a variable or number; ignoring it
REGISTRY WARNING: rv_tendf_stoch: rv_tendf_stoch_bt is not a variable or number; ignoring it
REGISTRY WARNING: rt_tendf_stoch: rt_tendf_stoch_b is not a variable or number; ignoring it
REGISTRY WARNING: rt_tendf_stoch: rt_tendf_stoch_bt is not a variable or number; ignoring it
REGISTRY WARNING: rand_pert: rand_pert_b is not a variable or number; ignoring it
REGISTRY WARNING: rand_pert: rand_pert_bt is not a variable or number; ignoring it
REGISTRY WARNING: pattern_spp_conv: pattern_spp_conv_b is not a variable or number; ignoring it
REGISTRY WARNING: pattern_spp_conv: pattern_spp_conv_bt is not a variable or number; ignoring it
REGISTRY WARNING: pattern_spp_pbl: pattern_spp_pbl_b is not a variable or number; ignoring it
REGISTRY WARNING: pattern_spp_pbl: pattern_spp_pbl_bt is not a variable or number; ignoring it
REGISTRY WARNING: pattern_spp_lsm: pattern_spp_lsm_b is not a variable or number; ignoring it
REGISTRY WARNING: pattern_spp_lsm: pattern_spp_lsm_bt is not a variable or number; ignoring it
REGISTRY WARNING: rstoch: rstoch_b is not a variable or number; ignoring it
REGISTRY WARNING: rstoch: rstoch_bt is not a variable or number; ignoring it
REGISTRY WARNING: field_u_tend_perturb: field_u_tend_perturb_b is not a variable or number; ignoring it
REGISTRY WARNING: field_u_tend_perturb: field_u_tend_perturb_bt is not a variable or number; ignoring it
REGISTRY WARNING: field_v_tend_perturb: field_v_tend_perturb_b is not a variable or number; ignoring it
REGISTRY WARNING: field_v_tend_perturb: field_v_tend_perturb_bt is not a variable or number; ignoring it
REGISTRY WARNING: field_t_tend_perturb: field_t_tend_perturb_b is not a variable or number; ignoring it
REGISTRY WARNING: field_t_tend_perturb: field_t_tend_perturb_bt is not a variable or number; ignoring it
ADVISORY: RSL_LITE version of gen_comms is linked in with registry program.

**Comment by jcwarner-usgs** [comment]
what is that output from?  is it from an ncl ?

**Comment by DYB2363021436** [comment]
YES

**Comment by jcwarner-usgs** [comment]
i am not sure.  the netcdf files from wrf should just be the same as from any other model.
can you try to read that netcdf file with matlab or ncview or some other tool?
