### ISSUE TITLE
Problems running WRF with quilting in COAWST setup

### ISSUE THREAD

**Issue by Butte9** [jcwarner-usgs/COAWST#212]
Hi, I ran WRF alone and set up the quilting without any problems, but I had problems running it after coupling WRF-ROMS-SWAN in COAWST. After the processes dedicated to I/O are finished running, the entire program exits. I would like to ask if COAWST currently supports WRF setting quilting?

**Comment by jcwarner-usgs** [comment]
i think it should work, but I know some people who also said they had troubles.
seems to be system dependent, but that is not an excuse.
I can look into it, but it will be some time.

**Comment by Butte9** [comment]
My problem seems to be that after the last I/O process of WRF ends, the ROMS and SWAN processes have not yet ended, which eventually causes the entire job to report an error and exit, but I can get the desired results.
I think we should tell the ROMS and SWAN processes after the last I/O process ends, instead of generating an error to end the entire job, which is easily misunderstood.
thank you very much!
