### ISSUE TITLE
MCT error 

### ISSUE THREAD

**Issue by Cherry-jw113** [jcwarner-usgs/COAWST#214]
Hello~

I encountered an error while coupling roms,wrf and ww3. Is it due to the inconsistency between the ROMS and WW3 grids? 
Error reported as follows：

MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch
LocalMap Gsize =       686917  RemoteMap Gsize =       588784
MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3
000.MCT(MPEU)::die.: from MCT::m_ExchangeMaps::ExGSMapGSMap_()
MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch
LocalMap Gsize =       588784  RemoteMap Gsize =       686917
MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3
040.MCT(MPEU)::die.: from MCT::m_ExchangeMaps::ExGSMapGSMap_()
Abort(2) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 0
Abort(2) on node 64 (rank 64 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 64

**Comment by jcwarner-usgs** [comment]
maybe when you made the scrip weight file, you entered the wrong grid sizes. 
is this the Sandy roms-wrf-ww3 test case?
or you own?

**Comment by Cherry-jw113** [comment]
My own. I check the scrip.in. The grid information looks right in it.
I noticed that in the Sandy roms-wrf-ww3 test case, the number of ww3 grids is equal to the number of roms grids. Probably because in my case, the number of ww3 grids is not equal to the number of roms grids

**Comment by jcwarner-usgs** [comment]
my ww3-roms coupling can only take 1 roms and 1 ww3 grid.  sorry.
you can have multiple roms and swan grids.

**Comment by Cherry-jw113** [comment]
ok~ Thanks~
