### ISSUE TITLE
Problem to compile roms - module_sf_clm.f90:(.text+0x68755): undefined reference to `nf_get_var_text_'

### ISSUE THREAD

**Issue by 10Secchi** [jcwarner-usgs/COAWST#218]
I tried to install COAWST 3.8, and at the final step to finish the compilation of ROMS I got the following problem:

/usr/bin/ld: /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/main/libwrflib.a(module_sf_clm.o): in function `__meganfactorsmod_MOD_megan_factors_init':
module_sf_clm.f90:(.text+0x68755): undefined reference to `nf_get_var_text_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x68826): undefined reference to `nf_get_var_double_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x688f1): undefined reference to `nf_get_var_int_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x69500): undefined reference to `nf_get_var_double_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x69683): undefined reference to `nf_get_var_double_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x6981a): undefined reference to `nf_get_var_double_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x6999d): undefined reference to `nf_get_var_double_'
/usr/bin/ld: module_sf_clm.f90:(.text+0x69b34): undefined reference to `nf_get_var_double_'
/usr/bin/ld: /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/main/libwrflib.a(module_sf_clm.o):module_sf_clm.f90:(.text+0x69cbf): more undefined references to `nf_get_var_double_' follow
collect2: error: ld returned 1 exit status
make: *** [Master/Module.mk:23: coawstM] Error 1

Anyone had a similar problem?

**Comment by jcwarner-usgs** [comment]
my first guess is that wrf is having trouble to find netcdf.
did you use
export NETCDF=....
wrf needs to know that path. 
look at the beginning of the build output and it will tell you if wrf found netcdf.

if you cant find it, can you post the entire output of the build? the error probably happened a lot earlier.  you can do
script build.log
./build_coawst.sh .....
exit
and then post the build.log

**Comment by 10Secchi** [comment]
@jcwarner-usgs thank you for your quick answer.

I am sending the log file, there some errors but I cant judge if they are the cause of the problem:
Line 4843 make[2]: [Makefile:17: em_wrf] Error 1 (ignored)
Line 5067 ---> Problems building executables, look for errors in the build log  <---

[log_new.log](https://github.com/DOI-USGS/COAWST/files/13999858/log_new.log)
 
 For additional support, I am also sending the flags which I used to set the PATHs for fortran and others libraries.
[export_coawst.txt](https://github.com/DOI-USGS/COAWST/files/13999871/export_coawst.txt)

**Comment by jcwarner-usgs** [comment]
not sure.
 undefined reference to `nf_get_var_text_
is having trouble to find the netcdf libs.  i see:

 -L/p2-varuna/secchi/exps/WRF_build2/libs/netcdf/lib -lnetcdff -L/p2-varuna/secchi/exps/WRF_build2/libs/lib -L/p2-varuna/secchi/exps/WRF_build2/libs/netcdf/lib -L/p2-varuna/secchi/exps/WRF_build2/libs/grib2/lib -lnetcdf -ldl -lm -lnetcdf -lz

you have a -lnetcdf, but i am not sure it is in the correct place.  how did you set these libs?
i think you need 
 -L/p2-varuna/secchi/exps/WRF_build2/libs/netcdf/lib -lnetcdff -lnetcdf

can you try something like that?

**Comment by 10Secchi** [comment]
Thank you ,

I tried some modifications on the paths but nothing solve the problem.

/p2-varuna/secchi/exps/WRF_build2/libs/bin/mpif90 -frepack-arrays -Wno-argument-mismatch -O3 -ffast-math -I/p2-varuna/secchi/exps/WRF_build2/libs/include -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/main -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/external/esmf_time_f90 -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/frame -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/share  ./Build_roms/esmf_atm.o ./Build_roms/propagator.o ./Build_roms/get_wrf_moving_grids.o ./Build_roms/roms_kernel.o ./Build_roms/read_coawst_par.o ./Build_roms/esmf_data.o ./Build_roms/esmf_wav.o ./Build_roms/master.o ./Build_roms/get_numswan_grids.o ./Build_roms/mct_coupler_utils.o ./Build_roms/read_model_inputs.o ./Build_roms/ocean_coupler.o ./Build_roms/esmf_esm.o ./Build_roms/coupler.o ./Build_roms/esmf_roms.o ./Build_roms/ww3_iounits.o ./Build_roms/esmf_ice.o ./Build_roms/mod_esmf_esm.o -o coawstM -L./Build_roms -lROMS **-L/p2-varuna/secchi/exps/WRF_build2/libs/lib -lnetcdff -lnetcdf** -L/p2-varuna/secchi/exps/WRF_build2/libs/lib -ldl -lm -lz /p2-varuna/secchi/exps/COAWST_build/COAWST/Build_roms/mct_coupler_params.o /p2-varuna/secchi/exps/COAWST_build/COAWST/Build_roms/mod_coupler_iounits.o /p2-varuna/secchi/exps/COAWST_build/COAWST/Build_roms/get_sparse_matrix.o -L/p2-varuna/secchi/exps/WRF_build2/libs/lib -lmct -lmpeu /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/main/module_wrf_top.o /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/main/libwrflib.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/fftpack/fftpack5/libfftpack.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_grib1/libio_grib1.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_grib_share/libio_grib_share.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_int/libwrfio_int.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/esmf_time_f90/libesmf_time.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/RSL_LITE/librsl_lite.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/frame/module_internal_header_util.o /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/frame/pack_utils.o /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_netcdf/libwrfio_nf.a

This is strange since WRF alone runs and compile with the same libraries.
I will try to compile the Libraries from scratch again.
So I can came later and say if the problem persisted

**Comment by jcwarner-usgs** [comment]
i dont think it is the libraries.  i dont think you need to recompile them.

try
 -L/p2-varuna/secchi/exps/WRF_build2/libs/lib  -lnetcdf -lnetcdff


if that fails try to just paste this command
/p2-varuna/secchi/exps/WRF_build2/libs/bin/mpif90 -frepack-arrays -Wno-argument-mismatch -O3 -ffast-math -I/p2-varuna/secchi/exps/WRF_build2/libs/include -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/main -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/external/esmf_time_f90 -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/frame -I/p2-varuna/secchi/exps/COAWST_build/COAWST//WRF/share ./Build_roms/esmf_atm.o ./Build_roms/propagator.o ./Build_roms/get_wrf_moving_grids.o ./Build_roms/roms_kernel.o ./Build_roms/read_coawst_par.o ./Build_roms/esmf_data.o ./Build_roms/esmf_wav.o ./Build_roms/master.o ./Build_roms/get_numswan_grids.o ./Build_roms/mct_coupler_utils.o ./Build_roms/read_model_inputs.o ./Build_roms/ocean_coupler.o ./Build_roms/esmf_esm.o ./Build_roms/coupler.o ./Build_roms/esmf_roms.o ./Build_roms/ww3_iounits.o ./Build_roms/esmf_ice.o ./Build_roms/mod_esmf_esm.o -o coawstM -L./Build_roms -lROMS -L/p2-varuna/secchi/exps/WRF_build2/libs/lib -ldl -lm -lz /p2-varuna/secchi/exps/COAWST_build/COAWST/Build_roms/mct_coupler_params.o /p2-varuna/secchi/exps/COAWST_build/COAWST/Build_roms/mod_coupler_iounits.o /p2-varuna/secchi/exps/COAWST_build/COAWST/Build_roms/get_sparse_matrix.o -L/p2-varuna/secchi/exps/WRF_build2/libs/lib -lmct -lmpeu /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/main/module_wrf_top.o /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/main/libwrflib.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/fftpack/fftpack5/libfftpack.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_grib1/libio_grib1.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_grib_share/libio_grib_share.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_int/libwrfio_int.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/esmf_time_f90/libesmf_time.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/RSL_LITE/librsl_lite.a /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/frame/module_internal_header_util.o /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/frame/pack_utils.o /p2-varuna/secchi/exps/COAWST_build/COAWST/WRF/external/io_netcdf/libwrfio_nf.a
 -L/p2-varuna/secchi/exps/WRF_build2/libs/lib -lnetcdff -lnetcdf

**Comment by 10Secchi** [comment]
Thank you John, I was able to finally compile the coawst using the following set from the scratch:

./configure --prefix=/p2-varuna/secchi/exps/COAWST_build/LIBRARIES/opt/ CFLAGS=-I/p2-varuna/secchi/exps/COAWST_build/LIBRARIES/opt/include FCFLAGS=-L/p2-varuna/secchi/exps/COAWST_build/LIBRARIES/opt/lib CPPFLAGS=-I/p2-varuna/secchi/exps/COAWST_build/LIBRARIES/opt/include LDFLAGS=-L/p2-varuna/secchi/exps/COAWST_build/LIBRARIES/opt/lib

For netcdf-c and -fortran I also reomeve the option for --disable-shared

**Comment by jcwarner-usgs** [comment]
nice!
