### ISSUE TITLE
Doubt about climate and boundary files in SANDY test case

### ISSUE THREAD

**Issue by met-sree** [jcwarner-usgs/COAWST#219]
Hi everyone,
   I have installed the Sandy test case and have some questions regarding climate and boundary conditions for the ROMS model.
**Boundary Files:**
In the Sandy folder, there are coawst_bdy_201210* and Sandy_bdy.nc files. The **coawst_bdy_201210*** files are utilized as boundary conditions in the ROMS input file (ocean_sandy.in).

**Climate Files:**
Similarly, in the Sandy folder, there are coawst_clm_201210* and Sandy_clm.nc files. The **Sandy_clm.nc** file is used as climate conditions in the ROMS input file (ocean_sandy.in).
     "Why is ocean_sandy.in configured to use **coawst_bdy_201210*** and **Sandy_clm.nc**, while not considering **Sandy_bdy.nc** and **coawst_clm_201210***?" Is there any specific reason for this?

Thank you,
Srinivas

**Comment by jcwarner-usgs** [comment]
i think i just listed the coawst_bdy_201210*  files as an example of how to use multiple input files.  it should run with the merged file or the individual files.

"When you run this m file, it will create multiple files:
- Inititial conditions: coawst_ini.nc
- Boundary conditions: coawst_bdy_20121028.nc, 29, 30, 31, 01 (5 files) and a 
merged_coawst_bdy.nc (all 5 of those merged into 1 file).
- Climatology: coawst_clm_20121028.nc, 29, 30, 31, 01 (5 files) and a 
merged_coawst_clm.nc (all 5 of those merged into 1 file). I renamed: 
coawst_ini.nc to Sandy_ini.nc
merged_coawst_bdy.nc to Sandy_bdy.nc
merged_coawst_clm.nc to Sandy_clm.nc"
