### ISSUE TITLE
COAWST user manual fails to open in Ubuntu

### ISSUE THREAD

**Issue by HathewayWill** [jcwarner-usgs/COAWST#221]
![Screenshot from 2024-01-25 15-31-29](https://github.com/DOI-USGS/COAWST/assets/118180342/962b9c92-9e43-4d4c-a210-eee2e8d8717b)

**Comment by jcwarner-usgs** [comment]
it's a .doc word file.  can you open it in word?

**Comment by HathewayWill** [comment]
Was able to open it in LibreOffice, but the default ubuntu document reader it wasn't supported.  Closing issue
