### ISSUE TITLE
Real.exe not working in COAWST

### ISSUE THREAD

**Issue by met-sree** [jcwarner-usgs/COAWST#223]
Hello everyone,
         I've successfully **installed the COAWST** model using Intel compilers. During the installation, real.exe was created, and wrf.exe is linked to coawstM. I plan to use real.exe to generate the wrfinput and wrfbdy files. However, I encountered the following error:
 **"starting wrf task            0  of            1
Abort(67715845) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Comm_rank: Invalid communicator, error stack:
PMPI_Comm_rank(106): MPI_Comm_rank(comm=0x0, rank=0x7ffd2a4a168c) failed
PMPI_Comm_rank(63).: Invalid communicator"**
          To crosscheck, I've also installed the **individual WRF model** using the same compilers and configuration as COAWST. With this setup, wrfinput and wrfbdy files are created successfully using the same metgrid files. If anyone has insights into this error or suggestions on how to rectify it, your valuable input would be greatly appreciated.

Thank you.
Srinivas

**Comment by jcwarner-usgs** [comment]
the best path here is to first compile coawst with just #define WRF_MODEL.
then you will get a real.exe.  run real and anything else just wrf related.
then modify your .h file to include roms swan etc.  recompile.
and that will give you a coawstM to run in coupled mode.

alternatively you can have a separate folder, get wrf from ncar  or use coawst, compile it in separate folder with just wrf model, and use that folder with real etc. then you always have that real.exe and dont need to recompile coawst.

-j
