### ISSUE TITLE
system hanging while installing COAWST

### ISSUE THREAD

**Issue by met-sree** [jcwarner-usgs/COAWST#224]
Hi everyone, 
        We are in the process of reinstalling the COAWST model using the "sandy.h" header file in a new folder, after a successful installation in the past. However, we are currently experiencing an issue where the system hangs during the installation process. The commands used are as follows:
                          **script coawst.log
                           ./build_coawst.sh -j 4**
       For your reference, the coawst.log file is attached below. Similar problems have been encountered in the past. We would appreciate any valuable suggestions to resolve this issue.
[coawst.txt](https://github.com/DOI-USGS/COAWST/files/14107115/coawst.txt)

Thankyou,
Srinivas

**Comment by jcwarner-usgs** [comment]
I think it is hanging at the location to build SWAN.  we use CMake now to build swan, and that will be needed for ROMS.
Other people have had this issue. But i dont know how to fix it on your system.
try this:

your build is having trouble using cmake. it is hard for me to work on that. here are some steps to try.
dowload SWAN directly from their site and get cmake to work for that. once that works, we can build coawst.

as a test to see if you can build swan by itself, you can get the swan code from delft and use cmake to build it on denali. this would be an easy way to see why cmake is not working for you. here are some simple steps:

make a dir called SWAN
-cd SWAN
get SWAN code here https://gitlab.tudelft.nl/citg/wavemodels/swan by doing
git clone https://gitlab.tudelft.nl/citg/wavemodels/swan.git .
-following the build instructions on that site. The steps are:
cd swan
mkdir build && cd build
cmake .. -G "Unix Makefiles" -DUNIX=ON -DMPI=ON -DNETCDF=ON -DCMAKE_VERBOSE_MAKEFILE=ON
make

if that works, let me know.

**Comment by jcwarner-usgs** [comment]
It should look something like this:::::   (yours stops after the libnetcdff.so)


-- The Fortran compiler identification is Intel 18.0.2.20180210
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /vortexfs1/apps/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiifort - skipped
-- Checking whether /vortexfs1/apps/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiifort supports Fortran 90
-- Checking whether /vortexfs1/apps/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiifort supports Fortran 90 - yes
-- Found Perl: /usr/bin/perl (found version "5.16.3")
-- Found MPI_Fortran: /vortexfs1/apps/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiifort (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found NetCDF: /vortexfs1/apps/impistack-1.0/include (found version "4.6.1") found components: Fortran
-- FindNetCDF defines targets:
--   - NetCDF_VERSION [4.6.1]
--   - NetCDF_PARALLEL [TRUE]
--   - NetCDF_C_CONFIG_EXECUTABLE [/vortexfs1/apps/impistack-1.0/bin/nc-config]
--   - NetCDF::NetCDF_C [SHARED] [Root: /vortexfs1/apps/impistack-1.0] Lib: /vortexfs1/apps/impistack-1.0/lib/libnetcdf.so
--   - NetCDF_Fortran_CONFIG_EXECUTABLE [/vortexfs1/apps/impistack-1.0/bin/nf-config]
--   - NetCDF::NetCDF_Fortran [SHARED] [Root: /vortexfs1/apps/impistack-1.0] Lib: /vortexfs1/apps/impistack-1.0/lib/libnetcdff.so
-- Found MPI: TRUE (found version "3.1") found components: Fortran
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/jwarner/Idalia2023/run4/SWAN/build
make[1]: Entering directory `/scratch/jwarner/Idalia2023/run4/SWAN/build'
/vortexfs1/apps/cmake-3.20.2/bin/cmake -S/scratch/jwarner/Idalia2023/run4/SWAN -B/scratch/jwarner/Idalia2023/run4/SWAN/build --check-build-system CMakeFiles/Makefile.cmake 0
/vortexfs1/apps/cmake-3.20.2/bin/cmake -E cmake_progress_start /scratch/jwarner/Idalia2023/run4/SWAN/build/CMakeFiles /scratch/jwarner/Idalia2023/run4/SWAN/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[2]: Entering directory `/scratch/jwarner/Idalia2023/run4/SWAN/build'
make  -f lib/CMakeFiles/swan41.45.dir/build.make lib/CMakeFiles/swan41.45.dir/depend
make[3]: Entering directory `/scratch/jwarner/Idalia2023/run4/SWAN/build'
cd /scratch/jwarner/Idalia2023/run4/SWAN/build && /vortexfs1/apps/cmake-3.20.2/bin/cmake -E cmake_depends "Unix Makefiles" /scratch/jwarner/Idalia2023/run4/SWAN /scratch/jwarner/Idalia2023/run4/SWAN/src_coawst /scratch/jwarner/Idalia2023/run4/SWAN/build /scratch/jwarner/Idalia2023/run4/SWAN/build/lib /scratch/jwarner/Idalia2023/run4/SWAN/build/lib/CMakeFiles/swan41.45.dir/DependInfo.cmake --color=
Scanning dependencies of target swan41.45
make[3]: Leaving directory `/scratch/jwarner/Idalia2023/run4/SWAN/build'
make  -f lib/CMakeFiles/swan41.45.dir/build.make lib/CMakeFiles/swan41.45.dir/build
make[3]: Entering directory `/scratch/jwarner/Idalia2023/run4/SWAN/build'
[  1%] Building Fortran object lib/CMakeFiles/swan41.45.dir/swmod1.f.o
cd /scratch/jwarner/Idalia2023/run4/SWAN/build/lib && /vortexfs1/apps/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpiifort  -I/vortexfs1/apps/impistack-1.0/include -O2 -W0 -assume byterecl -traceback -diag-disable 8290 -diag-disable 8291 -diag-disable 8293 -I/scratch/jwarner/Idalia2023/run4/Build_roms -I/vortexfs1/usgs/jwarner/models/MCT_stack/include -module ../mod -c /scratch/jwarner/Idalia2023/run4/SWAN/src_coawst/swmod1.f -o CMakeFiles/swan41.45.dir/swmod1.f.o
/vortexfs1/apps/cmake-3.20.2/bin/cmake -E cmake_copy_f90_mod mod/ocpcomm4.mod lib/CMakeFiles/swan41.45.dir/ocpcomm4.mod.stamp Intel
/vortexfs1/apps/cmake-3.20.2/bin/cmake -E cmake_copy_f90_mod mod/swcomm1.mod lib/CMakeFiles/swan41.45.dir/swcomm1.mod.stamp Intel
/vortexfs1/apps/cmake-3.20.2/bin/cmake -E cmake_copy_f90_mod mod/swcomm3.mod lib/CMakeFiles/swan41.45.dir/swcomm3.mod.stamp Intel
/vortexfs1/apps/cmake-3.20.2/bin/cmake -E cmake_copy_f90_mod mod/swcomm4.mod lib/CMakeFiles/swan41.45.dir/swcomm4.mod.stamp Intel
[  2%] Building Fortran object lib/CMakeFiles/swan41.45.dir/SdsBabanin.f90.o

**Comment by met-sree** [comment]
Sir, 
        Thank you, Sir. We followed the steps mentioned above for the SWAN installation, up to the 'make' stage. We believe it has been completed, concluding with the line mentioned below. 
**make[2]: Leaving directory '/home/user1/COAWST_BUILD/COAWST_main/SWAN/swan/build'
[100%] Built target hcat.exe
make[1]: Leaving directory '/home/user1/COAWST_BUILD/COAWST_main/SWAN/swan/build'
/usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E cmake_progress_start /home/user1/COAWST_BUILD/COAWST_main/SWAN/swan/build/CMakeFiles 0**

**The below files are created in swan/bin folder**
-rw-r--r-- 1 root root    7096 Jan 31 22:10 Makefile
-rw-r--r-- 1 root root    3449 Jan 31 22:10 cmake_install.cmake
drwxr-xr-x 2 root root    4096 Jan 31 22:10 CMakeFiles
-rwxr-xr-x 1 root root 5537792 Jan 31 22:11 swan.exe
-rwxr-xr-x 1 root root  839296 Jan 31 22:11 hcat.exe

**Comment by jcwarner-usgs** [comment]
ok.  
can you paste the full build in here?
then try the coawst build again.

**Comment by met-sree** [comment]
Sir,
Thank you. After successfully installing SWAN from the source code, we attempted to build COAWST. However, we encountered the same issue. Please find attached the tar file containing the SWAN model folder obtained after installation with the source code.
[swan.tar.gz](https://github.com/DOI-USGS/COAWST/files/14120276/swan.tar.gz)

**Comment by jcwarner-usgs** [comment]
ok.  i can see you built swanrun and swan.exe

lets see if we can get this to work in coawst, because we do the same thing.
make a project.h file with just #define SWAN_MODEL in it, and try to build that.

**Comment by met-sree** [comment]
Sir,
Thank you for your assistance. I attempted to use the COAWST model with only the SWAN header file, but the issue persists. Please find the attached log file for this specific configuration. Due to server overload, I had to forcefully stop the process by clicking Ctrl+X.
[coawst.log](https://github.com/DOI-USGS/COAWST/files/14128152/coawst.log)

**Comment by jcwarner-usgs** [comment]
when you installed swan from their source code git site,
can you send to me the same standard output file from that build?

**Comment by met-sree** [comment]
Sir, 
Please find the attached file as you requested
[swan.tar.gz](https://github.com/DOI-USGS/COAWST/files/14129382/swan.tar.gz)
[swan_cmake_from_sourcecode.log](https://github.com/DOI-USGS/COAWST/files/14129383/swan_cmake_from_sourcecode.log)
[swan_make_from_sourcecode.log](https://github.com/DOI-USGS/COAWST/files/14129385/swan_make_from_sourcecode.log)

**Comment by jcwarner-usgs** [comment]
ok i am still missing some information.
when you downloaded the src code from delft, then you made a dir called swan.
then you cd to swan

at this point, i want you to save a file that has all the commands in it. tpye:
     script    build.log
that will start a log file.
then you type
cd build
then you tpye
cmake .. -G "Unix Makefiles" -DUNIX=ON -DMPI=ON -DNETCDF=ON -DCMAKE_VERBOSE_MAKEFILE=ON

then type
make

when done, type exit and send the build.log file here.
I am not seeing the earlier lines.

**Comment by met-sree** [comment]
Sir,
Please find the attached file as you requested
[swan_build.log](https://github.com/DOI-USGS/COAWST/files/14129926/swan_build.log)

**Comment by jcwarner-usgs** [comment]
ok.  nice.

this worked:
-- The Fortran compiler identification is Intel 2021.9.0.20230302
... -- Check for working Fortran compiler: /opt/intel/oneapi/mpi/2021.9.0/bin/mpiifort - skipped
-- Found MPI_Fortran: /opt/intel/oneapi/mpi/2021.9.0/bin/mpiifort (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components: Fortran 
...


this did not work:
-- The Fortran compiler identification is Intel 2021.9.0.20230302
-- Check for working Fortran compiler: /opt/intel/oneapi/mpi/2021.9.0/bin/mpif90 - skipped

So it worked when it found mpiifort.
Maybe we need to modify your build_coawst.bash to point to mpiifort instead of mpif90. ??
There are several settings in the build_coawst.bash file, as well as the Compilers/Linux-? .mk file.
try to use this 
 export           USE_MPI=on            # distributed-memory parallelism
 export        USE_MPIF90=on            # compile with mpif90 script
 export         which_MPI=intel         # compile with mpiifort library
If you set FORT=ifort, then it will use the settings in Compilers/Linux-ifort.mk

**Comment by met-sree** [comment]
Thank you, Sir. It worked successfully.

**Comment by jcwarner-usgs** [comment]
nice!
