### ISSUE TITLE
 GET_SPARSE - error while opening file:

### ISSUE THREAD

**Issue by met-sree** [jcwarner-usgs/COAWST#226]
Hi everyone,
we have successfully installed the COAWST model, utilizing a single domain configuration for WRF, ROMS, and SWAN (similar to the sandy.h header file without NESTING; undef NESTING). But, during the running of the model, we encountered an error as follows:
 **GET_SPARSE - error while opening file: /home/user1/COAWST_BUILD/COAWST_1D_All/Lib/SCRIP_COAWST/scrip_joe_tc_d
 GET_SPARSE - error while opening file: /home/user1/COAWST_BUILD/COAWST_1D_All/Lib/SCRIP_COAWST/scrip_joe_tc_d**
 Kindly refer to the attached files below for additional information regarding the encountered errors. We would appreciate your insights and suggestions on resolving these errors.

Thank you,
Srinivas
[run_coawst.log](https://github.com/DOI-USGS/COAWST/files/14157140/run_coawst.log)
[scrip_coawst_joetc_diffgrid.in.txt](https://github.com/DOI-USGS/COAWST/files/14157146/scrip_coawst_joetc_diffgrid.in.txt)
[scrip_joe_tc_diffgrid_nc.tar.gz](https://github.com/DOI-USGS/COAWST/files/14157149/scrip_joe_tc_diffgrid_nc.tar.gz)

**Comment by jcwarner-usgs** [comment]
it seems to me to just be a "too long of a filename" issue.
It did not state the full name.
At  one point in time, we had like a 72 char filename limit, but i thought it was more than that now.
Do me favor and put that file here /home/user1/COAWST_BUILD/COAWST_1D_All/scrip_joe_tc_diffgrid.nc
and change the path to that file in the coupling.in.  then see if it works.
this is just a test to see if the path name is too long.
