### ISSUE TITLE
wrf

### ISSUE THREAD

**Issue by hgengqi** [jcwarner-usgs/COAWST#227]

**Comment by hgengqi** [comment]
WRF compile compile can not appear exe file, the specific error record is as follows, i don't know how to solve it,could you please help me
, thank you!

**Comment by hgengqi** [comment]
[Uploading compile.log…]()

**Comment by hgengqi** [comment]
**** Compiling WPS and all utilities ****
 
make[1]: Entering directory `/public/home/SJB20230001/COAWST-TEST/WPS/geogrid/src'
/bin/rm -f cio.o
mpicc -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DBIT32 -DNO_SIGNAL -D_MPI -D_GEOGRID  -c cio.c	
/bin/rm -f constants_module.o constants_module.mod
/usr/bin/cpp -P -traditional -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DBIT32 -DNO_SIGNAL -D_MPI -D_GEOGRID -DUSE_JPEG2000 -DUSE_PNG -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_netcdf -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib_share -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib1 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_int -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/inc -I/public/home/SJB20230001/model/Build_coawst/LIBRARIES/netcdf/include constants_module.F > constants_module.f90
mpif90  -ffree-form -O -fconvert=big-endian -frecord-marker=4 -c constants_module.f90 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_netcdf -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib_share -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib1 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_int -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/inc -I/public/home/SJB20230001/model/Build_coawst/LIBRARIES/netcdf/include
/bin/rm -f misc_definitions_module.o misc_definitions_module.mod
/usr/bin/cpp -P -traditional -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DBIT32 -DNO_SIGNAL -D_MPI -D_GEOGRID -DUSE_JPEG2000 -DUSE_PNG -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_netcdf -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib_share -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib1 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_int -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/inc -I/public/home/SJB20230001/model/Build_coawst/LIBRARIES/netcdf/include misc_definitions_module.F > misc_definitions_module.f90
mpif90  -ffree-form -O -fconvert=big-endian -frecord-marker=4 -c misc_definitions_module.f90 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_netcdf -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib_share -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib1 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_int -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/inc -I/public/home/SJB20230001/model/Build_coawst/LIBRARIES/netcdf/include
/bin/rm -f parallel_module.o parallel_module.mod
/usr/bin/cpp -P -traditional -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DBIT32 -DNO_SIGNAL -D_MPI -D_GEOGRID -DUSE_JPEG2000 -DUSE_PNG -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_netcdf -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib_share -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib1 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_int -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/inc -I/public/home/SJB20230001/model/Build_coawst/LIBRARIES/netcdf/include parallel_module.F > parallel_module.f90
mpif90  -ffree-form -O -fconvert=big-endian -frecord-marker=4 -c parallel_module.f90 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_netcdf -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib_share -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_grib1 -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/external/io_int -I/public/home/SJB20230001/COAWST-TEST/WPS/../WRF/inc -I/public/home/SJB20230001/model/Build_coawst/LIBRARIES/netcdf/include
parallel_module.f90:922:24:

  922 |          call MPI_Bcast(rval, 1, MPI_REAL, from_whom, comm, mpi_ierr)
      |                        1
......
  948 |          call MPI_Bcast(cval, n, MPI_CHARACTER, from_whom, comm, mpi_ierr)
      |                        2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/CHARACTER(*)).
parallel_module.f90:924:24:

  924 |          call MPI_Bcast(rval, 1, MPI_REAL, IO_NODE, comm, mpi_ierr)
      |                        1
......
  948 |          call MPI_Bcast(cval, n, MPI_CHARACTER, from_whom, comm, mpi_ierr)
      |                        2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/CHARACTER(*)).
parallel_module.f90:897:24:

  897 |          call MPI_Bcast(ival, 1, MPI_INTEGER, from_whom, comm, mpi_ierr)
      |                        1
......
  948 |          call MPI_Bcast(cval, n, MPI_CHARACTER, from_whom, comm, mpi_ierr)
      |                        2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/CHARACTER(*)).
parallel_module.f90:899:24:

  899 |          call MPI_Bcast(ival, 1, MPI_INTEGER, IO_NODE, comm, mpi_ierr)
      |                        1
......
  948 |          call MPI_Bcast(cval, n, MPI_CHARACTER, from_whom, comm, mpi_ierr)
      |                        2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/CHARACTER(*)).
parallel_module.f90:875:21:

  875 |       call MPI_Bcast(lval, 1, MPI_LOGICAL, IO_NODE, comm, mpi_ierr)
      |                     1
......
  948 |          call MPI_Bcast(cval, n, MPI_CHARACTER, from_whom, comm, mpi_ierr)
      |                        2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/CHARACTER(*)).
parallel_module.f90:519:29:

  519 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:527:29:

  527 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:539:29:

  539 |                call MPI_Send(patch_array(ps1:ps1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:547:29:

  547 |                call MPI_Recv(patch_array(me1-HALO_WIDTH+1:me1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:559:29:

  559 |                call MPI_Send(patch_array(ms1:me1,jj,kk), (me1-ms1+1), MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:567:29:

  567 |                call MPI_Recv(patch_array(ms1:me1,jj,kk), (me1-ms1+1), MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:579:29:

  579 |                call MPI_Send(patch_array(ms1:me1,jj,kk), (me1-ms1+1), MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:587:29:

  587 |                call MPI_Recv(patch_array(ms1:me1,jj,kk), (me1-ms1+1), MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:599:29:

  599 |                call MPI_Send(patch_array(ps1:ps1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:607:29:

  607 |                call MPI_Recv(patch_array(me1-HALO_WIDTH+1:me1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:619:29:

  619 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:627:29:

  627 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:639:29:

  639 |                call MPI_Send(patch_array(ps1:ps1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:647:29:

  647 |                call MPI_Recv(patch_array(me1-HALO_WIDTH+1:me1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:659:29:

  659 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:667:29:

  667 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_REAL, &
      |                             1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:464:35:

  464 |                      call MPI_Send(domain_array(idims(1):idims(2),jdims(1):jdims(2),kk), &
      |                                   1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2      
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:483:26:

  483 |             call MPI_Recv(patch_array(ps1:pe1,ps2:pe2,kk), (pe1-ps1+1)*(pe2-ps2+1), &
      |                          1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:343:35:

  343 |                      call MPI_Recv(domain_array(idims(1):idims(2),jdims(1):jdims(2),kk), &
      |                                   1
......
  711 |                call MPI_Recv(patch_array(ms1:ms1+HALO_WIDTH-1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2      
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
parallel_module.f90:362:26:

  362 |             call MPI_Send(patch_array(ps1:pe1,ps2:pe2,kk), (pe1-ps1+1)*(pe2-ps2+1), MPI_REAL, 0, my_proc_id, comm, mpi_ierr)
      |                          1
......
  703 |                call MPI_Send(patch_array(pe1-HALO_WIDTH+1:pe1,jj,kk), HALO_WIDTH, MPI_INTEGER, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).

**Comment by jcwarner-usgs** [comment]
this is an issue with WPS.
I think it is due to your use of gfortran and misisng a flag.
try this.
Edit WPS/configure.defaults and modify the FFLAGS from
FFLAGS              = -ffree-form -O -fconvert=big-endian -frecord-marker=4
to 
FFLAGS              = -ffree-form -O -fconvert=big-endian -frecord-marker=4 -fallow-argument-mismatch

i am not sure exactly which line to change.
probably line 160 or 184
then recompile

**Comment by hgengqi** [comment]
> this is an issue with WPS. I think it is due to your use of gfortran and misisng a flag. try this. Edit WPS/configure.defaults and modify the FFLAGS from FFLAGS = -ffree-form -O -fconvert=big-endian -frecord-marker=4 to FFLAGS = -ffree-form -O -fconvert=big-endian -frecord-marker=4 -fallow-argument-mismatch
> 
> i am not sure exactly which line to change. probably line 160 or 184 then recompile

i'm sorry but i can't find configure.defaults in WPS files,so i edit configure.wps FFLAGS but it didn't work

**Comment by jcwarner-usgs** [comment]
sorry. WPS/arch/configure.defaults

**Comment by hgengqi** [comment]
> -fallow-argument-mismatch

thank you for your help but it still doesn't work

**Comment by jcwarner-usgs** [comment]
can you show me the output of the build again?
