### ISSUE TITLE
Error compiling WRF

### ISSUE THREAD

**Issue by able93** [jcwarner-usgs/COAWST#228]
Hello,

1. I am trying to compile case Sandy, but keep getting an error message:

use module_ext_internal
      1
Fatal Error: Can't open module file ‘module_ext_internal.mod’ for reading at (1): No such file or directory
compilation terminated

Then it brings another error

time: Command not found

How do I fix this?

Please find attached my log file
[sandy.log](https://github.com/DOI-USGS/COAWST/files/14455902/sandy.log)

2. Also, ROMS and SWAN work properly on my grid of 461x511, but SWAN would only take 4, 8, 15 processors. Every time I try another number of processors from those, it only writes 
SWAN grid   1 is preparing computation and stays there for as long without progressing.

Thanks

**Comment by jcwarner-usgs** [comment]
i dont see any problems in that log file, but it is not complete.  the errors must be going some place else. 
try this,type:
scrip build.log
./coawst.bash -j X   (some number)
when it is done type: exit
then send build.log to me.

**Comment by able93** [comment]
[build.log](https://github.com/DOI-USGS/COAWST/files/14461924/build.log)

I have attached the build file.

Thanks

**Comment by able93** [comment]
Thank you so much.

I have attached the build log.

**Comment by jcwarner-usgs** [comment]
i see
make[4]: time: Command not found
make[4]: [module_internal_header_util.o] Error 127 (ignored)

the command 'time' is not found on your system.  that is used to track the amount of time in each subroutine.
can you have a system admin install that utility?
https://linuxpip.org/fix-time-command-not-found-error/

**Comment by able93** [comment]
Thank you. I have informed the system admin.

Meanwhile, I have a grid size of 461x511, but the number of processes
allowed by SWAN when running is either 4, 8, or 15, but nothing higher.

Is there how I can fix this?

Thanks

**Comment by jcwarner-usgs** [comment]
swan tiles along the longest dimension. so for your app it would be along the 511 side.
each tile should have wet points.  is there a chance that a tile would only get masked cells with other options?
when the model stops, does it create any Err* files?

**Comment by able93** [comment]
Yes, there are masked areas along the 511 side. Check below. The model
still keeps running but with no error or output, everything seizes. It
doesn't stop itself unless I do.

[image: image.png]

**Comment by jcwarner-usgs** [comment]
i cant see the image.

**Comment by NicJeffress** [comment]
I have also experienced this SWAN error when running ROMS + SWAN and SWAN only via COAWST 3.7. When I am using GNU compilers swan keeps running with no error or output or time stepping, but when I use intel compilers I get a segmentation fault error. I suspect it is an error related to not having enough allocated memory. When I have done separate runs in swan 41.45 i have found that when I use mpi the memory used for my the job scales linearly with number of processors (ex, 1 processor requires 8GB and 2 requires 16GB ...). When I run swan using OpenMP memory routines I have found that the memory requirement of the job is independent of number of processors (ex. 8GB for 1 and 8GB for 2...).  I think that the error with max number of processors for swan might be related to the max amount of RAM you have available for the job

**Comment by able93** [comment]
I have attached it.

**Comment by able93** [comment]
![domain](https://github.com/DOI-USGS/COAWST/assets/126428603/04f4cc7e-9f33-4988-92b7-528fffeb83db)

**Comment by jcwarner-usgs** [comment]
for your app, swan will tile along the N-S dimension (longest dim).  The first tile will need to be hi enough so that it is not all land. So the first tile will need to go from 22 lat to about 22.5 or 22.6 lat.  if the first tile was only from 22 to 22.1 then it would be all land and swan might not like that.
if you use 511/15 = ~ 34 cells.  what is lat_rho(1,34)?

**Comment by able93** [comment]
> I have also experienced this SWAN error when running ROMS + SWAN and SWAN only via COAWST 3.7. When I am using GNU compilers swan keeps running with no error or output or time stepping, but when I use intel compilers I get a segmentation fault error. I suspect it is an error related to not having enough allocated memory. When I have done separate runs in swan 41.45 i have found that when I use mpi the memory used for my the job scales linearly with number of processors (ex, 1 processor requires 8GB and 2 requires 16GB ...). When I run swan using OpenMP memory routines I have found that the memory requirement of the job is independent of number of processors (ex. 8GB for 1 and 8GB for 2...). I think that the error with max number of processors for swan might be related to the max amount of RAM you have available for the job

Thank you. I use HPC, so I am not sure if I have limitations. ROMS never had this problem because I use as many as 120 processors for it. But only have this problem with SWAN. I am guessing the suggestion that a wet cell being in every tile might be part of the problem. I wish I find a way around it to speed up my work.

**Comment by able93** [comment]
> for your app, swan will tile along the N-S dimension (longest dim). The first tile will need to be hi enough so that it is not all land. So the first tile will need to go from 22 lat to about 22.5 or 22.6 lat. if the first tile was only from 22 to 22.1 then it would be all land and swan might not like that. if you use 511/15 = ~ 34 cells. what is lat_rho(1,34)?

lat_rho(1,34) = 22.4243

**Comment by NicJeffress** [comment]
> > I have also experienced this SWAN error when running ROMS + SWAN and SWAN only via COAWST 3.7. When I am using GNU compilers swan keeps running with no error or output or time stepping, but when I use intel compilers I get a segmentation fault error. I suspect it is an error related to not having enough allocated memory. When I have done separate runs in swan 41.45 i have found that when I use mpi the memory used for my the job scales linearly with number of processors (ex, 1 processor requires 8GB and 2 requires 16GB ...). When I run swan using OpenMP memory routines I have found that the memory requirement of the job is independent of number of processors (ex. 8GB for 1 and 8GB for 2...). I think that the error with max number of processors for swan might be related to the max amount of RAM you have available for the job
> 
> Thank you. I use HPC, so I am not sure if I have limitations. ROMS never had this problem because I use as many as 120 processors for it. But only have this problem with SWAN. I am guessing the suggestion that a wet cell being in every tile might be part of the problem. I wish I find a way around it to speed up my work.

From my experience I have not had an issue with running out of memory for ROMS, but I have spent a good bit of time tracking down this error of swan running without timestepping or erroring, or when i use intel compilers segmentation faulting. I was using swan only via coawst 3.7 with mpi and 64 cpus and 400 GB of memory. When I dropped the number of processors or increased the allocated memory the issue went away for me. It might not be related to the error you are experiencing, i just wanted to share my experiences in case they might be helpful.

**Comment by jcwarner-usgs** [comment]
that looks like the issue.  when you use 15 cells, the bottom tile will go from 22 to 22.4. 
there are 2 ways to get around this.
1) - redo the grid and not have 34 rows of land along the bottom.
2) make an artificial lake from i= 200:220, j = 1: 32.  in that region set mask_rho = 1; this will create an isolated area that will never affect any part of your solution but then you can tile swan with maybe 30 cells or so.

**Comment by able93** [comment]
> that looks like the issue. when you use 15 cells, the bottom tile will go from 22 to 22.4. there are 2 ways to get around this.
> 
> 1. * redo the grid and not have 34 rows of land along the bottom.
> 2. make an artificial lake from i= 200:220, j = 1: 32.  in that region set mask_rho = 1; this will create an isolated area that will never affect any part of your solution but then you can tile swan with maybe 30 cells or so.

After following the second suggestion, it worked and now I can use as many processors as possible.

Meanwhile, I am yet to get them to install the time. I would update this thread if I faced any problem compiling WRF.

Thank you.

**Comment by able93** [comment]
[build.log](https://github.com/DOI-USGS/COAWST/files/14484007/build.log)
> i see make[4]: time: Command not found make[4]: [module_internal_header_util.o] Error 127 (ignored)
> 
> the command 'time' is not found on your system. that is used to track the amount of time in each subroutine. can you have a system admin install that utility? https://linuxpip.org/fix-time-command-not-found-error/

Thanks for the other time.

Now, the command utility is working, but it still sometimes says command time not found when compiling Sandy. I tried to call time before starting the compilation to ensure it is working. Please check the log file. Also, this error is still there:

use module_ext_internal
1
Fatal Error: Can't open module file ‘module_ext_internal.mod’ for reading at (1): No such file or directory
compilation terminated

Thanks

**Comment by able93** [comment]
Hi Professor John,

So I have the SWAN working well after putting an artificial lake.

Meanwhile, the WRF isn't compiling yet. I have attached the build file. I
now have the time working, it sees it at some point during the build, and
would not see it at another time. Also, this error remains:

use module_ext_internal
1
Fatal Error: Can't open module file ‘module_ext_internal.mod’ for reading
at (1): No such file or directory
compilation terminated

Can you have a look at the build?

Thanks

**Comment by jcwarner-usgs** [comment]
can u reattach the build file?
dont think it came through.

**Comment by able93** [comment]
[build.log](https://github.com/DOI-USGS/COAWST/files/14528590/build.log)
I have reattached it. Thank you

**Comment by jcwarner-usgs** [comment]
i still see

make[3]: time: Command not found
make[3]: [module_comm_dm_2.o] Error 127 (ignored)
rm -f module_comm_dm_3.o

that is enough to make wrf not able to complete teh build.
as you see, wrf continues on and tries to keep building, it does not stop like roms or swan would.
so you need to search through the log file. i search for the word 'error'.

**Comment by able93** [comment]
Hello,

Now, I have passed the time error, the problem now is linking to the netcdf
library as you can see from the error message.

track_driver.f90:(.text+0x1cdd): undefined reference to `nf_create_'

I have checked the linux-gfortran file in the compiler, and I have
-lnetcdff and -lnetcdf part of the LIBS. I also have use NETCDF=on.

You can check the log file as well for the error.

Thanks

**Comment by able93** [comment]
[build (1).log](https://github.com/DOI-USGS/COAWST/files/14549068/build.1.log)

**Comment by jcwarner-usgs** [comment]
ok.  i think you are missing a libnetcff  (2 f's).
i have something like:

mpif90 -f90=ifort  -o wrf.exe  -O3 -xAVX -w  -auto -ftz -fno-alias -fp-model fast=1 -no-prec-div -no-prec-sqrt -\
FR -convert big_endian -auto -align array64byte   -xAVX  wrf.o ../main/module_wrf_top.o libwrflib.a 
/vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/fftpack/fftpack5/libfftpack.a /vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/io_grib1/libio_grib1.a /vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/io_grib_share/libio_grib_share.a /vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/io_int/libwrfio_int.a 
-L/vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/esmf_time_f90 -lesmf_time 
/vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/RSL_LITE/librsl_lite.a /vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/frame/module_internal_header_util.o /vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/frame/pack_utils.o -L/vortexfs1/scratch/jwarner/COAWST_v3.8/test11/WRF/external/io_netcdf -lwrfio_nf 
-L/vortexfs1/apps/impistack-1.0/lib -lnetcdff -lnetcdf
 -L/vortexfs1/usgs/jwarner/models/MCT_stack/lib -lmct -lmpeu
   -L/vortexfs1/usgs/jwarner/mambaforge/lib -lnetcdf     

and you have

mpif90  -o wrf.exe  -O2 -ftree-vectorize -funroll-loops -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4     wrf.o ../main/module_wrf_top.o libwrflib.a  /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/fftpack/fftpack5/libfftpack.a /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/io_grib1/libio_grib1.a /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/io_grib_share/libio_grib_share.a /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/io_int/libwrfio_int.a -L/mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/esmf_time_f90 -lesmf_time /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/RSL_LITE/librsl_lite.a /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/frame/module_internal_header_util.o /mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/frame/pack_utils.o -L/mnt/beegfs/home/aadebiyi2022/roms/COAWST/WRF/external/io_netcdf -lwrfio_nf -L/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib  -lnetcdf                -L/mnt/beegfs/home/aadebiyi2022/roms/MCT/usr/local/lib -lmct -lmpeu      -L/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib -lnetcdf      


you are missing the lnetcdff.
can you check if that exists in your
/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib

**Comment by able93** [comment]
After checking through, I need both -lnetcdf, and -lnetcdff for the
compilation, I have both but in different folders.

The lnetcdf is here /opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib while
the lnetcdff is in
/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf-fortran/4.5.2/lib.

So once I set the environment to the first one, it doesn't see the
lnetcdff, and vice versa.

**Comment by able93** [comment]
Can I point to the 2 libraries in different folders?

**Comment by jcwarner-usgs** [comment]
for WRF, you need to set an env var called NETCDF.   looks like you have it set to be:
"Will use NETCDF in dir: /opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1"
then, WRF will look in that dir and subfolders lib and inc.
So i think the libnetcdf and libnetcdff have to be in the same folders.
You can ask on the WRF forum, as this is all wrf stuff and not really anything to do with me.
but i feel like they have to be in the same folder.
