### ISSUE TITLE
error run Sandy 

### ISSUE THREAD

**Issue by wjlyx** [jcwarner-usgs/COAWST#229]
When I run the Sandy example of COAWST, the compilation process completes, but I encountered the following error during execution. I'm not running it on a cluster; instead, I'm using my own computer with a WSL virtual machine running a Linux environment. How can I resolve this?

Abort(537478405) on node 2 (rank 2 in comm 0): Fatal error in PMPI_Comm_rank: Invalid communicator, error stack:
PMPI_Comm_rank(107): MPI_Comm_rank(comm=0x0, rank=0x7ffe3af1d638) failed
PMPI_Comm_rank(64).: Invalid communicator

**Comment by wjlyx** [comment]
[coawst.bash.txt](https://github.com/DOI-USGS/COAWST/files/14493951/coawst.bash.txt)

**Comment by jcwarner-usgs** [comment]
please post the full output of the run.  the mpi comm fail is just saying that mpi failed.

**Comment by wjlyx** [comment]
[build.log](https://github.com/DOI-USGS/COAWST/files/14496776/build.log)

**Comment by wjlyx** [comment]
Thank you for your reply. Here is the build.log file.
[build.log](https://github.com/DOI-USGS/COAWST/files/14496798/build.log)


> please post the full output of the run. the mpi comm fail is just saying that mpi failed.

**Comment by wjlyx** [comment]
> please post the full output of the run. the mpi comm fail is just saying that mpi fail
[run.log](https://github.com/DOI-USGS/COAWST/files/14496844/run.log)
ed.

Thank you for your reply. Here is the build.log and run.log.
[build.log](https://github.com/DOI-USGS/COAWST/files/14496843/build.log)

**Comment by wjlyx** [comment]
> please post the full output of the run. the mpi comm fail is just saying that mpi failed.

Thank you for your reply. Here is the build.log and run.log.

[build.log](https://github.com/DOI-USGS/COAWST/files/14496852/build.log)
[run.log](https://github.com/DOI-USGS/COAWST/files/14496866/run.log)

**Comment by jcwarner-usgs** [comment]
ok thanks.  unfortunately that did not offer a lot more information.
did you get any Err* files from swan?
is there any more info?
I am not sure.  maybe try a different test case, or Sandy with just roms, then roms+swan, then all 3 .

**Comment by wjlyx** [comment]
> ok thanks. unfortunately that did not offer a lot more information. did you get any Err* files from swan? is there any more info? I am not sure. maybe try a different test case, or Sandy with just roms, then roms+swan, then all 3 .

Thank you for your advice. I'll try some other test cases.
