### ISSUE TITLE
Issue with WEC_VF in ROMS-SWAN coupled model

### ISSUE THREAD

**Issue by ocean0510** [jcwarner-usgs/COAWST#234]
Hello,

 We are currently using the ROMS-SWAN coupled model. The COAWST version we're using is 3.8, and there are no issues when running ROMS or SWAN individually. However, when attempting the coupling, especially with #define WEC_VF, we are encountering the following message.

For your information, we had no problem running Rip Current example case with cpp WEC_VF on.

Can anyone lead us in fixing this issue?

Thank you!

-Joonho

![coawst_error_02](https://github.com/DOI-USGS/COAWST/assets/24581234/5c7d316a-8c48-46d7-b27d-53b85ece335c)

**Comment by jcwarner-usgs** [comment]
can you send to me your *.h file

**Comment by ocean0510** [comment]
Hello Warner, 

I am attaching all the file related with the case.

Thank you.
[WEC error (COAWSTv3.8).zip](https://github.com/DOI-USGS/COAWST/files/14680633/WEC.error.COAWSTv3.8.zip)

**Comment by jcwarner-usgs** [comment]
ok i fixed this.  It had to deal with a string length to declare what variables are being transferred. We updated the code to include a new stokes computation, and that needs lots of vars to be exchanged. I updated waves_coupler.ftn and mct_roms_swan.h.
can you do a git pull and try again?

**Comment by ocean0510** [comment]
Absolutely. I will download it, try to compile them and run. Thank you, John.

**Comment by ocean0510** [comment]
Thank you John. 

Now the model works very well.

We had an issue when we turn on WEC_VF(model ran without problem without WEC_VF).
Modified code from you, worked very well and now I can see the difference clearly. Thank you again for your work.

All the best,
-Joonho

WEC_VF off
![WECVF_off](https://github.com/DOI-USGS/COAWST/assets/24581234/892f07ec-2063-4fa9-86d4-0502db726845)

WEC_VF on
![WECVF_on](https://github.com/DOI-USGS/COAWST/assets/24581234/5d969f77-5759-4a9b-bebe-f075056af4cf)

**Comment by jcwarner-usgs** [comment]
nice !
