### ISSUE TITLE
Running the scrip_coawst.exe in COAWST gives an error (after #236)

### ISSUE THREAD

**Issue by linva7** [jcwarner-usgs/COAWST#237]
Hi John,
I am sorry to bother you again, there is still a error about my scrip_coawst.
Today I tried one more thing: converting the wrfinputd02 file to roms_grid.nc by wrf2roms_mw, and importing roms_grid.nc into GridBuilder to add mask and depth, with the depth coming from https://download.gebco.net/. Finally use the roms2swan.m to get the input grid file of SWAN, where the size of the SWAN grids is (120, 130).
Then I ran . /scrip_coawst.exe and got the same error as before, so I reduced the SWAN_NUMX(1) and SWAN_NUMY(1) in scrip.in to (110, 120), the ./scrip_coawst ran successfully, which is odd, but eventually Hwave is found to be a value of 0 for most of the region in the wrfout_d02 generated by .coawstM.

It should be emphasized that I'm trying to set up 3 nests of WRF, the innermost layer being moving nesting, and I have the domain image uploaded, is the root of all this a problem that I'm having trouble setting up the regions for both models? Does this setup make sense? I'm setting it up this way because I want to keep an eye on the d02 weather field and wave field while simulating a typhoon.
![domain](https://github.com/DOI-USGS/COAWST/assets/151035959/2e7d453f-f208-4725-9de7-e109f628b217)

**Comment by jcwarner-usgs** [comment]
sorry, i though this was working.
if you load the roms grid into matlab, what is 
size(h)
if your swan grid is the same as the roms grid, then you should enter those numbers into the scrip file.
for example,
if size(h) is  84 108, then use those numbers in the scrip file.
SWAN_NUMX(1)=84,
SWAN_NUMY(1)=108,
Then in the ocean.in, it would be 82 106.   
Then in the swan.in it would be 83 107.
Then in the wrfnamelist, it would be 84 108.
confusing enough?
Every model is different!

**Comment by linva7** [comment]
Hi John,
I understand what you mean, thanks for still answering for me. Despite the different setups and differences in each model, the development of these techniques is still respectable :) 
The problem has been solved, thank you very much!
