### ISSUE TITLE
svn: E155007: '/COAWST-master' is not a working copy

### ISSUE THREAD

**Issue by MobJerry** [jcwarner-usgs/COAWST#238]
I'm sorry I reported this error in ROMS forum first and not here. Thanks for warner's reminder, now I will repeat my question as follows, hoping to get your interesting suggestions:

I have a working directory COAWST_master/ in my remote machine with a coawst.bash file, and I need to compile in that working directory to generate the corresponding coawst.M. However, I mistakenly copied the coawst.bash to COAWST_master/Projects/upwelling for compilation, and there is no doubt that it is reporting an error.

Strangely enough, when I run./coawst.bash in the correct working directory, It also reports an error:

> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> rm -f -r core *.ipo ./Build /home/cy22/make_macros.mk
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> cp -f /mnt/sdc/littlemarcoleung/COAWST/LIBRARIES/netcdf/include/netcdf.mod ./Build
> cp -f /mnt/sdc/littlemarcoleung/COAWST/LIBRARIES/netcdf/include/typesizes.mod ./Build
> cp -p /home/cy22/make_macros.mk ./Build
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> \
> cd ./Build; \
> cpp -P -DFujian -D'HEADER="fujian.h"' -D'ROMS_HEADER="/mnt/sdd/cy22/COAWST-master/Projects/Fujian//fujian.h"' -I/mnt/sdd/cy22/COAWST-master//ROMS/Include /mnt/sdd/cy22/COAWST-master//Master/MCT_coupler/mod_coupler_kinds.F > mod_coupler_kinds.f90; \
> /mnt/sdd/cy22/COAWST-master//ROMS/Bin/cpp_clean mod_coupler_kinds.f90;
> \
> /mnt/sdc/littlemarcoleung/COAWST/LIBRARIES/mpich/bin/mpif90 -c -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include mod_coupler_kinds.f90; \
> cpp -P -DFujian -D'HEADER="fujian.h"' -D'ROMS_HEADER="/mnt/sdd/cy22/COAWST-master/Projects/Fujian//fujian.h"' -I/mnt/sdd/cy22/COAWST-master//ROMS/Include /mnt/sdd/cy22/COAWST-master//Master/MCT_coupler/mct_coupler_params.F > mct_coupler_params.f90; \
> /mnt/sdd/cy22/COAWST-master//ROMS/Bin/cpp_clean mct_coupler_params.f90;
> \
> /mnt/sdc/littlemarcoleung/COAWST/LIBRARIES/mpich/bin/mpif90 -c -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include mct_coupler_params.f90;
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: Nothing to be done for 'wrfclean'.
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: Nothing to be done for 'wrf'.
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: Nothing to be done for 'wrfhydroclean'.
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: Nothing to be done for 'wrfhydro'.
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: Nothing to be done for 'ww3clean'.
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: Nothing to be done for 'ww3'.
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy
> make: 'Build' is up to date.

according to Warner suggestion,coawst.bash is built ok. However, coawstM did not appear in my work directory, which confused me. In the past, after compiling coawst.bash, it would directly generate the executable file, but now it shows such an error, what happened? I appreciate everyone's suggestions for changes!

**Comment by jcwarner-usgs** [comment]
these statements
" svn: E155007: '/mnt/sdd/cy22/COAWST-master' is not a working copy"  
are not errors.  they are just saying that this is not an svn repo.  that is ok.  it is not an svn repo.

the make can not find anything new to build.

what did you type at the command prompt?
can u post a copy of your build_coawst.sh?
-j

**Comment by MobJerry** [comment]
i just post ./coawst.bash at the command prompt as i usually did before.What confused me was I had seen in COAWST_manual and some forums that build_coawst.sh was used to compile the executable, but until I ran into this error, I was running directly./coawst.bash to get my cowastM. Here is my bash file:
[coawst.txt](https://github.com/DOI-USGS/COAWST/files/14810391/coawst.txt)

**Comment by MobJerry** [comment]
ok Warner, I finally understand why I made this mistake. it turns out that I made an ironic oversight when defining the CPP option in the.h file: I forgot to #define ROMS_MODEL. This doesn't seem to be a problem now -- as long as ROMS_MODEL is defined in the.h file, the./coawst.bash file can be successfully generated. I'm sorry to have taken up some of your time.

**Comment by jcwarner-usgs** [comment]
all good. glad it works.
