### ISSUE TITLE
version 3.8 compile error

### ISSUE THREAD

**Issue by aiwuyouxi** [jcwarner-usgs/COAWST#257]
Hello,

I'm attempting a fresh installation of COAWST version 3.8, but have run into some issues. Here's the error I encountered during compilation:

```
gfortran: error: unrecognized command-line option ‘-assume’
make: *** [ROMS/Modules/Module.mk:15: Build_roms/mod_kinds.o] Error 1
```
![1111](https://github.com/DOI-USGS/COAWST/assets/129833996/0db58f24-bb62-4001-a5be-2be8397df8cd)

I've followed the discussion at 'https://github.com/DOI-USGS/COAWST/issues/174' and have already commented out the `-assume byterecl` option in the Linux-gfortran.mk file. Additionally, I have successfully installed cmake. However, after doing so, I've encountered another error.

![2222](https://github.com/DOI-USGS/COAWST/assets/129833996/53494697-728d-4f3a-8392-5da987d15cfc)

I'm wondering if there's something up with cmake that's causing my current hiccup. Could you tell me what the issue might be and what steps I should take to fix it? I'm hoping I can use your experience to help me work through this.

My current development environment details are as follows:
- gfortran version: v11.4.0
- cmake version: v3.22.1

I have the build_coawst.sh script and the associated log file available for review.
[build_log_1.log](https://github.com/DOI-USGS/COAWST/files/15331793/build_log_1.log)
[build_log_2.txt](https://github.com/DOI-USGS/COAWST/files/15331901/build_log_2.txt)
[build_coawst_sh.txt](https://github.com/DOI-USGS/COAWST/files/15331902/build_coawst_sh.txt)

Thank you in advance for your assistance.

**Comment by jcwarner-usgs** [comment]
I have seen Cmake stop like this before. There could be several reasons, but here are some issues that others have seen.

1- The folder name "COAWST-COAWST_v3.8"  can be bad.  The "-" in the name can sometimes give CMake a problem.
change the folder name to not have a "-" in it.

2- The MCT libs have to be compiled and the paths set.  What do you get when you type
$MCT_INCDIR
$MCT_LIBDIR
