### ISSUE TITLE
Bug Report: -j over 4 causes failures

### ISSUE THREAD

**Issue by HathewayWill** [jcwarner-usgs/COAWST#262]
Good morning,

I have found that if you build COAWST with the Sandy Case with the -j command set greater than 4 it causes swan or roms to fail to build.  

I think this is due to the version numbers of swan/roms/wrf etc.

Is there plans to update alll the packages to the latest versions?

**Comment by jcwarner-usgs** [comment]
i havent built the sandy case in a while, but i routinely use -j 14 or so for other builds.
I dont think it has an error due to the version numbers of the models.
what is the actual error you get?  how many cores do you have available to build on?

**Comment by HathewayWill** [comment]
@jcwarner-usgs 

strange it works now.  Must of been something with my system.  I rebooted and it works.

Just for clarification Sandy, has all the modules interacting with each other?  Wave/Air/Ocean?

[build_coawst.log](https://github.com/DOI-USGS/COAWST/files/15436845/build_coawst.log)

**Comment by jcwarner-usgs** [comment]
glad it works now.
Sandy can be set up in different formats. the distribution has roms+wrf+swan.  looks like that built for you.
There is a lot of info in the coawst user manual, how to change settings etc.

**Comment by HathewayWill** [comment]
Great i'm going to close this issue
