### ISSUE TITLE
What files are required to update SWAN/ROMS/WRF/etc to current version?

### ISSUE THREAD

**Issue by HathewayWill** [jcwarner-usgs/COAWST#264]
Quick question,

Trying to update all the components of the models to their current versions to test compatibility.  Also was wondering which versions of each model is currently being used in 3.8?  The manual for COAWST is v3.7 so I would like to know the difference.

**Comment by jcwarner-usgs** [comment]
It is not a simple task to just 'update' all the components.  We have modified different parts of the models to make  them compatible in the build process and the run phases.
If you go here:
https://github.com/DOI-USGS/COAWST
and get the code, the Manual is for v3.8
