### ISSUE TITLE
The Wolf-Swan-Romus coupling mode restarts with an error

### ISSUE THREAD

**Issue by DYB2363021436** [jcwarner-usgs/COAWST#265]
Hello, in the process of using the WRF-ROMS-SWAN coupling mode, due to the server restart, I restarted the study, and after modifying the restart command in the input file of the three modes, I started to restart the study, but the example reported an error in the following figure, where Figure 1 is the window output error, and Figure 2 is the output log. Have you ever encountered such a problem?
![Snipaste_2024-05-27_22-27-07](https://github.com/DOI-USGS/COAWST/assets/37389561/f3f88c59-a185-4312-9415-b2ba38b29dea)

![Snipaste_2024-05-27_22-25-13](https://github.com/DOI-USGS/COAWST/assets/37389561/9d0069e0-f6b9-4ff3-8842-5f28a84a99b0)

**Comment by jcwarner-usgs** [comment]
i am not sure.  it could be a lot of things.
Look in the Build_roms/def_rst.f90 file, at line 695 and see what it is trying to read in.

**Comment by DYB2363021436** [comment]
Hello, I would like to ask, in addition to modifying the contents of the diagram when restarting in ROMS mode, do I need to modify other content, I encountered the same problem when restarting when using the Sandy study
![2](https://github.com/DOI-USGS/COAWST/assets/37389561/d67fdcef-31db-429e-ae3d-a60dead67725)
![3](https://github.com/DOI-USGS/COAWST/assets/37389561/7d438c15-7891-49ee-a9af-5af88aa1f44f)

**Comment by DYB2363021436** [comment]
I have resolved the issue and need to modify it during the reboot. The next output reboot file name. Thank you for your continuous efforts

**Comment by jcwarner-usgs** [comment]
ok good. if this is resolved, can you close the ticket?
