### ISSUE TITLE
issue couple ROMS with WW3 -sandy test case

### ISSUE THREAD

**Issue by simion1232006** [jcwarner-usgs/COAWST#281]
Hi there,
I got some issue running the sandy test case.
I built the exe which is fine but when I run the simulation it shows errors below:

![image](https://github.com/user-attachments/assets/7e095e0d-587b-4764-9741-da97e531ef31)

could you please share your experiences?

Kind regards

**Comment by simion1232006** [comment]
Hi there,
I managed to track down the issue which likely assciated a compiling issue. I still got a exe but there are error messages showing  below. 
![image](https://github.com/user-attachments/assets/f21a1628-9226-4df2-aeec-1832480009b6)
![image](https://github.com/user-attachments/assets/0b103e7b-b044-44bc-ae95-6a5ad3a33651)

**Comment by simion1232006** [comment]
I encountered another issue when compiling ROMS with SWAN. Although I have installed MPI correctly (since I can run ROMS alone without any issues), the model cannot include mpif.h.
I've verified that MPI is correctly installed. Any help with resolving this would be greatly appreciated.
![image](https://github.com/user-attachments/assets/dbe0805a-6aa8-4305-b1bb-2e90d7b7cbff)

**Comment by simion1232006** [comment]
I am using netcdf installed in: /usr/local/netcdf/4.9.2/
MCT installed in: /usr/local/mct
MPICH installed via ubuntu apt-get in: /usr

**Comment by jcwarner-usgs** [comment]
ok. lets start with one thing at a time.
For the ROMS+WW3 coupling, looks like it is having trouble to read your ww3_grid.inp or the ww3_shel.inp files.  Are they in the run directory (where coawstM is located)?

The 'errors' you show are not errors, they are warnings.  that is not an issue.

For SWAN- can't find mpi.  others have had this issue. see
https://github.com/DOI-USGS/COAWST/issues/216
i need to see the full swan build to be more help.

**Comment by simion1232006** [comment]
Thanks a lot for your quick response, John. 
For ROMS coupling with SWAN. I can install SWAN standalone (not within COAWST model) using cmake following this instruction:
https://swanmodel.sourceforge.io/online_doc/swanimp/node17.html
while when I try it in COAWST, I still got the same issue.
I have notice that when I was trying to COAWST (couling with swan), the compiling process modified both the src and src_coawst folder. In the swmod.f file, the compiling process added couple of lines not found in orginal file (from orignal swan code). The highlighted block is commented out in orginal swan code, but everytime I tried coawst, it will add them in.
![image](https://github.com/user-attachments/assets/219e5660-0ce7-41a2-8610-baaa0414dfb3)
![image](https://github.com/user-attachments/assets/e9e5657c-045b-4211-99ff-0d1a17b73b72)

**Comment by simion1232006** [comment]
Regarding the coupling with WW3, it seems the issue was related to the input files not being found. I changed the project folder path, and this resolved the problem. I really appreciate your help with that.
However, I encountered a new error while running the model. Upon investigating, I noticed that I did not generate the ../../../WW3/model/exe/ww3_grid.exe during the compilation process. Consequently, the following files were not created: mask.ww3, mapsta.ww3, and mod_def.ww3.

![image](https://github.com/user-attachments/assets/3e5efe23-8b68-4e34-9f6a-26d838969bf8)

**Comment by simion1232006** [comment]
Hi John,
I managed to go through the previous error. I am now having all inputs in place:
The model start to run successfully. However, It stops at a point where ROMS is suppose to provide input for WW3 to read.

[model.log](https://github.com/user-attachments/files/16278324/model.log)

I don't why the program requires xl which is not a standard input parameter for ROMS.
![image](https://github.com/user-attachments/assets/54283977-9567-4aea-8ee8-a0d6184ab0c5)

**Comment by jcwarner-usgs** [comment]
is this using the Sandy grid we distribute?
in ROMS/Utility/get_grid.F it looks for
     IF (.not.find_string(var_name,n_var,'xl',vindex)) THEN
        IF (Master) WRITE (stdout,20) 'xl', TRIM(ncname)
        exit_flag=2
        RETURN
      END IF
      IF (.not.find_string(var_name,n_var,'el',vindex)) THEN
        IF (Master) WRITE (stdout,20) 'el', TRIM(ncname)
        exit_flag=2
        RETURN
      END IF
      IF (.not.find_string(var_name,n_var,'spherical',vindex)) THEN
        IF (Master) WRITE (stdout,20) 'spherical', TRIM(ncname)
        exit_flag=2
        RETURN
      END IF
.....

**Comment by simion1232006** [comment]
yes, it is the sandy case. I am trying to run the test case first to make sure the model is running OK. all input files are in the folder.

**Comment by simion1232006** [comment]
I tried inlet case which shows similar errors

![image](https://github.com/user-attachments/assets/a78b6630-4074-4c82-8f9f-8662970e3648)

**Comment by simion1232006** [comment]
> is this using the Sandy grid we distribute? in ROMS/Utility/get_grid.F it looks for IF (.not.find_string(var_name,n_var,'xl',vindex)) THEN IF (Master) WRITE (stdout,20) 'xl', TRIM(ncname) exit_flag=2 RETURN END IF IF (.not.find_string(var_name,n_var,'el',vindex)) THEN IF (Master) WRITE (stdout,20) 'el', TRIM(ncname) exit_flag=2 RETURN END IF IF (.not.find_string(var_name,n_var,'spherical',vindex)) THEN IF (Master) WRITE (stdout,20) 'spherical', TRIM(ncname) exit_flag=2 RETURN END IF .....

I am a little confused. Is this variable required for input? The distributed grid file does not have this variable.

**Comment by jcwarner-usgs** [comment]
can i see the full output?

**Comment by simion1232006** [comment]
> can i see the full output?

[log.txt](https://github.com/user-attachments/files/16285175/log.txt)

**Comment by jcwarner-usgs** [comment]
when you run the coawstM, what dir are you in?
where are the grid files?
I do notice that for Projects/Inlet_test/WW3/ocean_inlet_test.in it does point to
      GRDNAME == Projects/Inlet_test/Coupled/inlet_test_grid.nc 
and it should be
     GRDNAME == Projects/Inlet_test/WW3inlet_test_grid.nc 
but they should be the same file.

**Comment by simion1232006** [comment]
I am running in Projects/Inlet_test/WW3/ folder. I have modified the following files to make the build and input files more portable (project folder seperate from the source code), as i will need to run sythetic cyclones. 

[build_coawst_inlet.zip](https://github.com/user-attachments/files/16286018/build_coawst_inlet.zip)

**Comment by simion1232006** [comment]
[Uploading coupling_inlet_test.zip…]()

**Comment by jcwarner-usgs** [comment]
this is a strange one.
can you do an 
ls -ltr
and make sure the file size looks correct?
try to change the name to like inlet_test_grid2.nc
and see if it can not find that.

**Comment by simion1232006** [comment]
> ls -ltr

Hi John,
if I rename the grid, I got this:
![image](https://github.com/user-attachments/assets/cb7a3056-80e8-4be5-a29a-af9e9eb0c6a5)

this is the ls results of the folder:

![image](https://github.com/user-attachments/assets/9bfa4827-4b80-4e5e-a834-4add74fcb0ba)

**Comment by simion1232006** [comment]
just a update that I finally get it work. really appreciate your help John.
thing to note to couple ww3 and roms:

1. compiling MCT with export FCFLAGS="-w -fallow-argument-mismatch -O2"
2. make sure to include netcdf, mct and mpi in LD_LIBRARY_PATH
3. for sandy ww3, need to turn the wind from C to T if not coupling with wrf
4. need to run three preprocessing scripts for ww3. 
5. build the exe in the project folder with all ww3 inputs. somehow the exe only reads ww3 inputs from the same directory.

Tao

**Comment by jcwarner-usgs** [comment]
Glad you got it all to work!
-j

**Comment by simion1232006** [comment]
> Glad you got it all to work! -j

Yes, I used your script to convert the ROMS child grid to ww3. The coarse grid was the same, but I added extra layers so now they are slightly different. For child grid, I did not have the boundary nodes and everything is masked as within computing domian except the land.
