### ISSUE TITLE
MCT: Grid Size mismatch in WRF+ROMS+SWAN ( ROMS & SWAN have same grid)

### ISSUE THREAD

**Issue by liucongju** [jcwarner-usgs/COAWST#283]
Dear,

I have a problem with COAWST version 3.4 of my server. I can compile and run COAWST with WRF,ROMS,SWAN. But when I go to compile WRF+ROMS+SWAN I get an error that I haven't been able to resolve.

The grid for SWAN and ROMS(same grid) is 10206 (126×81), and the grid for WRF is 5841 (99×59). I have referred to the parameters and scripts set for Sandy and Joe_tc, so why does it still require the grid numbers to be the same? 
Thank u

 

```
> MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch LocalMap Gsize =         5841  RemoteMap Gsize =        10206
> MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3
> 001.MCT(MPEU)::die.: from MCT::m_ExchangeMaps::ExGSMapGSMap_()
>  MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch LocalMap Gsize =        10206  RemoteMap Gsize =         5841
> MCT::m_ExchangeMaps::ExGSMapGSMap_: Map Grid Size mismatch error, stat =3
> 000.MCT(MPEU)::die.: from MCT::m_ExchangeMaps::ExGSMapGSMap_()
> --------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
> with errorcode 2.
> 
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.
```

![捕获](https://github.com/user-attachments/assets/e9a7e43c-21f1-45a3-b031-b5cc9c16fcce)

**Comment by jcwarner-usgs** [comment]
did you activate 

[#define NESTING  ???]

#define WRF_MODEL
#define SWAN_MODEL
#undef  WW3_MODEL
#define MCT_LIB
#define MCT_INTERP_OC2AT
#define MCT_INTERP_WV2AT
#define MCT_INTERP_OC2WV

**Comment by liucongju** [comment]
> did you activate
> 
> [#define NESTING ???]
> 
> #define WRF_MODEL #define SWAN_MODEL #undef WW3_MODEL #define MCT_LIB #define MCT_INTERP_OC2AT #define MCT_INTERP_WV2AT #define MCT_INTERP_OC2WV

Thank you very much!!!  I have made modifications based on your reference and the program has run smoothly. 😊
