### ISSUE TITLE
A gfortran error when compiled the upwelling case

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#286]
hi all！
I am a beginner in COAWST, and the mode has just been installed (not sure if the installation was right or not)
when I compiled the upwelling case, a gfortran error coming
“
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [/home/wangling/coawst/Projects/upwelling/Build_roms/mod_kinds.o] Error 1
make: *** Waiting for unfinished jobs....
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [/home/wangling/coawst/Projects/upwelling/Build_roms/radiation_stress.o] Error 1
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [/home/wangling/coawst/Projects/upwelling/Build_roms/mod_strings.o] Error 1
gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?
make: *** [/home/wangling/coawst/Projects/upwelling/Build_roms/mod_stepping.o] Error 1
”

how can I solve this problem

**Comment by jcwarner-usgs** [comment]
i really think the correct compiler flag is 'fallow-argument-mismatch'
I am not sure if the -Wno-argument-mismatch would work.
-Can i see the full build.
-you can modify the flags in Compilers/Linux-gfortran  and try it with the -Wno... argument instead.
-are you sure you are using gfortran and not some other compiler.

**Comment by LiuJiao0408** [comment]
yes， I am sure gfortran be used。
I have tried to modify the flags to the "-Wno... ", but I cannot found where it  is.

what I done are
--cp /..../ROMS/Include/upwelling.h   ./.../projects/upwelling
 --cp /..../ROMS/External/roms_upwelling.in   ./projects/upwelling
--cp /..../coawst/COAWST/build_coawst.sh   ./projects/upwelling

and the follow are the build_coawst and the print of build

[build print.txt](https://github.com/user-attachments/files/16342944/build.print.txt)
[build_coawst.txt](https://github.com/user-attachments/files/16342949/build_coawst.txt)

**Comment by jcwarner-usgs** [comment]
the flags are set in
Compilers/Linux-gfortran.mk

**Comment by LiuJiao0408** [comment]
thank u so much. It works.
I run the upwelling case successfully!!!
Nice work!!!
