### ISSUE TITLE
A gfortran error When I tried to run Inlet_test/Pulsed

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#287]
Hi ALL，
When I was running Inlet_test/Coupled, I encountered a gfortran error while run "./build_comawst.sh".
And the print show something about the SWAN. Did the SWAN finish the compiling, or I have no cmake.
The follows are the print and the build_coawst

![图片1](https://github.com/user-attachments/assets/014c9e0b-6f4b-426b-92fd-26b15443bb73)
[build_INLET_TEST.txt](https://github.com/user-attachments/files/16388442/build_INLET_TEST.txt)
[build_coawst.txt](https://github.com/user-attachments/files/16388459/build_coawst.txt)

**Comment by jcwarner-usgs** [comment]
a couple of things here
1) for some reason your compiler does not like the assume-byterecl flag.
so you need to edit Compilers/Linux-gfortran.mk and change the line that has it on. In my current distribution i have it commented out already
ifdef USE_SWAN
#          FFLAGS += -assume byterecl
#          FFLAGS += -frecord-marker=4 -fconvert=big-endian

so you may be using an older version.

2) you need cmake for SWAN.
mkdir: cannot create directory ‘build’: File exists
/bin/sh: line 24: cmake: command not found
not sure why the dir already exists.
but your system can not find cmake.  you need cmake.

**Comment by LiuJiao0408** [comment]
Oh！ Thanks very much！
By modifying this statement, the first issue has been resolved! And the second issue was also resolved after I installed the cmake!

But now when I run the command: # mpirun np 4 ./ coawstM ocean_inlet_test.in (run the case Inlet_test/Coupled)
The following error occurred:
                    Coupled Input File name = ocean_inlet_test.in
                    READ MODEL INPUTS - Unable to open roms input file.
                    READ MODEL INPUTS - Unable to open roms input file.
                    READ MODEL INPUTS - Unable to open roms input file.
                    READ MODEL INPUTS - Unable to open roms input file.
                    MyRank =            0 
                    mct_coupler - Number assigned processors: 00000
                    not equal to spawned MPI nodes: 00004
I have checked the directories Inlet_test/Coupled  and the Data/ROMS, but there are no data files related to ocean_inlet_test.in below.
Do I need to create these input files myself?（The manual states that all files are in Inlet_test/Coupled）
