### ISSUE TITLE
ROMS tidal study plus forcing

### ISSUE THREAD

**Issue by hgengqi** [jcwarner-usgs/COAWST#288]
I'm getting a segmentital fault when running roms, the specific record is shown on log.txt.  can anyone help with this? Thank you so much
[log.txt](https://github.com/user-attachments/files/16398635/log.txt)

**Comment by jcwarner-usgs** [comment]
not sure.
set DEBUG=on
and recompile and run the coawstG

**Comment by hgengqi** [comment]
> not sure. set DEBUG=on and recompile and run the coawstG

i'm sorry but i'm not sure how to set DEBUG=on,and i don't use compile file,just run coawst.bash and then run the coawstM , thank you for your reply

**Comment by jcwarner-usgs** [comment]
edit the coawst.bash, and set
USE_DEBUG=on
recompile.
that will give you a coawstG
run the caowstG and see if that gives you more information.

**Comment by hgengqi** [comment]
> edit the coawst.bash, and set USE_DEBUG=on recompile. that will give you a coawstG run the caowstG and see if that gives you more information.

thank you for your reply，i had solve this issue. The reason is that the server nodes are running out of memory, and it is no problem to increase the number of nodes allocated.Thank you once again for your assistance.

**Comment by jcwarner-usgs** [comment]
glad it works.
