### ISSUE TITLE
ROMS: Influence of Grid Numbers on function editmask‘s coastline & land-sea mask

### ISSUE THREAD

**Issue by liucongju** [jcwarner-usgs/COAWST#291]
Dear,

I am currently using COAWST version 3.4 to reproduce the Sandy case. The code remains consistent with the code provided in the installation package and the examples in the User_Manual. I have encountered an issue related to the grid proportions in ROMS. 

It appears that the number of grid points in the x-direction (numx) and y-direction (numy) need to maintain a specific ratio. Otherwise, the coastline in editmask and the pre-defined land-sea mask exhibit a misalignment.

Below is a comparison between setting numx=86 according to the User_Manual and setting numx=186:

Could you please advise on the significance of this issue? Is there a recommended method to avoid this misalignment?

Thank you for your assistance.

                                        Sandy examples same as User_Manual numx=86

```
%Pick 4 corners for roms parent grid
xl=-82; xr=-65; % lon
yb= 28; yt= 43; % lat
%Pick number of points in the grid
numx=86; numy=64;
%Make a matrix of the lons and lats. 
dx=(xr-xl)/numx; dy=(yt-yb)/numy;
[lon, lat]=meshgrid(xl:dx:xr, yb:dy:yt);
lon=lon.';lat=lat.';
```
![image](https://github.com/user-attachments/assets/5c2f2b68-4573-4b1b-b474-d5623615f5d4)

                                         Sandy examples change numx=186

```
%Pick 4 corners for roms parent grid
xl=-82; xr=-65; % lon
yb= 28; yt= 43; % lat
%Pick number of points in the grid
numx=186; numy=64;
%Make a matrix of the lons and lats. 
dx=(xr-xl)/numx; dy=(yt-yb)/numy;
[lon, lat]=meshgrid(xl:dx:xr, yb:dy:yt);
lon=lon.';lat=lat.';
```

![image](https://github.com/user-attachments/assets/644df62d-6c86-4b61-9163-948b10025a09)

**Comment by jcwarner-usgs** [comment]
there is not a criteria for the ration of dx to dy.  what are the lons and lats on the edit mask screen for the 186 case?
there must be some other place that makes the grid be too long.
if you load the grids in matlab, and 
pcolor(lon_rho,lat_rho,mask_rho) they should be the same, just a different number of points.

- edit mask creates a mat file in the directory.  maybe delete that mat file with the ij indices?  and see if that helps?
- -j

**Comment by liucongju** [comment]
thank u very much!!! 
i add delete before editmask; 
```
delete('*ijcst*');
editmask(roms_grid,'h'); 
```
it works when i delete the mat file (*_grid_ijcst_h.mat) . it shows that if there is a .mat , the function won't calculate the coast.

**Comment by jcwarner-usgs** [comment]
glad it worked.
