### ISSUE TITLE
A problem about compiling COAWST v3.8

### ISSUE THREAD

**Issue by wjlyx** [jcwarner-usgs/COAWST#292]
Hello, I encountered the following error while compiling the Sandy case. How can I resolve it? 
![image](https://github.com/user-attachments/assets/df3f5cda-9b6b-42d2-81f0-fe34a68cfea6)

My ~/.bashrc content is as follows:
![image](https://github.com/user-attachments/assets/cce8f9cd-f8e9-45c4-9b3a-25f05e0a843c)
[build.txt](https://github.com/user-attachments/files/16520068/build.txt)

**Comment by jcwarner-usgs** [comment]
please post the full output of the build.
the error probably occurred near the beginning of the build, and WRF kept going.
Look at the output of the build starting at the top, and search for the word 'error'.  this can help you to find where it had trouble.

**Comment by wjlyx** [comment]
[build.txt](https://github.com/user-attachments/files/16521251/build.txt)
The './compile not found' appeared."

**Comment by wjlyx** [comment]
> please post the full output of the build. the error probably occurred near the beginning of the build, and WRF kept going. Look at the output of the build starting at the top, and search for the word 'error'. this can help you to find where it had trouble.

[build.txt](https://github.com/user-attachments/files/16521251/build.txt)
The './compile not found' appeared."

**Comment by wjlyx** [comment]
> please post the full output of the build. the error probably occurred near the beginning of the build, and WRF kept going. Look at the output of the build starting at the top, and search for the word 'error'. this can help you to find where it had trouble.

"It seems to be due to the absence of csh? I will install it and try again."

**Comment by jcwarner-usgs** [comment]
Compiling wrf
/bin/sh: 6: ./compile: not found

it can not find   ./compile  in the WRF dir.  I have

/proj/usgs/jwarner/models/COAWST/WRF
[jwarner@poseidon-l1 WRF]$ ls -ltr

-rwxrwxr-x 1 jwarner domain users  1027 Jun 30  2023 LICENSE.txt
-rwxrwxr-x 1 jwarner domain users 58004 Jun 30  2023 Makefile
-rwxrwxr-x 1 jwarner domain users 17697 Jun 30  2023 README
-rwxrwxr-x 1 jwarner domain users  1151 Jun 30  2023 README.md
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 Registry
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 arch
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 chem
-rwxrwxr-x 1 jwarner domain users  4023 Jun 30  2023 clean
-rwxrwxr-x 1 jwarner domain users 17528 Jun 30  2023 compile
-rwxrwxr-x 1 jwarner domain users 38010 Jun 30  2023 configure
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 doc
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 dyn_em
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 frame
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 hydro
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 inc
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 main
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 phys
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 run
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 share
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 test
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 tools
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 var
drwxrwxr-x 2 jwarner domain users  4096 Jun 30  2023 wrftladj
drwxrwxr-x 2 jwarner domain users  4096 Jul 14  2023 external

and see how compile is an executable.

**Comment by wjlyx** [comment]
> Compiling wrf /bin/sh: 6: ./compile: not found
> 
> it can not find ./compile in the WRF dir. I have
> 
> /proj/usgs/jwarner/models/COAWST/WRF [jwarner@poseidon-l1 WRF]$ ls -ltr
> 
> -rwxrwxr-x 1 jwarner domain users 1027 Jun 30 2023 LICENSE.txt -rwxrwxr-x 1 jwarner domain users 58004 Jun 30 2023 Makefile -rwxrwxr-x 1 jwarner domain users 17697 Jun 30 2023 README -rwxrwxr-x 1 jwarner domain users 1151 Jun 30 2023 README.md drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 Registry drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 arch drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 chem -rwxrwxr-x 1 jwarner domain users 4023 Jun 30 2023 clean -rwxrwxr-x 1 jwarner domain users 17528 Jun 30 2023 compile -rwxrwxr-x 1 jwarner domain users 38010 Jun 30 2023 configure drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 doc drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 dyn_em drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 frame drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 hydro drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 inc drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 main drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 phys drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 run drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 share drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 test drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 tools drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 var drwxrwxr-x 2 jwarner domain users 4096 Jun 30 2023 wrftladj drwxrwxr-x 2 jwarner domain users 4096 Jul 14 2023 external
> 
> and see how compile is an executable.

Thank you for yor suggestion. The problem was the absence of csh. After I installed csh, this issue has been solved and the coawstM file has been generated.

**Comment by jcwarner-usgs** [comment]
Nice !
-j
