### ISSUE TITLE
A question or error related to SCRIP_COAWST

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#297]
Hi all！
when I make the coupled grid file, I met then problem(I follewed the manual):

wangling@ln01 SCRIP_COAWST]$ ./scrip_coawst scrip_coawst_inlet_test_diffgrid.in 
[mpiexec@ln01] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
[mpiexec@ln01] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@ln01] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@ln01] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@ln01] main (ui/mpich/mpiexec.c:149): error parsing parameters

I have maked the SCRIP_COAWST(compiler is ifort(2019))，Anyone konws why！！！
Thank u your reply！！！

**Comment by jcwarner-usgs** [comment]
maybe try
mpirun -np 10 ./scrip_coawst scrip_coawst_inlet_test_diffgrid.in

**Comment by LiuJiao0408** [comment]
OH!!!!!!!!!!!!!!
I didn't need to add 10 on the virtual machine before, why do I need it on the server!!!
This is an interesting phenomenon, I am very curious!!

**Comment by jcwarner-usgs** [comment]
maybe not 10.  maybe just 1.
but i think you need to use mpirun.  not sure.
it looks like an error in the way you are running the  program,  not the program itself.

**Comment by LiuJiao0408** [comment]
Thank u very much！
I will try to find WHY！
I will kill this question for I have another one need ur help！！
Thanks again！！！
Nice for U！！
