### ISSUE TITLE
A error/problem abnout running the Inlet_test/DiffGrid

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#298]
When I run the case Inlet_test/DiffGrid, the screen print the followed words(I have run the Inlet_test/Coupled successfully):

the error is:
   GET_SPARSE - error while opening file: /data/home/wangling/Projects/Inlet_test/DiffGrid/scrip_inlet_test_diff
Any wrong with it, I cant find it!!!

scrren print as follows：
[wangling@ln01 DiffGrid]$ mpirun -n 2 ./coawstM coupling_inlet_test_diffgrid.in 
 Coupled Input File name = coupling_inlet_test_diffgrid.in
 Coupled Input File name = coupling_inlet_test_diffgrid.in

 Model Coupling: 

       Ocean Model MPI nodes: 00000 - 00000

       Waves Model MPI nodes: 00001 - 00001

       WAVgrid 01 dt=  60.0 -to- OCNgrid 01 dt=  60.0, CplInt:   600.0 Steps: 00010

       OCNgrid 01 dt=  60.0 -to- WAVgrid 01 dt=  60.0, CplInt:   600.0 Steps: 00010
--------------------------------------------------------------------------------
 Model Input Parameters:  ROMS/TOMS version 4.1  
                          Tuesday - August 13, 2024 - 11:53:31 PM
--------------------------------------------------------------------------------

SWAN grid   1 is preparing computation

 Inlet Test Case

 Operating system  : Linux
 CPU/hardware      : x86_64
 Compiler system   : ifort
 Compiler command  : /data/home/wangling/COAWST/CoawstLibs/mpich/bin/mpif90
 Compiler flags    : -fp-model precise -fc=ifort -heap-arrays -ip -O3 -traceback -assume byterecl -I/data/home/wangling/COAWST/SWAN/build/mod -I/data/home/wangling/COAWST/CoawstLibs/MCT/include 
 OCN Communicator  : -2080374781,  PET size = 1

 Input Script      : 

 GIT Root URL      : 
 GIT Revision      : 
 SVN Root URL      : https://www.myroms.org/svn/src/trunk
 SVN Revision      : 1151

 Local Root        : /data/home/wangling/COAWST
 Header Dir        : /data/home/wangling/Projects/Inlet_test/DiffGrid
 Header file       : inlet_test.h
 Analytical Dir    : /data/home/wangling/Projects/Sandy/Inlet_test

 Resolution, Grid 01: 75x70x8,  Parallel Nodes: 1,  Tiling: 1x1

 Physical Parameters, Grid: 01
 =============================

        720  ntimes            Number of timesteps for 3-D equations.
     60.000  dt                Timestep size (s) for 3-D equations.
         20  ndtfast           Number of timesteps for 2-D equations between
                                 each 3D timestep.
          1  ERstr             Starting ensemble/perturbation run number.
          1  ERend             Ending ensemble/perturbation run number.
          0  nrrec             Number of restart records to read from disk.
          T  LcycleRST         Switch to recycle time-records in restart file.
        720  nRST              Number of timesteps between the writing of data
                                 into restart fields.
          1  ninfo             Number of timesteps between print of information
                                 to standard output.
          T  ldefout           Switch to create a new output NetCDF file(s).
         60  nHIS              Number of timesteps between the writing fields
                                 into history file.
          0  nQCK              Number of timesteps between the writing fields
                                 into quicksave file.
 1.0000E-03  nl_visc2          NLM Horizontal, harmonic mixing coefficient
                                 (m2/s) for momentum.
          F  LuvSponge         Turning OFF sponge on horizontal momentum.
          F  LtracerSponge(01) Turning OFF sponge on tracer 01: temp
 5.0000E-06  Akt_bak(01)       Background vertical mixing coefficient (m2/s)
                                 for tracer 01: temp
 5.0000E-05  Akv_bak           Background vertical mixing coefficient (m2/s)
                                 for momentum.
 5.0000E-06  Akk_bak           Background vertical mixing coefficient (m2/s)
                                 for turbulent energy.
 5.0000E-06  Akp_bak           Background vertical mixing coefficient (m2/s)
                                 for turbulent generic statistical field.
      3.000  gls_p             GLS stability exponent.
      1.500  gls_m             GLS turbulent kinetic energy exponent.
     -1.000  gls_n             GLS turbulent length scale exponent.
 7.6000E-06  gls_Kmin          GLS minimum value of turbulent kinetic energy.
 1.0000E-12  gls_Pmin          GLS minimum value of dissipation.
 5.4770E-01  gls_cmu0          GLS stability coefficient.
 1.4400E+00  gls_c1            GLS shear production coefficient.
 1.9200E+00  gls_c2            GLS dissipation coefficient.
-4.0000E-01  gls_c3m           GLS stable buoyancy production coefficient.
 1.0000E+00  gls_c3p           GLS unstable buoyancy production coefficient.
 1.0000E+00  gls_sigk          GLS constant Schmidt number for TKE.
 1.3000E+00  gls_sigp          GLS constant Schmidt number for PSI.
   1400.000  charnok_alpha     Charnok factor for Zos calculation.
      0.500  zos_hsig_alpha    Factor for Zos calculation using Hsig(Awave).
      0.250  sz_alpha          Factor for Wave dissipation surface tke flux .
    100.000  crgban_cw         Factor for Craig/Banner surface tke flux.
      0.000  wec_alpha         WEC factor for roller/breaking energy distribution.
 3.0000E-04  rdrg              Linear bottom drag coefficient (m/s).
 2.5000E-02  rdrg2             Quadratic bottom drag coefficient.
 1.5000E-02  Zob               Bottom roughness (m).
 5.0000E-01  Zos               Surface roughness (m).
          1  Vtransform        S-coordinate transformation equation.
          1  Vstretching       S-coordinate stretching function.
 1.0000E+00  theta_s           S-coordinate surface control parameter.
 1.0000E+00  theta_b           S-coordinate bottom  control parameter.
      0.000  Tcline            S-coordinate surface/bottom layer width (m) used
                                 in vertical coordinate stretching.
   1025.000  rho0              Mean density (kg/m3) for Boussinesq approximation.
      0.000  dstart            Time-stamp assigned to model initialization (days).
       0.00  time_ref          Reference time for units attribute (yyyymmdd.dd)
 0.0000E+00  Tnudg(01)         Nudging/relaxation time scale (days)
                                 for tracer 01: temp
 0.0000E+00  Znudg             Nudging/relaxation time scale (days)
                                 for free-surface.
 0.0000E+00  M2nudg            Nudging/relaxation time scale (days)
                                 for 2D momentum.
 0.0000E+00  M3nudg            Nudging/relaxation time scale (days)
                                 for 3D momentum.
 0.0000E+00  obcfac            Factor between passive and active
                                 open boundary conditions.
          F  VolCons(1)        NLM western  edge boundary volume conservation.
          F  VolCons(2)        NLM southern edge boundary volume conservation.
          F  VolCons(3)        NLM eastern  edge boundary volume conservation.
          F  VolCons(4)        NLM northern edge boundary volume conservation.
     10.000  T0                Background potential temperature (C) constant.
     30.000  S0                Background salinity (PSU) constant.
   1027.000  R0                Background density (kg/m3) used in linear Equation
                                 of State.
 1.7000E-04  Tcoef             Thermal expansion coefficient (1/Celsius).
 7.6000E-04  Scoef             Saline contraction coefficient (1/PSU).
      1.000  gamma2            Slipperiness variable: free-slip (1.0) or 
                                                      no-slip (-1.0).
          F  LuvSrc            Turning OFF momentum point Sources/Sinks.
          F  LwSrc             Turning OFF volume influx point Sources/Sinks.
          F  LtracerSrc(01)    Turning OFF point Sources/Sinks on tracer 01: temp
          F  LsshCLM           Turning OFF processing of SSH climatology.
          F  Lm2CLM            Turning OFF processing of 2D momentum climatology.
          F  Lm3CLM            Turning OFF processing of 3D momentum climatology.
          F  LtracerCLM(01)    Turning OFF processing of climatology tracer 01: temp
          F  LnudgeM2CLM       Turning OFF nudging of 2D momentum climatology.
          F  LnudgeM3CLM       Turning OFF nudging of 3D momentum climatology.
          F  LnudgeTCLM(01)    Turning OFF nudging of climatology tracer 01: temp

          T  Hout(idBath)      Write out time-dependent bathymetry.
          T  Hout(idFsur)      Write out free-surface.
          T  Hout(idUbar)      Write out 2D U-momentum component.
          T  Hout(idVbar)      Write out 2D V-momentum component.
          T  Hout(idUvel)      Write out 3D U-momentum component.
          T  Hout(idVvel)      Write out 3D V-momentum component.
          T  Hout(idWvel)      Write out W-momentum component.
          T  Hout(idOvel)      Write out omega vertical velocity.
          T  Hout(idTvar)      Write out tracer 01: temp
          T  Hout(idpthR)      Write out time-varying dephts of RHO-points.
          T  Hout(idpthU)      Write out time-varying dephts of U-points.
          T  Hout(idpthV)      Write out time-varying dephts of V-points.
          T  Hout(idpthW)      Write out time-varying dephts of W-points.
          T  Hout(idUbms)      Write out bottom U-momentum stress.
          T  Hout(idVbms)      Write out bottom V-momentum stress.
          T  Hout(idUbrs)      Write out bottom U-current stress.
          T  Hout(idVbrs)      Write out bottom V-current stress.
          T  Hout(idUbws)      Write out wind-induced, bottom U-wave stress.
          T  Hout(idVbws)      Write out wind-induced, bottom V-wave stress.
          T  Hout(idUbcs)      Write out max wind + current, bottom U-wave stress.
          T  Hout(idVbcs)      Write out max wind + current, bottom V-wave stress.
          T  Hout(idUVwc)      Write out max wind + current, bottom UV-wave stress.
          T  Hout(idUbot)      Write out bed wave orbital U-velocity.
          T  Hout(idVbot)      Write out bed wave orbital V-velocity.
          T  Hout(idUbur)      Write out bottom U-momentum above bed.
          T  Hout(idVbvr)      Write out bottom V-momentum above bed.
          T  Hout(idU2rs)      Write out total 2D u-radiation stress.
          T  Hout(idV2rs)      Write out total 2D v-radiation stress.
          T  Hout(idU2Sd)      Write out 2D u-momentum stokes velocity.
          T  Hout(idV2Sd)      Write out 2D v-momentum stokes velocity.
          T  Hout(idU3rs)      Write out total 3D u-radiation stress.
          T  Hout(idV3rs)      Write out total 3D v-radiation stress.
          T  Hout(idU3Sd)      Write out 3D u-momentum stokes velocity.
          T  Hout(idV3Sd)      Write out 3D v-momentum stokes velocity.
          T  Hout(idW3Sd)      Write out 3D omega-momentum stokes velocity.
          T  Hout(idW3St)      Write out 3D w-momentum stokes velocity.
          T  Hout(idWztw)      Write out WEC quasi-static sea level adjustment.
          T  Hout(idWqsp)      Write out WEC quasi-static pressure.
          T  Hout(idWbeh)      Write out WEC Bernoulli head.
          T  Hout(idWamp)      Write out wave height.
          T  Hout(idWlen)      Write out wavelength.
          T  Hout(idWdir)      Write out mean wave direction.
          T  Hout(idWdip)      Write out peak wave direction.
          T  Hout(idWptp)      Write out wave surface period.
          T  Hout(idWpbt)      Write out wave bottom period.
          T  Hout(idWorb)      Write out wave bottom orbital velocity.
          T  Hout(idWdif)      Write out wave dissipation due to bottom friction.
          T  Hout(idWdib)      Write out wave dissipation due to breaking.
          T  Hout(idWdiw)      Write out wave dissipation due to white capping.
          T  Hout(idUwav)      Wave-avg surface u-velocity.
          T  Hout(idVwav)      Wave-avg surface v-velocity.
          T  Hout(idVvis)      Write out vertical viscosity: AKv.
          T  Hout(idMtke)      Write out turbulent kinetic energy.
          T  Hout(idMtls)      Write out turbulent generic length-scale.

          1  inp_lib           Using standard NetCDF library for input files.
          1  out_lib           Using standard NetCDF library for output files.

 Output/Input Files:

               Output Restart File:  ocean_rst.nc
               Output History File:  ocean_his_diff.nc
          Physical parameters File:  
                   Input Grid File:  /data/home/wangling/Projects/Inlet_test/DiffGrid/inlet_test_grid.nc
  ROMS I/O variables Metadata File:  /data/home/wangling/COAWST/ROMS/External/varinfo.dat

 Sediment Parameters, Grid: 01
 =============================

 Size     Sd50        Csed        Srho        Wsed        Erate       poros
 Class    (mm)       (kg/m3)     (kg/m3)     (mm/s)     (kg/m2/s)    (nondim)

   1    1.0000E-01  0.0000E+00  2.6500E+03  1.0000E+01  5.0000E-03  0.0000E+00

         tau_ce      tau_cd      nl_tnu2     nl_tnu4     Akt_bak      Tnudg
         (N/m2)      (N/m2)      (m2/s)      (m4/s)       (m2/s)      (day)

   1    1.0000E-01  1.0000E-02  0.0000E+00  0.0000E+00  5.0000E-06  0.0000E+00

         morph_fac
         (nondim)

   1    1.0000E+01

 New bed layer formed when deposition exceeds  0.10000E-01 (m).
 Two first layers are combined when 2nd layer smaller than  0.00000E+00 (m).
 Rate coefficient for bed load transport =  0.15000E+00

          F  LtracerSponge(02Turning OFF sponge on tracer 02: mud_01
          F  LtracerSrc(02)  Turning OFF point sources/Sink on tracer 02: mud_01
          F  LtracerCLM(02)  Turning OFF processing of climatology tracer 02: mud_01
          F  LnudgeTCLM(02)  Turning OFF nudging of climatology tracer 02: mud_01

          T  Hout(idTvar)   Write out sediment01: mud_01
          T  Hout(idfrac)   Write out bed fraction, sediment 01: mudfrac_01
          T  Hout(idmass)   Write out mass, sediment 01: mudmass_01
          T  Hout(idUbld)   Write out bed load at U-points, sediment 01: bedload_Umud_01
          T  Hout(idVbld)   Write out bed load at V-points, sediment 01: bedload_Vmud_01
          T  Hout(idSbed)   Write out BED property 01: bed_thickness
          T  Hout(idSbed)   Write out BED property 02: bed_age
          T  Hout(idSbed)   Write out BED property 03: bed_porosity
          T  Hout(idSbed)   Write out BED property 04: bed_biodiff
          T  Hout(idBott)   Write out BOTTOM property 01: grain_diameter
          T  Hout(idBott)   Write out BOTTOM property 02: grain_density
          T  Hout(idBott)   Write out BOTTOM property 03: settling_vel
          T  Hout(idBott)   Write out BOTTOM property 04: erosion_stress
          T  Hout(idBott)   Write out BOTTOM property 05: ripple_length
          T  Hout(idBott)   Write out BOTTOM property 06: ripple_height
          T  Hout(idBott)   Write out BOTTOM property 07: bed_wave_amp
          T  Hout(idBott)   Write out BOTTOM property 08: Zo_def
          T  Hout(idBott)   Write out BOTTOM property 09: Zo_app
          T  Hout(idBott)   Write out BOTTOM property 15: active_layer_thickness
          T  Hout(idBott)   Write out BOTTOM property 17: bed_inund_depth
          T  Hout(idBott)   Write out BOTTOM property 18: dep_net
          T  Hout(idBott)   Write out BOTTOM property 19: thck_wbl
          T  Hout(idBott)   Write out BOTTOM property 20: udelta_wbl
          T  Hout(idBott)   Write out BOTTOM property 21: fd_wbl
          T  Hout(idBott)   Write out BOTTOM property 22: Zr_wbl
          T  Hout(idBott)   Write out BOTTOM property 23: ksd_wbl
          T  Hout(idBott)   Write out BOTTOM property 24: ustrc_wbl
          T  Hout(idBott)   Write out BOTTOM property 25: phic_sgwbl
          T  Hout(idBott)   Write out BOTTOM property 26: phi_wc

 Tile partition information for Grid 01:  75x70x8  tiling: 1x1

     tile     Istr     Iend     Jstr     Jend     Npts

        0        1       75        1       70    42000

 Tile minimum and maximum fractional coordinates for Grid 01:
   (interior points only)

     tile     Xmin     Xmax     Ymin     Ymax     grid

        0     0.50    75.50     0.50    70.50  RHO-points

        0     1.00    75.00     0.50    70.50    U-points

        0     0.50    75.50     1.00    70.00    V-points

 Maximum halo size in XI and ETA directions:

               HaloSizeI(1) =     255
               HaloSizeJ(1) =     243
                TileSide(1) =      79
                TileSize(1) =    5925

 Tracer Advection Scheme: NLM
 ========================

 Variable               Grid  Horizontal         Vertical
 ---------              ----  ------------       ------------

 temp                     1   MPDATA             MPDATA

 mud_01                   1   HSIMT              HSIMT

 Akima4     Fourth-order Akima advection
 Centered2  Second-order centered differences advection
 Centered4  Fourth-order centered differences advection
 HSIMT      Third High-order Spatial Inteporlation at Middle Time Advection with TVD limiter
 MPDATA     Multidimensional Positive Definite Advection Algorithm, recursive method
 Splines    Conservative Parabolic Splines Reconstruction Advection (only vertical; not recommended)
 Split_U3   Split third-order Upstream Advection
 Upstream3  Third-order Upstream-biased Advection (only horizontal)

 Lateral Boundary Conditions: NLM
 ============================

 Variable               Grid  West Edge    South Edge   East Edge    North Edge
 ---------              ----  ----------   ----------   ----------   ----------

 zeta                     1   Gradient     Closed       Gradient     Clamped

 ubar                     1   Gradient     Closed       Gradient     Reduced

 vbar                     1   Gradient     Closed       Gradient     Reduced

 u                        1   Gradient     Closed       Gradient     Reduced

 v                        1   Gradient     Closed       Gradient     Reduced

 temp                     1   Gradient     Closed       Gradient     Gradient

 mud_01                   1   Gradient     Closed       Gradient     Gradient

 tke                      1   Gradient     Closed       Gradient     Gradient

 ubar_stokes              1   Gradient     Closed       Gradient     Gradient

 vbar_stokes              1   Gradient     Closed       Gradient     Gradient

 u_stokes                 1   Gradient     Closed       Gradient     Gradient

 v_stokes                 1   Gradient     Closed       Gradient     Gradient

 Activated C-preprocessing Options:

 INLET_TEST               Inlet Test Case
 ANA_BPFLUX               Analytical bottom passive tracers fluxes
 ANA_BSFLUX               Analytical kinematic bottom salinity flux
 ANA_BTFLUX               Analytical kinematic bottom temperature flux
 ANA_FSOBC                Analytical free-surface boundary conditions
 ANA_INITIAL              Analytical initial conditions
 ANA_M2OBC                Analytical 2D momentum boundary conditions
 ANA_SEDIMENT             Analytical sediment initial conditions
 ANA_SMFLUX               Analytical kinematic surface momentum flux
 ANA_SPFLUX               Analytical surface passive tracer fluxes
 ANA_SSFLUX               Analytical kinematic surface salinity flux
 ANA_STFLUX               Analytical kinematic surface temperature flux
 ASSUMED_SHAPE            Using assumed-shape arrays
 BEDLOAD_VANDERA          Activate bed load sediment transport vanDerA formula
 BEDLOAD_VANDERA_ASYM_LIMIActivate bed load vanDerA asymmetry limits
 BEDLOAD_VANDERA_SURFACE_WActivate bed load vanDerA surface wave
 BEDLOAD_VANDERA_WAVE_AVGDActivate bed load vanDerA wave avg stress
 BEDLOAD_VANDERA_MADSEN_UDActivate bed load madsen current calculation
 BOUNDARY_ALLREDUCE       Using mpi_allreduce in mp_boundary routine
 COLLECT_ALLREDUCE        Using mpi_allreduce in mp_collect routine
 DJ_GRADPS                Parabolic Splines density Jacobian (Shchepetkin, 2002)
 DOUBLE_PRECISION         Double precision arithmetic numerical kernel.
 GLS_MIXING               Generic Length-Scale turbulence closure
 KANTHA_CLAYSON           Kantha and Clayson stability function formulation
 MASKING                  Land/Sea masking
 MCT_LIB                  Using Model Coupling Toolkit library
 MIX_S_UV                 Mixing of momentum along constant S-surfaces
 MPI                      MPI distributed-memory configuration
 WEC_VF                   Vortex Force wave current interaction
 WDISS_WAVEMOD            Wave energy dissipation acquired from coupled wave model
 NONLINEAR                Nonlinear Model
 !NONLIN_EOS              Linear Equation of State for seawater
 N2S2_HORAVG              Horizontal smoothing of buoyancy and shear
 POWER_LAW                Power-law shape time-averaging barotropic filter
 PROFILE                  Time profiling activated
 K_GSCHEME                Third-order upstream advection of TKE fields
 REDUCE_ALLREDUCE         Using mpi_allreduce in mp_reduce routine
 RI_SPLINES               Parabolic Spline Reconstruction for Richardson Number
 !RST_SINGLE              Double precision fields in restart NetCDF file
 SEDIMENT                 Cohesive and noncohesive sediments
 SED_MORPH                Allow bottom model elevation to evolve
 SUSPLOAD                 Activate suspended sediment transport
 NONCOHESIVE_BED1         Activate non-cohesive (original) sediment bed.
 SPECTRUM_STOKES          Stokes drift estimated from wave spectrum.
 SOLVE3D                  Solving 3D Primitive Equations
 SPLINES_VDIFF            Parabolic Spline Reconstruction for Vertical Diffusion
 SPLINES_VVISC            Parabolic Spline Reconstruction for Vertical Viscosity
 SSW_BBL                  Styles and Glenn Bottom Boundary Layer - modified
 SSW_CALC_ZNOT            Internal computation of bottom roughness
 SSW_LOGINT               Bottom currents logarithmic interpolation
 SSW_LOGINT_WBL           Bottom currents logarithmic interpolation at wbl
 SWAN_COUPLING            SWAN model coupling
 UV_ADV                   Advection of momentum
 UV_U3HADVECTION          Third-order upstream horizontal advection of 3D momentum
 UV_C4VADVECTION          Fourth-order centered vertical advection of momentum
 UV_KIRBY                 Compute uwave and vwave Kirby avg velocities.
 UV_VIS2                  Harmonic mixing of momentum
 VAR_RHO_2D               Variable density barotropic mode
 WAVES_OCEAN              Two-way wave-ocean models coupling.

 Process Information:

 Node #    0 (pid=  148194) is active.

 GET_SPARSE - error while opening file: /data/home/wangling/Projects/Inlet_test/DiffGrid/scrip_inlet_test_diff
forrtl: severe (153): allocatable array or pointer is not allocated
Image              PC                Routine            Line        Source             
coawstM            0000000000D1AD94  Unknown               Unknown  Unknown
coawstM            0000000000429473  ocean_coupler_mod         301  ocean_coupler.f90
coawstM            0000000000412B32  roms_kernel_mod_m         149  roms_kernel.f90
coawstM            0000000000417579  MAIN__                    230  master.f90
coawstM            0000000000412062  Unknown               Unknown  Unknown
libc-2.17.so       00002AE9210B0445  __libc_start_main     Unknown  Unknown
coawstM            0000000000411F69  Unknown               Unknown  Unknown

**Comment by jcwarner-usgs** [comment]
i think this string is just too long
/data/home/wangling/Projects/Inlet_test/DiffGrid/scrip_inlet_test_diff
try to rename it to something shorter.

can u try this:
mv Projects/Inlet_test/DiffGrid/scrip_inlet_test_diffgrid.nc Projects/Inlet_test/DiffGrid/scrip_itdg.nc
edit Projects/Inlet_test/DiffGrid/coupling_inlet_test_diffgrid.in and change
   SCRIP_COAWST_NAME = Projects/Inlet_test/DiffGrid/scrip_inlet_test_diffgrid.nc
to
   SCRIP_COAWST_NAME = Projects/Inlet_test/DiffGrid/scrip_itdg.nc
and run that

**Comment by LiuJiao0408** [comment]
I have learned a new skill! nice
thank u so much
