### ISSUE TITLE
A Syntax error when running the Inlet_test/InWave

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#299]
Hi!!!
when I run the Inwave , a Syntax error comes as follows
is this a Syntax error? How can I solve it! Thanks ur reply!

analytical.f90(1054): error #5082: Syntax error, found ':' when expecting one of: % . = =>
      ana_sediment.h: no values provided for bottom(:,:,isd50) and
--------------------^
analytical.f90(1055): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ( % [ . = =>
                                             bottom(:,:,idens)
--------------------------------------------------------------^
cd /data/home/wangling/Projects/Inlet_test/InWave/Build_roms; /data/home/wangling/COAWST/CoawstLibs/mpich/bin/mpif90 -c -fp-model precise -fc=ifort -heap-arrays -ip -O3 -traceback ini_fields.f90
compilation aborted for analytical.f90 (code 1)
make: *** [/data/home/wangling/Projects/Inlet_test/InWave/Build_roms/analytical.o] Error 1

**Comment by jcwarner-usgs** [comment]
the ana_sediment.h file needs to have a section of code specific to the application you are running.
look in that file for examples.

**Comment by LiuJiao0408** [comment]
Thank u so much！！！
I have solved this problem, I give the wrong path of ana 
I will close this comment，
Thanks again！！！
