### ISSUE TITLE
A execvp error when running the Inlet_test/Swanonly

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#300]
Hi all!!!
when I run the Inlet_test/Swanonly, I met the problem. How can I solve it? Thank u for ur help!
 
[wangling@ln01 Swanonly]$ mpiexec –np 1 ./coawstM /data/home/wangling/Projects/Inlet_test/Swanonly/swan_inlet_test.in 
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)

**Comment by LiuJiao0408** [comment]
I have check the ./build_coawst.sh

there are errors show:
/opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin/for_main.o: In function `main':
for_main.c:(.text+0x2e): undefined reference to `MAIN__'
make[3]: *** [bin/swan.exe] Error 1
make[3]: Leaving directory `/data/home/wangling/COAWST/SWAN/build'
make[2]: *** [lib/CMakeFiles/swan.exe.dir/all] Error 2
make[2]: Leaving directory `/data/home/wangling/COAWST/SWAN/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/data/home/wangling/COAWST/SWAN/build'

but those errors also appeared when I run the Inlet_test/Coupled. Will these errors have no impact？

**Comment by jcwarner-usgs** [comment]
if you get a coawstM, then you are good.
you can disregard the 'undefined ref to MAIN.'  i dont let SWAN build a swan.exe.

the error you are having is with your mpi
"mpiexec –np 1 ./coawstM /data/home/wangling/Projects/Inlet_test/Swanonly/swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)"

"-np"   
maybe try

mpiexec –n 1 ./coawstM /data/home/wangling/Projects/Inlet_test/Swanonly/swan_inlet_test.in
or mpirun ??

**Comment by LiuJiao0408** [comment]
I have tried :
  mpiexec –n 1 ./coawstM swan_inlet_test.in
  [proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)

  mpirun –n 1 ./coawstM swan_inlet_test.in
  [proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)
  
  mpiexec –np 1 ./coawstM swan_inlet_test.in
  [proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)
but the error is still here

I do not konw if the path here is right or not!
  export     MY_HEADER_DIR=${MY_PROJECT_DIR}
  export MY_ANALYTICAL_DIR=/data/home/wangling/Projects/Sandy/Inlet_test

**Comment by jcwarner-usgs** [comment]
did you compile this case with nesting?

Manual page29

6.7. INLET_TEST/Swanonly = SWAN by itself, also with grid refinement.
This test case is basically the swan files from case 7 (mentioned above), but allows you to run swan by itself, and with a child grid. 

To run SWAN by itself, with only 1 grid, the header file should have 
#define SWAN_MODEL
#undef NESTING

./ build_coawst.sh to compile. 
One note is that this needs to be run with the command pointing to the swan input file(s). So to run the swan only with just one grid, run the model with (X can be any number of processors) 
mpiexec –np X ./coawstM.exe Projects/Inlet_test/Swanonly/swan_inlet_test.in

To run SWAN by itself and with a child grid, the header file should have 
#define SWAN_MODEL
#define NESTING

./ build_coawst.sh to compile. 
The command line needs to point to the swan input files. So to run the swan only with a parent and a child use (X can be any number of processors) 

mpiexec –np 1 ./coawstM.exe Projects/Inlet_test/Swanonly/swan_inlet_test.in
Projects/Inlet_test/Swanonly/swan_inlet_test_refined5.in
 (all that is on one line, the text is just word wrapping here).

you might need mpirun, not sure.
How do you normally launch an mpi job?

**Comment by LiuJiao0408** [comment]
yes
I  ./ build_coawst.sh to compile the model after confirmthe #undef NESTING
but the ERROR is still here
[wangling@ln01 Swanonly]$ mpiexec –np 1 ./coawstM.exe swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)
[wangling@ln01 Swanonly]$ mpiexec –n 1 ./coawstM.exe swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)
[wangling@ln01 Swanonly]$ mpirun –n 1 ./coawstM.exe swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)
[wangling@ln01 Swanonly]$ mpiexec –np 1 ./coawstM.exe /data/home/wangling/Projects/Inlet_test/Swanonly/swan_inlet_test.in 
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)

**Comment by LiuJiao0408** [comment]
yes
I  ./ build_coawst.sh to compile the model after confirmthe #undef NESTING

[wangling@ln01 Swanonly]$ mpiexec –np 1 ./coawstM.exe swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)
[wangling@ln01 Swanonly]$ mpiexec –n 1 ./coawstM.exe swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)
[wangling@ln01 Swanonly]$ mpirun –n 1 ./coawstM.exe swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)
[wangling@ln01 Swanonly]$ mpiexec –np 1 ./coawstM.exe /data/home/wangling/Projects/Inlet_test/Swanonly/swan_inlet_test.in 
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)

**Comment by LiuJiao0408** [comment]
Currently, my operations are carried out according to the manual
I run a case use  mpirun –n X ./coawstM.exe XXXXX.in

**Comment by LiuJiao0408** [comment]
And now， I meeting a problem:
  using mpiexec –n 2 ./coawstM swan_inlet_test.in
  error comes : HYDU_create_process (utils/launch/launch.c:75): execvp error on file –n (No such file or directory)
  
  using mpirun -n 2 ./coawstM swan_inlet_test.in 
  Num swan grids should = 1 for no nesting
  Num swan grids should = 1 for no nesting
  SWAN grid   1 is preparing computation
  
  forrtl: No such file or directory
  
  SWAN grid   2 is preparing computation
  
  forrtl: No such file or directory
  forrtl: severe (29): file not found, unit 602, file /data/home/wangling/Projects/Inlet_test/Swanonly/fort.602

where are the ana_ files.

**Comment by jcwarner-usgs** [comment]
i cant help you figure out how to run jobs on your machine.  You will need to ask local help on that.

It looks like mpirun is the correct command.
-If you compile the case with NESTING, then there should be 2 swan files on the input line and the swan input files need to have NUMSGRIDS 2
-If you compile the case without NESTING, then there should be 1 swan file on the input line and the swan input files need to have NUMSGRIDS 1

**Comment by LiuJiao0408** [comment]
Currently, my operations are carried out according to the manual
I run a case use mpirun –n X ./coawstM.exe XXXXX.in

I have checked this: NUMSGRIDS 1, 

now,
[wangling@ln01 Swanonly]$ mpiexec –np 2 ./coawstM swan_inlet_test.in
[proxy:0:0@ln01] HYDU_create_process (utils/launch/launch.c:75): execvp error on file –np (No such file or directory)
but  mpirun -n 2 ./coawstM swan_inlet_test.in  can run this case
the problem is still here

**Comment by LiuJiao0408** [comment]
I don not know why mpirun can do but mpiexec cannot now (the mpirun also cannot before)
It is very strange
