### ISSUE TITLE
A FATAL CALLED while run the JOE_TC/Coupled

### ISSUE THREAD

**Issue by LiuJiao0408** [jcwarner-usgs/COAWST#304]
Hi all!!!
some questiones need ur help!

Q1: in ocean_joe_tc.in
  NtileI == 4 ! I-direction partition
  NtileJ == 3 ! J-direction partition
are those number same as M&N in namelist.input 
  nproc_x = M
  nproc_y = N

Q2: when I run the JOE_TC/Coupled, I have followed the set in the manual, I got the error:
    module_io_quilt_old.F        2950 F
     module_io_quilt_old.F        2950 F
     module_io_quilt_old.F        2950 F
     module_io_quilt_old.F        2950 F
    -------------- FATAL CALLED ---------------
    FATAL CALLED FROM FILE:  <stdin>  LINE:    6829
    ERROR reading namelist namelist_quilt
    -------------------------------------------
    Abort(1) on node 8 (rank 8 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 8

if I set :
    nproc_x = 1
      nproc_y = 1
the errors are :
    module_io_quilt_old.F        2950 F
     module_io_quilt_old.F        2950 F
     module_io_quilt_old.F        2950 F
     module_io_quilt_old.F        2950 F
    Quilting with   1 groups of   0 I/O tasks.
    Quilting with   1 groups of   0 I/O tasks.
    Quilting with   1 groups of   0 I/O tasks.
    Quilting with   1 groups of   0 I/O tasks.
    Abort(67712517) on node 11 (rank 11 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
    PMPI_Cart_create(325): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x48a81d0, periods=0x7f200007eac0, reorder=0, comm_cart=0x7ffe3be6993c) failed
    PMPI_Cart_create(256): Invalid communicator
     Ntasks in X            1 , ntasks in Y            1
      Domain # 1: dx = 12000.000 m
    Abort(201930245) on node 9 (rank 9 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
    PMPI_Cart_create(325): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x48a81d0, periods=0x7f2000095540, reorder=0, comm_cart=0x7ffdc391593c) failed
    PMPI_Cart_create(256): Invalid communicator
    Abort(336147973) on node 10 (rank 10 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
    PMPI_Cart_create(325): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x48a81d0, periods=0x7f2000038e40, reorder=0, comm_cart=0x7ffc896ee33c) failed
    PMPI_Cart_create(256): Invalid communicator

How Can I Solve this!

Thanks for reply!

**Comment by jcwarner-usgs** [comment]
Q1 - no.
The number of procs for roms is NtileI and NtileJ.
The number of procs for WRF in nproc_x and nproc_y.  
In the coupling.in, you need to set Nnodes Atm to = nproc_x * nproc_y, and NnodesOCN to = NtileI * NtileJ.

2) not sure on the JOETC case.  have not run that in awhile.  Can you try Sandy?

**Comment by LiuJiao0408** [comment]
In the coupling.in, If I set Nnodes Atm to = 2*2, and NnodesOCN to = 2 * 2, and NnodesWAV =  4.
then all the Nnodes is Nnodes Atm+NnodesOCN+NnodesWAV = 12.
NtileI * NtileJ is roms
nproc_x * nproc_y is wrf
how about swan

**Comment by jcwarner-usgs** [comment]
you dont need to set the tiling for swan.  swan does it automatically.
a lot of this info is in the manual, or you can look at the handouts from the trainings.
