### ISSUE TITLE
Insufficient memory on the server when coupling WRFs

### ISSUE THREAD

**Issue by hgengqi** [jcwarner-usgs/COAWST#306]
I've recently been trying to couple WRF into SWAN and ROMS, and I have no problem running WRF on its own, and running SWAN coupled to ROMS on its own, but it always prompts for a memory error when the three modes are coupled. This is a problem that should not exist on the server, so the only possible problem is in my setup, but I don't know exactly how to troubleshoot the problem, is it defining the .h file for coawstM? Or the WRF namelist.input file? Or the coupling.in file that couples the three modes? All these three files and the runtime log file are below, I hope someone can help me, thank you very much for your help!

[coupling_haiou.in.txt](https://github.com/user-attachments/files/16738737/coupling_haiou.in.txt)
[haiou.h.txt](https://github.com/user-attachments/files/16738738/haiou.h.txt)
[namelist.input.txt](https://github.com/user-attachments/files/16738739/namelist.input.txt)

**Comment by Etandooley** [comment]
@hgengqi Are you using VPN when trying to couple?

**Comment by jcwarner-usgs** [comment]
i dont see the run time log.
for your cluster, you may need a command like
#SBATCH --mem-per-cpu=4096

**Comment by hgengqi** [comment]
> @hgengqi Are you using VPN when trying to couple?

no,i just run it on super computer

**Comment by Etandooley** [comment]
@hgengqi You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WRF07638
Please see the link below to our dedicated support line:
[WRF coupling live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by hgengqi** [comment]
> i dont see the run time log. for your cluster, you may need a command like #SBATCH --mem-per-cpu=4096

[log.txt](https://github.com/user-attachments/files/16741022/log.txt)
sorry i forgot this, here is my log file

**Comment by jcwarner-usgs** [comment]
I am not sure why your application ended.  Did you get any Err* files?

**Comment by hgengqi** [comment]
> I am not sure why your application ended. Did you get any Err* files?

yes，but all the error files are empty files

**Comment by jcwarner-usgs** [comment]
if you have an Err* file, then there is something wrong in the SWAN setup (INPUT file).

**Comment by hgengqi** [comment]
> if you have an Err* file, then there is something wrong in the SWAN setup (INPUT file).

There's a possibility, so I'll try it right away. Thank you, and I'll keep you updated with the results.

**Comment by hgengqi** [comment]
> > if you have an Err* file, then there is something wrong in the SWAN setup (INPUT file).
> 
> There's a possibility, so I'll try it right away. Thank you, and I'll keep you updated with the results.

Yes, I found that the problem is that I didn't set the absolute path but set it to a relative path during the run, and the swan didn't find part of the file

**Comment by jcwarner-usgs** [comment]
good.!  i will close the ticket now.  thanks.
