### ISSUE TITLE
v3.8 compiling got stuck

### ISSUE THREAD

**Issue by jwchenh** [jcwarner-usgs/COAWST#311]
When I try to compile the COAWST 3.8 through ./build_coawst.sh, it got stuck here not moving on:

-- Found NetCDF: /GPUFS/app/library/netcdf/4.5.0-icc-15/include (found version "4.5.0") found components: Fortran
-- FindNetCDF defines targets:
-- - NetCDF_VERSION [4.5.0]
-- - NetCDF_PARALLEL [TRUE]
-- - NetCDF_C_CONFIG_EXECUTABLE [/GPUFS/app/library/netcdf/4.5.0-icc-15/bin/nc-config]
-- - NetCDF::NetCDF_C [SHARED] [Root: /GPUFS/app/library/netcdf/4.5.0-icc-15] Lib: /GPUFS/app/library/netcdf/4.5.0-icc-15/lib/libnetcdf.so
-- - NetCDF_Fortran_CONFIG_EXECUTABLE [/GPUFS/app/library/netcdf/4.5.0-icc-15/bin/nf-config]
-- - NetCDF::NetCDF_Fortran [SHARED] [Root: /GPUFS/app/library/netcdf/4.5.0-icc-15] Lib: /GPUFS/app/library/netcdf/4.5.0-icc-15/lib/libnetcdff.so

the background running process:
/usr/bin/perl ./COAWST-COAWST_v3.8/SWAN/switch.pl -unix -impi -mpi -netcdf ./COAWST-COAWST_v3.8/SWAN/src_coawst/*.ftn ./COAWST-COAWST_v3.8/SWAN/src_coawst/*.ftn90

**Comment by jcwarner-usgs** [comment]
yes i have seen this before.  For some reason, the CMake can not build SWAN when you have a "-" in the path name.
what is the full path to the root COAWST code?  is it
./COAWST-COAWST_v3.8/
change the install to be in a path like
./COAWST_v3.8/

Suggest you make a dir, cd to that dir and use
git clone https://github.com/DOI-USGS/COAWST

**Comment by jwchenh** [comment]
It works! Thanks.
