### ISSUE TITLE
MULTIFILE_INFO_S2D - Error while processing lateral boundary multi-files:  data does not include initialization time

### ISSUE THREAD

**Issue by ZhangXYNUDT** [jcwarner-usgs/COAWST#313]
I am running ROMS only, and I got an error:

MULTIFILE_INFO_S2D - Error while processing lateral boundary multi-files: data does not include initialization time = 1858-11-17 00:00:00.00

ROMS/TOMS - Output NetCDF summary for Grid 01:
Found Error: 04 Line: 414 Source: ROMS/Utility/close_io.F, close_out

ROMS/TOMS - I/O error … exit_flag: 4

ERROR: I/O related problem.

Attached are my output result file and .in file. Thank you!
[ocean_mangkhut.in.txt](https://github.com/user-attachments/files/16918897/ocean_mangkhut.in.txt)
[slurm-3514498.txt](https://github.com/user-attachments/files/16918898/slurm-3514498.txt)

**Comment by jcwarner-usgs** [comment]
It is saying that the input data does not contain the initial time.

your model starts on
GET_STATE_NF90   - NLM: state initial conditions,                       1858-11-17 00:00:00.00

and the bc file is from
 2018-09-14 00:00:00.00  2018-09-16 12:00:00.00     myProjects/mangkhut/roms_bdy.nc

looks like you need to adjust the time in the roms_ini.nc to be 58375.0

**Comment by ZhangXYNUDT** [comment]
Thank you for your response! I discovered the issue: the ocean_time variable in roms_ini.nc is set to 0. This file was generated using roms_master_climatology_coawst_mw.m, but the function updatinit_coawst_mw did not correctly write the ocean_time variable.
