### ISSUE TITLE
Swan, roms, and wrf  coupling anomalous stalling

### ISSUE THREAD

**Issue by hgengqi** [jcwarner-usgs/COAWST#315]
I have a strange problem, when I run COAWST's three mode coupling (swan+roms+wrf), the modes get stuck at that time they are coupled, for example, if I set the time for exchanging the data at 3600s which is one hour, it gets stuck at one hour this time, if I set the time for exchanging the data at 600s which is ten minutes, it gets stuck at  If you set the time to 3600s (one hour), it will be stuck at one hour, if you set the data exchange time to 600s (10 minutes), it will be stuck at ten minutes, if you set the time long enough, it can run all the time without error but without coupling, there was a post with a similar problem (https://github.com/DOI-USGS/COAWST/issues/250), and Warner's advice was to carefully compare the calculation time steps of the three modes.But I've carefully compared this factor and still can't solve the problem.

I'll give my roms, swan, wrf setup and coupling file setup below
[coupling_haiou.in.txt](https://github.com/user-attachments/files/16948685/coupling_haiou.in.txt)
[namelist.input.txt](https://github.com/user-attachments/files/16948686/namelist.input.txt)
[ocean_haiou.in.txt](https://github.com/user-attachments/files/16948689/ocean_haiou.in.txt)
[swan_haiou.in.txt](https://github.com/user-attachments/files/16948690/swan_haiou.in.txt)

I hope someone can give me some advice, thank you from the bottom of my heart for your help!

**Comment by jcwarner-usgs** [comment]
can you post the full output when the model runs?
do you get any Err* files?

**Comment by hgengqi** [comment]
> can you post the full output when the model runs? do you get any Err* files?

There is no errfile，and the output file is here
[Uploading slurm-72805.out.txt…]()

**Comment by jcwarner-usgs** [comment]
i cant open that out.txt file.  can u try again.

**Comment by hgengqi** [comment]
> i cant open that out.txt file. can u try again.

[slurm-72805.out.txt](https://github.com/user-attachments/files/16967016/slurm-72805.out.txt)

**Comment by jcwarner-usgs** [comment]
DEF_HIS     - creating  history      file, Grid 01: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc
d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc
d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc
 Found Error: 02   Line: 8146     Source: ROMS/Modules/mod_netcdf.F, netcdf_create

 NETCDF_CREATE - unable to create output NetCDF file:
                 /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc
                 call from:  ROMS/Utility/def_his.F
                 No such file or directory                                                       
 Found Error: 03   Line: 127      Source: ROMS/Utility/def_his.F

**Comment by hgengqi** [comment]
> ```
> DEF_HIS     - creating  history      file, Grid 01: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc
> ```
> 
> d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc Found Error: 02 Line: 8146 Source: ROMS/Modules/mod_netcdf.F, netcdf_create
> 
> NETCDF_CREATE - unable to create output NetCDF file: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc call from: ROMS/Utility/def_his.F No such file or directory Found Error: 03 Line: 127 Source: ROMS/Utility/def_his.F

Thank you thank you thank you, this issue seems to be resolved for now, thank you for taking the time out of your busy schedule to answer my question!

**Comment by hgengqi** [comment]
> ```
> DEF_HIS     - creating  history      file, Grid 01: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc
> ```
> 
> d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc Found Error: 02 Line: 8146 Source: ROMS/Modules/mod_netcdf.F, netcdf_create
> 
> NETCDF_CREATE - unable to create output NetCDF file: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc call from: ROMS/Utility/def_his.F No such file or directory Found Error: 03 Line: 127 Source: ROMS/Utility/def_his.F

The schema started running but stopped after a while, the new output file was too large to upload

**Comment by hgengqi** [comment]
> ```
> DEF_HIS     - creating  history      file, Grid 01: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc
> ```
> 
> d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc d01 2014-09-12_00:00:30 calling inc/HALO_EM_PHYS_A_inline.inc Found Error: 02 Line: 8146 Source: ROMS/Modules/mod_netcdf.F, netcdf_create
> 
> NETCDF_CREATE - unable to create output NetCDF file: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc call from: ROMS/Utility/def_his.F No such file or directory Found Error: 03 Line: 127 Source: ROMS/Utility/def_his.F

The model started running but stopped after a while, the new output file was too large to upload

**Comment by jcwarner-usgs** [comment]
are you still getting this error
"NETCDF_CREATE - unable to create output NetCDF file: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc call from: ROMS/Utility/def_his.F No such file or directory Found Error: 03 Line: 127 Source: ROMS/Utility/def_his.F"
if so, then that error is saying that the outfile can not be created because that directory does not exist.

**Comment by hgengqi** [comment]
> are you still getting this error "NETCDF_CREATE - unable to create output NetCDF file: /home-yx/users/nsyx_hgq/haiou/out/scs_his_haiou_00001.nc call from: ROMS/Utility/def_his.F No such file or directory Found Error: 03 Line: 127 Source: ROMS/Utility/def_his.F" if so, then that error is saying that the outfile can not be created because that directory does not exist.

NO,but i found new error like：
DIAG speed trouble    79.564168962772442     
 Found Error: 01   Line: 341      Source: ROMS/Nonlinear/main3d.F
 Found Error: 01   Line: 331      Source: ROMS/Drivers/nl_ocean.h, ROMS_run

 Blowing-up: Saving latest model state into  RESTART file
     REASON: MaxSpeed =  8.0E+01

**Comment by jcwarner-usgs** [comment]
ok.  for that you need to look at the rst file and see what is going on.
if the error started early in the run, you could save the history files more often to see how the flow fields are evolving and that can help determine what is happening.

**Comment by hgengqi** [comment]
> ok. for that you need to look at the rst file and see what is going on. if the error started early in the run, you could save the history files more often to see how the flow fields are evolving and that can help determine what is happening.

I've shortened the simulation time step for each mode in the past few days, and I've been running it for three days now, and there is no error message in the output file, but it still stops running

**Comment by hgengqi** [comment]
> ok. for that you need to look at the rst file and see what is going on. if the error started early in the run, you could save the history files more often to see how the flow fields are evolving and that can help determine what is happening.

[slurm-73490.out.txt](https://github.com/user-attachments/files/17004399/slurm-73490.out.txt)
here is new output file and i found some unusual value in this file

**Comment by jcwarner-usgs** [comment]
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF

looks like WRF thinks it is done.

**Comment by hgengqi** [comment]
> d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF d01 2014-09-14_18:00:00 wrf: SUCCESS COMPLETE WRF
> 
> looks like WRF thinks it is done.

Okay I see, thank you，but Is this normal?
ROMStoSWAN Min/Max DEPTH   (m):        0.000000E+00  8.653170E+03
ROMStoSWAN Min/Max WLEV    (m):       -8.436514E-01  2.417531E+00
ROMStoSWAN Min/Max VELX    (ms-1):    -4.103941E+00  3.598493E+00
ROMStoSWAN Min/Max VELY    (ms-1):    -3.812577E+00  5.129143E+00
ROMStoSWAN Min/Max ZO      (m):        0.000000E+00  5.000000E-02
 == SWAN grid  1 recv data from WRF grid 1
WRFtoSWAN Min/Max  U10     (ms-1):    -3.482085E+01  1.888239E+01
WRFtoSWAN Min/Max  V10     (ms-1):    -3.107104E+01  3.810348E+01
 == SWAN grid  1 sent data to WRF grid     1
  ## WRF grid  1 recv data from WAVE grid  1
 WAVtoWRF  Min/Max HSIGN   (m):        0.000000E+00  1.411889E+01
 WAVtoWRF  Min/Max WLENP   (m):        0.000000E+00  5.511965E+02
 WAVtoWRF  Min/Max RTP     (m):        0.000000E+00  1.831721E+01
Timing for main: time 2014-09-14_18:00:00 on domain   1:   28.81616 elapsed seconds
Timing for main: time 2014-09-14_18:00:00 on domain   1:   28.81616 elapsed seconds

**Comment by jcwarner-usgs** [comment]
these seem high:
ROMStoSWAN Min/Max VELX (ms-1): -4.103941E+00 3.598493E+00
ROMStoSWAN Min/Max VELY (ms-1): -3.812577E+00 5.129143E+00

this seems high
WAVtoWRF Min/Max HSIGN (m): 0.000000E+00 1.411889E+01

is this a hurricane / TC storm?

you need to look at the netcdf output files and see what is going on.

**Comment by hgengqi** [comment]
> these seem high: ROMStoSWAN Min/Max VELX (ms-1): -4.103941E+00 3.598493E+00 ROMStoSWAN Min/Max VELY (ms-1): -3.812577E+00 5.129143E+00
> 
> this seems high WAVtoWRF Min/Max HSIGN (m): 0.000000E+00 1.411889E+01
> 
> is this a hurricane / TC storm?
> 
> you need to look at the netcdf output files and see what is going on.

yes，this is a hurricane simulate
