### ISSUE TITLE
Error when running SWAN: Error with boundary data

### ISSUE THREAD

**Issue by ZhangXYNUDT** [jcwarner-usgs/COAWST#316]
Dear Mr. Warner,
I am running SWAN, but I am encountering some errors:

 ** Severe error     : No convergence calculating the spectrum
 ** Severe error     : at the boundary using parametric bound. cond.

 ** No continuation of computation because of error level:  3
 ** No continuation of computation because of error level:

Attached are the swan.in and PRINT files.
[PRINT.txt](https://github.com/user-attachments/files/16979545/PRINT.txt)
[swan_mangkhut.in.txt](https://github.com/user-attachments/files/16979547/swan_mangkhut.in.txt)

**Comment by jcwarner-usgs** [comment]
i suggest you look at the TPAR files to make sure the data looks correct.
For some reason SWAN is having trouble to compute the spectra.
I have seen this if the period is 0.  make sure the periods are >0.
TPAR has HS Tp Dir Spread

**Comment by ZhangXYNUDT** [comment]
I have reviewed all the TPAR files, and each value in the TPAR files is greater than 0.

I use create_swanTpar_from_WW3.m to generate TPAR files, with data sourced from [NCEI NOAA WW3 catalog](https://www.ncei.noaa.gov/thredds-ocean/catalog/ncep/nww3/catalog.html). I will change the data source to verify if this issue persists.

**Comment by jcwarner-usgs** [comment]
maybe the periods need to be greater than 1?  not sure.
can you plot the periods?
how many tpar files do you have? 
if you remove them one at a time , you can figure out which file has the problem.
for example,

BOUND SHAPESPEC JONSWAP MEAN DSPR DEGREES
&BOUNDSPEC SEGMENT IJ  480    0  480   20 VARIABLE FILE 0 'myProject/mangkhut/TPAR1.txt'
BOUNDSPEC SEGMENT IJ  480   20  480   40 VARIABLE FILE 0 'myProject/mangkhut/TPAR2.txt'
BOUNDSPEC SEGMENT IJ  480   40  480   60 VARIABLE FILE 0 'myProject/mangkhut/TPAR3.txt'
BOUNDSPEC SEGMENT IJ  480   60  480   80 VARIABLE FILE 0 'myProject/mangkhut/TPAR4.txt'

would remove TPAR1, and see if that runs. if it still has that error then do
BOUND SHAPESPEC JONSWAP MEAN DSPR DEGREES
&BOUNDSPEC SEGMENT IJ  480    0  480   20 VARIABLE FILE 0 'myProject/mangkhut/TPAR1.txt'
&BOUNDSPEC SEGMENT IJ  480   20  480   40 VARIABLE FILE 0 'myProject/mangkhut/TPAR2.txt'
BOUNDSPEC SEGMENT IJ  480   40  480   60 VARIABLE FILE 0 'myProject/mangkhut/TPAR3.txt'
BOUNDSPEC SEGMENT IJ  480   60  480   80 VARIABLE FILE 0 'myProject/mangkhut/TPAR4.txt'

and see if that runs, etc.  tehn you can figure out which tpar file has the error.

**Comment by ZhangXYNUDT** [comment]
Thank you for your suggestion! I have figured out that the problem lies in TPAR12.txt and TPAR14.txt, but I haven’t been able to identify what’s wrong with them. Could you please take a look?
[TPAR12.txt](https://github.com/user-attachments/files/16982162/TPAR12.txt)
[TPAR14.txt](https://github.com/user-attachments/files/16982163/TPAR14.txt)

**Comment by jcwarner-usgs** [comment]
i am not sure.
are you still doing
COMPUTE STAT 20180914.000000

those lines in the files look ok
20180913.2100         0.73        7.40      48.       20
20180914.0000         0.70        13.50      61.       20
20180914.0300         0.66        16.59      70.       20

20180913.2100         0.78        16.60      68.       20
20180914.0000         0.73        16.59      68.       20
20180914.0300         0.70        16.58      68.       20

what if you did this
&BOUNDSPEC SEGMENT IJ   80    0  100    0 VARIABLE FILE 0 'myProject/mangkhut/TPAR12.txt'
BOUNDSPEC SEGMENT IJ  80    0  140    0 VARIABLE FILE 0 'myProject/mangkhut/TPAR13.txt'
&BOUNDSPEC SEGMENT IJ  120    0  140    0 VARIABLE FILE 0 'myProject/mangkhut/TPAR14.txt'

**Comment by ZhangXYNUDT** [comment]
If I remove TPAR12.txt and TPAR14.txt, there is no error.
&BOUNDSPEC SEGMENT IJ 80 0 100 0 VARIABLE FILE 0 'myProject/mangkhut/TPAR12.txt'
&BOUNDSPEC SEGMENT IJ 120 0 140 0 VARIABLE FILE 0 'myProject/mangkhut/TPAR14.txt'
I didn't find the reason. So I changed the expriment domain, and there was no error.
