### ISSUE TITLE
WRF+ROMS+SWAN run with 3 WRF grids, the last wrf grid is a moving grid, result in MCT gridsize mismach

### ISSUE THREAD

**Issue by gutw** [jcwarner-usgs/COAWST#321]
Recently, I run WRF+ROMS+SWAN through COAWST. WRF has 3 domains, with the last domain moving. However, I got the error, which shows 
'MCT::m_ExchangeMaps::ExGSMapGSMap_:: MCTERROR, Grid Size mismatch'. 

But when I use two WRF domains, which are both static, the model run normally. Could you know what's the reason? 

Thanks a lot!

Here are my relevant files.
[err.4691988.log](https://github.com/user-attachments/files/17151376/err.4691988.log)
[namelist.input.log](https://github.com/user-attachments/files/17151423/namelist.input.log)
[Trami_scrip.in.log](https://github.com/user-attachments/files/17151424/Trami_scrip.in.log)

**Comment by jcwarner-usgs** [comment]
not sure.
what does the stdout file look like?
what grids are this size: 101115 and 3537837?

**Comment by gutw** [comment]
> not sure. what does the stdout file look like? what grids are this size: 101115 and 3537837?

Thanks for your reply!
Here is my stdout file.
[out.4691988.log](https://github.com/user-attachments/files/17158315/out.4691988.log)

Here is scrip_coawst run log.
[scrip.out.4693686.log](https://github.com/user-attachments/files/17159581/scrip.out.4693686.log)

Here is weight file information.
[info.log](https://github.com/user-attachments/files/17158319/info.log)

The WRF domain's resolution of d01, d02, d03 is 15km, 5km, 1.67km respectively.
The size 101115 is wrfinput_d03 domain size, which is a moving grid.
The size 3537837 is nine times of wrfinput_d02 domain size 393093.

If I want to run WRF+ROMS+SWAN with WRF moving domain, are there any special settings in sandy.h which I did not edit before, or in namelist.input, ocean.in, swan.in?

**Comment by jcwarner-usgs** [comment]
did you compile WRF with the moving nest option?

**Comment by gutw** [comment]
> did you compile WRF with the moving nest option?

I recompiled the coupled model with the WRF moving nest option, and the coupled model ran smoothly with WRF moving grid.
Thanks a lot!

**Comment by jcwarner-usgs** [comment]
NICE !
