### ISSUE TITLE
 WRF+ROMS+SWAN run with ROMS and SWAN both have one grid, result in ROMS Found Error, can not find 'NGCNAME'.

### ISSUE THREAD

**Issue by gutw** [jcwarner-usgs/COAWST#322]
When I run WRF+ROMS+SWAN with ROMS and SWAN both have one grid, result in ROMS Found Error, can not find 'NGCNAME' in ocean.in. The NGCNAME file contains Nesting grids connectivity data: contact points information. However it is not needed and can not be povided in singal roms grid. I compiled COAWST with sandy.h. Could you know the reason?

Thanks a lot.

Here are relevant files.
[sandy.h.log](https://github.com/user-attachments/files/17151709/sandy.h.log)

**Comment by jcwarner-usgs** [comment]
you have 
#define NESTING
so that is telling roms and swan that you have more than 1 grid for each.
so then roms is looking for a connectivity file.

**Comment by gutw** [comment]
> you have #define NESTING so that is telling roms and swan that you have more than 1 grid for each. so then roms is looking for a connectivity file.

Thanks a lot! I will edit sandy.h with
#undef NESTING
and try to run again.

**Comment by gutw** [comment]
> > you have #define NESTING so that is telling roms and swan that you have more than 1 grid for each. so then roms is looking for a connectivity file.
> 
> Thanks a lot! I will edit sandy.h with #undef NESTING and try to run again.

I recompiled with #undef NESTING in sandy.h, and the coupled model ran smoothly with ROMS and SWAN both have one grid.
Thanks a lot!

**Comment by jcwarner-usgs** [comment]
NICE!
