### ISSUE TITLE
Compilation Error in COAWST: Syntax Error in module_sf_noahmp_glacier.f90

### ISSUE THREAD

**Issue by kirito2002** [jcwarner-usgs/COAWST#331]
Hello, I'm encountering a compilation error while building COAWST
[build.log](https://github.com/user-attachments/files/17609723/build.log)
[build2.log](https://github.com/user-attachments/files/17609724/build2.log)
Could you provide guidance on resolving the errors.
[build.log]: This log is from my custom project.h configuration.
[build2.log]: This log is from using the default joetc.h configuration.

**Comment by jcwarner-usgs** [comment]
in build log 2 i see

I/share/home/gaoyf/gaoyf_hec/COAWST/Build_roms  -I/share/home/gaoyf/gaoyf_hec/COAWST/Lib/MCT/1/include -real-size `expr 8 \* 4` -i4  module_sf_noahmp_glacier.f90
module_sf_noahmp_glacier.f90(23): error #5082: Syntax error, found '/' when expecting one of: => = . [ % ( :
noahmp/src/module_sf_noahmp_glacier.F
------^
module_sf_noahmp_glacier.f90(23): error #5082: Syntax error, found END-OF-FILE when expecting one of: <LABEL> <END-OF-STATEMENT> ; TYPE INTEGER REAL COMPLEX BYTE CHARACTER CLASS DOUBLE ...
noahmp/src/module_sf_noahmp_glacier.F
-------------------------------------^
module_sf_noahmp_glacier.f90(23): error #6793: The POINTER attribute is required.   [NOAHMP]
noahmp/src/module_sf_noahmp_glacier.F
^
compilation aborted for module_sf_noahmp_glacier.f90 (code 1)

there is something wrong with a WRF file.
can you see if that file has been updated in a newer version of WRF?

**Comment by kirito2002** [comment]
Thank you for your response.I found the module_sf_noahmp_glacier.F file in the noahmp/src/ directory, and it hasn't been updated—it’s still the same version from 2 years ago. @jcwarner-usgs

**Comment by kirito2002** [comment]
After replacing the source files in the WRF directory, I successfully compiled coawstM. Although the log 
[build4.log](https://github.com/user-attachments/files/17613745/build4.log)
still shows an ignored error for undefined reference to MAIN__ [em_wrf] Error 1 (ignored), from what I understand, this should be normal, and the compilation was likely successful. Thank you for your assistance! @jcwarner-usgs 

I noticed that build_coawst.sh includes commands to compile WRF-Hydro, so I’m assuming I need to add #define WRFHYDRO in the .h configuration file and place the WRF-Hydro source files in the /WRF/hydro_v5.0 directory. Do you have any recommendations or a tutorial for setting up WRF-Hydro within COAWST?

**Comment by jcwarner-usgs** [comment]
for_main.c:(.text+0x2a): undefined reference to `MAIN__'
0.69user 0.49system 0:01.60elapsed 74%CPU (0avgtext+0avgdata 123264maxresident)k
0inputs+144outputs (0major+87199minor)pagefaults 0swaps
make[2]: [em_wrf] Error 1 (ignored)

yes you can ignore that one.  i dont let wrf compile wrf.exe.

did you get a coawstM?  if so, then the build worked.

the wrf_hydro coupling is not fully functional yet in the current distribution.  that will be updated soon.
