### ISSUE TITLE
Calculation of Stokes Drift Velocity in ROMS

### ISSUE THREAD

**Issue by hgengqi** [jcwarner-usgs/COAWST#335]
I would like to know how ROMS calculates the Stokes drift velocity, in which subroutine it is calculated, as I couldn't find relevant information on the ROMS official website.I would greatly appreciate any guidance or assistance on this matter. Thank you in advance for your help!

**Comment by jcwarner-usgs** [comment]
ROMS/Nonlinear/Wec/wec_stokes.F
