### ISSUE TITLE
error running ROMS-WW3

### ISSUE THREAD

**Issue by jackjhz1321** [jcwarner-usgs/COAWST#340]
Hi all,
I got a problem running the coupled ROMS-WW3 model. The models with just ROMS or WW3 were running fine, but once I coupled them, I got the following error:

 *** WAVEWATCH III ERROR IN W3FLDG : 
     ERROR IN READING TIME, IOSTAT =    29

Anyone know what was causing this? Thank you!

Jiahua

FYI, I have attached the input files and the log, all converted to txt format so that I can attached them here.
[coupling_gulfstr.txt](https://github.com/user-attachments/files/18121547/coupling_gulfstr.txt)
[ocean_gs.txt](https://github.com/user-attachments/files/18121549/ocean_gs.txt)
[output.txt](https://github.com/user-attachments/files/18121550/output.txt)
[ww3_grid.txt](https://github.com/user-attachments/files/18121551/ww3_grid.txt)
[ww3_prep.txt](https://github.com/user-attachments/files/18121552/ww3_prep.txt)
[ww3_shel.txt](https://github.com/user-attachments/files/18121553/ww3_shel.txt)
[ww3_strt.txt](https://github.com/user-attachments/files/18121554/ww3_strt.txt)

**Comment by jcwarner-usgs** [comment]
Ok.  i have a lot of this explained in teh user manual.  section 11.
Are you using 2 roms + 2 ww3 grids, all structured?
please read the manual, there are many steps.

You need to set ww3_grid for grid 1 and run:
ww3_grid
ww3_strt
ww3_prep
 then 
cp mod_def.ww3 to mod_def.grd1
cp wind.ww3 to wind.grd1
cp restart.ww3 to restart.grd1

The you need to set ww3_grid for grid 2 and run:
ww3_grid
ww3_strt
ww3_prep
 then 
cp mod_def.ww3 to mod_def.grd2
cp wind.ww3 to wind.grd2
cp restart.ww3 to restart.grd2

Then you need to create a ww3_multi.inp and use the ww3_multi.inp in the coupling.in
can you try all that?

-j

**Comment by jackjhz1321** [comment]
Hi John,
Thank you for your reply. 

I decided to go back and run the sandy example and end up with the same problem. So I looked at the compiling log carefully and realized there was some "permission declined" issues. But somehow it still produced the coawstM which made me think that the compilation was successful. 

Anyway, I fixed that, and now the compilation would fail due to the following error:

      32 errors found, see /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/tmp/cwstwvcp.err
      *** compile error ***
          file cwstwvcp.o not found
make[1]: *** [makefile:858: /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/obj/cwstwvcp.o] Error 5

As instructed, I looked at the cwstwvcp.err. It contained a lot of errors with the first one as follow :

ifort: command line warning #10121: overriding '-xhost' with '-xhost'
cwstwvcp.F90(343): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MCT_COUPLER_PARAMS]
      USE MCT_COUPLER_PARAMS
----------^

It seemed like the program could not found mct_coupler_params. I checked that the mct_coupler_params.mod indeed was created in the $SCRATCH_DIR directory. 

When you have time, could you give me help on this? I have attached the compilation log file (log3.txt), coawst_build.bash, cwstwcp.err, and sandy.h for your reference.

Some additional information that may not be helpful:

I tried to copy the mct_coupler_params.mod and mct_coupler_kinds.mod to the MCT_INCDIR directory where all the m_*.mod files located. Now the compilation would fail due to:

ad3 : processing cwstwvcp 
ad3 : processing w3initmd 
      1 warnings found, see /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/tmp/cwstwvcp.out
ad3 : processing w3wavemd 
      1 warnings found, see /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/tmp/w3initmd.out
      1 warnings found, see /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/tmp/w3wavemd.out
ad3 : processing ww3_shel 
      1 warnings found, see /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/tmp/ww3_shel.out
      Linking ww3_shel
link with coawst
jcw Your link settings are ar -rv libWW3.a   ww3_shel.o wmmdatmd.o w3gdatmd.o w3wdatmd.o w3adatmd.o w3idatmd.o w3odatmd.o w3fldsmd.o w3initmd.o w3wavemd.o w3wdasmd.o w3updtmd.o w3profsmd.o w3pro3md.o w3uqckmd.o w3triamd.o w3srcemd.o w3flx1md.o w3sln1md.o w3src4md.o w3snl1md.o w3sbt4md.o w3sic2md.o w3sis2md.o w3sdb1md.o w3ref1md.o w3gig1md.o w3canomd.o w3parall.o w3iogrmd.o w3iogomd.o w3iopomd.o w3iotrmd.o w3iorsmd.o w3iobcmd.o cwstwvcp.o w3iosfmd.o w3partmd.o constants.o w3servmd.o w3timemd.o w3tidemd.o w3arrymd.o w3dispmd.o w3cspcmd.o w3gsrumd.o w3nmlshelmd.o  /libmct.a /libmpeu.a 
make[1]: *** [makefile:158: /gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/exe/ww3_shel] Error 1
make[1]: Leaving directory '/gpfs/research/coaps/jzhou/MODELS/COAWST_xc/WW3/model/ftn'

-------- Finished compiling WW3 ---------

So, I guess I need to do something else to get it correctly compiled.

Thank you!
Jiahua

[coawst_build.txt](https://github.com/user-attachments/files/18141744/coawst_build.txt)
[cwstwvcp.txt](https://github.com/user-attachments/files/18141745/cwstwvcp.txt)
[log3.txt](https://github.com/user-attachments/files/18141746/log3.txt)
[sandy.txt](https://github.com/user-attachments/files/18141747/sandy.txt)
---

**Comment by jcwarner-usgs** [comment]
can you use the more recent version of code?
you are using an older version.
please update to v3.8 and try again.
-j

**Comment by jackjhz1321** [comment]
Hi John,
Thanks again. I tried the v3.8 WW3-only compilation today and got an error as follow:

/gpfs/research/software/intel-oneapiHPC-2021.2/compiler/2021.2.0/linux/bin/intel64/ifort -Wl,-rpath -Wl,/opt/rcc/intel/lib64 -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/opt/rcc/intel/openmpi/lib64 -Wl,--enable-new-dtags -L/opt/rcc/intel/lib64 -L/usr/lib64 -O3 CMakeFiles/ww3_prtide.dir/ww3_prtide.F90.o -o ../../bin/ww3_prtide  -Wl,-rpath,/opt/rcc/intel/openmpi/lib64: ../../lib/libww3.a /opt/rcc/intel/openmpi/lib64/libnetcdff.so -L/opt/rcc/intel/lib64 -lnetcdff /opt/rcc/intel/openmpi/lib64/libnetcdf.so -L/opt/rcc/intel/lib64 -lnetcdf /opt/rcc/intel/openmpi/lib64/libmpi_usempif08.so /opt/rcc/intel/openmpi/lib64/libmpi_usempi_ignore_tkr.so /opt/rcc/intel/openmpi/lib64/libmpi_mpifh.so /opt/rcc/intel/openmpi/lib64/libmpi.so /gpfs/research/coaps/jzhou/Projects/sandy/build_roms_ww3/Build_ww3/mct_coupler_params.o -L/gpfs/research/coaps/jzhou/MODELS/COAWST_20241213/Lib/MCT/lib -lmct -lmpeu 
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_dxpl_mpio'
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_fapl_mpio'
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_all_coll_metadata_ops'
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_coll_metadata_write'
make[3]: *** [model/src/CMakeFiles/ww3_prtide.dir/build.make:107: bin/ww3_prtide] Error 1

It seemed like the program could not found the HDF5. This error occurred no matter if I set USE_HDF5 = on or not. 

I have attached the build_coawst.sh, my_build_paths.sh, compilation log, switch_sandy
, and coawst makefile for your reference. For the coawst makefile, I added "-DCMAKE_Fortran_COMPILER=ifort" to line 708, otherwise it would look for the gfortran compiler even though I set FORT=ifort in the build_coawst.sh.

[log_ww3.txt](https://github.com/user-attachments/files/18154777/log_ww3.txt)
[makefile.txt](https://github.com/user-attachments/files/18154778/makefile.txt)
[my_build_paths.txt](https://github.com/user-attachments/files/18154779/my_build_paths.txt)
[sandy_ww3.txt](https://github.com/user-attachments/files/18154780/sandy_ww3.txt)
[switch_sandy.txt](https://github.com/user-attachments/files/18154781/switch_sandy.txt)


Jiahua

**Comment by jackjhz1321** [comment]
Sorry I forgot to attach the build_coawst_ww3.sh. Here it is.
[build_coawst_ww3.txt](https://github.com/user-attachments/files/18154934/build_coawst_ww3.txt)
Jiahua

**Comment by jcwarner-usgs** [comment]
why do you do this:
#export USE_MY_LIBS=no            # use system default library paths
export USE_MY_LIBS=yes           # use my customized library paths

the error i see is 
/opt/rcc/intel/hdf5-1.10.4/lib64: file not recognized: Is a directory
make: *** [Master/Module.mk:23: /gpfs/research/coaps/jzhou/Projects/sandy/build_roms_ww3/coawstM] Error 1

this is coming from the link that has, in part
... -L/opt/rcc/intel/hdf5-1.10.4/lib64 /opt/rcc/intel/hdf5-1.10.4/lib64 ...

i think this is coming from the Compilers/Linux-ifort.mk
             LIBS += -L$(HDF5_LIBDIR) $(HDF5_LIBS)

did  you modify the Compilers file?

what if you set
USE_HDF5=
just keep it blank

-j

**Comment by jackjhz1321** [comment]
Hi John,
I was using the manually set paths because my MCT was not installed in the default directory. So, I need to set the MCT_INCDIR and MCT_LIBDIR manually. I also set the MPI_ROOT, NETCDF paths,  HDF5_LIBDIR and HDF5_INCDIR here to point to the correct directory. 

I did not change the Linux-ifort.mk file.

Compiling with "USE_HDF5=" will create a coawstM file, but in the log, it still said:

/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_dxpl_mpio'
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_fapl_mpio'
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_all_coll_metadata_ops'
/opt/rcc/intel/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_coll_metadata_write'
make[3]: *** [model/src/CMakeFiles/ww3_prtide.dir/build.make:107: bin/ww3_prtide] Error 1

With this compilation, the WW3 utilities (ww3_grid, etc.) was not found in the WW3/build/bin directory. The directory is empty.

Attached is the compile log with "USE_HDF5=".

Thank you for keep trying to help me!
[log_ww3_nohdf5.txt](https://github.com/user-attachments/files/18157367/log_ww3_nohdf5.txt)

Jiahua

**Comment by jcwarner-usgs** [comment]
H5Pset_dxpl_mpio' is for parallel IO.
That is cmake looking for the libs.

what if you did not use
 "-DCMAKE_Fortran_COMPILER=ifort"  and you allow cmake to use gfortran.
and in the build_coawst you set FORT=gfortran.

**Comment by jackjhz1321** [comment]
Hi John,
I tried to compile with gfortran, but the same error occurred:

/opt/rcc/gnu/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_dxpl_mpio'
/opt/rcc/gnu/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_fapl_mpio'
/opt/rcc/gnu/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_all_coll_metadata_ops'
/opt/rcc/gnu/openmpi/lib64/libnetcdf.so: undefined reference to `H5Pset_coll_metadata_write'
collect2: error: ld returned 1 exit status
make[3]: *** [model/src/CMakeFiles/ww3_prtide.dir/build.make:107: bin/ww3_prtide] Error 1

It seemed like the WW3 would like to use this 'H5Pset_dxpl_mpio' no matter what I set in the build_coawst.sh. Is there a way to give WW3 the path to the library? Which library is it trying to find?

Attached is the updated build_coawst.sh, my_build_paths.sh, and compile log.

Thank you for your time!
[build_coawst_ww3.txt](https://github.com/user-attachments/files/18168344/build_coawst_ww3.txt)
[log_gfortran.txt](https://github.com/user-attachments/files/18168345/log_gfortran.txt)
[my_build_paths.txt](https://github.com/user-attachments/files/18168346/my_build_paths.txt)

Jiahua

**Comment by jackjhz1321** [comment]
Hi John,
I would like to provide some update about the hdf5 issue. I think I have solved it by doing the following:

1. Add 	
                set(HDF5_ROOT "/opt/rcc/gnu/openmpi/")
	        find_package(HDF5 REQUIRED COMPONENTS Fortran)
   after 
               find_package(NetCDF REQUIRED COMPONENTS Fortran)
   in the CMakeLists.txt. 

2. Also in CMakeLists.txt, add
              target_link_libraries(ww3_lib PUBLIC HDF5::HDF5)
   after 
              target_link_libraries(ww3_lib PUBLIC NetCDF::NetCDF_Fortran)

I think these modification had linked the correct hdf5 library to the program, and the previous error indeed disappeared. But now I got a new error when compiling:

/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o: In function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[3]: *** [model/src/CMakeFiles/ww3_shel.dir/build.make:109: bin/ww3_shel] Error 1

I have attached here the modified CMakeLists.txt, and the new compile log for your reference.
[CMakeLists.txt](https://github.com/user-attachments/files/18170975/CMakeLists.txt)
[log_gfortran.txt](https://github.com/user-attachments/files/18170976/log_gfortran.txt)

Jiahua

**Comment by jcwarner-usgs** [comment]
ok. glad you got past the HDF5 issues.
Dont worry about the 'undef ref to main' issue.  That occurs because i dont let WW3 compile their exe.  I only allow ww3 to make a library.
Did you get the exes in WW3/build/bin ?

The error you have now is still the same as before:
/opt/rcc/gnu/hdf5-1.10.4/lib64: file not recognized: Is a directory
collect2: error: ld returned 1 exit status

that is coming from the list of Libs:
" -L/gpfs/research/coaps/jzhou/Projects/sandy/build_roms_ww3/Build_ww3 -lROMS  -L/opt/rcc/gnu/openmpi/lib64 -lnetcdff 
-L/opt/rcc/gnu/openmpi/lib64    /opt/rcc/gnu/hdf5-1.10.4/lib64 /gpfs/research/coaps/jzhou/Projects/sandy/build_roms_ww3/Build_ww3/mct_coupler_params.o "

there is a section in there    "/opt/rcc/gnu/hdf5-1.10.4/lib64 "  that either needs to go away, or needs  a '-L' in front of it.

**Comment by jackjhz1321** [comment]
Hi John
I figured out the "/opt/rcc/gnu/hdf5-1.10.4/lib64 is a directory" error can be resolved by unloading the module hdf5 on my HPC before compiling the MCT. However, I don't know the underlining rationale. It could be that loading the module overwrites the HDF5_LIBS variable.

But anyway, the coupled ROMS-WW3 model is now running for me. Thank you so much for your help!

Jiahua

**Comment by jcwarner-usgs** [comment]
nice !
