### ISSUE TITLE
COAWST compilation error when coupling ROMS with other models

### ISSUE THREAD

**Issue by shestakova-aa-92** [jcwarner-usgs/COAWST#57]
I am a COAWST user. I have successfully compiled and run different WRF+SWAN applications.
However, now I am stuck on the adding of the ROMS model.
When compiling WRF+SWAN+ROMS applications (my own as well as SANDY and JOE_TC) I have the following error:
`ocean_coupler.f90:1969:46:

      &                          OCN_COMM_WORLD)
                                              1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:1729:46:

      &                          OCN_COMM_WORLD)
                                              1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:1545:42:

      &                      OCN_COMM_WORLD, Router_A(ng,ia)%ROMStoWRF)
                                          1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:1402:40:

       CALL mpi_comm_rank (OCN_COMM_WORLD, MyRank, MyError)
                                        1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:935:26:

      &      OCN_COMM_WORLD)
                          1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:596:26:

      &      OCN_COMM_WORLD)
                          1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type
ocean_coupler.f90:405:42:

      &                      OCN_COMM_WORLD, Router_W(ng,iw)%ROMStoSWAN)
                                          1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:186:55:

         CALL MCTWorld_init (N_mctmodels, MPI_COMM_WORLD,                &
                                                       1
Error: Symbol ‘mpi_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
ocean_coupler.f90:174:40:

       CALL mpi_comm_rank (OCN_COMM_WORLD, MyRank, MyError)
                                        1
Error: Symbol ‘ocn_comm_world’ at (1) has no IMPLICIT type; did you mean ‘atm_comm_world’?
make: *** [Master/Module.mk:25: Build/ocean_coupler.o] Error 1 `

There were no other errors during compilation.

When compiling ROMS-only application, compilation succeeds.

What can be the reason of this error? It could be an mpi-related error, but why then SWAN+WRF were successfully coupled?

I have gfortran compiler v 3.8.0 and openMPI v 4.1.0. My compiler file and coawst.bash are attached.

--Anna

[Linux-gfortran.txt](https://github.com/jcwarner-usgs/COAWST/files/7421547/Linux-gfortran.txt
[coawst_bash.txt](https://github.com/jcwarner-usgs/COAWST/files/7421549/coawst_bash.txt)
[log.txt](https://github.com/jcwarner-usgs/COAWST/files/7421553/log.txt)
)

**Comment by jcwarner-usgs** [comment]
not sure why that is happening.  did you get the code from this github site?
can you send the file Build/ocean_coupler.f90
thanks
j

**Comment by shestakova-aa-92** [comment]
Yes, I downloaded the code from this site. 
Here is the ocean_coupler.f90
[ocean_coupler.txt](https://github.com/jcwarner-usgs/COAWST/files/7446412/ocean_coupler.txt)

**Comment by jcwarner-usgs** [comment]
i just grabbed the most recent version and set it to compile JOE_TC and it worked fine.
so i am still puzzled.

the error says ocn_comm_world’ at (1) has no implicit type.
but  the ocean_coupler.f90 has
      USE mod_parallel

if you look in Build/mod_parallel.f90 do you see
!
!  Distributed-memory group communicator handles.
!
      integer :: OCN_COMM_WORLD             ! internal ROMS communicator
!
?

 I think i see the answer.  did you change
         CPPFLAGS += -DMPI
to
         CPPFLAGS += -DMPI2_SUPPORT
?? 
 put it back for ROMS to just be -DMPI, and then that will activate the ocn_comm_world in mod_parallel.

**Comment by shestakova-aa-92** [comment]
Thank you very much, John! 
I changed CPPFLAGS as you suggested and COAWST has compiled successfully!
