### ISSUE TITLE
Issues of HYCOM datasets 

### ISSUE THREAD

**Issue by nuist2284494698** [jcwarner-usgs/COAWST#58]
I want to make a simulation on th TC " Yan Hua" in the year of 2021. However, there is no data of HYCOM in this year, how can I make bdy and ini file that can feed to the COAWST model.

**Comment by jcwarner-usgs** [comment]
can you look around here:
https://www.hycom.org/dataserver/

**Comment by nuist2284494698** [comment]
Thanks for your reply. Yes，I have looked through this website of HYCOM，but failed to find the global data in 2021，it is missing data.
So，is there any other dataset and codes to create ini，bdy and cli file to feed to the COAWST model. Thanks in advance and looking forward to hearing from you.





发自我的iPhone


------------------ Original ------------------
From: john warner ***@***.***&gt;
Date: Fri,Oct 29,2021 3:20 AM
To: jcwarner-usgs/COAWST ***@***.***&gt;
Cc: nuist2284494698 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jcwarner-usgs/COAWST] Issues of HYCOM datasets  (Issue #58)





 
can you look around here:
 https://www.hycom.org/dataserver/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jcwarner-usgs** [comment]
what is in here
https://tds.hycom.org/thredds/catalogs/GLBy0.08/expt_93.0.html
then click on
GLBy0.08 expt 93.0 ssh ts3z uv3z ...
https://tds.hycom.org/thredds/catalogs/GLBy0.08/expt_93.0.html?dataset=GLBy0.08-expt_93.0

**Comment by nuist2284494698** [comment]
Thanks, john. I have also found the website as you provided and successfully created  the  ini, cli , bdy file to the Roms model.  Thanks a lot for your assistance again.
