### ISSUE TITLE
Boundary condition for ROMS model

### ISSUE THREAD

**Issue by Ntmanh18196** [jcwarner-usgs/COAWST#59]
Hi John,
I have a question related to the BCs in ROMS model. I've attached my domain and my BCs  set-up for ROMS:
   LBC(isFsur) ==   Clo    Cha    Cha    Cha        ! free-surface
   LBC(isUbar) ==   Clo    Fla    Fla    Fla            ! 2D U-momentum
   LBC(isVbar) ==   Clo    Fla    Fla    Fla            ! 2D V-momentum
   LBC(isUvel) ==   Clo RadNud RadNud RadNud        ! 3D U-momentum
   LBC(isVvel) ==   Clo RadNud RadNud RadNud        ! 3D V-momentum
   LBC(isMtke) ==   Clo     Gra    Gra    Gra        ! mixing TKE

   LBC(isTvar) ==   Clo RadNud RadNud RadNud \       ! temperature
                             Clo RadNud RadNud RadNud         ! salinity

Can you kindly help to define the reasonable option for my domain? I have tried change my vertical level and transformation equation, stretching function but the intensity of TC isn't better.
Thank you very much!
![domain](https://user-images.githubusercontent.com/38093402/140002148-a7e9ac62-a60a-420b-b6c0-8e975b9d8749.png)

**Comment by jcwarner-usgs** [comment]
i would assume that the intensity of a TC is not so much dependent on the ROMS open boundaries. the intensity would be more dependent on the atm-ocn fluxes and the ocean SST.

**Comment by Ntmanh18196** [comment]
Dear Dr. John,
I have used the initial condition (wrfinput file) from WRF-CTRL (with SST updating option) for running the COAWST model. Despite the fact that the SST values at the initial time from 2 models are equal, the SST output from the COAWST model is becoming smaller than that of the WRF model (as you can see in the below figures).
I have changed the vertical number levels of the ROMS model from 30 to 36, 42 but it seems not effective.
Can you give me some suggestions to reduce the cooler SST value in the COAWST model?
Thank you very much!




![couple_12Z02NOV2017_1](https://user-images.githubusercontent.com/38093402/144535984-89260405-7b8a-4999-b80b-7f27818de5af.png)
![couple_21Z03NOV2017_34](https://user-images.githubusercontent.com/38093402/144535991-44f852af-a394-4e7d-a138-cc3b824be5ca.png)
![sst_damrey_CTL_12Z02NOV2017_1](https://user-images.githubusercontent.com/38093402/144536006-e120a3f6-6caf-43e6-bf3c-e67e7c0e3fd8.png)
![sst_damrey_CTL_21Z03NOV2017_34](https://user-images.githubusercontent.com/38093402/144536009-7f00b2bf-ca57-4aaf-8726-1938d1c8c5c7.png)

**Comment by jcwarner-usgs** [comment]
do you have ATM2OCN_FLUXES turned on?
can you look at the surface heat fluxes to see how they compare to non-coupled run? 
GSW GLW LH HFX
USTRESS VSTRESS

**Comment by Ntmanh18196** [comment]
Dear Dr. John,
Thank you for your reply. 
According to your suggestion, I have compared the LH and HFX value from coupled and control run, the results show that the values from the coupled case are significantly smaller than that of control one (as you can see in the figures below).
Besides, I did turn on the #define ATM2OCN_FLUXES option in my project.h file, the detail of this set-up is that:
# ifdef WRF_MODEL
#  undef  BULK_FLUXES
#  define ATM2OCN_FLUXES
#  undef  ANA_SSFLUX
#  undef  LONGWAVE_OUT
# else
#  define BULK_FLUXES
# endif
# define ANA_NUDGCOEF
# define ATM_PRESS
# define ANA_BTFLUX
# define ANA_BSFLUX
# define ANA_BPFLUX
# define ANA_SPFLUX
# define ANA_SRFLUX
# define EMINUSP
# define SOLAR_SOURCE
Lh from Coawst
![lh_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/144701184-eaf5a448-83f5-4451-bea7-0f0e7251ce32.png)
hfx from Coawst
![hfx_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/144701191-0ad7d674-db26-46b4-8eb7-31354f5cee6e.png)
glw from Coawst 
![glw_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/144701195-fd8d4c91-188c-4d1e-b105-4b5062b467db.png)
Lh from WRF-control
![lh_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/144701203-00d58eeb-2a0d-4305-8c34-b47af4708787.png)
Hfx from WRF-control
![hfx_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/144701213-882c8215-cead-4609-b7b9-012510460784.png)
Glw from WRF-control
![glw_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/144701218-2b3c3469-2880-4227-babd-0f1218ac050b.png)

**Comment by Ntmanh18196** [comment]
Hi John,
I have changed the stretching function option from 2 to 5, and the theta_s, theta_b as well, but it did not make the intensity of the typhoon stronger.
Do you have any suggestions to address this problem?
Thank you very much!

**Comment by jcwarner-usgs** [comment]
maybe you could undef atm2ocn fluxes, and use bulk fluxes, compare the different heat flux contributions, and this might lead to a better understanding of what is going on.

**Comment by Ntmanh18196** [comment]
Dear Dr. John,
Thank you for your suggestion. I will recompile the model and try running model with the bulk fluxes option.

**Comment by Ntmanh18196** [comment]
Dear Dr. John,
I have recompiled the coawst model with define bulk fluxes and undef atm2ocn fluxes option, however LH, HFX and  LONG WAVE FLUX are weaker than that of CTRL run.
My CPP option is that:
`# ifdef WRF_MODEL
#  define  BULK_FLUXES
#  undef ATM2OCN_FLUXES
#  define  ANA_SSFLUX
#  define  LONGWAVE_OUT
# else
#  define BULK_FLUXES
# endif
# define ANA_NUDGCOEF
# define ATM_PRESS
# define ANA_BTFLUX
# define ANA_BSFLUX
# define ANA_BPFLUX
# define ANA_SPFLUX
# define ANA_SRFLUX
# define EMINUSP
# define SOLAR_SOURCE`
SENSIBLE HEAT FLUX 
![hfx_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/146633804-73c61ce6-1826-4e03-a98f-6dc23dedeaa7.png)
LATENT HEAT FLUX
![lh_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/146633805-a18e7738-277b-4bac-9722-7d6f597a54ef.png)
DOWNWARD LONG WAVE FLUX AT GROUND SURFACE
![glw_21Z03NOV2017](https://user-images.githubusercontent.com/38093402/146633802-35e4fd8e-cafd-4cff-b1f6-7e5214612b17.png)
