### ISSUE TITLE
How to change the wave roughness parameterizations 

### ISSUE THREAD

**Issue by Ntmanh18196** [jcwarner-usgs/COAWST#60]
Hi John,
I have read your research related to the wave roughness parameterizations from Taylor and Yelland (2001), Drennan et al. (2005), and Oost et al. (2002) to the WRF surface physics schemes. 
With my knowledge of WRF model, these scheme aren't included in the namelist option. 
Can you kindly help me how to apply these scheme for WRF model.
Thank you very much!

**Comment by jcwarner-usgs** [comment]
We have these coded into the WRF version in COAWST.  You can activate these options with the cppdefs.  The Sandy test case has some of these, you can look in the manual on page 10. you would need to set one of these:

#define COARE_TAYLOR_YELLAND 
Taylor, P. K., and M. A. Yelland, 2001: The dependence of sea surface roughness on the height and steepness of the waves. J. Phys. Oceanogr., 31, 572-590.

#define COARE_OOST
Oost, W. A., G. J. Komen, C. M. J. Jacobs, and C. van Oort, 2002:New evidence for a relation between wind stress and wave age from measurements during ASGAMAGE. Bound.-Layer Meteor., 103, 409-438.

#define DRENNAN
Drennan, W.M., P.K. Taylor and M.J. Yelland, 2005: Parameterizing the sea surface roughness. J. Phys. Oceanogr. 35, 835-848.

**Comment by Ntmanh18196** [comment]
Hi John,
Thank you for your reply.
Following your suggestion, I have successfully compiled the model with each sea surface roughness option by setting one of these schemes on the project.h file.
Thank you very much!
