### ISSUE TITLE
Make error with SCRIPT_COAWST

### ISSUE THREAD

**Issue by ljstella13** [jcwarner-usgs/COAWST#61]
I am trying to build SCRIP_COAWST following the instructions on the word document. I have changed my fortran compiler to gfortran. However I get the following issue:
f951: Fatal Error: Reading module ‘grids’ at line 1934 column 20: Unexpected EOF
compilation terminated.
make: *** [makefile:124: read_wrf.o] Error 1
Please find the output in buildoutput.txt attached.

**Comment by ljstella13** [comment]
For some reason I cannot add the file. The file reads:

/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/kinds_mod.f
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/constants.f
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/iounits.f
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/netcdf.f
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/scripwrap_mod.f
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/create_fullgrid.f
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/grids.f
/usr/bin/cpp -P -traditional -w               -DMPI  /home/leahs/COAWST/Lib/SCRIP_COAWST/read_swan.f  /home/leahs/COAWST/Lib/SCRIP_COAWST/read_swan.fpp
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/read_swan.fpp
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/read_ww3.f
/usr/bin/cpp -P -traditional -w               -DMPI  /home/leahs/COAWST/Lib/SCRIP_COAWST/read_roms.f  /home/leahs/COAWST/Lib/SCRIP_COAWST/read_roms.fpp
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/read_roms.fpp
/usr/bin/cpp -P -traditional -w               -DMPI  /home/leahs/COAWST/Lib/SCRIP_COAWST/read_wrf.f  /home/leahs/COAWST/Lib/SCRIP_COAWST/read_wrf.fpp
/usr/bin/mpif90 -frepack-arrays -O3 -ftree-vectorize -ftree-loop-linear -funroll-loops -w -ffree-form -ffree-line-length-none -frecord-marker=4 -fconvert=big-endian -I/usr/include -c /home/leahs/COAWST/Lib/SCRIP_COAWST/read_wrf.fpp

**Comment by jcwarner-usgs** [comment]
ok.  seems like you could not add the file.
can you email the file to me at
jcwarner@usgs.gov
does the file contain the full build.out?
also, if it had trouble with grid.f or grid.fpp, can you send those files also?
thansk
john

**Comment by SakuraLz** [comment]
Is there a solution to this problem, I also encountered this problem, I can't generate the script_coawst.exe file
[build.TXT](https://github.com/jcwarner-usgs/COAWST/files/8403680/build.TXT)
.

**Comment by jcwarner-usgs** [comment]
your executable is created here:
-o ./scrip_coawst

so it does not have a .exe on the end. do a
ls -ltr
and do you see
.....
-rw-rw-r-- 1 jwarner domain users 103960 Jan 10 2020 remap_write.o
-rw-rw-r-- 1 jwarner domain users 19413 Jan 10 2020 scrip.fpp
-rw-rw-r-- 1 jwarner domain users 20302 Jan 10 2020 scrip.mod
-rw-rw-r-- 1 jwarner domain users 32112 Jan 10 2020 scrip.o
-rw-rw-r-- 1 jwarner domain users 106457 Jan 10 2020 create_masks.fpp
-rw-rw-r-- 1 jwarner domain users 46241 Jan 10 2020 create_masks.mod
-rw-rw-r-- 1 jwarner domain users 276344 Jan 10 2020 create_masks.o
-rw-rw-r-- 1 jwarner domain users 7026 Jan 10 2020 scrip_coawst.fpp
-rw-rw-r-- 1 jwarner domain users 36296 Jan 10 2020 scrip_coawst.o
-rwxrwxr-x 1 jwarner domain users 1780472 Jan 10 2020 scrip_coawst

the 'x' means executable, and here it is just scrip_coawst

**Comment by occsail** [comment]
Hi again,
I'm trying to compile the scrip_coawst so I followed the manual and edited the makefile to specify ifort=gfortran and the file directory for the compiler.  However, when i tried make clean, I only get these:

/bin/rm *.o *.mod
/bin/rm: cannot remove '*.o': No such file or directory
/bin/rm: cannot remove '*.mod': No such file or directory
make: *** [makefile:187: clean] Error 1

Looks like nothing is being done, but I don't know what I missed.   Sorry for the bother, but help please.

**Comment by jcwarner-usgs** [comment]
ok, well try to just do the make, not clean.  since there is nothing to remove, it is having troubles. so just type

make
