### ISSUE TITLE
COAWST compilation error -- wec_vf.f90

### ISSUE THREAD

**Issue by xiaomei01** [jcwarner-usgs/COAWST#63]
Hi all,

I am trying to compile the Inlet_test case in the most recent version of  COAWST,  but when I run coawst.bash, I receive the following error message:

_wec_vf.f90(89): error #6460: This is not a field name that is defined in the encompassing structure.   [DISSIP_BREAK]
     &                            FORCES(ng) % Dissip_break,            &
-----------------------------------------------^
wec_vf.f90(90): error #6460: This is not a field name that is defined in the encompassing structure.   [DISSIP_WCAP]
     &                            FORCES(ng) % Dissip_wcap,             &
-----------------------------------------------^
wec_vf.f90(89): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [DISSIP_BREAK]
     &                            FORCES(ng) % Dissip_break,            &
-----------------------------------------------^
wec_vf.f90(90): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [DISSIP_WCAP]
     &                            FORCES(ng) % Dissip_wcap,             &
-----------------------------------------------^
compilation aborted for wec_vf.f90 (code 1)
make: *** [Build/wec_vf.o] Error 1_

The system operates on Red Hat  Linux, and I am using ifort, netCDF 4.4, openmpi.
Please let me know if I am overlooking something, or need to provide further information. 
Thank you for your assistance!

Regards,
xiaomei

**Comment by jcwarner-usgs** [comment]
i just downloaded a new version of code, and it compiled successfully for the inlet_test/coupled.
can you send the entire output of the build?
did you modify the coawst.bash or any other files?
thanks,
john

**Comment by xiaomei01** [comment]
Thank you so much. I rechecked my coawst.bash and found I made a mistake before. It compiles successfully now
