### ISSUE TITLE
Small significant wave height

### ISSUE THREAD

**Issue by xiaomei01** [jcwarner-usgs/COAWST#65]
Hello,

I am running a coupled ROMS-SWAN application. However, the significant wave height doesn’t change with the change of wind field (the largest wind speed is around 20 m/s). The wind input file I made from the ROMS forcing file (ECMWF) using the file named ncei_2swan.m.  I think there may be something wrong with the wind file, but I can't find it. Could you give me some suggestions?

Thank you 
xiaomei

![Hs at one station](https://user-images.githubusercontent.com/95325840/145169000-173ddb73-4e1d-47ef-80b2-d4acd847fc41.png)

**Comment by jcwarner-usgs** [comment]
ok, here are some things to look at.
what does Hwave look like spatially?
you can have swan write out the winds to a mat file, and then look at them.

**Comment by xiaomei01** [comment]
Thank you for your prompt reply.
I wrote out the winds to a netcdf file and found the winds are the same at different time. But the input wind file is not. 
I have attached the input (wind.dat), output (wind.nc) and swan.in.




Xiaomei Xu
Graduate student (Marine Geology)
Nanjing University
School of Geography and Ocean Science
163 Xianlin Avenue, Qixia District, Nanjing, China, 210023
Email: ***@***.***

           ***@***.*** 


On 12/8/2021 21:28，john ***@***.***> wrote：

ok, here are some things to look at.
what does Hwave look like spatially?
you can have swan write out the winds to a mat file, and then look at them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

从网易邮箱大师发来的云附件
wind.zip(163.0MB,2021年12月24日 17:8 到期)
下载

**Comment by jcwarner-usgs** [comment]
i did not get the attachments.
i do not want to look at the wind.nc and wind.dat, i can trust that you looked at them.
let me see what the swan.in file is.  if it does not come attached, you can just paste the contents of that file here.  it is only ~100 lines or so.

**Comment by xiaomei01** [comment]
OK, thank you.
I paste the contents of the swan.in below.


_PROJECT 'NYS' ' '
 'NYS'
 'Bathymetry: swan_bathy.bot'
 'COMMENTS'

MODE NONSTATIONARY TWODIMENSIONAL

SET DEPMIN 0.10 INRHOG 1 NAUTICAL
COORDINATES SPHERICAL

&& KEYWORD for number of nested SWAN grids.
NSGRIDS 1

&& KEYWORDS TO CREATE AND READ COMPUTATIONAL GRID &&
CGRID CURVILINEAR 301 381 EXC 9.999000e+003 &
        CIRCLE 36 0.04 1.0 24
READGRID COORDINATES 1 'swan_coord.grd' 4 0 0 FREE

&& KEYWORDS TO CREATE AND READ BATHYMETRY GRID &&
INPGRID BOTTOM CURVILINEAR 0 0 301 381 EXC 9.999000e+003        
READINP BOTTOM  1 'swan_bathy.bot' 4 0 FREE

&& KEYWORD TO CREATE CURRENT GRID &&
INPGRID CURRENT CURVILINEAR 0 0 301 381 EXC 9.999000e+003              &
        NONSTATIONARY  20201215.000000 31 DAY 20210115.000000

&& KEYWORD TO CREATE WATER LEVEL GRID &&
INPGRID WLEV CURVILINEAR 0 0 301 381 EXC 9.999000e+003                 &
        NONSTATIONARY  20201215.000000 31 DAY 20210115.000000

&& KEYWORD TO CREATE BOTTOM FRICTION GRID &&
INPGRID FRIC CURVILINEAR 0 0 301 381 EXC 9.999000e+003                 &
        NONSTATIONARY  20201215.000000 31 DAY 20210115.000000

&& KEYWORD TO CREATE WIND GRID &&
INPGRID WIND CURV 0. 0.  301 381 EXC -999 
READINP WIND 1 'swan_wind.dat' 4 0 FREE


&& BOUNDARY FORCING &&
BOUND SHAPESPEC JONSWAP MEAN DSPR DEGREES
BOUNDSPEC SEGMENT IJ 0 0 301 0 CONSTANT PAR 1.0 10.0 0. 20.
BOUNDSPEC SEGMENT IJ 301 0 301 381 CONSTANT PAR 1.0 10.0 0. 20.

 
& Restart name **********************************
&INIT HOTSTART 'swan_nys_rst.dat'

& PHYSICS  **************************************
GEN3
FRICTION MADSEN 0.05
&OFF QUAD

BLOCK 'COMPGRID' NOHEADER 'wind.nc'   LAY 4 WIND 1.   OUTPUT 20201215.000000 1 HR
BLOCK 'COMPGRID' NOHEADER 'hsig.nc'   LAY 4 HSIGN 1.    OUTPUT 20201215.000000 3 HR

POINTS  'point1' 5000.0 10000.0
SPECOUT 'point1' SPEC2D 'point1.spc2d' OUTPUT 20201215.000000 1 HR
TABLE   'point1' HEADER 'point1.table' HSIGN DIR DIRBOT WLEN OUTPUT 20201215.000000 3 HR

PROP BSBT
RESTART 'swan_nys_rst.dat' FREE 1 HR

COMPUTE NONSTATIONARY 20201215.000000 1200 SEC 20210115.000000

STOP_
