### ISSUE TITLE
Error to create the nested grid by using the coarse2fine program

### ISSUE THREAD

**Issue by Ntmanh18196** [jcwarner-usgs/COAWST#66]
Dear Dr. John,
I'm practicing to create the nested grid of ROMS model by using the coarse2fine program, however, I got the error when creating the second domain:
`>> run generate_roms_grid.m
ROMS domain 2 information is to be saved to ROMS_COAWST_grd2.nc

theWRFFile =

    'wrfinput_d02'

fid =

    -1

Error using fclose
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in nc_interface (line 99)
  fclose(fid);

Error in nc_getatt (line 61)
[method,~,~] = nc_interface(ncfile);

Error in nc_inq (line 69)
A = nc_getatt(ncfile);            % NetCDF file global attributes

Error in get_roms_grid (line 98)
  Ginfo = nc_inq(Ginp);

Error in coarse2fine (line 59)
C = get_roms_grid(Ginp);

Error in wrf2roms_mw_ref (line 26)
   coarse2fine(ParROMSFile,theROMSFile,eval(num2str(pgratio)),eval(num2str(pistart)),eval(num2str(piend)),eval(num2str(pjstart)),eval(n   str(pjend)))

Error in generate_roms_grid (line 123)
   [rho,projection] =
   wrf2roms_mw_ref(theWRFFile,theROMSFile,rlim,npass,order,mini_depth,bathy_source,mod_dom,corr_ocean_mask,num_passes)

Error in run (line 86)
evalin('caller', [script ';']);`
All of my controlling programs are attached in the below.
Please help me to address this issue.
[coarse2fine.m.txt](https://github.com/jcwarner-usgs/COAWST/files/7726484/coarse2fine.m.txt)
[generate_roms_grid.m.txt](https://github.com/jcwarner-usgs/COAWST/files/7726485/generate_roms_grid.m.txt)
[wrf2roms_mw_ref.m.txt](https://github.com/jcwarner-usgs/COAWST/files/7726486/wrf2roms_mw_ref.m.txt)

**Comment by jcwarner-usgs** [comment]
this looks like a series of wrapper codes that you wrote to start with a wrf grid  and then make a roms grid and a child roms grid. It looks like it will be useful. But i dont have the time to debug your code.
I suggest you take it step by step. 
it looks like you are using the wrf grid as a parent to create a roms child.
you first need to create a roms parent grid, then a roms child grid.

suggest you first just use the WRF grid to make a roms grid. that is wrf2roms_mw.
then use that roms grid to make a child grid.
suggest you do this step by step at the command line, then make a wrapper that does it all at once.
