### ISSUE TITLE
master.f90(22): error #7002: Error in opening the compiled module file. 

### ISSUE THREAD

**Issue by yanfeng7** [jcwarner-usgs/COAWST#68]
I tried to run the case JOE_TC by coupling the WRF and ROMS. When compiling COAWST and running the coawst.bash file, it always came up error like below. Can someone solve this problem? Thank you very much！

master.f90(22): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MODULE_WRF_TOP]
      USE module_wrf_top, ONLY : wrf_init
----------^
master.f90(22): error #6580: Name in only-list does not exist or is not accessible.   [WRF_INIT]
      USE module_wrf_top, ONLY : wrf_init
---------------------------------^
master.f90(23): error #6580: Name in only-list does not exist or is not accessible.   [WRF_RUN]
      USE module_wrf_top, ONLY : wrf_run
---------------------------------^
master.f90(24): error #6580: Name in only-list does not exist or is not accessible.   [WRF_FINALIZE]
      USE module_wrf_top, ONLY : wrf_finalize
---------------------------------^
compilation aborted for master.f90 (code 1)
make: *** [/home/yuxp/WORK/yf/coawst/COAWST-master/Build/master.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jcwarner-usgs** [comment]
there was most likely a problem before this one.
can you attach a file that has the entire build output?

**Comment by yanfeng7** [comment]
the entire build output has been written in the file below
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/7843200/coawst.txt)

**Comment by yanfeng7** [comment]
the entire build output has been written in the file below
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/7843258/coawst.txt)

**Comment by jcwarner-usgs** [comment]
i see a couple of issues.
1)  /home/yuxp/WORK/yf/coawst/build/software_library/openmpi/bin/mpif90 -c  -fastsse -Mipa=fast -Kieee -I/home/yuxp/WORK/yf/coawst/build/software_library/MCT/include -I/main -I/external/esmf_time_f90 -I/frame -I/share mct_coupler_params.f90;
ifort: command line warning #10006: ignoring unknown option '-fastsse'
ifort: command line warning #10006: ignoring unknown option '-Mipa=fast'

this is telling me that you might have set FORT = pgi in  coawst.bash, but your compiler is intel.  try to set FORT = ifort and see if that is the correct compiler for your mpif90.

2) i see 
/bin/sh: line 1: ./configure: Permission denied
 if you do an 
ls -ltr
in WRF/
do you have permissions to run that file?  or maybe you need to set it as an executable.
here is what i have:
 ls -ltr /vortexfs1/usgs/jwarner/models/COAWST/WRF/
drwxrwxr-x 19 jwarner domain users  4096 Mar 18  2020 test
-rwxrwxr-x  1 jwarner domain users  1143 Mar 18  2020 README.md
-rwxrwxr-x  1 jwarner domain users  1027 Mar 18  2020 LICENSE.txt
drwxrwxr-x 16 jwarner domain users  4096 Apr 27  2020 external
drwxrwxr-x 17 jwarner domain users  4096 Apr 27  2020 hydro_v5.0
-rwxrwxr-x  1 jwarner domain users 37163 May  6  2021 configure
-rwxrwxr-x  1 jwarner domain users  3385 May  6  2021 clean
drwxrwxr-x  2 jwarner domain users 12288 May  6  2021 phys
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 main
drwxrwxr-x 13 jwarner domain users  4096 May  6  2021 var
-rwxrwxr-x  1 jwarner domain users 20697 May  6  2021 compile
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 frame
-rwxrwxr-x  1 jwarner domain users 17648 May  6  2021 README
drwxrwxr-x  4 jwarner domain users  4096 May  6  2021 tools
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 dyn_nmm
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 share
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 run
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 doc
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 Registry
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 inc
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 dyn_em
drwxrwxr-x  3 jwarner domain users 12288 May  6  2021 chem
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 arch
-rwxrwxr-x  1 jwarner domain users 60005 May  6  2021 Makefile
drwxrwxr-x  2 jwarner domain users  4096 May  6  2021 wrftladj
drwxrwxr-x 19 jwarner domain users  4096 Nov  4 21:49 hydro

**Comment by yanfeng7** [comment]
after i set it as an executable, here is what i have. but i still have the problem, and the entire build output has been written in the file below. can you help me find some issues? thank you very much!
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/7844746/coawst.txt)

total 3584
drwxr-xr-x  2 yuxp users   4096 May 10  2021 wrftladj
drwxr-xr-x 13 yuxp users   4096 May 10  2021 var
drwxr-xr-x 19 yuxp users   4096 May 10  2021 test
-rw-r--r--  1 yuxp users   1143 May 10  2021 README.md
-rw-r--r--  1 yuxp users  17648 May 10  2021 README
-rw-r--r--  1 yuxp users  87521 May 10  2021 module_wrf_top.F
-rw-r--r--  1 yuxp users  60005 May 10  2021 Makefile
-rw-r--r--  1 yuxp users   1027 May 10  2021 LICENSE.txt
drwxr-xr-x 15 yuxp users   4096 May 10  2021 hydro_v5.0
drwxr-xr-x 13 yuxp users   4096 May 10  2021 hydro
drwxr-xr-x 16 yuxp users   4096 May 10  2021 external
drwxr-xr-x  2 yuxp users   4096 May 10  2021 dyn_nmm
drwxr-xr-x  2 yuxp users   4096 May 10  2021 doc
-rwxrwxrwx  1 yuxp users  37163 May 10  2021 configure
-rwxrwxrwx  1 yuxp users  20697 May 10  2021 compile
-rwxrwxrwx  1 yuxp users   3385 May 10  2021 clean
drwxr-xr-x  3 yuxp users 262144 May 10  2021 chem
drwxr-xr-x  2 yuxp users   4096 May 10  2021 arch
-rw-r--r--  1 yuxp users  21725 Jan 11 15:02 configure.wrf.backup
-rw-r--r--  1 yuxp users  21725 Jan 11 15:02 configure.wrf
drwxr-xr-x  4 yuxp users 262144 Jan 11 15:03 tools
drwxr-xr-x  2 yuxp users   4096 Jan 11 15:03 Registry
drwxr-xr-x  2 yuxp users 262144 Jan 11 15:03 inc
drwxr-xr-x  2 yuxp users 262144 Jan 11 15:10 phys
drwxr-xr-x  2 yuxp users 262144 Jan 11 15:10 frame
drwxr-xr-x  2 yuxp users 262144 Jan 11 15:10 dyn_em
drwxr-xr-x  2 yuxp users 262144 Jan 11 15:10 share
drwxr-xr-x  2 yuxp users   4096 Jan 11 15:10 main
drwxr-xr-x  2 yuxp users   4096 Jan 11 15:10 run

**Comment by jcwarner-usgs** [comment]
https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?t=9273

that has the same problem as you.  they suggest to update the compiler.

**Comment by yanfeng7** [comment]
i try to update the gcc to version 9.2.0, but it still has the same problem. could you help me find a way to solve this problem? thank you very much!
[coawst.txt](https://github.com/jcwarner-usgs/COAWST/files/7851600/coawst.txt)

**Comment by jcwarner-usgs** [comment]
i do see
./clean_kpp: Permission denied.
suggest you find where that is and change the permissions.
how did you get the code?  not sure why the permissions are changing on you.

here is what is happening.
mpif90 -f90=gfortran   -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4     -o module_internal_header_util.o -c module_internal_header_util.f

module_internal_header_util.f(12): error #5149: Illegal character in statement label field  [M]
MODULE module_internal_header_util
^
module_internal_header_util.f(12): error #5149: Illegal character in statement label field  [O]
MODULE module_internal_header_util
....

So gfortran is trying to compile the file module_internal_header_util.f but it starts to read that file and has an error. The error should not occur if the  -ffree-form is used, but for some reason the compiler is not seeing that flag.  

https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html

is there someone else there who can help you look at this?  are you compiling on a shared computer or your local desktop?
