### ISSUE TITLE
Sea ice in COAWST

### ISSUE THREAD

**Issue by shestakova-aa-92** [jcwarner-usgs/COAWST#71]
Hi John,
I have a question about sea ice in the COAWST. 
Is there any working vesrion of COAWST with the Budgell sea ice inside ROMS?
I found only stand-alone ROMS with ice.

Anna

**Comment by jcwarner-usgs** [comment]
Kate Hedstrom had a version with ice, but she does not support that anymore.
I think Rutgers is coupling roms with cice.

**Comment by shestakova-aa-92** [comment]
Thank you for the reply, John.
