### ISSUE TITLE
undefined reference to 'main' error when configure coawst. bash

### ISSUE THREAD

**Issue by dophine-liu** [jcwarner-usgs/COAWST#73]
Dear Dr. Warner,

I meet the error:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status

when I configure coawst.bash (WRF+SWAN).
It seems the error related to wrong link of netcdf, but no idea how to fix.  I attached my build.log here as well. 
I use gfortran and openmpi in configuration. 
Looking for your reply.
[build.log](https://github.com/jcwarner-usgs/COAWST/files/7956408/build.log)

**Comment by jcwarner-usgs** [comment]
there could be a lot of things that are going on.
i do not see that error in the log file, so maybe that was from a different build.
I do see 
"Warning: Nonexistent include directory "-I/main"
Warning: Nonexistent include directory "/external/esmf_time_f90"
Warning: Nonexistent include directory "/frame"
Warning: Nonexistent include directory "/share"
Warning: Nonexistent include directory "-I/main"
Warning: Nonexistent include directory "/external/esmf_time_f90"
Warning: Nonexistent include directory "/frame"
Warning: Nonexistent include directory "/share""


maybe you did not get the whole code correctly? can you try to get the code again.
suggest you start with something simple, like just wrf, or just swan, or roms only.
then try again.
keep me posted.
-j

**Comment by dophine-liu** [comment]
Thanks for your prompt reply.
I redownloaded the code and configured several modes. 
WRF only: ok (log file attached)
ROMS only: ok
SWAN only: ok
ROMS + SWAN: ok (log file attached. I am not so familiar with ROMS/SWAN, seems configuration successful as coawstM was generated. Correct me if I am wrong.)
WRF + ROMS/SWAN: failed. (log file attached)
And the error came at the same point. 

My setting for WRF+SWAN was as below: 
#undef ROMS_MODEL
#undef NESTING
#define WRF_MODEL
#define SWAN_MODEL
#undef  WW3_MODEL
#define MCT_LIB
#undef MCT_INTERP_OC2AT
#define MCT_INTERP_WV2AT
#undef MCT_INTERP_OC2WV


[build_swan_roms.log](https://github.com/jcwarner-usgs/COAWST/files/7993632/build_swan_roms.log)

[build_wrf_swan.log](https://github.com/jcwarner-usgs/COAWST/files/7993630/build_wrf_swan.log)

[build_wrf.log](https://github.com/jcwarner-usgs/COAWST/files/7993628/build_wrf.log)

**Comment by jcwarner-usgs** [comment]
did you attach the
"WRF + ROMS/SWAN: failed. (log file attached)"
i see 3 attachments for the wrf, swan+roms, and wrf+swan.
-j

**Comment by dophine-liu** [comment]
Hi I mean WRF+ROMS and WRF+SWAN both failed.
I uploaded both log files here.

[build_wrf_roms.log](https://github.com/jcwarner-usgs/COAWST/files/7996440/build_wrf_roms.log)
[build_wrf_swan.log](https://github.com/jcwarner-usgs/COAWST/files/7996443/build_wrf_swan.log)

**Comment by jcwarner-usgs** [comment]
ok.  pick a WRF compile number that only has dm (distributed memory = MPI).  The coupled system works with MPI (and that is DM).  The coupled system does not work with sm (shared memory = OpenMP ).
you selected 35 and that is dm+sm
try 34 and see if that works.
-j

**Comment by dophine-liu** [comment]
Thanks for your advise. It works! 
Although still show same error in the log file, it generated coawstM file and generated ndown.exe, real.exe, tc.exe in WRF/main (without wrf.exe). Think I have configured successfully?

**Comment by jcwarner-usgs** [comment]
if you get coawstM, then you are good.  always look for a new coawstM.

If there is only 1 wrf model, then i create a wrf.exe  and coawstM will point to that wrf.exe.
But if there are more than 1 model and they are coupled, then i create a coawstM that drives both wrf and roms. I do not want the individual exe for each model, that would be confusing.  i only need 1 exe and that is coawstM[.exe].
does that make sense?

**Comment by dophine-liu** [comment]
I got it!
I also run the test case, works fine!
Many thanks for your help!
