### ISSUE TITLE
How to get the coawst version that includes wrfv3.6

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#74]
Hi! I'm currently using wrf and roms coupling in coawst, but when using a tool I need wrfv3.6 version and roms coupling. Please how can I get the old version of coawst.

**Comment by jcwarner-usgs** [comment]
i would not recommend to go backwards.  there are always things that we correct along the way.
What tool are you using?
There are commands to go back in git versions, but i would not know what revision to use.

**Comment by SakuraLz** [comment]
hi! thank you for your reply. For the wrf version problem, because I want to use wrf's tc bogus program to eliminate a double typhoon, but the program will error on v3.6 and above, so I can only look for lower versions of coawst. 
Don't know if you have touched this part.
And I noticed that in the earliest coawst version you posted on github, the minimum version of wrf is v4.0.
