### ISSUE TITLE
ERROR while reading namelist physics/dynamics

### ISSUE THREAD

**Issue by yanfeng7** [jcwarner-usgs/COAWST#75]
when i run the real.exe, the rsl.error.0000 file will be written as following, and it doesn't make wrfinput or wrfbdy files. could someone tell me what's wrong with my namelist.input file which is also attached below.
[namelist_input.txt](https://github.com/jcwarner-usgs/COAWST/files/8148298/namelist_input.txt)
 
the rsl.error.0000 file:
taskid: 0 hostname: ln01
   ------ ERROR while reading namelist physics ------
   ------ ERROR while reading namelist dynamics ------
 -------------- FATAL CALLED ---------------
 FATAL CALLED FROM FILE:  <stdin>  LINE:    9895
 ERRORS while reading one or more namelists from namelist.input.
 -------------------------------------------
Abort(1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

**Comment by yanfeng7** [comment]
can someone help me solve this problem? please, i still have this problem...

**Comment by jcwarner-usgs** [comment]
there is not a lot of information here.
Compile the model to just use WRF only.
then do all the real etc processing.  run WRF only.
Then compile for multiple models.
will that help?
