### ISSUE TITLE
A couple problem when compiling coawstM

### ISSUE THREAD

**Issue by wanghong78** [jcwarner-usgs/COAWST#76]
Hi,

I met an ocean_coupler problem when I ran the WRF-ROMS coupling case.  I can run ROMS or WRF alone successifully while when ran the ROMS alone with some ANA_ force field setting in the .h file. My head file setting as below:

#define ROMS_MODEL
#define WRF_MODEL
#undef NESTING
#define MCT_LIB
#define ATM2OCE_FLUXES
/*Physics + numerics*/
#undef  LOG_PROFILE
#define UV_ADV
#define UV_COR
#define UV_LOGDRAG
#define SALINITY
#define SOLVE3D
#define SPHERICAL
#undef SEDIMENT
/*Grid and Initial*/
#define MASKING
/*Turbulence closure*/
#undef SPLINES
#undef  ANA_VMIX    
#define GLS_MIXING
#ifdef GLS_MIXING
# define KANTHA_CLAYSON
# define  N2S2_HORAVG
#endif

/*Forcing*/
#undef ANA_SSFLUX
#undef LONGWAVE_OUT
#undef BULK_FLUXES 
#define ANA_BTFLUX
#define ANA_BSFLUX
#define EMINUSP
#define SOLAR_SOURCE

Then I did the weight_coawst.nc file and when I coupled them and compiled the coawst.bash file, I met the wrong information as belows:
  
![image](https://user-images.githubusercontent.com/104638617/165968848-8ef0ddb2-4c7c-4b45-a2f7-f76132936207.png)
The attachment is my log.file and I would appreciate it if you could give me some guidance! 

[build.log](https://github.com/jcwarner-usgs/COAWST/files/8591691/build.log)

Thanks a lot!

**Comment by jcwarner-usgs** [comment]
i think you have a misspelled cpp def

define ATM2OCE_FLUXES
should be
define ATM2OCN_FLUXES

then do a ./coawst.bash and see if that compiles better.
-john
[Top](https://www.myroms.org/forum/viewtopic.php?p=23761#top)
