### ISSUE TITLE
define a constant bottom heat flux 

### ISSUE THREAD

**Issue by fatimash12** [jcwarner-usgs/COAWST#78]
Dear John,
I want to define a constant bottom heat flux in my ROMS model. Should I define it in my initial file or is there any cpp options? Could you please help me. 
regards,
Fatima

**Comment by jcwarner-usgs** [comment]
the bottom heat flux can be put in one of the ANA_*
I would recommend that you copy ROMS/Functionals/ana_btflux.h to your applications folder, edit that file, and add a section such as
      IF (itrc.eq.itemp) THEN
        DO j=JstrT,JendT
          DO i=IstrT,IendT
            btflux(i,j,itrc)=0.0_r8   <----  put some other value here
          END DO
        END DO

you will need to do some tests, so do a run without this first.  then add some value, recompile, and do a second run with tht btflux value.  diff the 2 simulations and see if the flux is correct.

**Comment by fatimash12** [comment]
Dear John,
I did this process, but nothing changed in my outputs. I add 3_r8. Could you please help me?
Regards,

**Comment by jcwarner-usgs** [comment]
not sure.
try to use 30.0_r8  (notice the .0)
just to see if it is coming in.
Check Build/analytical.f90 to make sure your section of code was included in the build.
