### ISSUE TITLE
Error when running wrf+roms+swan coupled mode

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#80]
Hello John,

I have successfully run the wrf+roms coupled model and recently tried to add swan mode but when I try to run it, the model does not work. My model uses double nesting for wrf, and a single grid for roms and swan.
According to the output file of the run, I cannot find the cause of the error, it just says "BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES".
Can you help me please?
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/8792885/logs.txt)

**Comment by jcwarner-usgs** [comment]
Did you get any Err* files?  Look in the PRINT* files to see what is in there.

**Comment by SakuraLz** [comment]
Thanks for the heads up, I see the err* and PRINT01 files. And I have adjusted some of the parameters and now the model crashes at the first step. Although I can see the error in the logs file, I don't know why my err* file is blank and the output of the PRINT01 file doesn't seem to be fully displayed.
Do you know what is wrong with my model?
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/8801808/logs.txt)
[PRINT01.txt](https://github.com/jcwarner-usgs/COAWST/files/8801816/PRINT01.txt)

**Comment by jcwarner-usgs** [comment]
i am not sure, but SWAN likes to have some kind of a wind. i see you have

 && KEYWORD TO CREATE WIND GRID &&
 &INPGRID WIND REGULAR -105 10 0 220 160 0.25 0.25 &
 &       NONSTATIONARY 20180913.000000 6 HR 20121031.000000
 &READINP WIND 1 'Projects/Mangkhut/swan_GFS_Oct2012.dat' 4 0 FREE
 
maybe just try
WIND  1.0 0.0

and see if it runs with that.
