### ISSUE TITLE
Error in modifying INLET_TEST/REFINED

### ISSUE THREAD

**Issue by venuscheung** [jcwarner-usgs/COAWST#82]
hi all, I am trying to modify the case in inlet_test/refined. Yet, when I implemented a new grid system, error occurred.

The error message is as below:
DIAG speed trouble 21.738337879173105
DIAG speed ijk 24.693944728437998 121 1 16 2
Found Error: 01 Line: 345 Source: ROMS/Nonlinear/main3d.F
Found Error: 01 Line: 331 Source: ROMS/Drivers/nl_ocean.h, ROMS_run

After finding out this error, I tried to change the grid to the one in sandy, same error occurred.

I have run a few more cases without the initial file. And I find that the problem might arise from the roms_contact.nc or boundary problem. 

![large](https://user-images.githubusercontent.com/50226567/175012592-f89c93d2-2ace-478b-abe2-204d363b019e.png)
![small](https://user-images.githubusercontent.com/50226567/175012600-7e2cbe60-3642-40bf-8874-3a9be1b4e08f.png)

I have attached the swan and roms grids, as well as the contact file and scrip file. 
May I know how to solve this boundary issue. 
[question.zip](https://github.com/jcwarner-usgs/COAWST/files/8956935/question.zip)
 [ocean_inlet_test_ref3.txt](https://github.com/jcwarner-usgs/COAWST/files/8955307/ocean_inlet_test_ref3.txt)

the contact file is created by the command below: 
Gnames={roms_grid,roms_child_grid};
[S,G]=contact(Gnames,'roms_contact.nc');

Thank you in advance

**Comment by venuscheung** [comment]
(I have merged two comment into one)

**Comment by jcwarner-usgs** [comment]
can you do a code update and try again?  I want to make sure you are using a more recent version of nesting.F.

**Comment by venuscheung** [comment]
Thank you for your reply. There is my nesting.F. I believe it is the latest version. Please let me what else I can check. Thank you.
[nesting.txt](https://github.com/jcwarner-usgs/COAWST/files/9017325/nesting.txt)

**Comment by jcwarner-usgs** [comment]
can you do an update.  i made some changes since that version you have.

**Comment by venuscheung** [comment]
May I ask which version should I update to? 
The version of my ROMS is as below: 
ROMS/TOMS Framework: March 25, 2021

Copyright (c) 2002-2021 The ROMS/TOMS Group
  Licensed under a MIT/X style license
  See License_ROMS.txt

svn: $HeadURL: https://www.myroms.org/svn/src/trunk/ROMS/Version $
svn: $LastChangedBy: arango $
svn: $LastChangedRevision: 1058 $
svn: $LastChangedDate: 2021-03-25 15:04:23 -0400 (Thu, 25 Mar 2021) $

it should be the same as the master version: https://code.usgs.gov/coawstmodel/COAWST/-/blob/master/ROMS/Version 

Thank you for your suggestion!

**Comment by jcwarner-usgs** [comment]
the version on code.usgs.gov is for released versions. 
Please use the version on this github site.
https://github.com/jcwarner-usgs/COAWST
can you update to that please.
-j

**Comment by venuscheung** [comment]
Thank you very much! 
The nesting problem is solved. Yet, there is another problem. 

(1) When I use create_roms_child_init to create a initial condition for the nested grid. The simulation quickly blow up. However, if the initial condition for the nested grid is created by roms_master_climatology_coawst, which is the same way for creating initial file for the parent grid, the simulation does not blow up that fast (there is still blow up error after several steps). May I ask why this happened and how can it be solved? 

Attached is the matlab file I used to create the initial condition for the nested grid.
[create_roms_child_init_amd.txt](https://github.com/jcwarner-usgs/COAWST/files/9053679/create_roms_child_init_amd.txt)

(2) Also, may I ask is it possible not to set any initial condition for the nested grid, but remain the initial condition for the parent grid without the following situation occurs? 
![without_nestedini](https://user-images.githubusercontent.com/50226567/177522543-d5761eb0-f374-4796-a20a-182a23d421e0.png)

(3) If the clm.nc also contains the information for the first time step, is it possible to replace the initial file and how can it be done?

Thank you very much in advance!!

**Comment by jcwarner-usgs** [comment]
ok.   i would like you to step back and see the bigger picture, rather than just running some m files and seeing which one works.

Obviously there is something wrong with those initial conditions. 
Is that the plot above with the parent and child init zeta? or is that plot after the model ran for some time?

**Comment by venuscheung** [comment]
Thank you for your reply. 

The figure above is with the parent grid init zeta after 4-hour run. 
Below are the initial condition for the parent grid and child grid. 
[coawst_ini.zip](https://github.com/jcwarner-usgs/COAWST/files/9056286/coawst_ini.zip)

After several trial, I turn off all the initial condition and clm files. The simulation still blow up and the figure is as below. 
![without_ini](https://user-images.githubusercontent.com/50226567/177591739-72dce816-9052-42f3-aa16-9b6f3d1baba9.png)

Is that mean the problem at the start still occurring? What files should I update or I should remake COAWST using this link: https://github.com/jcwarner-usgs/COAWST 

Thank you.

**Comment by jcwarner-usgs** [comment]
lets start with you using COAWST from this site here.
https://github.com/jcwarner-usgs/COAWST
that may fix a lot.

then, make a pcolor of zeta from parent and zeta from child at t=0.
figure
pcolor(lon_rho,lat_rho,zeta_parent(:,:,1)
hold on
pcolor(lon_rho,lat_rho,zeta_child(:,:,1)

-j

**Comment by venuscheung** [comment]
After updating the COAWST in that site, the nesting problem still exist. It can be observed when the initial condition and clm file are turned off.
![without_ini](https://user-images.githubusercontent.com/50226567/177754989-b86f7135-18d8-4485-8462-2b4abc32a1e9.png)
![without_ini2](https://user-images.githubusercontent.com/50226567/177756520-e94af365-2f6a-420e-a71f-eb38d588e2c2.png)

Yet, the location that have this extreme value changes every time.


For the initial file, I cannot see any strange values. The lower one is the initial condition zoomed into the nested grid. 
![zetaini](https://user-images.githubusercontent.com/50226567/177690693-763db0f4-dc04-4e10-bc20-3acee496c991.PNG)
![zetaini_zoom](https://user-images.githubusercontent.com/50226567/177690696-21a99439-ac3b-4474-a3d4-fa4d4c7695a3.PNG)

Thank you.

**Comment by venuscheung** [comment]
After several trial, I decide to try the header file from sandy instead of inlet_test. Yet, the error message below pop out. Please let me know which file should I check. Thank you very much.

mod_param.f90:357:62:

         logical ::         ! parabolic splines (vertical only)
                                                              1
Error: Invalid character in name at (1)
mod_param.f90:783:32:

             Hadvection(itrc,ng)% = .FALSE.
                                1
Error: Expected structure component name at (1)
mod_param.f90:799:32:

             Vadvection(itrc,ng)% = .FALSE.
                                1
Error: Expected structure component name at (1)
ROMS/Modules/Module.mk:15: recipe for target '/mnt/d/COAWST/case/scs_nested_m/Build/mod_param.o' failed
make: *** [/mnt/d/COAWST/case/scs_nested_m/Build/mod_param.o] Error 1


[log.txt](https://github.com/jcwarner-usgs/COAWST/files/9065603/log.txt)
[sandy.txt](https://github.com/jcwarner-usgs/COAWST/files/9065604/sandy.txt)

**Comment by jcwarner-usgs** [comment]
i am not sure what is happening here.   I have not ever seen the cpp preprocessor change the code like this.

can you look on line 416 of ROMS/Modules/mod_param.F, it should be
        logical :: SPLINES        ! parabolic splines (vertical only)
that is being preprocessed to
    logical ::         ! parabolic splines (vertical only)
for some reason the word SPLINES is being removed.  i am not sure why.

Can you start over, and try to compile Inlet_test/Refined the way it is distributed and lets make sure the distribution works for you, before you start to modify anything,

**Comment by venuscheung** [comment]
Hi all. 
I have solved the SPLINE problem by removing "define SPLINE" in my sandy.h file. I did not why this statement appears in the header file but this option seems does not exist as shown in the WikiROMS. 

Anyway, all the problem solved and I have successfully run the nesting case. Thank you very much for all of your help!!!
