### ISSUE TITLE
increasing Mean temperature over the time

### ISSUE THREAD

**Issue by fatimash12** [jcwarner-usgs/COAWST#84]
Dear John,
I am working with a bowl shape bathymetry. I ran the model for 100000 timesteps. My mean temperature increased over time, but my total energy stayed constant. How I can be sure that the result is trustable.

**Comment by jcwarner-usgs** [comment]
did the kinetic and potential energy change?  ke is based on momentum, and pe is based on the volume.
look in ROMS/Nonlinear/diag.F
-j

**Comment by fatimash12** [comment]
[00_upwroms.6600463.zip](https://github.com/jcwarner-usgs/COAWST/files/8992086/00_upwroms.6600463.zip)
Thank you for your quick answer. Yes, ke changed, but potential Energy looks constant.

**Comment by jcwarner-usgs** [comment]
i looked at this quick.  the energy values do change, but only slightly.
i am not sure the application, but i dont see anything wrong.
