### ISSUE TITLE
COAWST nesting run

### ISSUE THREAD

**Issue by HyeJJange** [jcwarner-usgs/COAWST#85]
Dear John.

Hello,  I have tried to nesting run COAWST v3.3.1 by coupling in. (Because I have WRFv3.9.1.1 output...)
However, the run failed because the file NGCNAME did not exist.

According to the roms_option.in 

----------------------------------------------------------------------------
! Nesting grids connectivity data: contact points information. This
! NetCDF file is special and complex. It is currently generated using
! the script "matlab/grid/contact.m" from the Matlab repository.

     NGCNAME =  roms_ngc.nc
----------------------------------------------------------------------------

I found the "matlab/grid/contact.m" in the path below
https://github.com/jcwarner-usgs/COAWST/blob/master/Tools/mfiles/rutgers/grid/contact.m
Is this file correct?

Also, Is there a user guide for creating a "matlab/grid/contact.m" file?
How can I create matlab/grid/contact.m file?

It's an old version, but can you help me?

[namelist_input.txt](https://github.com/jcwarner-usgs/COAWST/files/8992361/namelist_input.txt)
[roms_option_in.txt](https://github.com/jcwarner-usgs/COAWST/files/8992362/roms_option_in.txt)
[coawst.log](https://github.com/jcwarner-usgs/COAWST/files/8992363/coawst.log)
[coupling_in.txt](https://github.com/jcwarner-usgs/COAWST/files/8992364/coupling_in.txt)

**Comment by jcwarner-usgs** [comment]
we have a lot of detailed information in the COAWST user manual.  can you please look through that document first.  it does explain how to create contact files.
-j
