### ISSUE TITLE
Error using multiple nodes while running coupled (ROMS+WW3) simulation.

### ISSUE THREAD

**Issue by noviceroms** [jcwarner-usgs/COAWST#86]
Hi Warner,

I am trying to run an ocean-wave coupled simulation as ROMS + WW3. The stand-alone ROMS and WW3 are running with multiple nodes without any issues.  Coupled ROMS+WW3 is running if I am using only one node (A total of 20 processors per node, (16 For ROMS and 4 for WW3)  ). But since this is a high-resolution configuration, I have to move to multiple nodes.  But the ROMS+WW3 is blowing up while using multiple nodes with the following error. I am also attaching the full log file. Any insights into this problem will be really helpful.

Thanks in advance

> Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
> Backtrace for this error:
> #0  0x2B8AD4553697
> #1  0x2B8AD4553CDE
> #1  0x2AEEDC2D7CDE
> #2  0x2B8AD52022EF
> #3  0x60B819 in __vs3dbc_mod_MOD_vs3dbc_tile
> #3  0x60B819 in __vs3dbc_mod_MOD_vs3dbc_tile
> #4  0x5F84C0 in __wec_stokes_mod_MOD_wec_stokes_tile at wec_stokes.f90:?
> #4  0x5F84C0 in __wec_stokes_mod_MOD_wec_stokes_tile at wec_stokes.f90:?
> #5  0x5FDED3 in __wec_stokes_mod_MOD_wec_stokes
> #5  0x5FDED3 in __wec_stokes_mod_MOD_wec_stokes
> #6  0x41C896 in main3d_
> #6  0x41C896 in main3d_
> #7  0x41B559 in __ocean_control_mod_MOD_roms_run
> #7  0x41B559 in __ocean_control_mod_MOD_roms_run
> #8  0x408FD9 in MAIN__ at master.f90:?
> #3  0x60CBA0 in __vs3dbc_mod_MOD_vs3dbc_tile
> #8  0x408FD9 in MAIN__ at master.f90:?
> #4  0x5F84C0 in __wec_stokes_mod_MOD_wec_stokes_tile at wec_stokes.f90:?
> #2  0x2AEEDCF862EF
> #5  0x5FDED3 in __wec_stokes_mod_MOD_wec_stokes
> #6  0x41C896 in main3d_
> #7  0x41B559 in __ocean_control_mod_MOD_roms_run
> #8  0x408FD9 in MAIN__ at master.f90:?
> #3  0x60CBA0 in __vs3dbc_mod_MOD_vs3dbc_tile
> #4  0x5F84C0 in __wec_stokes_mod_MOD_wec_stokes_tile at wec_stokes.f90:?
> #5  0x5FDED3 in __wec_stokes_mod_MOD_wec_stokes
> #6  0x41C896 in main3d_
> #3  0x60B819 in __vs3dbc_mod_MOD_vs3dbc_tile
> #4  0x5F84C0 in __wec_stokes_mod_MOD_wec_stokes_tile at wec_stokes.f90:?
> #7  0x41B559 in __ocean_control_mod_MOD_roms_run
> #3  0x60B819 in __vs3dbc_mod_MOD_vs3dbc_tile
> #8  0x408FD9 in MAIN__ at master.f90:?
> #5  0x5FDED3 in __wec_stokes_mod_MOD_wec_stokes
> #6  0x41C896 in main3d_
> #4  0x5F84C0 in __wec_stokes_mod_MOD_wec_stokes_tile at wec_stokes.f90:?
> #7  0x41B559 in __ocean_control_mod_MOD_roms_run
> #5  0x5FDED3 in __wec_stokes_mod_MOD_wec_stokes
> #8  0x408FD9 in MAIN__ at master.f90:?
> #6  0x41C896 in main3d_
> #7  0x41B559 in __ocean_control_mod_MOD_roms_run
> #8  0x408FD9 in MAIN__ at master.f90:?
> --------------------------------------------------------------------------
> mpirun noticed that process rank 71 with PID 23632 on node node039 exited on signal 11 (Segmentation fault).
> --------------------------------------------------------------------------
[COAWST.log](https://github.com/jcwarner-usgs/COAWST/files/9012985/COAWST.log)

**Comment by jcwarner-usgs** [comment]
i am not sure. 
how many nodes can you run with ww3?  is that 80 cores?
can you try with 60?
what is the ww3 grid size(numx, numy, num freqs, num dirs)

**Comment by noviceroms** [comment]
Hi Warner,
I can run the standalone WW3 with any number of cores (20,60 or 80). The model is running. The ww3 grid is created from the ROMS grid using the COAWST-Matlab tools.  It has the following dimensions NumX=780, NumY=560, NumFreq=25, NumDir=24.

Thanks for your time and consideration
