### ISSUE TITLE
 Unable to open input file.

### ISSUE THREAD

**Issue by lsf911** [jcwarner-usgs/COAWST#87]
Hi all

I am having trouble to run a coupled ROMS+SWAN after successful compiling. When I submitted the model run and specified the files of swan.in and ocean.in in the coupling.in. I got the following error. 

Coupled Input File name = coupling.in 
 get num swan grids - Unable to open swan input file.
./swan.in  
 READ MODEL INPUTS - Unable to open roms input file.

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
coawstM            0000000000D9E75C  Unknown               Unknown  Unknown
libpthread-2.12.s  0000003EE760F7E0  Unknown               Unknown  Unknown
coawstM            0000000000CA99D5  Unknown               Unknown  Unknown
coawstM            0000000000CAAA1A  Unknown               Unknown  Unknown
coawstM            0000000000DC929E  Unknown               Unknown  Unknown
coawstM            0000000000DC1D86  Unknown               Unknown  Unknown
coawstM            0000000000DBF157  Unknown               Unknown  Unknown
coawstM            000000000044F03B  read_coawst_par_           83  read_coawst_par.f90
coawstM            0000000000441ED6  MAIN__                     64  master.f90
coawstM            00000000004419DE  Unknown               Unknown  Unknown
libc-2.12.so       0000003EE721ED20  __libc_start_main     Unknown  Unknown
coawstM            00000000004418E9  Unknown               Unknown  Unknown

It seems that the model cannot find the input files, but those files are correctly specified. This probably is something really silly, but I can't see/figure it out. Any suggestions? Thank you in advance.

Ethan

**Comment by jbzambon** [comment]
can you add in your coupling.in script? Where is swan.in located?

**Comment by lsf911** [comment]
Hi. Following is my coupling.in script. swan.in is located in the current folder where the job is submitted. 

!
! Number of parallel nodes assigned to each model in the coupled system.
! Their sum must be equal to the total number of processors.

   NnodesATM =  0                   ! atmospheric model
   NnodesWAV =  96                 ! wave model
   NnodesOCN =  96                 ! ocean model

! Time interval (seconds) between coupling of models.

!  TI_ATM2WAV =   1800.0d0              ! atmosphere to wave coupling interval
!  TI_ATM2OCN =   1800.0d0              ! atmosphere to ocean coupling interval
!  TI_WAV2ATM =   1800.0d0              ! wave to atmosphere coupling interval
  TI_WAV2OCN =    1800.0d0              ! wave to ocean coupling interval
  TI_OCN2WAV =    1800.0d0              ! ocean to wave coupling interval
!  TI_OCN2ATM =   1800.0d0              ! ocean to atmosphere coupling interval

! Enter names of Atm, Wav, and Ocn input files.
! The Wav program needs multiple input files, one for each grid.

!   ATM_name = namelist.input                           ! atmospheric model
   WAV_name =  ./swan.in                        ! wave model
   OCN_name =  ./ocean.in               ! ocean model

! Sparse matrix interpolation weights files. You have 2 options:
! Enter "1" for option 1, or "2" for option 2, and then list the
! weight file(s) for that option.

    SCRIP_WEIGHT_OPTION = 1
!
! Option 1: IF you set "SCRIP_WEIGHT_OPTION = 1", then enter name
!           of the single netcdf file containing all the exchange
!           weights. This file is created using the code in
!           Lib/SCRIP_COAWST/scrip_coawst[.exe]
    SCRIP_COAWST_NAME = ../../../input/scrip_nscs_static.nc

**Comment by lsf911** [comment]
> can you add in your coupling.in script? Where is swan.in located?

Hi. Following is my coupling.in script. swan.in is located in the current folder where the job is submitted.

!
! Number of parallel nodes assigned to each model in the coupled system.
! Their sum must be equal to the total number of processors.

NnodesATM = 0 ! atmospheric model
NnodesWAV = 96 ! wave model
NnodesOCN = 96 ! ocean model

! Time interval (seconds) between coupling of models.

! TI_ATM2WAV = 1800.0d0 ! atmosphere to wave coupling interval
! TI_ATM2OCN = 1800.0d0 ! atmosphere to ocean coupling interval
! TI_WAV2ATM = 1800.0d0 ! wave to atmosphere coupling interval
TI_WAV2OCN = 1800.0d0 ! wave to ocean coupling interval
TI_OCN2WAV = 1800.0d0 ! ocean to wave coupling interval
! TI_OCN2ATM = 1800.0d0 ! ocean to atmosphere coupling interval

! Enter names of Atm, Wav, and Ocn input files.
! The Wav program needs multiple input files, one for each grid.

! ATM_name = namelist.input ! atmospheric model
WAV_name = ./swan.in ! wave model
OCN_name = ./ocean.in ! ocean model

! Sparse matrix interpolation weights files. You have 2 options:
! Enter "1" for option 1, or "2" for option 2, and then list the
! weight file(s) for that option.

SCRIP_WEIGHT_OPTION = 1

!
! Option 1: IF you set "SCRIP_WEIGHT_OPTION = 1", then enter name
! of the single netcdf file containing all the exchange
! weights. This file is created using the code in
! Lib/SCRIP_COAWST/scrip_coawst[.exe]
SCRIP_COAWST_NAME = ../../../input/scrip_nscs_static.nc

**Comment by jcwarner-usgs** [comment]
for this to work, the coawstM, swan.in, ocean.in, and coupling.in all need to be in the same directory.

**Comment by lsf911** [comment]
> for this to work, the coawstM, swan.in, ocean.in, and coupling.in all need to be in the same directory.

Hi John,

Thank you for your suggestion. After I checked the *.in file again, the model is now able to read the input files but comes across a new error on the couplling.  I was wondering do you have any clues on this? Thank you. 


forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
coawstM            0000000000DD8F4C  Unknown               Unknown  Unknown
libpthread-2.12.s  0000003EE760F7E0  Unknown               Unknown  Unknown
coawstM            0000000000BDA769  Unknown               Unknown  Unknown
coawstM            0000000000C12160  Unknown               Unknown  Unknown
coawstM            0000000000BFB598  Unknown               Unknown  Unknown
coawstM            00000000009C2844  waves_coupler_mod         374  waves_coupler.f90
coawstM            00000000009B984C  waves_control_mod          85  waves_control.f90
coawstM            0000000000445BAD  MAIN__                    218  master.f90
coawstM            00000000004422DE  Unknown               Unknown  Unknown
libc-2.12.so       0000003EE721ED20  __libc_start_main     Unknown  Unknown
coawstM            00000000004421E9  Unknown               Unknown  Unknown
yhrun: error: cn9862: task 96: Exited with exit code 174

Following is the swan.in

PROJECT 'NSCS_SW04' '01'
'SWAN-ROMS'
''
''
MODE NONSTATIONARY TWODIMENSIONAL 
SET DEPMIN 0.1 MAXERR 100 INRHOG 1 NAUTICAL PWTAIL 5
COORDINATES SPHERICAL

&& KEYWORD for number of nested SWAN grids.
NSGRIDS 1  

&& KEYWORDS TO CREATE AND READ COMPUTATIONAL GRID &&
CGRID CURVILINEAR 1501 551 EXC 9.999e+003 9.999e+003 CIR 36 0.04 1.0    
READGRID COORDINATES 1 '../../../input/swan_coord_17.grd' 4 0 0 FREE

&& KEYWORDS TO CREATE AND READ BATHYMETRY GRID &&
INPGRID BOTTOM CURVILINEAR 0 0 1501 551 EXC 9.999e+003
READINP BOTTOM 1 '../../../input/swan_bathy_17.grd' 4 0 FREE

&& KEYWORD TO CREATE CURRENT GRID &&
INPGRID CURRENT CURVILINEAR  0  0 1501 551 EXC 9.999e+003 &          
        NONSTAT  20150701.000000 30 DAY 20150731.000000

&& KEYWORD TO CREATE WATER LEVEL GRID &&
INPGRID WLEV  CURVILINEAR  0  0 1501 551 EXC 9.999e+003 &              
         NONSTAT  20150701.000000 30 DAY 20150731.000000 
		
&Wind forcing constant 
&INP WI REG 279.833 33.833 0.0  484 256 0.083 0.083 &
& NONSTAT 20100801.000000 3 HR 20101001.000000 
&READ WI 1.0 '../swan_narr_1.dat' 4 0 FREE 
WIND 4.2 225

&& BOUNDARY FORCING &&
&&BOUND  SHAPESPEC JONSWAP 3.3 PEAK DSPR DEGREES
&BOUNDSPEC SEGMENT IJ   479     0   479    12 VARIABLE PAR 0 1.0 10.0 0. 20. 
&&BOUndnest3 WW3 '/scratch/sflin/coawst_20200614/ecs/201008/nest.ww3' 
&BOUNDSPEC SEGMENT IJ  479  0 479 6 VARIABLE FILE 0 '../ecmwf/WW3part_001.spc2d'

& Restart name **********************************
INIT DEFault

& PHYSICS  ************************************** 
GEN3 ST6 2.8E-6 3.5E-5 4.0 4.0 UP HWANG VECTAU U10PROXY 32.0 AGROW 
SSWELL ZIEGER 0.00025
NEGATINP 0.04 
&WCAP AB
BREaking CON
FRICtion MADSEN
&SETUP

BLOCK 'COMPGRID' NOHEADER 'WATLEV.mat'   LAY 4 WATLEV   1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'VEL.mat'      LAY 4 VEL      1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'DEPTH.mat'    LAY 4 DEPTH    1.   OUTPUT 20150701.000000 24  HR
&BLOCK 'COMPGRID' NOHEADER 'GENWIND.mat'  LAY 4 GENWIND  1.   OUTPUT 20150701.000000 24  HR
&BLOCK 'COMPGRID' NOHEADER 'DISSIP.mat'   LAY 4 DISSIP   1.   OUTPUT 20150701.000000 24  HR
&BLOCK 'COMPGRID' NOHEADER 'DISBOT.mat'   LAY 4 DISBOT   1.   OUTPUT 20150701.000000 24  HR
&BLOCK 'COMPGRID' NOHEADER 'DISSURF.mat'  LAY 4 DISSURF  1.   OUTPUT 20150701.000000 24  HR
&BLOCK 'COMPGRID' NOHEADER 'DISWCAP.mat'  LAY 4 DISWCAP  1.   OUTPUT 20150701.000000 24  HR
&BLOCK 'COMPGRID' NOHEADER 'DISSWELL.mat' LAY 4 DISSWELL 1.   OUTPUT 20150701.000000 24  HR

BLOCK 'COMPGRID' NOHEADER 'HSIGN.mat'    LAY 4 HSIGN    1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'HSWELL.mat'   LAY 4 HSWELL   1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'TPS.mat'      LAY 4 TPS      1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'TM01.mat'     LAY 4 TM01     1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'DIR.mat'      LAY 4 DIR      1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'WLEN.mat'     LAY 4 WLEN     1.   OUTPUT 20150701.000000 24  HR
BLOCK 'COMPGRID' NOHEADER 'URMS.mat'     LAY 4 URMS     1.   OUTPUT 20150701.000000 24  HR
 
&POINTS '41025'   284.597	35.005	 
&TABLE 'SMAR3'  NOHEAD 'SMAR3.table' HSIGN HSWELL TM01 TM02 RTP TPS WLEN DIR PDIR &
&OUTPUT 20100801.000000 1 HR 
&SPECOUT '41025' SPEC2D '41025.spc2d' OUTPUT 20100801.000000 1 HR
&SPECOUT '41025' SPEC1D '41025.spc1d' OUTPUT 20100801.000000 1 HR
&TAB 'COMPGRID' NOHEAD 'ECS_all.tab' HSIGN TM02 TPS WLEN DIR OUTPUT 20100801.000000 3 HR   
	
PROP BSBT

COMPUTE NONSTATIONARY 20150701.000000 360 SEC 20150731.000000

STOP

**Comment by jcwarner-usgs** [comment]
what is on  line 374   Build/waves_coupler.f90

also, look at the entire output.  there may have been earlier messages.

**Comment by jcwarner-usgs** [comment]
is this working yet?  would like to resolve this issue.

**Comment by lsf911** [comment]
> is this working yet? would like to resolve this issue.

Hi John, Thank you for you comments. The issuse was solved when I tried another version of compiler for ifort.
