### ISSUE TITLE
Errors in compilation of COAWST  WRF + ROMS + SWAN (  undefined reference to `MAIN__' )

### ISSUE THREAD

**Issue by dickson2021** [jcwarner-usgs/COAWST#88]
The wrf.exe could not be generated due to the following error.

mpiifort  -o wrf.exe -qopenmp -fpp -auto -qoverride-limits -O3 -xAVX -w -qopenmp -fpp -auto -qoverride-limits -auto -ftz -fno-alias -fp-model fast=1 -nofor-main -no-prec-div -no-prec-sqrt -FR -convert big_endian -auto -align array64byte   -xAVX  wrf.o ../main/module_wrf_top.o libwrflib.a  ...
,.......     
/opt/intel/compilers_and_libraries_2019.5.281/linux/compiler/lib/intel64_lin/libifcoremt.a(for_main.o): In function `main':
for_main.c:(.text+0x42): undefined reference to `MAIN__'
make[2]: [em_wrf] Error 1 (ignored)

If wrf.exe could not be generated , it cannot link to coawstM  in the coawst makefile.

        ln -sf WRF/main/wrf.exe coawstM;
 

How can I fix this ? I got the   libwrflib.a and .o files .   Can I link all  .o and .a files to coawstM without wrf.exe ?  

Thank you

Dickson

**Comment by jcwarner-usgs** [comment]
is this a coupled application?
i know the manual has a lot of info, and here is some hidden handy information:

section 5.1

" In some instances you may see an error or warning “undefined wrf.main.” That is the only error that is ok. We can not allow a wrf.exe to be built, nor an ocean.exe, and/or swan.exe to be created. Only one executable is created, and that is called coawstM[.exe]."

**Comment by dickson2021** [comment]
Thanks Jcwarner.

Yes it is a coupling system WRF + ROMS + SWAN

Assume I ignore the wrf.exe error. I encounter another errors below that could not allow to go further .  I think this caused the problem in creating the coawstM

There are some missing libraries linkage of  openmp , grib2 and jasper  libraries when I trace the error.  In fact these libraries exist in the WRF configure file.    I can see the libio_grib1.a is present in the code below but the linkage of libio_grib2.a is missing.  I have defined the environment path of libio_grib2.a at the beginning of the WRF configure file.   However, I don't know where I can add more flags  such as   "-qopenmp ,  WRF/external/io_grib2/libio_grib2.a and -L/usr/local/jasper/lib64 -ljasper  to this part of compilation code in the Makefile. (which make file should I add ? ) 

I could successfully compile this bit manually after I add  -qopenmp ,  WRF/external/io_grib2/libio_grib2.a and -L/usr/local/jasper/lib64 -ljasper  but  I would like to add them in Makefile / configure file so that it can compile automatically when I run coawst.bash  


****  After WRF compilation ****

ar: creating /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM.a
ranlib /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM.a
/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin/mpiifort -fp-model precise -ip -O3 -traceback -assume byterecl -I/home/user/MCT/include -I/home/user/COAWST//WRF/main -I/home/user/COAWST//WRF/external/esmf_time_f90 -I/home/user/COAWST//WRF/frame -I/home/user/COAWST//WRF/share -fp-model precise -ip -O3 -traceback /home/user/COAWST/task/WRF_ROMS_SWAN/Build/roms_import.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/get_sparse_matrix.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/master.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/roms_export.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/read_coawst_par.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/get_wrf_moving_grids.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/get_numswan_grids.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/mct_coupler_utils.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/propagator.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/read_model_inputs.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/ocean_coupler.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/coupler.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/mod_coupler_iounits.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/esmf_roms.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/ocean_control.o /home/user/COAWST/task/WRF_ROMS_SWAN/Build/ww3_iounits.o -o /home/user/COAWST/task/WRF_ROMS_SWAN/coawstM  /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM_bio.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM_sed.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM_wec.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM_veg.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libANA.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libUTIL.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libMODS.a /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libSWAN.a  /home/user/COAWST/task/WRF_ROMS_SWAN/Build/libNLM.a          -L/usr/local/NETCDF4_ifort/lib -lnetcdff -L/usr/local/NETCDF4_ifort/lib -lnetcdf -lnetcdf -lhdf5_hl -lhdf5 /home/user/COAWST/task/WRF_ROMS_SWAN/Build/mct_coupler_params.o -L/home/user/MCT/lib -lmct -lmpeu WRF/main/module_wrf_top.o WRF/main/libwrflib.a WRF/external/fftpack/fftpack5/libfftpack.a **WRF/external/io_grib1/libio_grib1.a** WRF/external/io_grib_share/libio_grib_share.a WRF/external/io_int/libwrfio_int.a WRF/external/esmf_time_f90/libesmf_time.a WRF/external/RSL_LITE/librsl_lite.a WRF/frame/module_internal_header_util.o WRF/frame/pack_utils.o WRF/external/io_netcdf/libwrfio_nf.a
WRF/main/module_wrf_top.o: In function `module_wrf_top_mp_wrf_dfi_':
module_wrf_top.f90:(.text+0xd6): undefined reference to `__kmpc_global_thread_num'
module_wrf_top.f90:(.text+0x114): undefined reference to `__kmpc_threadprivate_cached'
WRF/main/libwrflib.a(module_domain.o): In function `module_domain_mp_alloc_space_field_':
module_domain.f90:(.text+0x7831): undefined reference to `__kmpc_global_thread_num'
module_domain.f90:(.text+0x78dc): undefined reference to `__kmpc_threadprivate_cached'
WRF/main/libwrflib.a(module_wrf_error.o): In function `wrf_message_':
module_wrf_error.f90:(.text+0x31): undefined reference to `__kmpc_global_thread_num'
module_wrf_error.f90:(.text+0x50): undefined reference to `__kmpc_master'
module_wrf_error.f90:(.text+0x156): undefined reference to `__kmpc_end_master'
WRF/main/libwrflib.a(module_wrf_error.o): In function `wrf_message2_':
module_wrf_error.f90:(.text+0x195): undefined reference to `__kmpc_global_thread_num'
module_wrf_error.f90:(.text+0x1a6): undefined reference to `__kmpc_master'
module_wrf_error.f90:(.text+0x1fc): undefined reference to `__kmpc_end_master'

WRF/main/libwrflib.a(module_tiles.o): In function `module_tiles_mp_set_tiles2_':
module_tiles.f90:(.text+0x4af7): undefined reference to `omp_get_max_threads_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_real_arr_':
module_io.f90:(.text+0x49f): undefined reference to `ext_gr2_get_dom_ti_real_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_real_sca_':
module_io.f90:(.text+0xbd0): undefined reference to `ext_gr2_get_dom_ti_real_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_put_dom_ti_real_arr_':
module_io.f90:(.text+0x1243): undefined reference to `ext_gr2_put_dom_ti_real_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_put_dom_ti_real_sca_':
module_io.f90:(.text+0x17fc): undefined reference to `ext_gr2_put_dom_ti_real_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_double_arr_':
module_io.f90:(.text+0x1dd2): undefined reference to `ext_gr2_get_dom_ti_double_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_double_sca_':
module_io.f90:(.text+0x23d0): undefined reference to `ext_gr2_get_dom_ti_double_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_put_dom_ti_double_arr_':
module_io.f90:(.text+0x29a2): undefined reference to `ext_gr2_put_dom_ti_double_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_put_dom_ti_double_sca_':
module_io.f90:(.text+0x2f4c): undefined reference to `ext_gr2_put_dom_ti_double_'
WRF/main/libwrflib.a(module_io.o): In function `module_io_mp_wrf_get_dom_ti_integer_arr_':
 
Thanks

**Comment by jcwarner-usgs** [comment]
when you compile, do not use openmp (smpar).
only use mpi (dmpar)

**Comment by dickson2021** [comment]
Thank you so much for your suggestion.  The  coawstM could be successfully generated finally using dmpar compilation  without grib2 output. 

However, I still got  errors  in generating coawstM  when the option "output to grib2" is set to "True" in the Config.pl ( $I_really_want_to_output_grib2_from_WRF = "TRUE" ; ).  It seemed that the grib2 library (  WRF/external/io_grib2/libio_grib2.a ) could not be linked or included in the last step of compilation procedure below.  It only had  WRF/external/io_grib1/libio_grib1.a but not grib2.a  How to add grib2.a to the path ? 

/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin/mpiifort -fp-model precise -ip -O3 -traceback -I/home/user/MCT/include -I/home/user/COAWST//WRF/main -I/home/user/COAWST//WRF/external/esmf_time_f90 -I/home/user/COAWST//WRF/frame -I/home/user/COAWST//WRF/share -I/home/user/COAWST/WW3/model/mod_MPI -fp-model precise -ip -O3 -traceback /home/user/COAWST/task/WRF_ROMS_WW3/Build/roms_import.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/get_sparse_matrix.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/master.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/roms_export.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/read_coawst_par.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/get_wrf_moving_grids.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/get_numswan_grids.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/mct_coupler_utils.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/propagator.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/read_model_inputs.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/ocean_coupler.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/coupler.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/mod_coupler_iounits.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/esmf_roms.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/ocean_control.o /home/user/COAWST/task/WRF_ROMS_WW3/Build/ww3_iounits.o -o /home/user/COAWST/task/WRF_ROMS_WW3/coawstM  /home/user/COAWST/task/WRF_ROMS_WW3/Build/libNLM.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libNLM_bio.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libNLM_sed.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libNLM_wec.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libNLM_veg.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libANA.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libUTIL.a /home/user/COAWST/task/WRF_ROMS_WW3/Build/libMODS.a  /home/user/COAWST/task/WRF_ROMS_WW3/Build/libNLM.a          -L/usr/local/NETCDF/lib -lnetcdff -L/usr/local/NETCDF/lib -lnetcdf -lnetcdf -lhdf5_hl -lhdf5 /home/user/COAWST/task/WRF_ROMS_WW3/Build/mct_coupler_params.o -L/home/user/MCT/lib -lmct -lmpeu WRF/main/module_wrf_top.o WRF/main/libwrflib.a WRF/external/fftpack/fftpack5/libfftpack.a **WRF/external/io_grib1/libio_grib1.a WRF/external/io_grib_share/libio_grib_share.a** WRF/external/io_int/libwrfio_int.a WRF/external/esmf_time_f90/libesmf_time.a WRF/external/RSL_LITE/librsl_lite.a WRF/frame/module_internal_header_util.o WRF/frame/pack_utils.o WRF/external/io_netcdf/libwrfio_nf.a WW3/model/obj_MPI/libWW3.a
WRF/main/libwrflib.a(module_io_quilt.o): In function `module_wrf_quilt_mp_quilt_pnc_':
module_io_quilt.f90:(.text+0x3e5): undefined reference to `ext_gr2_ioinit_'
module_io_quilt.f90:(.text+0x164e): undefined reference to `ext_gr2_inquire_filename_'
module_io_quilt.f90:(.text+0x1718): undefined reference to `ext_gr2_open_for_write_commit_'
module_io_quilt.f90:(.text+0x1918): undefined reference to `ext_gr2_open_for_write_begin_'
module_io_quilt.f90:(.text+0x1ae6): undefined reference to `ext_gr2_inquire_filename_'
module_io_quilt.f90:(.text+0x1b15): undefined reference to `ext_gr2_ioclose_'
module_io_quilt.f90:(.text+0x1e1f): undefined reference to `ext_gr2_put_var_ti_char_'

Thank you

**Comment by jcwarner-usgs** [comment]
this looks like a grb2 issue, nothing to do with mct.
can you ask on the wrf forum?
-j

**Comment by dickson2021** [comment]
Thanks.

When I run the Sandy case. I got the following errors.

Any  idea which caused the problem ?  It seems to relate to MPI and Open MPI issued. I used dmpar,  so openmpi should not be used during compilation.   Thank you for your help in advance.  

WRF V4.1.5 MODEL
Abort(738797317) on node 13 (rank 13 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
PMPI_Cart_create(313): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x7ffe19568380, periods=0x7f20000d8fc0, reorder=0, comm_cart=0x7ffe1956834c) failed
PMPI_Cart_create(244): Invalid communicator
Abort(470361861) on node 14 (rank 14 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
PMPI_Cart_create(313): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x7ffc6e40fa80, periods=0x7f20001dd000, reorder=0, comm_cart=0x7ffc6e40fa4c) failed
PMPI_Cart_create(244): Invalid communicator
Abort(336144133) on node 15 (rank 15 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
PMPI_Cart_create(313): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x7ffeb9ed0680, periods=0x7f2000199080, reorder=0, comm_cart=0x7ffeb9ed064c) failed
PMPI_Cart_create(244): Invalid communicator
Abort(470361861) on node 16 (rank 16 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
PMPI_Cart_create(313): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x7ffcf81d1400, periods=0x7f2000135cc0, reorder=0, comm_cart=0x7ffcf81d13cc) failed
PMPI_Cart_create(244): Invalid communicator
Abort(134817541) on node 17 (rank 17 in comm 0): Fatal error in PMPI_Cart_create: Invalid communicator, error stack:
PMPI_Cart_create(313): MPI_Cart_create(comm=0xffff8002, ndims=2, dims=0x7ffd49140200, periods=0x7f20001ae540, reorder=0, comm_cart=0x7ffd491401cc) failed
PMPI_Cart_create(244): Invalid communicator

**Comment by dickson2021** [comment]
Thanks.  When I run the Sandy case.  I got the following errors on mct. How can I solve ? I am using default   AT:1. OC:1 WV:1 
Thank you for your help in advance

 *************************************
 Nesting domain
 ids,ide,jds,jde            1         100           1         100
 ims,ime,jms,jme           -4         105          -4         105
 ips,ipe,jps,jpe            1         100           1         100
 INTERMEDIATE domain
 ids,ide,jds,jde           31          69           6          44
 ims,ime,jms,jme           26          74           1          49
 ips,ipe,jps,jpe           29          71           4          46
 *************************************
d01 2012-10-28_12:00:00  alloc_space_field: domain            2 ,               19073544  bytes allocated
d01 2012-10-28_12:00:00  alloc_space_field: domain            2 ,               19073544  bytes allocated

SWAN grid   2 is preparing computation

MCT::m_MCTWorld::initm_MCTERROR:  MCTWorld has already been initialized...Continuing
m_GlobalSegMap::comp_id_ MCTERROR:  GSMap argument not initialized...exiting
001.MCT(MPEU)::die.: from m_GlobalSegMap::comp_id_()
Abort(2) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 1

**Comment by jcwarner-usgs** [comment]
for some reason your last message is not listed here, about the 

**SWAN grid 2 is preparing computation

MCT::m_MCTWorld::initm_MCTERROR: MCTWorld has already been initialized...Continuing
m_GlobalSegMap::comp_id_ MCTERROR: GSMap argument not initialized...exiting
001.MCT(MPEU)::die.: from m_GlobalSegMap::comp_id_()
Abort(2) on node 1 (rank 1 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 1**

can you post the entire std out?
is this the Sandy case exactly as distributed, or did you make any changes?

**Comment by dickson2021** [comment]
Hi jcwarner.

Yes. I deleted the message as I had solved the problem. It was my mistake to type a wrong path pointing to a hotfile in swan input file. The sandy case could successfully be run after I corrected the path.  Sometime the error messages were misleading. Anyway, thank you so much for your advice and help.

**Comment by jcwarner-usgs** [comment]
ok good.  !
glad you got it to work.-j
