### ISSUE TITLE
Tidal force data not found in Sandy test case

### ISSUE THREAD

**Issue by s193264** [jcwarner-usgs/COAWST#89]
Nice to meet you
I'm just starting to use the COAWST model and I'm not sure
So I'm sorry if it's a common basic problem.

I am implementing Sandy test cases according to User_manual.
However, when adding tidal force to the calculation of P.61, ROMS, I am in trouble because the ADCIRC data cannot be downloaded.

`svn checkout https://coawstmodel.sourcerepo.com/coawstmodel/data`
When I run this command, I get the following error:

`svn: E170013: Unable to connect to a repository at URL 'https://coawstmodel.sourcerepo.com/coawstmodel/data/tide'
svn: E670002: Name or service not known`

How should this be resolved?

**Comment by jcwarner-usgs** [comment]
the code from that svn site has been discontinued.
get the code from this github site

https://github.com/jcwarner-usgs/COAWST
you can use git clone

-j

**Comment by s193264** [comment]
Dear @jcwarner-usgs 

thank you for your reply.
I got the code from github.
But I don't know where "adcirc2001" is.

Sorry to bother you again. Can you tell me where adcirc2001 is in COAWST?
I think it's in COAWST / Tools / mfiles / tides, but I don't know which file it is.
I would appreciate it if you could tell me. thank you.

**Comment by jcwarner-usgs** [comment]
ok so i just updated the Tools/mfiles/tides/create_roms_tides.m
In there there are 3 options to make the tides
1- use an older adcirc data base, and i just added 2 mat files. (  so you will need to do an update).
2 and 3 are to use newer adcirc or OSU .  For those i just suggest you go to Rutgers site and follow those instructions here:
https://www.myroms.org/wiki/Tidal_Forcing

let me know if that works
-j

**Comment by s193264** [comment]
Dear @jcwarner-usgs 

Thanks to your prompt response, we were able to successfully create tidal force data.
I really appreciate it.


I have an additional question to ask.
I would appreciate it if you could reply when you have time.

I would like to perform the 2005 Katrina calculation with the COAWST model (WRF + ROMS + SWAN).
I have used the WRF model before, and I know the necessary input data.
However, I am not familiar with ROMS / SWAN and I am not familiar with it.

So, can you tell us what kind of input data is necessary to carry out the COAWST calculation?
If possible, it would be very helpful if you could tell us the appropriate file name in the Sandy test case.
I know it's very rude.
If you have any reference materials, I would appreciate it if you could.

thank you.

**Comment by jcwarner-usgs** [comment]
the best path here is for you to look in the user manual.  there is a ton of descriptions on how to set up roms, swan, ini files, etc etc.  We also have some videos from the last workshop here:

https://drive.google.com/drive/folders/1OIV4r5lym-kRiBvuOMpojjySXgxWDsZy

-j
