### ISSUE TITLE
Creating initial field, boundary field files from grid files

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#90]
HI！
I now have a question. Why do some of the grid files have all zero data in the output file when the initial boundary file is created?
I am currently using the GridBuilder program to create the master grid. However, I find that grid files generated using this program have zero data for u, v, temp, etc. when creating the primary boundary file.
I am currently using the GridBuilder program to create the master grid. However, I have found that the grid files generated using this program have zero data for u, v, temp etc. when creating the primary boundary file.
I'm sure it's not a network fluctuation problem because when I create the grid using the method in COAWST, the data is present in the regenerated primary boundary file.The time period I used was 13-17 September 2018
I have placed the grid generated by my GridBuilder below in the hope that you can help me.

**Comment by SakuraLz** [comment]
[Grid_Builder_roms.zip](https://github.com/jcwarner-usgs/COAWST/files/9125045/Grid_Builder_roms.zip)

**Comment by jcwarner-usgs** [comment]
i am not clear on your question.
The grid file has information like lon_rho,lat_rho,h, etc. there is not a u v sal in the grid file.
I do not use GridBuilder so i cant really help there. maybe ask a message on the ROMS forum.  this is for roms, not really a coawst coupled question.
Not sure what you mean by the 'output file' ?   his file?
what are you using to create the initial and boundary files?
those are 2 separate files.

**Comment by SakuraLz** [comment]
Well, I will go to the forum and ask about it.
I have another problem here, when I create the grid using the method in the coawst user manual, I can run roms successfully. but I find the zeta data in the result file is strange. It may be that there are some areas where the water depth is too low and there are anomalies. Here are the results that I viewed using ncview.
![roms](https://user-images.githubusercontent.com/44939791/179384101-e237a5c1-e1e0-45e2-ad78-fd95c4916c9a.png)
Meanwhile, I plotted the zeta data at a certain moment with ncl and found that the results are normal for most of the areas. Have you encountered this situation?
![ncl_zeta](https://user-images.githubusercontent.com/44939791/179384224-ce0e55bb-b4cf-4643-9593-85efc305dac8.png)

**Comment by jcwarner-usgs** [comment]
the zeta is draped over the topo.
what does the 'h' look like in that viewer?
-j


John C. Warner, Ph.D.
U.S. Geological Survey
384 Woods Hole Road
Woods Hole, MA 02543
508-457-2237<tel:508-457-2237> ph. 508-457-2310<tel:508-457-2310> fax
***@***.******@***.***>

https://www.usgs.gov/staff-profiles/john-warner

________________________________
From: April ***@***.***>
Sent: Sunday, July 17, 2022 12:41 AM
To: jcwarner-usgs/COAWST ***@***.***>
Cc: Warner, John C ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [jcwarner-usgs/COAWST] Creating initial field, boundary field files from grid files (Issue #90)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Well, I will go to the forum and ask about it.
I have another problem here, when I create the grid using the method in the coawst user manual, I can run roms successfully. but I find the zeta data in the result file is strange. It may be that there are some areas where the water depth is too low and there are anomalies. Here are the results that I viewed using ncview.
[roms]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44939791%2F179384101-e237a5c1-e1e0-45e2-ad78-fd95c4916c9a.png&data=05%7C01%7Cjcwarner%40usgs.gov%7Ccc0e01a3c9be4c30fb2608da67aeb15b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637936297274555520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uVBZsVB49Yij7gmMQMdECupTyVhfi0%2BY1QpO%2BxS0Hgk%3D&reserved=0>
Meanwhile, I plotted the zeta data at a certain moment with ncl and found that the results are normal for most of the areas. Have you encountered this situation?
[ncl_zeta]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44939791%2F179384224-ce0e55bb-b4cf-4643-9593-85efc305dac8.png&data=05%7C01%7Cjcwarner%40usgs.gov%7Ccc0e01a3c9be4c30fb2608da67aeb15b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637936297274555520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FJIvZEY%2FBa5oE4bLhUrwX%2B2V4R5z5b9euW3GDEhLqhQ%3D&reserved=0>

**Comment by SakuraLz** [comment]
This is the "h" data I checked. It looks like there is nothing wrong with it.
![h](https://user-images.githubusercontent.com/44939791/180346948-4802762c-f022-4ddc-a750-bf0dcb636ec1.png)
