### ISSUE TITLE
Why use etopo5 bathymetric data?

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#93]
Hello.
I noticed that you are using etopo5 bathymetry data during the coawst pre-processing? Why didn't you use the etopo1 data, which is probably more accurate? What should I do if I want to use etopo1 bathymetry.

**Comment by jcwarner-usgs** [comment]
you can use any topo/bathy you want.
we collect our own bathy at many locations.  Those test cases are examples of the steps needed.  You can use other methods/data to fit your own application.
