### ISSUE TITLE
Error opening RRTM_DATA" when coupling wrf-roms-swan

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#94]
I'm having some problems running the wrf-roms-swan model.
According to the logs.
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE: LINE: 7632
module_ra_rrtm: error opening RRTM_DATA on unit 10

I have been able to run the wrf-roms model successfully, so I think there may be a problem with the swan model.
I noticed that someone else had a similar error to mine. I changed the contents of Compilers/Linux-gfortran.mk as you gave me "FFLAGS += fconvert=big-endian -frecord-marker=4" and recompiled. But there is still the same error.
Also, I found the RRTM_DATA file in my program, but I did not find the coawstG file. Only the coawstM file exists in the root directory.
I hope you can help me.

**Comment by jcwarner-usgs** [comment]
the coawst M or G depends on the setting in the coawst.bash.  if you set DEBUG=on then you get the G.

for the RRTM issue - can you do a clean build and send the output to me.  this can be from
script build.log
./coawst.bash -j 4
exit
then send build.log to me

-j

**Comment by SakuraLz** [comment]
OK, I'll export the results of the build. But using '. /coawst.bash -j 4' I can't get the log file, so I output it like this:
. /coawst.bash -j 4 > build.log
The file looks like this
[build.log](https://github.com/jcwarner-usgs/COAWST/files/9330578/build.log)

**Comment by SakuraLz** [comment]
Also, here is my runtime file, which may help.
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/9330587/logs.txt)

**Comment by jcwarner-usgs** [comment]
is the RRTM_DATA file in the same location as the coawstM ?

**Comment by SakuraLz** [comment]
I think I've found the cause of the problem. It may be that I deleted the RRTM file from the root directory a while ago, which prevented it from compiling. I have found a replacement file, hope that helps.
Thanks for your reply!
