### ISSUE TITLE
Biofennel gives error when running COAWST

### ISSUE THREAD

**Issue by mf99274** [jcwarner-usgs/COAWST#95]
Dear all, 

I am trying to run biofennel + vegetation module + ROMS in COAWST and I get the following error:

TIME-STEP YYYY-MM-DD hh:mm:ss.ss  KINETIC_ENRG   POTEN_ENRG    TOTAL_ENRG    NET_VOLUME
                     C => (i,j,k)       Cu            Cv            Cw         Max Speed

         0 2015-05-01 00:00:00.00  0.000000E+00  6.377852E+01  6.377852E+01  5.692375E+08
                     (000,000,00)  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00
 BIO trouble in DIAG   5.753503713568942E-003  1.080793484693523E+103
  3.991185527058441E+064  1.363477102694197E+117   3846274.60425583     
  3.991185527058447E+064  1.363477102694197E+117  2.857618877996498E-317
  0.000000000000000E+000   2098.66406250000        2419.07031250000     
   234.849556546822     
 BIO trouble in DIAG   5.753503713568942E-003  1.080793484693523E+103
  3.991185527058441E+064  1.363477102694197E+117   3846274.60425583     
  3.991185527058447E+064  1.363477102694197E+117  2.857618877996498E-317
  0.000000000000000E+000   2098.66406250000        2419.07031250000     
   234.849556546822     
 BIO trouble in DIAG   5.753503713568942E-003  1.080793484693523E+103
  3.991185527058441E+064  1.363477102694197E+117   3846274.60425583     
  3.991185527058447E+064  1.363477102694197E+117  2.857618877996498E-317
  0.000000000000000E+000   2098.66406250000        2419.07031250000     
   234.849556546822     
 BIO trouble in DIAG   5.753503713568942E-003  1.080793484693523E+103
  3.991185527058441E+064  1.363477102694197E+117   3846274.60425583     
  3.991185527058447E+064  1.363477102694197E+117  2.857618877996498E-317
  0.000000000000000E+000   2098.66406250000        2419.07031250000     
   234.849556546822     
 BIO trouble in DIAG   5.753503713568942E-003  1.080793484693523E+103
  3.991185527058441E+064  1.363477102694197E+117   3846274.60425583     
  3.991185527058447E+064  1.363477102694197E+117  2.857618877996498E-317
  0.000000000000000E+000   2098.66406250000        2419.07031250000     
   234.849556546822     
 BIO trouble in DIAG   5.753503713568942E-003  1.080793484693523E+103
  3.991185527058441E+064  1.363477102694197E+117   3846274.60425583     
  3.991185527058447E+064  1.363477102694197E+117  2.857618877996498E-317
  0.000000000000000E+000   2098.66406250000        2419.07031250000     
   234.849556546822     
 Found Error: 01   Line: 351      Source: ROMS/Nonlinear/main3d.F
 Found Error: 01   Line: 320      Source: ROMS/Drivers/nl_ocean.h

I have closed all boundaries and used only IC, have changed all boundaries to gradient, have added boundary conditions to one side of the domain, only activated OXYGEN, added ana_srflux, decreased the dt because of CFL, turned off Vegetation module and still the same error in the same time-step happens. This model is an idealized model that I have already running and working and validated. 

I am running out of options and ideas and I was wondering if this is a COAWST bug. Also, I haven't turned on the diagnostic for biofennel so I don't know why it gives me the diag for biology. I think my biological values are reasonable because I got them from CMIP6 dataset. 

I have uploaded the output file for it
[outputfile.txt](https://github.com/jcwarner-usgs/COAWST/files/9473794/outputfile.txt)

Thank you in advance,
Matt

**Comment by jcwarner-usgs** [comment]
so if you had a model that worked.
then add one thing - Bio oxygen. ?
what does the rst file look like?  where are those large Bio values occurring?

**Comment by mf99274** [comment]
I literally don't know either. For example, when I run only hypoxia_srm model it works perfectly for the time I want to run. I have tried to zero the IC for the variables and close the boundaries but still the same error.

**Comment by jcwarner-usgs** [comment]
of here is a non-standard way to see if you can get some output.
edit Build/diag.f90 and look for a section of code like this:

          DO ibt=1,NBT
            IF (maxbio(ibt,ng).gt.max_bio(ibt)) THEN
              IF (Master) print *, 'BIO trouble in DIAG ', maxbio(:,ng)
              exit_flag=1
            END IF
          END DO


put a comment on the exit flag line


          DO ibt=1,NBT
            IF (maxbio(ibt,ng).gt.max_bio(ibt)) THEN
              IF (Master) print *, 'BIO trouble in DIAG ', maxbio(:,ng)
!              exit_flag=1
            END IF
          END DO

recompile, and run it.
have the his be every time step.

look at the output and see what is happening.

**Comment by jcwarner-usgs** [comment]
to recompile, just do
./coawst.bash -noclean

**Comment by mf99274** [comment]
Hi John, 

It gets stuck saving the netcdf files and hasn't passed that for 2 hrs. 

[outputfile.txt](https://github.com/jcwarner-usgs/COAWST/files/9479048/outputfile.txt)

Thank you,

**Comment by jcwarner-usgs** [comment]
is there anything in that his file?

**Comment by mf99274** [comment]
Yeap, 
the values I set up using ana_biology.h  Also, it went through the first hour but only saved the first time-step, there is nothing else inside the history file and I am saving every 10 min.

**Comment by jcwarner-usgs** [comment]
save every time step.
set NHIS =1
watch the file and if it does write more and get big, then stop the job.
scancel 12345523 (job id)

**Comment by mf99274** [comment]
It does get big! Is that a good thing?

**Comment by jcwarner-usgs** [comment]
well it means data is being written out.
so you will need to look at it, start at the first time step and see what happens.  it should be obvious near the beginning what and where the data is bad.
-j

**Comment by mf99274** [comment]
But as of right now I am literally using ana_biology.h as my IC, doesn't that mean it should work without giving the error?

**Comment by jcwarner-usgs** [comment]
i am really not sure.  i dont run the bio stuff much.
is there a test case that i can try ? 
if you just have ana stuff (grids, bio etc ) can you send those files to me?

**Comment by mf99274** [comment]
Sounds good I will send you the ic file and grid file in the email. What would be the best email to send you the dataset? Thank you John.

**Comment by jcwarner-usgs** [comment]
how big are the files?
i would need the 

kelp_biofennel.h
the ocean.in
ana_* files 
  Input Grid File:  /home/mf99274/COAWST_sap2test/Projects/datasets/kelp/grid_kelp.nc
  Input Nonlinear Initial File:  /home/mf99274/COAWST_sap2test/Projects/datasets/kelp/ini_biofennel.nc
  Input Boundary File 01:  /home/mf99274/COAWST_sap2test/Projects/datasets/kelp/bc_kelp_bio.nc
   Station positions File:  /home/mf99274/COAWST_sap2test/Projects/kelp/stations.in
   Biology Parameters File:  /home/mf99274/COAWST_sap2test/Projects/kelp_biofennel/bio_Fennel.in
   Vegetation Parameters File:  /home/mf99274/COAWST_sap2test/Projects/kelp_biofennel/vegetation.in
any more ?

i cant get files over 20 megs.
jcwarner@usgs.gov

**Comment by mf99274** [comment]
I am not forcing with bc and not using ic file so we only have grid_kelp.nc and the other .in files, also not running vegetation or stations. 
The subject of my email is : biofennel not running - dataset

Thank you once again!

**Comment by jcwarner-usgs** [comment]
got ur files.
can you try something?
your ocean.in does not have the Advection choices.  look at ocean_sandy.in or any other ocean.in .
You need to add something like:

[right after the NtileI NtileJ]
...      NtileI == 1                                ! I-direction partition
...      NtileJ == 1                                ! J-direction partition

Add this:::::  ------->

! Set horizontal and vertical advection schemes for active and inert
! tracers. A different advection scheme is allowed for each tracer.
! For example, a positive-definite (monotonic) algorithm can be activated
! for salinity and inert tracers, while a different one is set for
! temperature. [1:NAT+NPT,Ngrids] values are expected.
!
!   Keyword    Advection Algorithm
!
!   A4         4th-order Akima (horizontal/vertical)
!   C2         2nd-order centered differences (horizontal/vertical)
!   C4         4th-order centered differences (horizontal/vertical)
!   HSIMT      3th-order HSIMT-TVD (horizontal/vertical)
!   MPDATA     recursive flux corrected MPDATA (horizontal/vertical)
!   SPLINES    parabolic splines (only vertical)
!   SU3        split third-order upstream (horizontal/vertical)
!   U3         3rd-order upstream-biased (only horizontal)
!
! The user has the option of specifying the full Keyword or the first
! two letters, regardless if using uppercase or lowercase. If nested
! grids, specify values for each grid (see glossary below).

   Hadvection == U3   \  
                 U3   \                        ! temperature
                 U3   \ 
                 U3                            ! salinity

   Vadvection == C4   \
                 C4   \                        ! temperature
                 C4   \
                 C4                            ! salinity


or whatever choices you want.

**Comment by mf99274** [comment]
Hi John, 

can I just add that for an older version of COAWST? Would I have to change something else?

**Comment by mf99274** [comment]
Hi John, 

going through the diag.F code I noticed one thing that I forgot to mention. When I was trying to compile with ifort it used to give me the following error:
diag.f90
diag.f90(132): error #6279: A specification expression object must be a dummy argument, a COMMON block object, or an object accessible through host or use association.   [NREDUCE]
      integer :: Nreduce
-----------------^
compilation aborted for diag.f90 (code 1)

So I was able to "fix" that by doing the following:

ifdef DISTRIBUTE
 ifdef SOLVE3D
  ifdef BIOLOGY
      integer :: **Nreduce**
  else
      integer, parameter :: Nreduce = 5
  endif
      integer, parameter :: Ncourant = 7
 else
      integer, parameter :: Nreduce = 4
      integer, parameter :: Ncourant = 5
 endif
      real(r8), dimension(Ncourant) :: Courant
 ifndef BIOLOGY
      real(r8), dimension(**Nreduce**) :: buffer
      character (len=3), dimension(**Nreduce**) :: op_handle
      character (len=6), dimension(**Nreduce**) :: C_handle
 else

To 

ifdef DISTRIBUTE
 ifdef SOLVE3D
  ifdef BIOLOGY
      integer :: Nreduce
  else
      integer, parameter :: Nreduce = 5
  endif
      integer, parameter :: Ncourant = 7
 else
      integer, parameter :: Nreduce = 4
      integer, parameter :: Ncourant = 5
 endif
     real(r8), dimension(Ncourant) :: Courant
 ifndef BIOLOGY
      real(r8), dimension(**5**) :: buffer
      character (len=3), dimension(**5**) :: op_handle
      character (len=6), dimension(**5**) :: C_handle
 else

Could that be the reason why it gives me error and exits the simulation? 

Thank you

**Comment by mf99274** [comment]
Quick update:

I changed 

ifndef BIOLOGY
real(r8), dimension(5) :: buffer
character (len=3), dimension(5) :: op_handle
character (len=6), dimension(5) :: C_handle

to 

      real(r8), dimension(NBT+5) :: buffer
      character (len=3), dimension(NBT+5) :: op_handle
      character (len=6), dimension(NBT+5) :: C_handle

And now works and no diagnostic print happens! However, I don't know how much that will mess up the rest.

**Comment by jcwarner-usgs** [comment]
that seems to be what is in the newer version of the code.
if you got it to work then that is great.
I am going to close this ticket.
