### ISSUE TITLE
Choice of namelist.input physical scheme

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#96]
I have recently been using the wrf-roms coupling mode and adjusting the physical parameter scheme in wrf. When I use "ra_lw_physics: RRTMG, ra_sw_physics: RRTMG", the wrf-roms coupling mode runs with an error.
An error is displayed: "At line 3355 of file module_ra_cam_support.f90 (unit = 27)
Fortran runtime error: Cannot open file 'ozone_plev.formatted'"
But I don't have this problem when I use the RRTMG scheme for a separate wrf.

I would like to know if you know what the cause is?
Thank you very much for your help.
[namelist.txt](https://github.com/jcwarner-usgs/COAWST/files/9541978/namelist.txt)
[logs.txt](https://github.com/jcwarner-usgs/COAWST/files/9541979/logs.txt)

**Comment by jcwarner-usgs** [comment]
i think those files are in WRF/run
you may have to copy them to the run location (ie where the coawstM is).
-j

**Comment by jbzambon** [comment]
Yes, whenever I download a new COAWST git, I always `cp WRF/run/RRTM*` and `cp WRF/run/ozone*` to the main directory.
