### ISSUE TITLE
roms_master_climatology_coawst_mw

### ISSUE THREAD

**Issue by jc-suen** [jcwarner-usgs/COAWST#97]
Hello, everyone
  I'm using roms_master_climatology_coawst_MW. When M, I encountered an error. Does anyone have the same problem? How do you fix it?
`Using NCDataset incorrectly (line 97)

Failed to open http://tds.hycom.org/thredds/dodsC/GLBa0.08/expt_93.0

Error CFDATASET (line 59)

obj = obj@ncdataset(url);

Error NCGeodataset (line 74)

obj = obj@cfdataset(url);

Error get_ijrg (line 66)

nc=ncgeodataset(url2);

Error roms_master_climatology_coawst_MW (line 79)

get_ijrg(gn,url)

The reason:

Cannot resolve the name ucar.nc2.dataset.Net cdfDataset openDataset.
`

**Comment by jcwarner-usgs** [comment]
the thredds server can often time out.  this is common.
please try it again.  you can go to the site directly and download the files if you continue to have problems.
