### ISSUE TITLE
About the setting of sea surface temperature (sst) in wrf-roms coupling mode

### ISSUE THREAD

**Issue by SakuraLz** [jcwarner-usgs/COAWST#99]
I have recently been using the coupled model of wrf-roms to simulate the effects of typhoons and the ocean. But during the simulations I found that roms is largely unaffected by typhoons in the offshore region sst and there is no morning or evening temperature change. I think this may be because I have some switches that are not turned on.
For the sst temperature field I used the fnl data and generated the wrflowinp file.
I wonder if you know what to do to solve this problem.
Here are some of my parameters, I hope you can help me.
[mangkhut.h.txt](https://github.com/jcwarner-usgs/COAWST/files/9716802/mangkhut.h.txt)
[namelist.input.txt](https://github.com/jcwarner-usgs/COAWST/files/9716805/namelist.input.txt)
[roms_mangkhut_r1.in.txt](https://github.com/jcwarner-usgs/COAWST/files/9716808/roms_mangkhut_r1.in.txt)

**Comment by SakuraLz** [comment]
![image](https://user-images.githubusercontent.com/44939791/194098635-56c7e70d-b9d5-42f3-bfcd-191a8044a4fa.png)
![image](https://user-images.githubusercontent.com/44939791/194098670-30fd44dc-bbdc-4ce3-a3b7-159f0c20fb31.png)
The thin black line in the diagram is the result of my simulation, the model also had two days of warm-up time before. It looks like it was basically unaffected by the typhoon and I'm not sure what the reason for this is.

**Comment by jcwarner-usgs** [comment]
what does a color plot of the WRF SST look like on 09/16 00:00?
how does that compare to the ROMS surface temp?

is roms getting the wind stresses?  if you plot sustr or svstr, are the stresses coming to roms?

**Comment by SakuraLz** [comment]
I put the colour chart of sst at 09/16 00:00 below. And I have plotted the sst minus 09/15 00:00 results for each moment after that.
As you can see, the change in sst is noticeable in the deeper water, but very little change in the offshore area.
![image](https://user-images.githubusercontent.com/44939791/194462070-aef32d89-c36e-4b75-af54-aaa4bdd204cb.png)
![image](https://user-images.githubusercontent.com/44939791/194462211-e54da8cb-4e14-4e8f-b8b8-70768d983e66.png)
As for sustr or svstr. I think the roms have received the wind effects of wrf. I have likewise put the sustr results for 09/16 00:00 below. Do you have any idea where the problem lies?
![image](https://user-images.githubusercontent.com/44939791/194462650-e504ca21-9677-4e21-bc27-b0ec59bb7968.png)
![image](https://user-images.githubusercontent.com/44939791/194462711-eb7e4ebb-719a-4f27-8022-d51d573c4ddf.png)

**Comment by jcwarner-usgs** [comment]
which Q locations are the time series from?  i cant read the title on those figures.
Do you have a time series of temp at station Q4?
maybe add those Q sites onto the temp pcolors.
In general it looks like lots of cooling offshore  !! that is good.
but not as much cooling at the coastal Q sites.  That could be from the initial temperature structure.  
something you could  do is look at why the ocean cooled.  was it from vertical mixing?  how deep did it mix.  etc.

**Comment by SakuraLz** [comment]
I have placed the temperature changes for the four stations below. As you can see, the temperature change is more pronounced at site Q4 and only weak when offshore.
I am a little less understanding of what you mean by the initial temperature structure. Is it caused by the initial boundary field file? But why don't typhoons make SSTs lower? This is somewhat different from the measured data. And there is no early or late variation in SSTs, is this not related to the parameter file settings?Is there any way to make the SST variation more pronounced in the offshore area?
![image](https://user-images.githubusercontent.com/44939791/194686182-b058a1bf-69a8-43e5-bfc0-80acdba3eebc.png)
![image](https://user-images.githubusercontent.com/44939791/194686158-25510585-2c8c-4423-83a0-3f626016a94b.png)

**Comment by jcwarner-usgs** [comment]
i think the model is working correctly.  but there problem is with the initial temp field.
none of the time series have the same buoy and ocean starting temp.  so the model is not going to be able to get to a final temperature that matches the buoys if the model does not start correctly.

some other things you can try is to activate SWAN and allow the waves to enhance the mixing
#define SWAN_MODEL
#define MCT_INTERP_OC2AT
#define MCT_INTERP_WV2AT
#define MCT_INTERP_OC2WV

#if defined WRF_MODEL && defined SWAN_MODEL
# define DRAGLIM_DAVIS
# define COARE_TAYLOR_YELLAND              <--- there are several options here such as DRENNAN or OOST
#endif

taht will create more mixing. the Sandy test case has all 3 models as an example.

**Comment by SakuraLz** [comment]
OK, thank you for your help. I will try to adjust the initial field of the temperature afterwards and check the results. I will also try to couple the SWAN model. I will let you know if the results improve.

**Comment by jcsunn** [comment]
I have to bother you again, after I run it in the Projects/Upwelling folder, in the log file I find a message :module_physics_init.F: LANDUSE_INIT: open failure for LANDUSE.TBL, so this needs to link all the files in wrf/run ? I have another question for you, for general simulations, do you recommend to compile the operations directly in the root directory, or in a different folder in Projects?
